import {useEffect,useState} from 'react';
import {supplierInvoiceReview as api} from '../services/api';
import {Button} from '../ui';
const amount=n=>Number(n).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const blank=()=>({fecha:new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date()),importe:'',referencia:'',notas:'',client_operation_uuid:crypto.randomUUID()});
export default function SupplierInvoicePaymentPanel({invoiceId,editable,onRegistered}){
 const [balance,setBalance]=useState(null),[form,setForm]=useState(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;api(`/${invoiceId}/pagos`).then(data=>alive&&setBalance(data)).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[invoiceId]);
 const change=(key,value)=>setForm(f=>({...f,[key]:value,client_operation_uuid:crypto.randomUUID()}));
 async function save(){if(busy)return;setBusy(true);setError('');try{setBalance(await api(`/${invoiceId}/pagos`,{method:'POST',body:form}));setForm(blank());onRegistered?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="supplier-review"><h3>Pagos de esta factura</h3><p>Registra un pago que ya se haya realizado. Los importes incluyen los impuestos de la factura; registrar el pago no ejecuta una transferencia bancaria.</p>{error&&<p role="alert">{error}</p>}{!balance&&!error&&<p role="status">Consultando saldo…</p>}{balance&&<><p>Total {amount(balance.total)} · Pagado {amount(balance.pagado)} · <strong>Pendiente {amount(balance.pendiente)}</strong></p><ul>{balance.pagos.map(p=><li key={p.id}>{String(p.fecha).slice(0,10)} · {amount(p.importe)} · {p.referencia||'Sin referencia'} · {p.estado}</li>)}</ul>{editable&&balance.pendiente>0&&<><div className="supplier-review-grid"><label>Fecha real de pago<input type="date" value={form.fecha} disabled={busy} onChange={e=>change('fecha',e.target.value)}/></label><label>Importe pagado (€)<input inputMode="decimal" placeholder={String(balance.pendiente).replace('.',',')} value={form.importe} disabled={busy} onChange={e=>change('importe',e.target.value)}/></label><label>Referencia del pago<input value={form.referencia} disabled={busy} onChange={e=>change('referencia',e.target.value)} placeholder="Referencia de transferencia o recibo"/></label><label>Notas<input value={form.notas} disabled={busy} onChange={e=>change('notas',e.target.value)}/></label></div><Button variant="primary" disabled={busy||!form.importe||!form.referencia} onClick={save}>{busy?'Guardando pago…':'Registrar pago realizado'}</Button></>}{balance.total<0&&<p>Es un abono del proveedor; no se registra como un pago a su favor.</p>}</>}</section>;
}
