import { useMemo, useState } from "react";
import { Drawer, Select, KpiCard, Button, DataTable, MobileDataCard, EmptyState } from "../../ui";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
const euros=n=>Number(n||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
export default function DashboardBI({ onClose, period, setPeriod, metrics, clients, series, loading, error }) {
  const [query,setQuery]=useState("");
  const [order,setOrder]=useState("total");
  const [limit,setLimit]=useState("all");
  const [measure,setMeasure]=useState("all");
  const totalClients=clients.reduce((sum,c)=>sum+Number(c.total||0),0);
  const rows=useMemo(()=>clients.filter(c=>String(c.name||"").toLocaleLowerCase("es").includes(query.toLocaleLowerCase("es"))).sort((a,b)=>order==="name" ? String(a.name).localeCompare(String(b.name),"es") : Number(b[order]||0)-Number(a[order]||0)).slice(0,limit==="all" ? undefined : Number(limit)),[clients,query,order,limit]);
  const topShare=totalClients>0 ? Math.max(0,...clients.map(c=>Number(c.total||0)))/totalClients*100 : 0;
  function exportRows() {
    const cell=v=>'"'+String(v??"").replace(/"/g,'""')+'"';
    const safe=v=>/^[=+@-]/.test(String(v)) ? "'"+v : v;
    const lines=[["Cliente","Facturado","Realizado sin factura","Ingreso gestionado","Participación %"],...rows.map(c=>[safe(c.name),Number(c.facturado||0),Number(c.pendiente||0),Number(c.total||0),totalClients ? Number(c.total||0)/totalClients*100 : 0])];
    const url=URL.createObjectURL(new Blob(['\ufeff'+lines.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`clientes-bi-${period}.csv`;a.click();URL.revokeObjectURL(url);
  }
  const cards=[['Ingreso gestionado',metrics.ingreso,'Facturado + realizado sin factura'],['Facturado',metrics.facturado,'Base imponible emitida'],['Pendiente de facturar',metrics.sinFactura,'Viajes realizados'],['Margen realizado',metrics.margen,'Venta realizada menos costes'],['Cobrado',metrics.cobrado,'Importe con impuestos'],['Pendiente de cobro',metrics.pendiente,'Importe con impuestos']];
  function csv(){const lines=[['Indicador','Valor'],...cards.map(([name,value])=>[name,Number(value||0)]),['Viajes realizados',metrics.realizados],['EUR por km',metrics.eurKm],['Kilómetros realizados',metrics.km]];const blob=new Blob(['\ufeff'+lines.map(r=>r.join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`dashboard-bi-${period}.csv`;a.click();URL.revokeObjectURL(url);}
  return <Drawer title="Análisis BI" onClose={onClose} width={1040}>
    <div className="dashboard-bi-controls"><Select label="Periodo del análisis BI" value={period} onChange={e=>setPeriod(e.target.value)}>{[['mes','Mes actual'],['7d','Últimos 7 días'],['3m','Últimos 90 días'],['6m','Últimos 180 días'],['1y','Últimos 365 días'],['all','Todo el histórico']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Button disabled={loading} onClick={csv}>Exportar indicadores</Button></div>
    {loading&&<p role="status">Actualizando análisis…</p>}{error&&<p role="alert">{error} Se muestran los cálculos disponibles del listado cargado.</p>}
    <div className="dashboard-bi-kpis">{cards.map(([label,value,detail])=><KpiCard key={label} label={label} value={euros(value)} detail={detail} tone={label==='Margen realizado'&&value<0?'danger':'neutral'}/>)}</div>
    <div className="dashboard-bi-facts"><span><strong>{metrics.realizados}</strong> viajes realizados</span><span><strong>{euros(metrics.eurKm)}</strong> por km realizado</span><span><strong>{Number(metrics.margenPct||0).toLocaleString('es-ES')}%</strong> margen realizado</span><span><strong>{metrics.facturas}</strong> facturas</span></div>
    <h3>Qué conviene revisar</h3><ul className="dashboard-bi-insights">{metrics.sinFactura>0&&<li>{euros(metrics.sinFactura)} de viajes realizados pendientes de facturar.</li>}{metrics.pendiente>0&&<li>{euros(metrics.pendiente)} pendientes de cobro.</li>}{metrics.margen<0&&<li>El coste de los viajes realizados supera su venta en {euros(-metrics.margen)}.</li>}{metrics.pod>0&&<li>{metrics.pod} viajes realizados sin POD.</li>}{metrics.sinKm>0&&<li>{metrics.sinKm} pedidos sin kilómetros: revisar antes de comparar rentabilidad por km.</li>}{!metrics.sinFactura&&!metrics.pendiente&&metrics.margen>=0&&!metrics.pod&&!metrics.sinKm&&<li>No se detectan pendientes en estos indicadores del periodo.</li>}</ul>
    <div className="dashboard-bi-controls"><h3>Evolución del ingreso gestionado</h3><Select label="Serie financiera" value={measure} onChange={e=>setMeasure(e.target.value)}><option value="all">Ambas series</option><option value="facturado">Facturado</option><option value="pendiente">Realizado sin factura</option></Select></div>{series.length?<div className="dashboard-bi-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={series}><XAxis dataKey="name" tick={{fill:'var(--text3)',fontSize:11}}/><YAxis tick={{fill:'var(--text3)',fontSize:11}}/><Tooltip formatter={euros} contentStyle={{background:'var(--card-bg)',borderColor:'var(--border)'}}/>{measure!=="pendiente"&&<Bar dataKey="facturado" name="Facturado" fill="var(--accent)"/>}{measure!=="facturado"&&<Bar dataKey="pendiente" name="Realizado sin factura" fill="#82cdb8"/>}</BarChart></ResponsiveContainer></div>:<EmptyState title="Sin movimientos financieros en este periodo"/>}
    <div className="dashboard-bi-facts"><span><strong>{clients.length}</strong> clientes en el periodo</span><span><strong>{topShare.toLocaleString('es-ES',{maximumFractionDigits:1})}%</strong> del ingreso en el principal cliente</span><span><strong>{euros(clients.length ? totalClients/clients.length : 0)}</strong> ingreso medio por cliente</span></div>
    <h3>Clientes · ingreso gestionado</h3><p className="dashboard-caption">Filtra y ordena el desglose. La participación se calcula sobre todos los clientes del periodo; los KPI superiores mantienen ese alcance.</p>
    <div className="dashboard-bi-controls"><input aria-label="Buscar cliente en BI" placeholder="Buscar cliente…" value={query} onChange={e=>setQuery(e.target.value)}/><Select label="Orden del desglose" value={order} onChange={e=>setOrder(e.target.value)}><option value="total">Mayor ingreso</option><option value="pendiente">Mayor pendiente de facturar</option><option value="facturado">Mayor facturación</option><option value="name">Nombre</option></Select><Select label="Número de clientes" value={limit} onChange={e=>setLimit(e.target.value)}><option value="all">Todos</option><option value="5">Top 5</option><option value="10">Top 10</option></Select><Button onClick={exportRows} disabled={loading||!rows.length}>Exportar clientes</Button></div>
    <DataTable rows={rows} rowKey={r=>r.name} columns={[{key:'name',label:'Cliente'},{key:'facturado',label:'Facturado',render:r=>euros(r.facturado)},{key:'pendiente',label:'Sin facturar',render:r=>euros(r.pendiente)},{key:'total',label:'Gestionado',render:r=>euros(r.total)},{key:'share',label:'Participación',render:r=>`${(totalClients ? Number(r.total||0)/totalClients*100 : 0).toLocaleString('es-ES',{maximumFractionDigits:1})}%`}]} renderMobile={r=><MobileDataCard title={r.name} amount={euros(r.total)} subtitle={`Facturado: ${euros(r.facturado)} · Sin facturar: ${euros(r.pendiente)}`}/>}/>
    <p className="dashboard-caption">El análisis conserva los criterios de facturación y costes del programa. Los indicadores operativos se actualizan por separado en el Dashboard.</p>
  </Drawer>;
}
