import { Drawer, Select, KpiCard, Button, DataTable, MobileDataCard, EmptyState } from "../../ui";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
const euros=n=>Number(n||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
export default function DashboardBI({ onClose, period, setPeriod, metrics, clients, series, loading, error }) {
  const cards=[['Ingreso gestionado',metrics.ingreso,'Facturado + realizado sin factura'],['Facturado',metrics.facturado,'Base imponible emitida'],['Pendiente de facturar',metrics.sinFactura,'Viajes realizados'],['Margen realizado',metrics.margen,'Venta realizada menos costes'],['Cobrado',metrics.cobrado,'Importe con impuestos'],['Pendiente de cobro',metrics.pendiente,'Importe con impuestos']];
  function csv(){const lines=[['Indicador','Valor'],...cards.map(([name,value])=>[name,Number(value||0)]),['Viajes realizados',metrics.realizados],['EUR por km',metrics.eurKm],['Kilómetros realizados',metrics.km]];const blob=new Blob(['\ufeff'+lines.map(r=>r.join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`dashboard-bi-${period}.csv`;a.click();URL.revokeObjectURL(url);}
  return <Drawer title="Análisis BI" onClose={onClose} width={1040}>
    <div className="dashboard-bi-controls"><Select label="Periodo del análisis BI" value={period} onChange={e=>setPeriod(e.target.value)}>{[['mes','Mes actual'],['7d','Últimos 7 días'],['3m','Últimos 90 días'],['6m','Últimos 180 días'],['1y','Últimos 365 días'],['all','Todo el histórico']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Button disabled={loading} onClick={csv}>Exportar indicadores</Button></div>
    {loading&&<p role="status">Actualizando análisis…</p>}{error&&<p role="alert">{error} Se muestran los cálculos disponibles del listado cargado.</p>}
    <div className="dashboard-bi-kpis">{cards.map(([label,value,detail])=><KpiCard key={label} label={label} value={euros(value)} detail={detail} tone={label==='Margen realizado'&&value<0?'danger':'neutral'}/>)}</div>
    <div className="dashboard-bi-facts"><span><strong>{metrics.realizados}</strong> viajes realizados</span><span><strong>{euros(metrics.eurKm)}</strong> por km realizado</span><span><strong>{Number(metrics.margenPct||0).toLocaleString('es-ES')}%</strong> margen realizado</span><span><strong>{metrics.facturas}</strong> facturas</span></div>
    <h3>Qué conviene revisar</h3><ul className="dashboard-bi-insights">{metrics.sinFactura>0&&<li>{euros(metrics.sinFactura)} de viajes realizados pendientes de facturar.</li>}{metrics.pendiente>0&&<li>{euros(metrics.pendiente)} pendientes de cobro.</li>}{metrics.margen<0&&<li>El coste de los viajes realizados supera su venta en {euros(-metrics.margen)}.</li>}{metrics.pod>0&&<li>{metrics.pod} viajes realizados sin POD.</li>}{metrics.sinKm>0&&<li>{metrics.sinKm} pedidos sin kilómetros: revisar antes de comparar rentabilidad por km.</li>}{!metrics.sinFactura&&!metrics.pendiente&&metrics.margen>=0&&!metrics.pod&&!metrics.sinKm&&<li>No se detectan pendientes en estos indicadores del periodo.</li>}</ul>
    <h3>Evolución del ingreso gestionado</h3>{series.length?<div className="dashboard-bi-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={series}><XAxis dataKey="name" tick={{fill:'var(--text3)',fontSize:11}}/><YAxis tick={{fill:'var(--text3)',fontSize:11}}/><Tooltip formatter={euros} contentStyle={{background:'var(--card-bg)',borderColor:'var(--border)'}}/><Bar dataKey="facturado" name="Facturado" fill="var(--accent)"/><Bar dataKey="pendiente" name="Realizado sin factura" fill="#82cdb8"/></BarChart></ResponsiveContainer></div>:<EmptyState title="Sin movimientos financieros en este periodo"/>}
    <h3>Clientes · ingreso gestionado</h3><DataTable rows={clients} rowKey={r=>r.name} columns={[{key:'name',label:'Cliente'},{key:'facturado',label:'Facturado',render:r=>euros(r.facturado)},{key:'pendiente',label:'Sin facturar',render:r=>euros(r.pendiente)},{key:'total',label:'Gestionado',render:r=>euros(r.total)}]} renderMobile={r=><MobileDataCard title={r.name} amount={euros(r.total)} subtitle={`Facturado: ${euros(r.facturado)} · Sin facturar: ${euros(r.pendiente)}`}/>}/>
    <p className="dashboard-caption">El análisis conserva los criterios de facturación y costes del programa. Los indicadores operativos se actualizan por separado en el Dashboard.</p>
  </Drawer>;
}
