FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json ./
RUN npm install --no-audit --no-fund
COPY . .
ENV CI=false
ENV DISABLE_ESLINT_PLUGIN=true
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx-accounting.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
