const assert=require('node:assert/strict'),crypto=require('crypto');
module.exports=async function({db,base,company,user,token,password,pdf}){
 let checks=0;const call=async(method,path,body,status=200,auth=token)=>{const r=await fetch(base+path,{method,headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();assert.equal(r.status,status,JSON.stringify(v));checks++;return v;};
 const other=(await call('POST','/auth/login',{email:'planner-b@example.invalid',password})).token;
 const client=(await db.query('SELECT id FROM clientes WHERE empresa_id=$1 LIMIT 1',[company])).rows[0].id;
 const order=crypto.randomUUID();await db.query("INSERT INTO pedidos(id,empresa_id,numero,cliente_id,estado,importe,importe_revision_combustible,origen,destino) VALUES($1,$2,'QA-DETENTION',$3,'entregado',1000,50,'A','B')",[order,company,client]);
 const doc=(await db.query("INSERT INTO pedido_docs(empresa_id,pedido_id,tipo,nombre,file_base64,file_mime) VALUES($1,$2,'espera','Espera sintética.pdf',$3,'application/pdf') RETURNING id",[company,order,pdf.file_base64])).rows[0].id;
 const path=`/pedidos/${order}/paralizaciones`,body={operacion:crypto.randomUUID(),inicio:'2026-01-01T07:00:00Z',fin:'2026-01-01T09:00:00Z',documentado:200,aceptado:150,estado:'aceptada',documento_id:doc,acuerdo:'Acuerdo sintético cliente',motivo:'Aceptación acreditada'};
 await call('GET',path,null,404,other);await call('POST',path,body,404,other);
 const [claim,claimReplay]=await Promise.all([call('POST',path,body),call('POST',path,body)]);assert.equal(claimReplay.id,claim.id);
 await call('POST',path,{...body,operacion:crypto.randomUUID()},409);
 await call('POST',path,{...body,id:claim.id,version:0,operacion:crypto.randomUUID()},409);
 const result=await call('GET',path);assert.equal(result.resumen.aceptado,150);assert.equal(result.resumen.cobrado,null);
 const p=(await db.query('SELECT * FROM pedidos WHERE id=$1',[order])).rows[0];assert.equal(Number(p.importe),1000);assert.equal(Number(p.importe_paralizacion),150);
 await assert.rejects(db.query('UPDATE pedidos SET importe_paralizacion=0 WHERE id=$1',[order]),/revisión documentada/);
 const generator=require('../src/services/invoiceFuelLines'),lines=generator.fuelInvoiceLines(p);generator.validateFuelInvoiceLines([p],lines);
 assert.equal(lines.reduce((n,l)=>n+l.cantidad*l.precio_unit,0),1150);assert.throws(()=>generator.validateFuelInvoiceLines([p],lines.slice(0,2)),/paralización/);
 const invoice=await call('POST','/facturas',{cliente_id:client,serie:'A',lineas:lines,pedidos_ids:[order]},201);
 assert.equal(Number(invoice.base_imponible),1150);
 assert.equal((await db.query('SELECT count(*)::int n FROM factura_lineas WHERE factura_id=$1 AND paralizacion_pedido_id=$2',[invoice.id,order])).rows[0].n,1);
 const automaticOrder=crypto.randomUUID();await db.query("INSERT INTO pedidos(id,empresa_id,numero,cliente_id,estado,importe,importe_revision_combustible,importe_paralizacion,origen,destino) VALUES($1,$2,'QA-DETENTION-AUTO',$3,'entregado',1000,50,150,'A','B')",[automaticOrder,company,client]);
 await require('../src/routes/pedidos')._test.crearFacturaBorradorPedido(automaticOrder,company,user);
 const automatic=(await db.query('SELECT f.base_imponible,f.id FROM facturas f JOIN pedidos p ON p.factura_id=f.id WHERE p.id=$1',[automaticOrder])).rows[0];
 assert.equal(Number(automatic.base_imponible),1150);
 assert.equal((await db.query('SELECT count(*)::int n FROM factura_lineas WHERE factura_id=$1 AND paralizacion_pedido_id=$2',[automatic.id,automaticOrder])).rows[0].n,1);
 await db.query("UPDATE pedidos SET origen='Paralización QA única',destino='Conciliación QA',fecha_descarga='2026-01-05' WHERE empresa_id=$1 AND id=ANY($2::uuid[])",[company,[order,automaticOrder]]);
 const workspace=await call('GET','/informes/bi/workspace?desde=2026-01-01&hasta=2026-12-31&ruta='+encodeURIComponent('Paralización QA única → Conciliación QA'));
 assert.equal(workspace.economia.ingreso_servicios_realizados,2300);
 assert.equal(workspace.evolucion.reduce((n,r)=>n+r.ingreso,0),2300);
 assert.equal(workspace.servicios.rows.reduce((n,r)=>n+r.ingreso,0),2300);
 const center=require('../src/services/biReportCenter'),exporter=require('../src/services/biReportExport'),template=center.TEMPLATES.ejecutivo;
 const config=center.validateConfig({template:'ejecutivo',periodo:'personalizado',desde:'2026-01-01',hasta:'2026-12-31',metricas:template.metrics,columnas:template.columns,visualizaciones:template.charts});
 const report=center.projectReport(workspace,config,{name:'Paralizaciones SINTÉTICAS'});
 assert.equal(report.metrics.find(m=>m.id==='ingreso_realizado').valor,2300);
 assert.equal(report.rows.reduce((n,r)=>n+r.ingreso,0),2300);
 assert.ok(exporter.buildCsv(report).toString().includes('2300'));
 assert.ok(exporter.buildReportXlsx(report).length>1000);
 const rendered=await require('pdf-parse/lib/pdf-parse')(await exporter.buildPdf(report));assert.ok(rendered.text.includes('2300,00 €'));
 await call('POST',path,{...body,id:claim.id,version:1,operacion:crypto.randomUUID(),aceptado:140},409);
 const recoveryService=require('../src/services/detentionWorkflow');
 const recoveryOrders=(await db.query('SELECT * FROM pedidos WHERE empresa_id=$1 AND id=ANY($2::uuid[])',[company,[order,automaticOrder]])).rows;
 const cut='2026-12-31';
 let recovery=await recoveryService.recovery(db,company,recoveryOrders,cut);assert.equal(recovery.documentado,200);assert.equal(recovery.facturado,0); // Drafts excluded.
 assert.equal((await recoveryService.recovery(db,company,recoveryOrders,'2025-12-31')).documentado,null);
 await db.query("UPDATE facturas SET estado='emitida',fecha='2026-09-27' WHERE id=$1",[invoice.id]);
 recovery=await recoveryService.recovery(db,company,recoveryOrders,cut);assert.equal(recovery.facturado,150);assert.equal(recovery.porcentaje,75);assert.equal(recovery.cobrado,null);
 await db.query("UPDATE facturas SET estado='borrador' WHERE id=$1",[invoice.id]);
 const opsUrl='/informes/bi/workspace?vista=operaciones&desde=2026-01-01&hasta=2026-12-31&ruta='+encodeURIComponent('Paralización QA única → Conciliación QA');
 const opsRecovery=(await call('GET',opsUrl+'&limit=1')).operations.paralizaciones;
 assert.equal(opsRecovery.documentado,200);assert.equal(opsRecovery.detalle.rows.length,1);
 const opsNext=(await call('GET',opsUrl+'&limit=1&page=2')).operations.paralizaciones;assert.equal(opsNext.documentado,200);assert.equal(opsNext.detalle.rows.length,0);
 const quickOrder=crypto.randomUUID();await db.query("INSERT INTO pedidos(id,empresa_id,numero,cliente_id,estado,importe,origen,destino) VALUES($1,$2,'QA-PREFACTURA',$3,'entregado',700,'Valencia','Madrid')",[quickOrder,company,client]);
 const quickPath=`/pedidos/${quickOrder}/paralizaciones`,quick={operacion:crypto.randomUUID(),inicio:'2026-01-01T07:00:00Z',fin:'2026-01-01T10:00:00Z',tipo:'carga',motivo:'Espera sintética',no_imputable:true};
 assert.equal((await call('POST',quickPath+'/calcular',quick)).importe,80);
 await call('POST',quickPath+'/calcular',quick,404,other);
 await call('POST',quickPath+'/prefactura',quick,404,other);
 const [pref,prefReplay]=await Promise.all([call('POST',quickPath+'/prefactura',quick,201),call('POST',quickPath+'/prefactura',quick,201)]);assert.equal(pref.id,prefReplay.id);assert.equal(pref.prefactura.calculo.importe,80);
 await call('POST',quickPath+'/prefactura',{...quick,operacion:crypto.randomUUID()},409);
 assert.equal(Number((await db.query('SELECT importe_paralizacion FROM pedidos WHERE id=$1',[quickOrder])).rows[0].importe_paralizacion),0);
 const getPdf=auth=>fetch(base+quickPath+'/'+pref.id+'/prefactura.pdf',{headers:{Authorization:'Bearer '+auth}});
 assert.equal((await getPdf(other)).status,404);checks++;
 const file=await getPdf(token);assert.equal(file.status,200);assert.match(file.headers.get('cache-control'),/no-store/);const parsed=await require('pdf-parse/lib/pdf-parse')(Buffer.from(await file.arrayBuffer()));assert.ok(parsed.text.includes('80,00'));assert.ok(parsed.text.includes('PREFACTURA'));checks++;
 await call('POST',quickPath,{...body,id:pref.id,version:1,operacion:crypto.randomUUID(),inicio:quick.inicio,fin:quick.fin,documento_id:doc},404);
 const quickDoc=(await db.query("INSERT INTO pedido_docs(empresa_id,pedido_id,tipo,nombre,file_base64) VALUES($1,$2,'espera','Evidencia.pdf',$3) RETURNING id",[company,quickOrder,pdf.file_base64])).rows[0].id;
 await call('POST',quickPath,{...body,id:pref.id,version:1,operacion:crypto.randomUUID(),inicio:quick.inicio,fin:quick.fin,documentado:80,aceptado:80,documento_id:quickDoc});
 assert.equal(Number((await db.query('SELECT importe_paralizacion FROM pedidos WHERE id=$1',[quickOrder])).rows[0].importe_paralizacion),80);
 assert.equal((await require('../src/services/detentionQuote').read(db,company,quickOrder,pref.id)).calculo.importe,80);
 const wms=(accion,input)=>call('POST','/planner/wms/accion',{accion,operacion:crypto.randomUUID(),...input},201);
 const art=crypto.randomUUID();await db.query("INSERT INTO planner_articulos(id,empresa_id,referencia,descripcion,unidad) VALUES($1,$2,'AUTO-QA','Artículo sintético','unidad')",[art,company]);
 const src=(await wms('ubicacion',{almacen:'AUTO-QA',codigo:'Reserva'})).resultado;
 const dst=(await wms('ubicacion',{almacen:'AUTO-QA',codigo:'Picking'})).resultado;
 const stock=await require('../src/services/plannerInventory').move(db,company,user,{articulo_id:art,tipo:'recepcion',almacen:src.almacen,ubicacion:src.codigo,lote:'L1',cantidad:100,motivo:'Ensayo sintético',operacion:crypto.randomUUID()});
 await db.query("UPDATE planner_existencias SET calidad='liberado' WHERE id=$1",[stock.id]);
 const rule=(await wms('regla_reposicion',{articulo_id:art,ubicacion_id:dst.id,minimo:10,objetivo:30,conteo_dias:30,motivo:'Mínimo de picking'})).resultado.regla;
 const proposals=()=>call('GET','/planner/wms/automatismos');let auto=await proposals(),proposal=auto.reposiciones.find(r=>r.regla_id===rule.id);assert.equal(proposal.movimientos[0].cantidad,30);
 assert.equal((await call('GET','/planner/wms/automatismos',null,200,other)).reglas.some(r=>r.id===rule.id),false);
 await call('POST','/planner/wms/accion',{accion:'regla_reposicion',operacion:crypto.randomUUID(),articulo_id:art,ubicacion_id:dst.id,minimo:10,objetivo:30,conteo_dias:30,motivo:'Otra empresa'},404,other);
 await call('POST','/planner/wms/accion',{accion:'reponer_propuesta',operacion:crypto.randomUUID(),regla_id:rule.id,huella:'stale',confirmado:true,motivo:'Ensayo'},409);
 const move={accion:'reponer_propuesta',operacion:crypto.randomUUID(),regla_id:rule.id,huella:proposal.huella,confirmado:true,motivo:'Traslado físico verificado'};
 await Promise.all([call('POST','/planner/wms/accion',move,201),call('POST','/planner/wms/accion',move,201)]);
 assert.equal(Number((await db.query('SELECT cantidad FROM planner_existencias WHERE id=$1',[stock.id])).rows[0].cantidad),70);
 auto=await proposals();assert.equal(auto.reposiciones.some(r=>r.regla_id===rule.id),false);const count=auto.conteos.find(r=>r.regla_id===rule.id);assert.ok(count);
 const opened=(await wms('abrir_conteo',{existencia_id:count.existencia_id})).resultado;
 assert.equal((await wms('abrir_conteo',{existencia_id:count.existencia_id})).resultado.id,opened.id);
 assert.equal((await proposals()).conteos.some(r=>r.existencia_id===count.existencia_id),false);
 await wms('confirmar_conteo',{conteo_id:opened.id,cantidad:30,motivo:'Conteo físico conforme'});
 assert.equal((await proposals()).conteos.some(r=>r.existencia_id===count.existencia_id),false);
 await require('../src/services/plannerAutomation').docks(db,company,{inicio:'2026-10-05T08:00:00Z'});
 await call('GET','/planner/wms/muelles-propuestos?inicio=2026-10-05T08%3A00%3A00Z');
 const routes={provider:'local',stops:[{id:'c',type:'carga',shipment_id:order,name:'Origen sintético',address:'Valencia',lat:39.47,lng:-.37,weight_kg:500},{id:'d',type:'descarga',shipment_id:order,name:'Destino sintético',address:'Madrid',lat:40.4,lng:-3.7,weight_kg:500}],constraints:{start_day:'2026-10-05',start_time:'08:00',capacity_kg:1000}};
 await call('POST','/route-optimizer/optimize',{...routes,pedido_id:order},403,other); // Planner alone has no transport optimizer.
 const carrier=(await call('POST','/auth/login',{email:'network-qa@example.invalid',password})).token;
 await call('POST','/route-optimizer/optimize',{...routes,pedido_id:order},404,carrier);
 await call('POST','/route-optimizer/optimize',{...routes,constraints:{start_day:'2026-03-29',start_time:'02:30'}},400);
 const route=await call('POST','/route-optimizer/optimize',routes);assert.equal(route.constraint_review.estado,'parcial');assert.ok(route.constraint_review.incidencias.some(i=>i.code==='TRAVEL'));assert.equal(route.constraint_review.paradas[1].arrival_at,null);
 return {checks,detentionNetLines:true,noDoubleCharge:true,revisionAndTenant:true,replenishmentAtomicRetry:true,cycleCounts:true,dockProposal:true};
};
