const assert=require('node:assert/strict'),crypto=require('crypto');
module.exports=async function({db,company,user,base,token,password,transportCompany,transportClient,sharedOrder,legacyToken,pdf,stock}){
 let checks=0;async function request(method,path,body,status=200,session=token){body=await require('./audit_company_login.cjs')(db,path,body);const response=await fetch(base+path,{method,headers:{Authorization:'Bearer '+session,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();assert.equal(response.status,status,JSON.stringify(data));checks++;return data;}
 const carrierUser=crypto.randomUUID();await db.query("INSERT INTO usuarios(id,empresa_id,nombre,email,password_hash,rol,activo) VALUES($1,$2,'Gerente Network sintético','network-qa@example.invalid',$3,'gerente',true)",[carrierUser,transportCompany,await require('bcryptjs').hash(password,4)]);
 const carrier=(await request('POST','/auth/login',{email:'network-qa@example.invalid',password})).token;
 const other=(await request('POST','/auth/login',{email:'planner-b@example.invalid',password})).token;
 const path='/transport-exchange',all=['pedidos','estados','recursos','eta','gps','documentos','pod','slots'];
 await request('POST',path+'/conectar',{token:legacyToken,cliente_id:transportClient,scopes:['pedidos'],acepta_condiciones:true},404,carrier);
 const op={pedido_id:sharedOrder.id,scopes:all,operacion:crypto.randomUUID()};
 const invitation=await request('POST',path+'/invitaciones',op,201);assert.equal((await request('POST',path+'/invitaciones',op,201)).token,invitation.token);
 await request('POST',path+'/invitaciones',{...op,scopes:['pedidos']},409);
 const view=await request('POST',path+'/previsualizar',{token:invitation.token},200,carrier);assert.equal(view.encargo.precio_colaborador,'350.00');assert.equal(view.encargo.importe,undefined);
 await request('POST',path+'/previsualizar',{token:invitation.token},404,other);
 await request('POST',path+'/previsualizar',{token:invitation.token},404);
 const accept=(invite,scopes=all)=>({token:invite.token,cliente_id:transportClient,scopes,acepta_condiciones:true});
 const linked=await request('POST',path+'/conectar',accept(invitation,['pedidos']),201,carrier);
 assert.equal((await request('POST',path+'/conectar',accept(invitation,['pedidos']),201,carrier)).viaje_id,linked.viaje_id);
 let trip=(await db.query('SELECT * FROM pedidos WHERE empresa_id=$1 AND id=$2',[transportCompany,linked.viaje_id])).rows[0];assert.equal(Number(trip.importe),350);
 await db.query("UPDATE pedidos SET estado='en_curso',updated_at=now() WHERE id=$1 AND empresa_id=$2",[trip.id,transportCompany]);
 await db.query("INSERT INTO pedido_docs(empresa_id,pedido_id,tipo,nombre,file_base64,file_mime) VALUES($1,$2,'pod','POD sintético.pdf',$3,'application/pdf')",[transportCompany,trip.id,pdf.file_base64]);
 await request('POST',path+'/sincronizar',{});
 assert.equal((await db.query('SELECT estado FROM pedidos WHERE id=$1',[sharedOrder.id])).rows[0].estado,'confirmado','unconsented states cannot propagate');
 assert.equal((await db.query("SELECT COUNT(*)::int AS n FROM pedido_docs WHERE pedido_id=$1 AND empresa_id=$2 AND tipo='pod'",[sharedOrder.id,company])).rows[0].n,0);
 const withheld=await request('GET',path+'/seguimiento/'+sharedOrder.id);assert.equal(withheld.gps,undefined);assert.equal(withheld.eta,undefined);assert.equal(withheld.estado,undefined);
 await request('GET',path+'/viajes/'+trip.id+'/albaran',null,404,carrier);
 await request('POST',path+'/viajes/'+trip.id+'/hueco',{},404,carrier);
 // Renew bilateral consent; extra fields in request cannot widen the source's offer.
 const restricted=await request('POST',path+'/invitaciones',{pedido_id:sharedOrder.id,scopes:['pedidos'],operacion:crypto.randomUUID()},201);
 await request('POST',path+'/conectar',accept(restricted,all),403,carrier);
 const renewed=await request('POST',path+'/invitaciones',{...op,operacion:crypto.randomUUID()},201);
 await request('POST',path+'/conectar',accept(renewed),201,carrier);
 await request('POST',path+'/sincronizar',{});await request('POST',path+'/sincronizar',{},200,carrier);
 const noChange=await request('POST',path+'/sincronizar',{});assert.equal(noChange.updated,0);assert.equal(noChange.documents,0,'retries do not create redundant events or copies');
 assert.equal((await db.query('SELECT estado FROM pedidos WHERE id=$1',[sharedOrder.id])).rows[0].estado,'en_curso');
 assert.equal((await db.query("SELECT COUNT(*)::int AS n FROM pedido_docs WHERE pedido_id=$1 AND empresa_id=$2 AND tipo='pod'",[sharedOrder.id,company])).rows[0].n,1);
 const vehicle=crypto.randomUUID();await db.query("INSERT INTO vehiculos(id,empresa_id,matricula,tipo) VALUES($1,$2,'QA-NET-001','tractora')",[vehicle,transportCompany]);
 await db.query('UPDATE pedidos SET vehiculo_id=$1 WHERE id=$2 AND empresa_id=$3',[vehicle,trip.id,transportCompany]);
 const now=new Date().toISOString();await require('../src/services/vehicleTracking').record(db,{empresaId:transportCompany,vehiculoId:vehicle,provider:'app',input:{lat:40.4,lng:-3.7,recorded_at:now,accuracy_m:10}});
 const state=await request('GET',path+'/seguimiento/'+sharedOrder.id);assert.equal(state.gps.status,'reciente');assert.equal(state.gps.position.lat,40.4);assert.equal(state.eta.value,null);
 await request('GET',path+'/seguimiento/'+sharedOrder.id,null,404,other);
 const estimated={value:new Date(Date.now()+600000).toISOString(),status:'estimado',provider:'osrm',definition:'Ensayo sintético'};
 await db.query('INSERT INTO tracking_eta_snapshot(empresa_id,pedido_id,position_recorded_at,eta) VALUES($1,$2,$3,$4)',[transportCompany,trip.id,now,JSON.stringify(estimated)]);
 assert.equal((await request('GET',path+'/seguimiento/'+sharedOrder.id)).eta.value,estimated.value);
 await db.query("UPDATE tracking_eta_snapshot SET position_recorded_at=position_recorded_at-interval '1 second' WHERE empresa_id=$1 AND pedido_id=$2",[transportCompany,trip.id]);
 assert.equal((await request('GET',path+'/seguimiento/'+sharedOrder.id)).eta.value,null,'ETA is invalidated by a different GPS fix');
 // Accepted price is stable through sync, then may be explicitly renegotiated.
 await db.query('UPDATE pedidos SET precio_colaborador=360 WHERE id=$1 AND empresa_id=$2',[sharedOrder.id,company]);await request('POST',path+'/sincronizar',{});
 assert.equal(Number((await db.query('SELECT importe FROM pedidos WHERE id=$1',[trip.id])).rows[0].importe),350);
 const priceInvite=await request('POST',path+'/invitaciones',{...op,operacion:crypto.randomUUID()},201);await request('POST',path+'/conectar',accept(priceInvite),201,carrier);
 assert.equal(Number((await db.query('SELECT importe FROM pedidos WHERE id=$1',[trip.id])).rows[0].importe),360);
 // A connected carrier receives the current immutable dispatch note, not legacy v1.
 await db.query("UPDATE pedidos SET origen_producto='planner' WHERE id=$1 AND empresa_id=$2",[sharedOrder.id,company]);
 const prep=await request('POST','/planner/inventario/preparaciones',{pedido_id:sharedOrder.id,lineas:[{existencia_id:stock.id,cantidad:1}]},201);
 let detail=await request('GET',`/planner/inventario/preparaciones/${prep.id}`);
 for(const line of detail.lineas)detail=await request('POST',`/planner/inventario/preparaciones/${prep.id}/accion`,{accion:'preparar_linea',linea_id:line.id,preparada:true,version:detail.version});
 detail=await request('POST',`/planner/inventario/preparaciones/${prep.id}/accion`,{accion:'lista',version:detail.version});
 const note1=await request('POST',`/planner/inventario/preparaciones/${prep.id}/albaran`,{},201);
 await db.query("UPDATE pedidos SET referencia_cliente='VERSIÓN NUEVA NETWORK' WHERE id=$1 AND empresa_id=$2",[sharedOrder.id,company]);
 const note2=await request('POST',`/planner/inventario/preparaciones/${prep.id}/albaran`,{},201);assert.notEqual(note1.id,note2.id);
 const privatePdf=await request('GET',`/planner/inventario/albaranes/${note2.id}/pdf`);
 const sharedPdf=await request('GET',path+'/viajes/'+trip.id+'/albaran',null,200,carrier);assert.equal(sharedPdf.version,2);assert.equal(sharedPdf.file_base64,privatePdf.file_base64);
 const supplierUser=crypto.randomUUID();await db.query("INSERT INTO usuarios(id,empresa_id,nombre,email,password_hash,rol,activo,colaborador_id) VALUES($1,$2,'Proveedor sintético Network','supplier-network-qa@example.invalid',$3,'colaborador',true,$4)",[supplierUser,company,await require('bcryptjs').hash(password,4),sharedOrder.colaborador_id]);
 const portal=(await request('POST','/auth/login',{email:'supplier-network-qa@example.invalid',password})).token;
 const portalPdf=await request('GET',`/supplier-app/pedidos/${sharedOrder.id}/albaran-salida`,null,200,portal);assert.equal(portalPdf.version,2);assert.equal(portalPdf.file_base64,privatePdf.file_base64);
 await request('GET',path+'/viajes/'+trip.id+'/albaran',null,404,other);
 await request('POST',`/planner/inventario/preparaciones/${prep.id}/accion`,{accion:'cancelar',version:detail.version,motivo:'Fin ensayo sintético'});
 // Economic exchange is opt-in even for an otherwise fully connected pair.
 const bp=path+'/facturacion/'+linked.conexion_id,invoice=crypto.randomUUID();
 await db.query("INSERT INTO facturas(id,empresa_id,numero,cliente_id,estado,base_imponible,cuota_iva,total) VALUES($1,$2,'QA-NET-INVOICE',$3,'emitida',360,75.60,435.60)",[invoice,transportCompany,transportClient]);
 await db.query('INSERT INTO factura_pedidos(factura_id,pedido_id) VALUES($1,$2)',[invoice,trip.id]);
 const original={factura_id:invoice,nombre:'QA-NET-INVOICE.pdf',base64:pdf.file_base64,confirmado:true};
 await request('POST',bp+'/compartir',original,403,carrier);
 await request('GET',bp,null,404,other);await request('GET',bp,null,403,portal);
 await request('POST',bp+'/consentimiento',{autorizar:true});
 assert.equal((await request('GET',bp,null,200,carrier)).autorizado,false);
 await request('POST',bp+'/consentimiento',{autorizar:true},200,carrier);
 assert.equal((await request('GET',bp,null,200,carrier)).autorizado,true);
 const sharedInvoice=await request('POST',bp+'/compartir',original,201,carrier);
 assert.equal((await request('POST',bp+'/compartir',original,201,carrier)).id,sharedInvoice.id);
 const recv=(await request('GET',bp)).facturas.find(f=>f.id===sharedInvoice.id);assert.equal(recv.revision,'revision');assert.equal(Number(recv.total),435.6);
 const stored=await request('GET','/supplier-invoice-review/'+recv.recibida_id+'/original');assert.equal(stored.base64,pdf.file_base64);
 await request('GET','/supplier-invoice-review/'+recv.recibida_id+'/original',null,404,carrier);
 assert.equal((await request('GET','/supplier-invoice-review/'+recv.recibida_id)).datos.lineas[0].pedido_id,sharedOrder.id);
 const coverage=(await db.query('SELECT conciliacion FROM factura_proveedor_lineas WHERE empresa_id=$1 AND factura_id=$2',[company,recv.recibida_id])).rows[0].conciliacion.documentacion;
 assert.equal(coverage.estado,'disponible_para_revision');assert.ok(coverage.documentos.length>0);
 await request('POST',bp+'/consentimiento',{autorizar:false},200,carrier);
 assert.equal((await request('GET',bp)).facturas.length,0);await request('POST',bp+'/compartir',original,403,carrier);
 assert.equal((await request('GET','/supplier-invoice-review/'+recv.recibida_id+'/original')).base64,pdf.file_base64,'recipient retains its received original after revocation');
 await request('DELETE',path+'/'+linked.conexion_id,null,404,other);
 await request('DELETE',path+'/'+linked.conexion_id,null,200,carrier);await request('DELETE',path+'/'+linked.conexion_id,null,200,carrier);
 await request('GET',path+'/seguimiento/'+sharedOrder.id,null,404);await request('GET',path+'/viajes/'+trip.id+'/albaran',null,404,carrier);
 await request('POST',path+'/conectar',accept(priceInvite),404,carrier);
 await db.query("UPDATE pedidos SET estado='entregado' WHERE id=$1 AND empresa_id=$2",[trip.id,transportCompany]);await request('POST',path+'/sincronizar',{});
 assert.equal((await db.query('SELECT estado FROM pedidos WHERE id=$1',[sharedOrder.id])).rows[0].estado,'en_curso');
 const audit=await request('GET',path+'/auditoria/'+linked.conexion_id);assert.ok(audit.datos.some(e=>e.tipo==='conexion.revocada'));await request('GET',path+'/auditoria/'+linked.conexion_id,null,404,other);
 return {checks,bilateral:true,scopes:true,agreedPrice:true,retry:true,currentImmutableNote:true,gpsAndEtaPrivacy:true,revoke:true,billingBilateral:true,billingOriginalAndReview:true,billingIdempotency:true};
};
