const assert=require('node:assert/strict'),crypto=require('crypto'),jwt=require('jsonwebtoken');
module.exports=async({db,base,company,token,password})=>{
 const service=require('../src/services/companyMembership'),groupBi=require('../src/services/companyGroupBi');
 const uid=jwt.decode(token).sub,other=crypto.randomUUID();
 await db.query("INSERT INTO empresas(id,nombre,cif,email_admin,plan,estado) VALUES($1,'GRUPO B SINTÉTICO','B00000007','group@example.invalid','enterprise','activa')",[other]);
 const call=async(method,path,body,t=token)=>{const r=await fetch(base+path,{method,headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 const save=async(companyId,values)=>{const row=(await db.query('SELECT * FROM usuario_empresas WHERE usuario_id=$1 AND empresa_id=$2',[uid,companyId])).rows[0];return service.saveMembership({usuario_id:uid,empresa_id:companyId,revision:row?.revision||0,rol:'gerente',permisos:{},activo:true,bi_consolidado:true,...values},'synthetic-auditor');};
 assert.equal((await service.memberships(uid)).filter(m=>m.empresa_id===company).length,1);
 await save(company,{});await save(other,{rol:'contable',permisos:{modulos:{nominas:{ver:false,editar:false}}}});
 assert.equal((await call('GET','/auth/companies')).data.companies.length,2);
 await db.query('UPDATE empresas SET bloqueo_manual=true WHERE id=$1',[company]);
 const login=await call('POST','/auth/login',{email:'audit@example.invalid',password});assert.equal(login.status,200,JSON.stringify(login.data));assert.equal(login.data.user.empresa_id,other);assert.equal(login.data.bloqueado,null);
 await db.query('UPDATE empresas SET bloqueo_manual=false WHERE id=$1',[company]);
 const portalCustomer=crypto.randomUUID(),portalUser=crypto.randomUUID();
 await db.query("INSERT INTO clientes(id,empresa_id,nombre) VALUES($1,$2,'Portal compartido sintético')",[portalCustomer,company]);
 await db.query("INSERT INTO usuarios(id,empresa_id,nombre,email,username,password_hash,rol,cliente_id,permisos) SELECT $1,$2,'Portal compartido','shared-portal@example.invalid','shared-portal',password_hash,'cliente',$3,'null'::jsonb FROM usuarios WHERE id=$4",[portalUser,company,portalCustomer,uid]);
 assert.deepEqual((await db.query('SELECT permisos FROM usuario_empresas WHERE usuario_id=$1',[portalUser])).rows[0].permisos,{});
 await service.saveMembership({usuario_id:portalUser,empresa_id:other,revision:0,rol:'visualizador',permisos:{},activo:true,bi_consolidado:false},'synthetic-auditor');
 assert.equal((await call('POST','/clientes/'+portalCustomer+'/portal-user',{reset_password:true})).status,403);

 const switched=await call('POST','/auth/company',{empresa_id:other});assert.equal(switched.status,200,JSON.stringify(switched.data));const bt=switched.data.token;
 const me=await call('GET','/auth/me',null,bt);assert.equal(me.data.empresa_id,other);assert.equal(me.data.rol,'contable');assert.equal(me.data.permisos.modulos.nominas.ver,false);
 assert.equal((await call('GET','/auth/me')).data.empresa_id,company);
 assert.equal((await call('POST','/auth/company',{empresa_id:crypto.randomUUID()})).status,403);
 const forged=jwt.sign({sub:uid,empresa_id:crypto.randomUUID(),rol:'gerente'},process.env.JWT_SECRET,{expiresIn:'5m'});assert.equal((await call('GET','/auth/me',null,forged)).status,401);
 const customer=crypto.randomUUID(),order=crypto.randomUUID();await db.query("INSERT INTO clientes(id,empresa_id,nombre) VALUES($1,$2,'Cliente grupo B')",[customer,other]);
 await db.query("INSERT INTO pedidos(id,empresa_id,cliente_id,numero,estado,fecha_descarga,importe,coste_otros,km_ruta,km_vacio) VALUES($1,$2,$3,'BI-GROUP-B','entregado','2026-09-20',600,200,400,100)",[order,other,customer]);
 assert.equal((await call('GET','/pedidos/'+order)).status,404);assert.equal((await call('GET','/pedidos/'+order,null,bt)).status,200);
 const group=await service.saveGroup({nombre:'Grupo QA explícito',empresas:[company,other]},'synthetic-auditor');
 const path='/informes/bi/consolidado?grupo_id='+group.id+'&desde=2026-09-20&hasta=2026-09-20';
 const consolidated=await call('GET',path);assert.equal(consolidated.status,200,JSON.stringify(consolidated.data));assert.equal(consolidated.data.empresas.length,2);assert.equal(consolidated.data.totales.ingreso,2100);assert.equal(consolidated.data.totales.margen_directo,650);assert.equal(consolidated.data.totales.km_totales,1500);assert.equal(consolidated.data.totales.ingreso_km,1.4);
 assert.equal((await call('GET','/usuarios')).status,200);
 assert.equal((await call('PATCH','/usuarios/'+uid,{nombre:'NOT ALLOWED'})).status,403);
 await save(other,{rol:'contable',activo:false});assert.equal((await call('GET','/auth/me',null,bt)).status,401);assert.equal((await call('GET',path)).status,403);
 await db.query(require('fs').readFileSync(require('path').join(__dirname,'migrations/20260927_multiempresa.sql'),'utf8'));
 assert.equal((await db.query('SELECT activo FROM usuario_empresas WHERE usuario_id=$1 AND empresa_id=$2',[uid,other])).rows[0].activo,false);
 await save(other,{rol:'cliente',cliente_id:customer,bi_consolidado:false,permisos:{modulos:{informes:{ver:true,editar:true}}}});
 const client=await call('POST','/auth/company',{empresa_id:other});assert.equal(client.status,200);assert.equal((await call('GET',path,null,client.data.token)).status,403);
 const inventedRole=jwt.sign({sub:uid,empresa_id:other,rol:'gerente'},process.env.JWT_SECRET,{expiresIn:'5m'});assert.equal((await call('GET','/auth/me',null,inventedRole)).data.rol,'cliente');
 await assert.rejects(()=>save(company,{rol:'cliente',cliente_id:customer,bi_consolidado:false}),/Ficha vinculada/);
 const source={economia:{ingreso_servicios_realizados:1500,costes_directos:{directo_registrado:1250},margen_directo:250,kilometros:{total:1000,vacios:200,cobertura:{total:2,evaluables:2}}}};
 assert.equal(groupBi.consolidate([source]).ingreso_km,1.5);source.economia.kilometros.cobertura.evaluables=1;assert.equal(groupBi.consolidate([source]).ingreso_km,null);
 const cache=require('../src/services/cache');cache.clear();let computes=0;
 const cached=(tenant,revision)=>{let body;const res={statusCode:200,setHeader(){},json(value){body=value;}};cache.cacheMiddleware(30)({method:'GET',originalUrl:'/fixture',empresaId:tenant,user:{id:uid,rol:'gerente',membership_revision:revision}},res,()=>{computes++;res.json({tenant,revision});});return body;};
 assert.equal(cached(company,1).tenant,company);cached(company,1);assert.equal(computes,1);assert.equal(cached(other,1).tenant,other);assert.equal(cached(company,2).revision,2);assert.equal(computes,3);
 await save(other,{rol:'contable',activo:process.env.AUDIT_BROWSER==='1'});
 return {membershipEveryRequest:true,scopeSwitch:true,rolesAndPermissions:true,revocation:true,forgedScopeDenied:true,consolidationReconciles:true,migrationReplay:true,sharedIdentityProtected:true};
};
