const assert=require('node:assert/strict'),crypto=require('node:crypto');
module.exports=async function({base,fetch,db,managerToken,driverToken,company}){
 let checks=0;
 const call=async(path,body,status=200,token=managerToken)=>{
   const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
   const data=await r.json();assert.equal(r.status,status,JSON.stringify(data));checks++;return data;
 };
 const ids=[crypto.randomUUID(),crypto.randomUUID()];
 for(const [i,id] of ids.entries())await db.query("INSERT INTO pedidos(id,empresa_id,numero,estado,origen,destino,importe,peso_kg,bultos,cliente_id) SELECT $1,$2,$3,'pendiente','Valencia','Madrid',600,1000,10,id FROM clientes WHERE empresa_id=$2 ORDER BY id LIMIT 1",[id,company,'REPLAN-SYN-'+i]);
 const group=await call('/pedidos/grupaje/combinar',{pedido_ids:ids,borrador:false,client_operation_uuid:crypto.randomUUID()});
 let model=await call(`/pedidos/${ids[0]}/operativa`),trip=model.viajes[0];
 const original=trip.paradas[0];
 await db.query("UPDATE viaje_paradas SET estado='finalizada',llegada_real_at='2026-09-27T07:00:00Z',fin_real_at='2026-09-27T08:00:00Z',evidencias='[{\"hash\":\"synthetic-original\"}]' WHERE empresa_id=$1 AND id=$2",[company,original.id]);
 await db.query("UPDATE viajes_operativos SET estado='en_curso',km_cargados=800,km_vacios=200 WHERE id=$1",[trip.id]);
 await db.query("UPDATE pedidos SET estado='en_curso' WHERE id=ANY($1::uuid[])",[ids]);
 const before=(await db.query('SELECT * FROM viaje_paradas WHERE id=$1',[original.id])).rows[0];
 const body={version:trip.version,client_operation_uuid:crypto.randomUUID(),motivo:'Cambiar orden de entrega',paradas:[trip.paradas[0].id,trip.paradas[1].id,trip.paradas[3].id,trip.paradas[2].id]};
 await call(`/pedidos/${ids[0]}/operativa/replanificar`,body,403,driverToken);
 await call(`/pedidos/${ids[0]}/operativa/replanificar`,{...body,paradas:[...body.paradas].reverse()},409);
 await call(`/pedidos/${crypto.randomUUID()}/operativa/replanificar`,body,409);
 let saved=await call(`/pedidos/${ids[0]}/operativa/replanificar`,body);
 assert.equal((await call(`/pedidos/${ids[0]}/operativa/replanificar`,body)).replayed,true);
 assert.deepEqual((await db.query('SELECT * FROM viaje_paradas WHERE id=$1',[original.id])).rows[0],before);
 await call(`/pedidos/${ids[0]}/operativa/replanificar`,{...body,client_operation_uuid:crypto.randomUUID()},409);
 const vehicle=crypto.randomUUID(),driver=crypto.randomUUID();
 await db.query("INSERT INTO vehiculos(id,empresa_id,matricula,clase,estado,activo) VALUES($1,$2,'RELEVO-SYN','tractora','disponible',true)",[vehicle,company]);
 await db.query("INSERT INTO choferes(id,empresa_id,nombre,estado,activo) VALUES($1,$2,'Conductor relevo sintético','disponible',true)",[driver,company]);
 const relief={...body,version:saved.version,client_operation_uuid:crypto.randomUUID(),asignacion:{vehiculo_id:vehicle,chofer_id:driver},ubicacion_relevo:'Base sintética',relevo_confirmado:true};
 saved=await call(`/pedidos/${ids[0]}/operativa/replanificar`,relief);
 trip=(await call(`/pedidos/${ids[0]}/operativa`)).viajes[0];
 assert.equal(trip.relevos.length,1);assert.equal(trip.relevos[0].siguiente.chofer_id,driver);
 assert.equal((await db.query('SELECT count(*)::int n FROM pedidos WHERE id=ANY($1::uuid[]) AND chofer_id=$2',[ids,driver])).rows[0].n,2);
 assert.equal((await db.query('SELECT count(*)::int n FROM viaje_plan_versiones WHERE viaje_id=$1',[trip.id])).rows[0].n,3);
 const rec=require('../src/services/financialJourneys').reconcileJourneys({empresaId:company,orders:ids.map(id=>({id})),journeys:[trip],members:ids.map(id=>({empresa_id:company,viaje_id:trip.id,pedido_id:id,peso_kg:1000}))});
 assert.equal(rec.orders.reduce((s,p)=>s+p.km_ruta+p.km_vacio,0),1000);
 assert.ok(rec.orders.every(p=>p.vehiculo_id===null&&p.bi_assignment_warning));
 await db.query("UPDATE viajes_operativos SET estado='entregado' WHERE id=$1",[trip.id]);
 await call(`/pedidos/${ids[0]}/operativa/replanificar`,{...relief,version:saved.version,client_operation_uuid:crypto.randomUUID()},409);
 return {checks,status:'passed',evidence:'Started group: immutable stop evidence, reordering, resources, version/retry, roles, missing journey, one physical distance and unresolved historical allocation'};
};
