const assert=require('node:assert/strict'),jwt=require('jsonwebtoken'),crypto=require('crypto');
module.exports=async({db,base,company,token})=>{
 const service=require('../src/services/integrationRegistry');
 const sa=jwt.sign({superadmin:true,id:'registry-audit'},process.env.SUPERADMIN_JWT_SECRET,{algorithm:'HS256',expiresIn:'5m'});
 const request=async(method,path,body,auth=sa)=>{const r=await fetch(base+'/superadmin/integraciones/registry'+path,{method,headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 assert.equal((await request('GET','?empresa_id='+company,null,token)).status,401);
 let result=await request('GET','?empresa_id='+company);assert.equal(result.status,200);assert.equal(result.data.rows.length,16);assert.ok(result.data.rows.every(r=>r.state==='planned'));
 const edit=async(input)=>{const row=(await service.list(company)).rows.find(r=>r.provider==='here');return request('PUT','/here',{empresa_id:company,revision:row.revision,...input});};
 assert.equal((await edit({state:'production_ready',environment:'production',api_version:'v8'})).status,409);
 assert.equal((await edit({state:'development',environment:'production',api_version:'v8'})).status,200);
 assert.equal((await edit({evidence:{criterion:'healthcheck',reference:'FAKE forged health',passed:true}})).status,400);
 for(const criterion of service.CRITERIA.filter(c=>c!=='healthcheck'))assert.equal((await edit({evidence:{criterion,reference:'Synthetic test evidence '+criterion,passed:true}})).status,200);
 assert.equal((await edit({state:'production_ready'})).status,409);
 await service.recordProbe(company,'here',{ok:true,reference:'Synthetic injected probe',environment:'sandbox',apiVersion:'v8'});
 assert.equal((await edit({state:'production_ready'})).status,409);
 await service.recordProbe(company,'here',{ok:true,reference:'Synthetic injected probe',environment:'production',apiVersion:'v8'});
 assert.equal((await edit({state:'production_ready'})).status,200);
 assert.equal((await service.list(company)).rows.find(r=>r.provider==='here').effective_state,'production_ready');
 assert.equal((await request('PUT','/here',{empresa_id:company,revision:0,state:'planned'})).status,409);
 const foreign=crypto.randomUUID();await db.query("INSERT INTO empresas(id,nombre,cif,email_admin,plan,estado) VALUES($1,'REGISTRY ISOLATED','B00000008','registry@example.invalid','starter','activa')",[foreign]);
 assert.equal((await service.list(foreign)).rows.find(r=>r.provider==='here').evidence.length,0);assert.equal((await service.list(null)).rows.find(r=>r.provider==='here').evidence.length,0);
 await service.recordProbe(company,'here',{ok:false,reference:'Synthetic failure',environment:'production',apiVersion:'v8'});
 assert.equal((await service.list(company)).rows.find(r=>r.provider==='here').effective_state,'degraded');
 await service.invalidate(company,'here');
 assert.equal((await service.list(company)).rows.find(r=>r.provider==='here').health,'failed');
 assert.equal((await edit({state:'development',api_version:'v9'})).status,200);assert.equal((await service.list(company)).rows.find(r=>r.provider==='here').missing.length,9);
 assert.equal(service.readiness({state:'production_ready',api_version:'v8',environment:'production'},service.CRITERIA.map(criterion=>({criterion,passed:true,api_version:'v8',environment:'production',source:'server_probe',created_at:new Date(Date.now()-31*864e5)}))).ready,false);
 return {httpAuthorization:true,evidenceGate:true,scopeIsolation:true,healthVersionEnvironment:true,staleness:true,conflicts:true,noExternalCalls:true};
};
