const assert=require('node:assert/strict');
const {serviceIncome}=require('../src/services/financialKpis');
const {buildEconomics}=require('../src/services/financialEconomics');
const {orderTotals}=require('../src/services/financialAnalytics');
const {evolution}=require('../src/services/financialWorkspace');
const {buildRouteSheet}=require('../src/services/financialRouteSheet');
const {fuelInvoiceLines,validateFuelInvoiceLines}=require('../src/services/invoiceFuelLines');
const range={desde:'2026-01-01',hasta:'2026-01-31'};
const p={id:'synthetic',empresa_id:'a',estado:'entregado',fecha_bi:'2026-01-05',importe:1000,importe_revision_combustible:50,importe_paralizacion:150,coste_operativo:600,coste_gasoil:600,km_ruta:800,km_vacio:200,pendiente_factura:true};
const economy=buildEconomics({empresaId:'a',range,orders:[p]});
assert.equal(serviceIncome(p),1150);assert.equal(serviceIncome({...p,importe:null}),null);
assert.equal(economy.ingreso_servicios_realizados,1150);assert.equal(economy.margen_directo,550);
assert.equal(economy.ingreso_km_total,1.15);assert.equal(economy.pendiente_facturar.importe,1150);
assert.equal(orderTotals([p]).ingresos,1150);assert.equal(evolution([p],'dia')[0].ingreso,1150);
assert.equal(buildRouteSheet({range,orders:[p],repostajes:[],noches:[],expenses:[],repairs:[]}).ingresos,1150);
const lines=fuelInvoiceLines(p);validateFuelInvoiceLines([p],lines);
assert.equal(lines.reduce((n,l)=>n+l.cantidad*l.precio_unit,0),1150);
assert.equal(lines.filter(l=>l.paralizacion_pedido_id===p.id).length,1);
assert.equal(economy.cobros_efectivos,null);
console.log('PASS detention: transport 1000 (fuel 50 included) + separately recorded detention 150 = income/invoice 1150, margin 550; unknown cash remains null.');

const {recoveryTotals}=require('../src/services/detentionWorkflow');
const claim={id:'c',empresa_id:'a',pedido_id:p.id,estado:'aceptada',documentado:200,aceptado:150};
const line={id:'l',pedido_id:p.id,importe:150};
const recovery=recoveryTotals('a',[p,{...p,id:'manual'}],[claim,claim,{...claim,id:'foreign',empresa_id:'b'}],[line,line,{id:'unmatched',pedido_id:'manual',importe:80}]);
assert.equal(recovery.documentado,200);assert.equal(recovery.aceptado,150);assert.equal(recovery.facturado,150);assert.equal(recovery.porcentaje,75);assert.equal(recovery.cobrado,null);assert.equal(recovery.facturado_sin_expediente,80);
assert.equal(recoveryTotals('b',[p],[claim],[line]).documentado,null);
assert.equal(recoveryTotals('a',[p],[{...claim,estado:'rechazada'}],[]).porcentaje,null);
assert.equal(recoveryTotals('a',[p],[{...claim,documentado:0,aceptado:0}],[]).documentado,0);
console.log('PASS detention recovery: weighted ratio, tenant/cohort, duplicate lines, documented zero and unlinked amounts.');
