const assert=require('node:assert/strict');
const {reconcileJourneys}=require('../src/services/financialJourneys');
const {buildEconomics,physicalKm}=require('../src/services/financialEconomics');
const period={desde:'2026-09-01',hasta:'2026-09-30'},company='a';
const orders=[1,2].map(n=>({id:'p'+n,empresa_id:company,estado:'entregado',fecha_bi:'2026-09-10',importe:n*500,peso_kg:n*500,bultos:n,vehiculo_id:'new-truck',coste_operativo:0}));
const journey={id:'j1',empresa_id:company,estado:'entregado',km_cargados:800,km_vacios:200,asignacion_snapshot:{vehiculo_id:'historic-truck'}};
const members=orders.map(p=>({...p,pedido_id:p.id,viaje_id:journey.id}));
const cost={id:'cost',empresa_id:company,viaje_id:'j1',importe_neto:1250,referencia:'synthetic'};
const reconcile=(more={})=>reconcileJourneys({empresaId:company,orders,journeys:[journey],members,costs:[cost],...more});
let data=reconcile(), economics=buildEconomics({empresaId:company,range:period,orders:data.orders});
assert.equal(economics.ingreso_km_total,1.5);assert.equal(economics.coste_km_total,1.25);assert.equal(economics.margen_km_total,0.25);assert.equal(economics.margen_directo,250);assert.equal(economics.porcentaje_vacio,20);assert.equal(economics.margen_directo_pct_sin_redondeo,250/1500*100);
assert.equal(data.orders[0].vehiculo_id,'historic-truck');assert.equal(data.orders[0].bi_journey_cost,416.66);assert.equal(data.orders[1].bi_journey_cost,833.34);
assert.equal(physicalKm(data.orders).total,1000);
const filtered=reconcile({orders:[orders[0]]});assert.equal(filtered.orders[0].bi_journey_cost,416.66,'stable denominator before dimension filter');
assert.equal(reconcile({costs:[cost,cost]}).reconciliation.costes_incluidos,1250);
assert.equal(reconcile({costs:[{...cost,anulado_at:'2026-09-10'}]}).reconciliation.costes_incluidos,0);
assert.equal(reconcile({costs:[{...cost,empresa_id:'other'}]}).reconciliation.costes_incluidos,0);
data=reconcile({orders:orders.map(p=>({...p,coste_operativo:10})),members:members.map(p=>({...p,coste_operativo:10}))});assert.equal(data.orders[0].coste_operativo,10);assert.equal(data.reconciliation.costes_sin_conciliar,1250,'no double cost');
data=reconcile({members:members.map(p=>({...p,peso_kg:null}))});assert.equal(data.orders[0].bi_legs[0].criterio,'bultos');
data=reconcile({members:members.map(p=>({...p,peso_kg:null,bultos:null}))});assert.equal(data.orders[0].km_ruta,null);assert.equal(data.reconciliation.costes_sin_conciliar,1250);
data=reconcile({journeys:[{...journey,km_vacios:null}]});assert.equal(buildEconomics({empresaId:company,range:period,orders:data.orders}).ingreso_km_total,null);
data=reconcile({costs:[{...cost,importe_neto:0}]});assert.equal(buildEconomics({empresaId:company,range:period,orders:data.orders}).costes_directos.directo_registrado,0,'recorded zero differs from no record');
const large=Array.from({length:1501},(_,i)=>({...orders[0],id:'large'+i,importe:1,coste_operativo:0,km_ruta:1}));
assert.equal(buildEconomics({empresaId:company,range:period,orders:large,page:1,limit:1}).ingreso_servicios_realizados,1501);assert.equal(buildEconomics({empresaId:company,range:period,orders:large,page:2,limit:100}).ingreso_servicios_realizados,1501);
console.log('PASS physical BI: weighted cents, 1501 orders, before-filter allocation, historic vehicle, scoped sources, cancellation, known zero, no duplicate costs, unknown quantities/km.');
