const assert=require('node:assert/strict');
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const {PGlite}=require('@electric-sql/pglite');
const provider=require('../src/services/fiscalProviderVerifacti');
const xml=require('../src/services/claveicon/xml');
const cfg={codemp:'005',ivaope:'1',ivadia:'01',ivacon:'NF',codusu:'SA',codtipopre:'G',codban:'30',sales_account:'700000000000001',customer_root:'430',sign_confirmed:true,amount_sign:1,ivagenast:true,ivbtret:'1'};
const party={nombre:'Muñoz & Hijos',cif:'B12345678',direccion:'Calle España 2',ciudad:'Jaén',provincia:'Jaén',cp:'23001'};
const invoice={numero:'A-2026-1',serie:'A',fecha:'2026-12-31',fecha_vencimiento:'2027-01-30',base_imponible:100,tipo_iva:21,cuota_iva:21,tipo_irpf:15,cuota_irpf:15,total:106};
function payload(rate=21){return {expedicion:{numero:'A-2026-1',serie:'A',fecha_factura:'2026-09-22'},emisor:{nif:'B12345678'},receptor:{nombre:'QA Cliente',nif:'B87654321'},importes:{base_imponible:100,tipo_iva:rate,cuota_iva:rate,cuota_irpf:15,total:100+rate-15},lineas:[{concepto:'Servicio'}]};}
async function main(){
 const officialUrlForImage='https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR?nif=B12345678';
 const suppliedQr=await require('qrcode').toBuffer(officialUrlForImage,{width:320});
 const {officialQrImage}=require('../src/services/fiscalQr');
 assert.deepEqual(await officialQrImage(officialUrlForImage,suppliedQr.toString('base64')),suppliedQr,'Keep the original provider PNG');
 assert.equal(await officialQrImage('https://example.invalid/qr',suppliedQr.toString('base64')),null);
 const {applyFiscalInvoiceSnapshot}=require('../src/services/fiscalInvoiceSnapshot');
 const currentInvoice={estado:'emitida',cliente_nombre:'Changed',cliente_cif:'Changed',cliente_direccion:'New address'};
 const frozenIdentity=applyFiscalInvoiceSnapshot(currentInvoice,{payload:{receptor:{nombre:'Original',nif:'Original NIF',direccion:'',cp:'28001',ciudad:'Madrid'},emisor:{nombre:'Issuer',nif:'Issuer NIF',domicilio:'Original address'}}});
 assert.equal(frozenIdentity.cliente_direccion,'');assert.equal(frozenIdentity.cliente_dir,'');assert.equal(frozenIdentity.cliente_nombre,'Original');assert.equal(frozenIdentity.emisor_fiscal.domicilio,'Original address');assert.equal(frozenIdentity.fiscal_identity_frozen,true);
 assert.deepEqual(applyFiscalInvoiceSnapshot({...currentInvoice,estado:'borrador'},{payload:{receptor:{nombre:'Original'}}}),{...currentInvoice,estado:'borrador'});
 for(const rate of [21,10,0]){const p=provider.mapInternalPayloadToVerifacti(payload(rate));assert.equal(p.importe_total,String(100+rate)+'.00');assert.equal(p.lineas[0].tipo_impositivo,String(rate));}
 const exempt=payload(0);exempt.importes.iva_regimen='exento';assert.throws(()=>provider.mapInternalPayloadToVerifacti(exempt),/exención/);exempt.importes.operacion_exenta='E1';assert.equal(provider.mapInternalPayloadToVerifacti(exempt).lineas[0].operacion_exenta,'E1');
 const corrected=payload();corrected.expedicion.rectificativa_de='A-2026-0';assert.throws(()=>provider.mapInternalPayloadToVerifacti(corrected),/rectificativa/);corrected.expedicion.rectificacion={tipo_factura:'R4',tipo_rectificativa:'I',original_numero:'A-2026-0',original_serie:'A',original_fecha:'2026-09-21'};assert.equal(provider.mapInternalPayloadToVerifacti(corrected).tipo_factura,'R4');
 assert.equal(provider.normalizeStatus('Enviado'),'pending');assert.equal(provider.normalizeStatus('Incorrecto'),'error');assert.equal(provider.normalizeStatus('Correcto'),'accepted');assert.equal(provider.normalizeStatus('Aceptado con errores'),'accepted_with_errors');assert.equal(provider.normalizeStatus('Anulado'),'error');
 assert.equal(provider.officialQrUrl('https://evil.invalid/qr'),null);
 const account=xml.buildAccountXml(party,'430000000000001',cfg).toString('latin1');assert.match(account,/codemp="005"/);assert.match(account,/Mu&#241;oz &amp; Hijos/);assert.match(account,/Ja&#233;n/);assert.ok([...account].every(c=>c.charCodeAt(0)<128));
 const sale=xml.buildInvoiceXml(invoice,party,'430000000000001',cfg).toString('latin1');assert.match(sale,/codeje="2026"/);assert.match(sale,/ivagenprev="0"/);assert.match(sale,/ivagenast="1"/);assert.match(sale,/ivatfra="106.00"/);
 const receivable=xml.buildReceivableXml(invoice,'430000000000001',cfg).toString('latin1');assert.match(receivable,/ejeemp="2026"/);assert.match(receivable,/prevto="2027-01-30 00:00:00"/);assert.match(receivable,/pretip="C"/);
 assert.throws(()=>xml.buildReceivableXml({...invoice,fecha_vencimiento:null},'430',cfg),/Fecha/);
 assert.throws(()=>xml.buildInvoiceXml(invoice,party,'430',{...cfg,sign_confirmed:false}),/CONFIRMACIÓN/);
 assert.throws(()=>xml.buildInvoiceXml({...invoice,factura_original_id:'original'},party,'430',cfg),/CONFIRMACIÓN/);
 const pg=new PGlite();const db={query:(...a)=>pg.query(...a),transaction:fn=>pg.transaction(c=>fn(c))};require.cache[require.resolve('../src/services/db')]={exports:db};
 await pg.exec(`CREATE TABLE empresas(id uuid PRIMARY KEY,nombre text,configuracion jsonb,cfg_precios jsonb);CREATE TABLE usuarios(id uuid PRIMARY KEY);CREATE TABLE clientes(id uuid PRIMARY KEY,empresa_id uuid,nombre text,cif text,email text,email_facturacion text,direccion text,cp text,ciudad text,pais text);CREATE TABLE facturas(id uuid PRIMARY KEY,empresa_id uuid,cliente_id uuid,numero text,serie text,fecha date,fecha_vencimiento date,estado text,base_imponible numeric,tipo_iva numeric,cuota_iva numeric,tipo_irpf numeric,cuota_irpf numeric,total numeric,iva_regimen text,factura_original_id uuid,factura_original_numero text);CREATE TABLE factura_lineas(id uuid, factura_id uuid,concepto text,cantidad numeric,precio_unit numeric,orden int);`);
 const migration=fs.readFileSync(path.join(__dirname,'migrations/022_fiscal_accounting_delivery.sql'),'utf8');await pg.exec(migration);await pg.exec(migration);
 const eid=crypto.randomUUID(),fid=crypto.randomUUID(),cid=crypto.randomUUID(),rid=crypto.randomUUID(),qid=crypto.randomUUID();
 const fiscalCfg={modo:'verifactu',entorno:'pruebas',nif_declarante:'B12345678',verifactu:{proveedor:'verifacti',provider_base_url:'https://api.verifacti.com',provider_api_key:'test-only'}};
 await pg.query('INSERT INTO empresas VALUES($1,$2,$3,$4)',[eid,'QA',JSON.stringify({facturacion_fiscal:fiscalCfg,claveicon:{...cfg,enabled:true}}),'{}']);
 await pg.query('INSERT INTO clientes(id,empresa_id,nombre,cif) VALUES($1,$2,$3,$4)',[cid,eid,party.nombre,party.cif]);
 await pg.query(`INSERT INTO facturas(id,empresa_id,cliente_id,numero,serie,fecha,fecha_vencimiento,estado,base_imponible,tipo_iva,cuota_iva,tipo_irpf,cuota_irpf,total) VALUES($1,$2,$3,'A-2026-1','A','2026-12-31','2027-01-30','emitida',100,21,21,15,15,106)`,[fid,eid,cid]);
 await pg.query("INSERT INTO factura_registros_fiscales(id,empresa_id,factura_id,modo,huella,payload) VALUES($1,$2,$3,'verifactu','hash',$4)",[rid,eid,fid,JSON.stringify(payload())]);
 await pg.query("INSERT INTO factura_envios_fiscales(id,registro_id,factura_id,empresa_id,sistema,payload) VALUES($1,$2,$3,$4,'verifactu',$5)",[qid,rid,fid,eid,JSON.stringify(payload())]);
 await pg.query("UPDATE factura_envios_fiscales SET idempotency_key=$1,request_payload=$2,request_hash=$3,first_attempt_at=NOW() WHERE id=$4",[`transgest:${eid}:${fid}:${rid}`,JSON.stringify(provider.mapInternalPayloadToVerifacti(payload())),require('../src/services/fiscalIdentity').digest(provider.mapInternalPayloadToVerifacti(payload())),qid]);
 let calls=[];const originalFetch=global.fetch;
 global.fetch=async(url,options)=>{if(url.endsWith('/health'))return new Response(JSON.stringify({estado:'OK',nif:'B12345678',entorno:'test'}),{status:200});calls.push({url,options});return new Response(JSON.stringify({uuid:'provider-qa',estado:'Pendiente',url:'https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR?nif=B12345678',qr:'test-qr'}),{status:200});};
 try{
  const {processPendingFiscalQueue}=require('../src/services/fiscalProcessor');
  await db.transaction(c=>processPendingFiscalQueue({empresaId:eid,client:c}));
  assert.equal(calls.length,1);assert.match(calls[0].options.headers['Idempotency-Key'],/^transgest:/);
  let item=(await pg.query('SELECT * FROM factura_envios_fiscales WHERE id=$1',[qid])).rows[0];assert.equal(item.provider_uuid,'provider-qa');assert.equal(item.estado,'pendiente');
  const queue=require('../src/services/fiscalQueueState');
  await db.transaction(c=>queue.markQueueAccepted(c,item,{provider:'verifacti',provider_uuid:'provider-qa',provider_status:'accepted',response:{estado:'Correcto'}},null));
  await db.transaction(c=>queue.markQueueAccepted(c,item,{provider:'verifacti',provider_status:'accepted'},null));
  await db.transaction(c=>queue.markQueuePending(c,item,{provider:'verifacti',provider_status:'pending'},null));
  assert.equal((await pg.query('SELECT estado FROM factura_envios_fiscales WHERE id=$1',[qid])).rows[0].estado,'aceptado');
  assert.equal((await pg.query('SELECT count(*)::int AS n FROM accounting_invoice_outbox')).rows[0].n,0);
  assert.equal(await queue.findLatestQueueItemByProviderUuid(pg,crypto.randomUUID(),'verifactu','provider-qa'),null);
  const outbox=require('../src/services/claveicon/outbox');
  await db.transaction(c=>outbox.recoverAcceptedInvoices(c,eid));
  await db.transaction(c=>outbox.recoverAcceptedInvoices(c,eid));
  let entries=(await pg.query('SELECT * FROM accounting_invoice_outbox')).rows;
  assert.equal(entries.length,3,'Recovery is idempotent and only follows committed acceptance');
  const accountJob=entries.find(r=>r.entity_type==='account'),invoiceJob=entries.find(r=>r.entity_type==='invoice');
  await assert.rejects(()=>db.transaction(c=>outbox.exportEntity(c,eid,invoiceJob.id)),/Confirma primero/);
  const file=await db.transaction(c=>outbox.exportEntity(c,eid,accountJob.id));assert.match(file.buffer.toString(),/cuecod="430000000000001"/);
  await pg.query("UPDATE accounting_invoice_outbox SET status='synced' WHERE id=$1",[accountJob.id]);
  const exported=await db.transaction(c=>outbox.exportEntity(c,eid,invoiceJob.id));assert.match(exported.buffer.toString(),/ivatfra="106.00"/);
  const receivableJob=entries.find(r=>r.entity_type==='receivable');
  await assert.rejects(()=>db.transaction(c=>outbox.exportEntity(c,eid,receivableJob.id)),/Confirma primero/);
  await pg.query("UPDATE accounting_invoice_outbox SET status='synced' WHERE id=$1",[invoiceJob.id]);
  const exportedReceivable=await db.transaction(c=>outbox.exportEntity(c,eid,receivableJob.id));
  assert.match(exportedReceivable.buffer.toString(),/preimporte="106.00"/);
  await pg.query("UPDATE accounting_invoice_outbox SET status='synced' WHERE id=$1",[receivableJob.id]);
  assert.equal((await pg.query("SELECT count(*)::int AS n FROM accounting_invoice_outbox WHERE factura_id=$1 AND status='synced'",[fid])).rows[0].n,3);
  await assert.rejects(()=>db.transaction(c=>outbox.exportEntity(c,crypto.randomUUID(),invoiceJob.id)),/no encontrado/);
  const {validSignature}=require('../src/services/verifactiWebhook');const raw=Buffer.from('[{"uuid":"qa"}]');const signature=crypto.createHmac('sha256','qa-secret').update(raw).digest('hex');assert.ok(validSignature(raw,signature,'qa-secret'));assert.equal(validSignature(Buffer.from('[]'),signature,'qa-secret'),false);
  // Real review + emission services, including a response lost after registration.
  await pg.exec(`ALTER TABLE facturas ADD COLUMN observaciones text;ALTER TABLE facturas ADD COLUMN referencia_cliente text;ALTER TABLE facturas ADD COLUMN updated_by uuid;
   CREATE TABLE pedidos(id uuid,empresa_id uuid,factura_id uuid,numero text,estado text,cliente_id uuid,referencia_cliente text,origen text,destino text,fecha_carga date,fecha_descarga date,importe numeric,peso_kg numeric,mercancia text);
   CREATE TABLE factura_pedidos(factura_id uuid,pedido_id uuid);
   CREATE TABLE pedido_docs(id uuid,pedido_id uuid,empresa_id uuid,tipo text,nombre text,file_base64 text,file_url text);
   CREATE TABLE factura_extracostes(id uuid,factura_id uuid,tipo text,concepto text,importe numeric);`);
  const review=require('../src/services/invoiceReview');await review.ensureSchema();
  const draft=crypto.randomUUID();
  await pg.query(`INSERT INTO facturas(id,empresa_id,cliente_id,numero,serie,fecha,fecha_vencimiento,estado,base_imponible,tipo_iva,cuota_iva,tipo_irpf,cuota_irpf,total) VALUES($1,$2,$3,'A-2026-2','A','2026-09-22','2026-10-22','borrador',100,21,21,0,0,121)`,[draft,eid,cid]);
  await pg.query("UPDATE empresas SET configuracion=jsonb_set(configuracion,'{facturacion_fiscal,verifactu,envio_automatico}','true') WHERE id=$1",[eid]);
  const emission=require('../src/services/fiscalEmission');
  assert.throws(()=>emission.assertRepresentation({entorno:'produccion',nif_declarante:'B12345678',verifactu:{representacion:{estado:'pendiente'}}}),/representación/);
  await assert.rejects(()=>emission.prepareFiscalEmission({facturaId:draft,empresaId:eid}),/revisión/);
  await db.transaction(c=>review.review(c,draft,eid,null,''));
  let creates=0,lookups=0;
  const officialUrl='https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR?nif=B12345678';
  global.fetch=async(url,options)=>{
   if(url.endsWith('/health'))return new Response(JSON.stringify({estado:'OK',nif:'B12345678',entorno:'test'}));
   if(url.endsWith('/create')){creates++;throw new Error('Simulated response lost after provider registered invoice');}
   if(options.method==='POST'){lookups++;return new Response(JSON.stringify({uuid:'lost-response',estado:'Correcta'}));}
   return new Response(JSON.stringify({uuid:'lost-response',estado:'Correcto',url:officialUrl}));
  };
  await assert.rejects(()=>emission.prepareFiscalEmission({facturaId:draft,empresaId:eid}),/lost/);
  const frozen=(await pg.query('SELECT * FROM factura_envios_fiscales WHERE factura_id=$1',[draft])).rows[0];
  assert.ok(frozen.idempotency_key && frozen.request_hash && frozen.first_attempt_at);
  assert.equal((await pg.query('SELECT estado FROM facturas WHERE id=$1',[draft])).rows[0].estado,'borrador');
  await pg.query('UPDATE factura_envios_fiscales SET next_retry_at=NOW() WHERE factura_id=$1',[draft]);
  await emission.prepareFiscalEmission({facturaId:draft,empresaId:eid});
  assert.equal(creates,1,'Reconciliation must never create a second provider record');assert.equal(lookups,1);
  assert.equal((await pg.query('SELECT count(*)::int AS n FROM accounting_invoice_outbox WHERE factura_id=$1',[draft])).rows[0].n,0,'Draft must not be accounted');
  await pg.query("UPDATE facturas SET estado='emitida' WHERE id=$1",[draft]);
  await db.transaction(c=>outbox.recoverAcceptedInvoices(c,eid));
  assert.equal((await pg.query('SELECT count(*)::int AS n FROM accounting_invoice_outbox WHERE factura_id=$1',[draft])).rows[0].n,3);
  const finalized=(await pg.query('SELECT * FROM factura_registros_fiscales WHERE factura_id=$1',[draft])).rows[0];
  assert.equal(finalized.official_qr_url,officialUrl);assert.ok(finalized.official_qr_base64.startsWith('iVBOR'));
  const beforeHash=finalized.huella;
  await db.transaction(c=>require('../src/services/fiscal').ensureFacturaFiscalRecord({facturaId:draft,empresaId:eid,force:true,client:c}));
  assert.equal((await pg.query('SELECT huella FROM factura_registros_fiscales WHERE factura_id=$1',[draft])).rows[0].huella,beforeHash);
  await assert.rejects(()=>db.transaction(c=>require('../src/services/fiscalMetadata').saveFiscalMetadata(c,draft,eid,null,{})),/no se pueden modificar/);
  const pdf=await require('../src/services/invoicePdf').buildFacturaPdfBuffer({...invoice,estado:'emitida',fiscal:finalized},[{concepto:'QA',cantidad:1,precio_unit:100}],{nombre:'QA'});
  const pdfText=await require('pdf-parse')(new Uint8Array(pdf));assert.match(pdfText.text,/VERI\*FACTU/);
  const express=require('express');const app=express();
  app.use(express.json({limit:'1mb',verify(req,res,bytes){req.rawBody=Buffer.from(bytes);}}));
  app.use(require('../src/routes/fiscal_webhook'));
  await pg.query("UPDATE empresas SET configuracion=jsonb_set(configuracion,'{facturacion_fiscal,verifactu,provider_webhook_secret}','\"qa-secret\"') WHERE id=$1",[eid]);
  const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
  try {
   const eventId=crypto.randomUUID();
   const webhookBody=JSON.stringify([{uuid:'lost-response',nif:'B12345678',estado:'Pendiente'}]);
   const send=(body,signature,id=eventId)=>originalFetch(`http://127.0.0.1:${server.address().port}/webhook/verifacti/${eid}`,{method:'POST',headers:{'content-type':'application/json','X-Webhook-Id':id,'X-Webhook-Signature':signature},body});
   const sign=body=>crypto.createHmac('sha256','qa-secret').update(body).digest('hex');
   assert.equal((await send(webhookBody,'0'.repeat(64))).status,401);
   assert.equal((await send(webhookBody,sign(webhookBody))).status,202);
   assert.equal((await (await send(webhookBody,sign(webhookBody))).json()).duplicate,true);
   const changed=webhookBody.replace('Pendiente','Correcto');assert.equal((await send(changed,sign(changed))).status,409);
   const wrongNif=webhookBody.replace('B12345678','B00000000');assert.equal((await send(wrongNif,sign(wrongNif),crypto.randomUUID())).status,400);
   await db.transaction(c=>require('../src/services/verifactiWebhook').processReceipts(c,eid));
   assert.equal((await pg.query('SELECT estado_envio FROM factura_registros_fiscales WHERE factura_id=$1',[draft])).rows[0].estado_envio,'aceptado','Late pending webhook cannot undo acceptance');
   assert.equal((await pg.query('SELECT count(*)::int AS n FROM fiscal_webhook_receipts')).rows[0].n,1);
  }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
 }finally{global.fetch=originalFetch;await pg.close();}
 console.log('Fiscal/ClaveiCon: mapping, XML, migration, idempotency, acceptance, isolation, HMAC and ordered exports passed.');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
