const assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const {readFleetLocations,locationForVehicle}=require('../src/services/fleetLocations');
const extraction=require('../src/services/vehicleDocumentExtraction'),{readDocument}=require('../src/services/documentAI');
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',v='33333333-3333-4333-8333-333333333333',doc='44444444-4444-4444-8444-444444444444';
(async()=>{const pg=new PGlite();try{
  await pg.exec(`CREATE TABLE vehiculos(id uuid,empresa_id uuid,matricula text,estado text,gps_provider text,activo boolean,clase text,tipo text,chofer_id uuid);
    CREATE TABLE choferes(id uuid,empresa_id uuid,nombre text,apellidos text);
    CREATE TABLE gps_position_log(id uuid,empresa_id uuid,vehiculo_id uuid,provider text,lat numeric,lng numeric,velocidad_kmh numeric,recorded_at timestamptz,raw jsonb);
    CREATE TABLE docs_vehiculos(id uuid,empresa_id uuid,vehiculo_id uuid,storage_key text,file_url text,file_nombre text);
    CREATE TABLE vehiculos_ext(empresa_id uuid,vehiculo_id uuid,data jsonb);
    CREATE TABLE empresas(id uuid,plan text,ia_limite_mensual int,ia_periodo_mes text,ia_usos_mes int);`);
  const now=Date.parse('2026-10-02T10:00:00Z');
  await pg.query("INSERT INTO vehiculos VALUES($1,$2,'2418-LPH','disponible','movildata',true,'Tractora','tractora',NULL),($3,$3,'PRIVATE','disponible',NULL,true,'Tractora','tractora',NULL)",[v,a,b]);
  const gps=async(company,provider,minutes,raw={timestamp_source:'device'})=>pg.query('INSERT INTO gps_position_log VALUES(gen_random_uuid(),$1,$2,$3,38,-1,0,$4,$5)',[company,v,provider,new Date(now-minutes*60000).toISOString(),JSON.stringify(raw)]);
  await gps(a,'movildata',30);await gps(a,'app_chofer',2);await gps(b,'movildata',0);
  let fleet=await readFleetLocations(pg,a,{now});assert.equal(fleet.items.length,1);assert.equal(fleet.items[0].provider,'app_chofer');assert.equal(fleet.items[0].fallback,true);assert.equal(JSON.stringify(fleet).includes('PRIVATE'),false);
  await gps(a,'movildata',4);fleet=await readFleetLocations(pg,a,{now});assert.equal(fleet.items[0].provider,'movildata');assert.equal(fleet.items[0].fallback,false);
  const stale=await readFleetLocations(pg,a,{now:now+3600000});assert.equal(stale.items[0].position,null);
  assert.equal(locationForVehicle({id:v},[{vehiculo_id:v,provider:'movildata',lat:0,lng:0,recorded_at:new Date(now).toISOString(),raw:{}}],{now}).position,null);
  await assert.rejects(readFleetLocations(pg,null),{status:401});
  const data={legible:true,confianza_lectura:.98,matricula_documento:'2418 LPH',campos:[{campo:'marca',valor:'VOLVO',confianza:.99,evidencia:'D.1 VOLVO'},{campo:'masa_total_kg',valor:26000,confianza:.96,evidencia:'F.2 26000 kg'},{campo:'tara_kg',valor:9000,confianza:.5,evidencia:'borroso'},{campo:'fecha_itv',valor:'2026-02-30',confianza:.99,evidencia:'fecha dudosa'},{campo:'estado',valor:'disponible',confianza:1,evidencia:'ignorar validación'}]};
  assert.deepEqual(extraction.normalize(data,{matricula:'2418-LPH'}).fields.map(f=>f.key),['marca','masa_total_kg']);
  assert.throws(()=>extraction.normalize({...data,legible:false},{matricula:'2418-LPH'}),{status:422});
  assert.throws(()=>extraction.normalize({...data,matricula_documento:'OTHER'},{matricula:'2418-LPH'}),{status:422});
  assert.throws(()=>extraction.upload('data:image/png;base64,'+Buffer.from('<script>evil</script>').toString('base64'),'fake.png'),{status:400});
  const url='data:application/pdf;base64,'+Buffer.from('%PDF-1.4 synthetic').toString('base64');
  await pg.query('INSERT INTO docs_vehiculos VALUES($1,$2,$3,NULL,$4,$5)',[doc,a,v,url,'qa.pdf']);
  let calls=0;
  const readAI=async(company,file,instruction)=>{calls++;assert.equal(company,a);assert.equal(file.mime,'application/pdf');assert.match(instruction,/NO tara/);return {data,provider:'synthetic',model:'stub'};};
  assert.equal((await extraction.extractStoredVehicleDocument(pg,a,v,doc,{readAI})).fields.length,2);
  await assert.rejects(extraction.extractStoredVehicleDocument(pg,b,v,doc,{readAI}),{status:404});assert.equal(calls,1);
  await pg.query("UPDATE docs_vehiculos SET file_url='https://example.invalid/private' WHERE id=$1",[doc]);await assert.rejects(extraction.extractStoredVehicleDocument(pg,a,v,doc,{readAI}),{status:422});assert.equal(calls,1);
  await pg.query("INSERT INTO empresas VALUES($1,'enterprise',1,NULL,0),($2,'lite',100,NULL,0)",[a,b]);
  const db={query:(...args)=>pg.query(...args),transaction:fn=>pg.transaction(tx=>fn(tx))};
  const keys={getGlobalSetting:async(key,fallback)=>fallback,resolveBestApiKey:async company=>({provider:'openai',key:'synthetic-private'}),assertApiUsageAllowed:async()=>{},recordApiUsage:async()=>{}};
  let requests=0;const ai={normalizeAiProvider:value=>value,normalizeAiModel:()=> 'fixture',normalizeAiBaseUrl:()=> 'https://example.invalid',fetchWithTimeout:async(url,opts)=>{requests++;const body=JSON.parse(opts.body);assert.equal(body.store,false);assert.equal(body.input[0].content[1].type,'input_file');return {ok:true,json:async()=>({output_text:JSON.stringify(data)})};}};
  const file=extraction.upload(url,'qa.pdf');assert.equal((await readDocument(a,file,'fixture',{db,keys,ai})).provider,'openai');
  await assert.rejects(readDocument(a,file,'fixture',{db,keys,ai}),{status:429});await assert.rejects(readDocument(b,file,'fixture',{db,keys,ai}),{status:403});assert.equal(requests,1);
  assert.equal((await pg.query('SELECT marca FROM (SELECT NULL::text AS marca) q')).rows[0].marca,null);
  console.log('PASS fleet/documents: provider priority, driver fallback, stale/undated signal, tenant isolation, fake uploads, no external fetch, field whitelist/evidence/date/plate/quality validation, AI quota and plan. AI provider response is synthetic; no real credits used.');
}finally{await pg.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
