const assert=require('node:assert/strict'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const {PGlite}=require('@electric-sql/pglite');
const inbox=require('../src/services/orderInbox'),{verifySignature}=require('../src/routes/orderInboxInbound');
(async()=>{
 const pg=new PGlite(),db={query:(...a)=>pg.query(...a),transaction:fn=>pg.transaction(tx=>fn({query:(...a)=>tx.query(...a)}))};
 try{
  const sql=fs.readFileSync(path.join(__dirname,'migrations/20260926_ai_inbox.sql'),'utf8');await pg.exec(sql);await pg.exec(sql);
  await pg.exec('CREATE TABLE pedidos(id UUID,empresa_id UUID,numero TEXT)');
  const a=crypto.randomUUID(),b=crypto.randomUUID(),u=crypto.randomUUID();
  const body={texto:'Cliente: Pruebas\nOrigen: Madrid\nDestino: Valencia\nCarga: 25/09/2026',message_id:'<synthetic@example.invalid>'};
  const item=await inbox.receive(db,a,u,body);assert.equal(item.state,'nuevo');
  assert.equal((await inbox.receive(db,a,u,body)).id,item.id);
  assert.notEqual((await inbox.receive(db,b,u,body)).id,item.id);
  await assert.rejects(inbox.receive(db,a,u,{...body,texto:'Otra orden completamente distinta'}),{status:409});
  const otherBody={texto:'Otra orden con identificador independiente',message_id:'<second@example.invalid>'};
  await inbox.receive(db,a,u,otherBody);
  await assert.rejects(inbox.receive(db,a,u,{...otherBody,message_id:body.message_id}),{status:409});
  await assert.rejects(inbox.get(db,b,item.id),{status:404});
  const stored=(await db.query('SELECT encrypted_payload FROM ai_inbox_items WHERE id=$1',[item.id])).rows[0];assert.ok(stored.encrypted_payload.startsWith('v1:'));assert.ok(!stored.encrypted_payload.includes('Madrid'));
  const claimed=await inbox.claim(db,a,item.id,u);await assert.rejects(inbox.claim(db,a,item.id,u),{status:409});
  await assert.rejects(inbox.finish(db,a,item.id,crypto.randomUUID(),u,{},null),{status:409});
  const result={pedido:{cliente_id:crypto.randomUUID(),origen:'Madrid',destino:'Valencia',fecha_carga:'2026-09-25'}};
  const reviewed=await inbox.finish(db,a,item.id,claimed.token,u,result);assert.equal(reviewed.state,'revisar');assert.equal((await inbox.claim(db,a,item.id,u)).replay,true);
  await assert.rejects(inbox.changeState(db,a,item.id,u,{state:'listo',version:reviewed.version}),{status:422});
  await assert.rejects(inbox.changeState(db,a,item.id,u,{state:'listo',version:1,reviewed:true}),{status:409});
  const ready=await inbox.changeState(db,a,item.id,u,{state:'listo',version:reviewed.version,reviewed:true});assert.equal(ready.reviewed_by,u);
  const payload={...result.pedido,importe:100};const meta={inbox_id:item.id,human_reviewed:true};
  await assert.rejects(db.transaction(tx=>inbox.lockForCreation(tx,a,u,{...meta,human_reviewed:false},payload)),{status:409});
  const pedidoId=crypto.randomUUID();
  await assert.rejects(db.transaction(async tx=>{const lock=await inbox.lockForCreation(tx,a,u,meta,payload);await tx.query('INSERT INTO pedidos VALUES($1,$2,$3)',[pedidoId,a,'TEST']);await inbox.created(tx,a,lock.id,u,pedidoId,lock.creationHash);throw Error('rollback');}),/rollback/);
  assert.equal((await inbox.get(db,a,item.id)).state,'listo');assert.equal((await db.query('SELECT * FROM pedidos')).rows.length,0);
  await db.transaction(async tx=>{const lock=await inbox.lockForCreation(tx,a,u,meta,payload);await tx.query('INSERT INTO pedidos VALUES($1,$2,$3)',[pedidoId,a,'TEST']);await inbox.created(tx,a,lock.id,u,pedidoId,lock.creationHash);});
  assert.equal((await db.transaction(tx=>inbox.lockForCreation(tx,a,u,meta,payload))).replay.id,pedidoId);
  await assert.rejects(db.transaction(tx=>inbox.lockForCreation(tx,a,u,meta,{...payload,importe:200})),{status:409});
  await assert.rejects(inbox.changeState(db,a,item.id,u,{state:'descartado',version:3}),{status:409});
  assert.throws(()=>inbox.validatePayload({texto:'a'.repeat(20001)}));
  assert.throws(()=>inbox.validatePayload({attachments:[{name:'falso.pdf',mediaType:'application/pdf',base64:Buffer.from('MZejecutable').toString('base64')}]}));
  assert.throws(()=>inbox.validatePayload({attachments:Array(9).fill({})}));
  const eml=Buffer.from('Message-ID: <mime-test@example.invalid>\r\nSubject: Carga de prueba\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary="BOUNDARY"\r\n\r\n--BOUNDARY\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: base64\r\n\r\n'+Buffer.from(body.texto).toString('base64')+'\r\n--BOUNDARY\r\nContent-Type: text/plain\r\nContent-Disposition: attachment; filename="orden.txt"\r\nContent-Transfer-Encoding: base64\r\n\r\n'+Buffer.from('Mercancia: cemento 20 palets').toString('base64')+'\r\n--BOUNDARY--');
  const mime=await inbox.receive(db,a,u,{attachments:[{name:'correo.eml',base64:eml.toString('base64')}]});
  const decoded=await inbox.expandEmails((await inbox.get(db,a,mime.id,{payload:true})).payload);assert.match(decoded.texto,/Madrid/);assert.equal(decoded.attachments[0].name,'orden.txt');assert.ok(mime.message_hash);
  const failed=await inbox.claim(db,a,mime.id,u);await inbox.finish(db,a,mime.id,failed.token,u,null,'fixture failure');assert.equal((await inbox.get(db,a,mime.id)).state,'error');assert.ok((await inbox.claim(db,a,mime.id,u)).token);
  const secret=crypto.randomBytes(32).toString('hex'),raw=Buffer.from('{}'),ts=String(Math.floor(Date.now()/1000));
  const sig='sha256='+crypto.createHmac('sha256',secret).update(ts+'.').update(raw).digest('hex');
  assert.equal(verifySignature(raw,ts,sig,secret),true);assert.equal(verifySignature(Buffer.from('{"x":1}'),ts,sig,secret),false);assert.equal(verifySignature(raw,ts,sig,secret,Date.now()+600000),false);
  assert.equal(inbox.inboundConfiguration(a,{}).address,null);
  console.log('PASS inbox: durable encrypted originals, Message-ID/content dedup, tenant isolation, analysis lease, human review, optimistic concurrency, creation retry/rollback, MIME email, limits and inbound signature. No external AI/mail.');
 }finally{await pg.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
