const assert=require('node:assert/strict'),crypto=require('crypto'),wms=require('../src/services/plannerWms'),inventory=require('../src/services/plannerInventory');
// Uses the real migrated PostgreSQL-compatible database of planner_inventory_check.
module.exports=async function({db,company,other,user}){
 const call=(accion,body={})=>wms.act(db,company,user,{accion,operacion:crypto.randomUUID(),...body});
 const current=async id=>(await db.query('SELECT * FROM planner_existencias WHERE id=$1',[id])).rows[0];
 const a=(await db.query("INSERT INTO planner_articulos(empresa_id,referencia,descripcion,unidad,peso_kg) VALUES($1,'WMS-QA','Sintético WMS','unidad',2) RETURNING id",[company])).rows[0].id;
 const loc=(await call('ubicacion',{almacen:'WMS-QA',codigo:'A-01',zona:'Recepción'})).resultado;
 const dest=(await call('ubicacion',{almacen:'WMS-QA',codigo:'B-01'})).resultado;
 const asn=(await call('asn',{referencia:'ASN-QA',fecha_prevista:'2030-01-01',lineas:[{articulo_id:a,cantidad:10}]})).resultado;
 const receipt={accion:'recibir',operacion:crypto.randomUUID(),asn_id:asn.id,linea_id:asn.lineas[0].id,ubicacion_id:loc.id,cantidad:6,lote:'L1',caducidad:'2030-06-30'};
 const first=await wms.act(db,company,user,receipt);assert.equal(first.resultado.estado,'parcial');assert.equal(first.resultado.discrepancia,-4);
 assert.deepEqual(await wms.act(db,company,user,receipt),first);
 await assert.rejects(wms.act(db,company,user,{...receipt,cantidad:7}),/otra operación/);
 await assert.rejects(wms.act(db,other,user,{...receipt,operacion:crypto.randomUUID()}),/no disponible/);
 const sid=first.resultado.existencia_id;assert.equal(Number((await current(sid)).cantidad),6);
 await assert.rejects(call('recibir',{...receipt,operacion:crypto.randomUUID(),caducidad:'2031-01-01'}),/caducidad/);
 assert.equal(Number((await current(sid)).cantidad),6,'expiry conflict rolls back receipt');
 const oid=crypto.randomUUID();await db.query("INSERT INTO pedidos(id,empresa_id,numero,estado,origen_producto) VALUES($1,$2,'WMS-QA','pendiente','planner')",[oid,company]);
 const prepare=()=>inventory.prepare(db,company,user,{pedido_id:oid,lineas:[{existencia_id:sid,cantidad:2}]});
 await assert.rejects(prepare(),/calidad/);
 await call('calidad',{existencia_id:sid,version:(await current(sid)).version,calidad:'liberado',motivo:'Inspección conforme'});
 const proposal=await wms.suggest(db,company,a,'FEFO');assert.equal(proposal.datos[0].id,sid);assert.equal(proposal.cobertura,'completo');
 assert.equal((await wms.suggest(db,other,a,'FEFO')).datos.length,0);
 const prep=await prepare();
 await assert.rejects(call('trasladar',{existencia_id:sid,version:(await current(sid)).version,ubicacion_id:dest.id,cantidad:5,motivo:'Reposición'}),/reservada/);
 const transfer={accion:'trasladar',operacion:crypto.randomUUID(),existencia_id:sid,version:(await current(sid)).version,ubicacion_id:dest.id,cantidad:3,motivo:'Reposición picking'};
 const moved=await wms.act(db,company,user,transfer);await wms.act(db,company,user,transfer);
 assert.equal(Number((await current(sid)).cantidad),3);assert.equal(Number((await current(moved.resultado.destino)).cantidad),3);
 const stale=(await call('abrir_conteo',{existencia_id:moved.resultado.destino})).resultado;
 await call('calidad',{existencia_id:moved.resultado.destino,version:(await current(moved.resultado.destino)).version,calidad:'bloqueado',motivo:'Reinspección'});
 await assert.rejects(call('confirmar_conteo',{conteo_id:stale.id,cantidad:3,motivo:'Igual cantidad'}),/Hubo movimientos/);
 const count=(await call('abrir_conteo',{existencia_id:moved.resultado.destino})).resultado;
 const counted=await call('confirmar_conteo',{conteo_id:count.id,cantidad:0,motivo:'Merma verificada'});assert.equal(counted.resultado.diferencia,-3);
 assert.equal(Number((await current(moved.resultado.destino)).cantidad),0);
 const excess=await call('recibir',{...receipt,operacion:crypto.randomUUID(),cantidad:5});assert.equal(excess.resultado.discrepancia,1);assert.equal(excess.resultado.estado,'recibida');
 assert.equal((await current(sid)).calidad,'pendiente','new receipt quarantines mixed lot');
 const closed=await call('cerrar_asn',{asn_id:asn.id,motivo:'Se acepta una unidad adicional'});assert.equal(closed.resultado.discrepancias.length,1);
 await assert.rejects(call('recibir',{...receipt,operacion:crypto.randomUUID()}),/no disponible/);
 const makeCode=prefix=>{for(let i=0;i<10;i++)if(wms.gs1Check(prefix+i))return prefix+i;};
 const sscc=makeCode('12345678901234567'),gtin=makeCode('1234567890123');
 const parsed=wms.parseGs1(`(01)${gtin}(17)300600(10)L1(37)12`);assert.equal(parsed.lote,'L1');assert.equal(parsed.cantidad,12);
 assert.throws(()=>wms.parseGs1(`(01)${gtin}(17)301332`),/Fecha/);
 assert.throws(()=>wms.parseGs1('(00)123456789012345670'),/control/);
 await call('gtin',{articulo_id:a,gtin});await assert.rejects(wms.act(db,other,user,{accion:'gtin',operacion:crypto.randomUUID(),articulo_id:a,gtin}),/no encontrado/);
 const pl=(await db.query('SELECT id FROM planner_preparacion_lineas WHERE preparacion_id=$1',[prep.id])).rows[0].id;
 const pack=await call('packing',{preparacion_id:prep.id,sscc,lineas:[{linea_id:pl,cantidad:2}]});assert.equal(pack.resultado.sscc,sscc);
 await assert.rejects(call('packing',{preparacion_id:prep.id,sscc:makeCode('22345678901234567'),lineas:[{linea_id:pl,cantidad:1}]}),/excede/);
 await assert.rejects(call('checkin',{reserva_id:crypto.randomUUID()}),/no encontrada/);
 const dock=(await db.query("INSERT INTO planner_muelles(id,empresa_id,nombre,almacen) VALUES(gen_random_uuid(),$1,'QA-WMS','WMS-QA') RETURNING id",[company])).rows[0].id;
 const reservation=(await db.query("INSERT INTO planner_reservas(id,empresa_id,muelle_id,pedido_id,tipo,inicio,fin) VALUES(gen_random_uuid(),$1,$2,$3,'carga',now(),now()+interval '1 hour') RETURNING id",[company,dock,oid])).rows[0].id;
 const arrival={accion:'checkin',operacion:crypto.randomUUID(),reserva_id:reservation};assert.equal((await wms.act(db,company,user,arrival)).resultado.estado,'en_muelle');await wms.act(db,company,user,arrival);
 await assert.rejects(call('checkin',{reserva_id:reservation}),/ya registró/);
 await inventory.transition(db,company,user,prep.id,{accion:'cancelar',version:2,motivo:'Fin ensayo'});
 assert.equal(Number((await current(sid)).reservado),0,'blocked quality still allows cancellation');
 console.log('PASS WMS: ASN, QC, quarantine, transactional transfers, count revision/zero, expiry, GS1, SSCC, FIFO/FEFO, check-in, tenant isolation and idempotency');
};
