const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {PGlite}=require('@electric-sql/pglite');
const inventory=require('../src/services/plannerInventory');
(async()=>{
 const pg=new PGlite(),company=crypto.randomUUID(),other=crypto.randomUUID(),user=crypto.randomUUID(),order=crypto.randomUUID(),order2=crypto.randomUUID();
 const db={query:(s,a)=>pg.query(s,a),transaction:fn=>pg.transaction(tx=>fn({query:(s,a)=>tx.query(s,a)}))};
 try{
 await pg.exec(`CREATE TABLE empresas(id uuid PRIMARY KEY);CREATE TABLE usuarios(id uuid PRIMARY KEY);CREATE TABLE colaboradores(id uuid PRIMARY KEY);
 CREATE TABLE pedidos(id uuid PRIMARY KEY,empresa_id uuid,numero text,estado text,puntos_descarga jsonb);
 CREATE TABLE facturas(id uuid PRIMARY KEY,empresa_id uuid);CREATE TABLE clientes(id uuid PRIMARY KEY);CREATE TABLE pedido_docs(id uuid PRIMARY KEY);
 INSERT INTO empresas VALUES('${company}'),('${other}');INSERT INTO usuarios VALUES('${user}');
 INSERT INTO pedidos VALUES('${order}','${company}','PED-1','confirmado','[{"ciudad":"Madrid"},{"ciudad":"Toledo"}]'),('${order2}','${company}','PED-2','pendiente','[]');`);
 await pg.exec('ALTER TABLE pedidos ADD peso_kg numeric;ALTER TABLE pedidos ADD palets_cantidad numeric;ALTER TABLE pedidos ADD bultos numeric;ALTER TABLE pedidos ADD mercancia text;ALTER TABLE pedidos ADD cliente_id uuid;ALTER TABLE pedidos ADD colaborador_id uuid;ALTER TABLE pedidos ADD colaborador_precio_confirmado boolean');
 const sql=fs.readFileSync(path.join(__dirname,'migrations/019_planner_inventory.sql'),'utf8');await pg.exec(sql);await pg.exec(sql);
 const article=(await pg.query("INSERT INTO planner_articulos(empresa_id,referencia,descripcion,coste,precio_venta) VALUES($1,'REF-1','Artículo',2,3) RETURNING id",[company])).rows[0].id;
 const movement={articulo_id:article,tipo:'fabricacion',almacen:'Principal',ubicacion:'A1',lote:'L1',cantidad:'24,2',motivo:'Fabricación terminada',operacion:crypto.randomUUID()};
 const first=await inventory.move(db,company,user,movement),repeated=await inventory.move(db,company,user,movement);assert.equal(first.id,repeated.id);
 await assert.rejects(inventory.move(db,company,user,{...movement,cantidad:40}),/otro movimiento/);
 let stock=(await pg.query('SELECT * FROM planner_existencias')).rows[0];assert.equal(Number(stock.cantidad),24.2,'retry cannot duplicate receipt');
 await assert.rejects(inventory.move(db,other,user,{...movement,operacion:crypto.randomUUID()}),/disponible/);
 await assert.rejects(inventory.prepare(db,company,user,{pedido_id:order,lineas:[{existencia_id:stock.id,cantidad:30}]}),/insuficiente/);
 assert.equal((await pg.query('SELECT * FROM planner_preparaciones')).rows.length,0,'failed preparation rolls back');
 const prep=await inventory.prepare(db,company,user,{pedido_id:order,lineas:[{existencia_id:stock.id,cantidad:10,parada:1},{existencia_id:stock.id,cantidad:10,parada:2}]});
 stock=(await pg.query('SELECT * FROM planner_existencias')).rows[0];assert.equal(Number(stock.reservado),20);
 await assert.rejects(inventory.prepare(db,company,user,{pedido_id:order2,lineas:[{existencia_id:stock.id,cantidad:5}]}),/insuficiente/);
 await assert.rejects(inventory.move(db,company,user,{...movement,tipo:'ajuste',cantidad:-10,operacion:crypto.randomUUID()}),/reservada/);
 await assert.rejects(inventory.transition(db,company,user,prep.id,{version:1,accion:'lista'}),/todas las líneas/);
 await assert.rejects(inventory.transition(db,other,user,prep.id,{version:1,accion:'lista'}),/no encontrada/);
 let version=1;const act=async body=>{const row=await inventory.transition(db,company,user,prep.id,{version,...body});version=row.version;return row;};
 const lines=(await pg.query('SELECT * FROM planner_preparacion_lineas WHERE preparacion_id=$1',[prep.id])).rows;
 for(const l of lines)await act({accion:'preparar_linea',linea_id:l.id,preparada:true});
 await assert.rejects(inventory.transition(db,company,user,prep.id,{version:1,accion:'lista'}),/ha cambiado/);
 await act({accion:'lista'});await assert.rejects(act({accion:'expedir'}),/camión cargado/);
 for(const situacion of ['espera_carga','cargando','cargado'])await act({accion:'camion',situacion});
 const done=await act({accion:'expedir'});assert.equal(done.estado,'expedida');assert.equal(done.situacion_camion,'salida');
 await assert.rejects(act({accion:'expedir'}),/cerrada/);
 stock=(await pg.query('SELECT * FROM planner_existencias')).rows[0];assert.equal(Number(stock.reservado),0);assert.equal(Number(stock.cantidad),4.2);
 const cancel=await inventory.prepare(db,company,user,{pedido_id:order2,lineas:[{existencia_id:stock.id,cantidad:4}]});
 await inventory.transition(db,company,user,cancel.id,{version:1,accion:'cancelar',motivo:'Cambio de fecha'});
 stock=(await pg.query('SELECT * FROM planner_existencias')).rows[0];assert.equal(Number(stock.reservado),0);assert.equal(Number(stock.cantidad),4.2);
 const retry=await inventory.prepare(db,company,user,{pedido_id:order2,lineas:[{existencia_id:stock.id,cantidad:1}]});assert.notEqual(retry.id,cancel.id,'cancelled preparation can be replaced without erasing history');
 const customer=crypto.randomUUID(),supplier=crypto.randomUUID();await pg.query('INSERT INTO colaboradores VALUES($1)',[supplier]);await pg.query('UPDATE pedidos SET cliente_id=$1 WHERE id=$2',[customer,order]);
 const {saleLines}=require('../src/services/plannerInvoice');
 await assert.rejects(saleLines(db,company,prep.id,other),/otro cliente/);
 await assert.rejects(saleLines(db,other,prep.id,customer),/no encontrada/);
 await pg.query('UPDATE planner_articulos SET precio_venta=999,peso_kg=999 WHERE id=$1',[article]);
 const invoiceLines=await saleLines(db,company,prep.id,customer);assert.equal(invoiceLines.length,2);assert.equal(Number(invoiceLines[0].precio_unit),3,'invoice uses agreed snapshot price');
 await pg.query('INSERT INTO facturas(id,empresa_id,planner_preparacion_id) VALUES($1,$2,$3)',[crypto.randomUUID(),company,prep.id]);
 await assert.rejects(saleLines(db,company,prep.id,customer),/ya tiene una factura/);
 const {requestSlot}=require('../src/services/plannerSupplierSlots'),{reserve}=require('../src/services/plannerBooking');
 await pg.query('UPDATE pedidos SET colaborador_id=$1,colaborador_precio_confirmado=false WHERE id=$2',[supplier,order2]);
 const tomorrow=new Date();tomorrow.setUTCDate(tomorrow.getUTCDate()+2);tomorrow.setUTCHours(8,0,0,0);const end=new Date(+tomorrow+3600000),slot={inicio:tomorrow.toISOString(),fin:end.toISOString()};
 await assert.rejects(requestSlot(db,company,supplier,user,order2,slot),/Acepta/);
 await pg.query('UPDATE pedidos SET colaborador_precio_confirmado=true WHERE id=$1',[order2]);
 await assert.rejects(requestSlot(db,other,supplier,user,order2,slot),/no encontrada/);
 const requested=await requestSlot(db,company,supplier,user,order2,slot);
 await assert.rejects(requestSlot(db,company,supplier,user,order2,slot),/pendiente/);
 const dock=crypto.randomUUID();await pg.query("INSERT INTO planner_muelles(id,empresa_id,nombre,almacen,dias) VALUES($1,$2,'M1','Principal','{1,2,3,4,5,6,7}')",[dock,company]);
 const booked=await reserve(db,company,user,{...slot,muelle_id:dock,tipo:'carga',pedido_id:order2,solicitud_id:requested.id});assert.ok(booked.id);
 assert.equal((await pg.query('SELECT estado FROM planner_solicitudes_hueco WHERE id=$1',[requested.id])).rows[0].estado,'asignada');
 await assert.rejects(requestSlot(db,company,supplier,user,order2,slot),/ya tiene un hueco/);
 await assert.rejects(reserve(db,company,user,{...slot,muelle_id:dock,tipo:'carga'}),/reservado/);
 const movements=(await pg.query('SELECT * FROM planner_movimientos')).rows;assert.equal(movements.filter(m=>m.tipo==='expedicion').length,2);
 console.log('PASS Planner: migration repeat, decimal stock, retry, tenant isolation, transactional shortage, reservations, multi-stop picking, version conflicts, ordered truck states, single dispatch, release/reprepare, snapshot sale price, duplicate invoice rejection, accepted supplier slot requests and atomic assignment');
 }finally{await pg.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
