const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
function route(file,db){const h={},uses=[],router={use(...f){uses.push(...f);}};for(const v of ['get','post','put','patch','delete'])router[v]=(p,...f)=>h[v+' '+p]=f.at(-1);const s={module:{exports:{}},Date,URL,console,require(n){if(n==='express')return{Router:()=>router};if(n.includes('/db'))return db;if(n.includes('/supportSchema')){const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/services/supportSchema.js'),'utf8'),{module,require:()=>db});return module.exports;}if(n.includes('/auth'))return{requireRole:()=>()=>{}};if((n==='./planner_inventory'||n==='./planner_vehicles'||n==='./planner_providers'))return {};if(n.includes('/plannerBooking'))return require('../src/services/plannerBooking');if(n==='crypto')return require('node:crypto');if(n.includes('uploadValidation'))return require('../src/services/uploadValidation');if(file==='cliente_portal.js')return {};throw Error(n);}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/routes',file),'utf8'),s);return{h,uses,exported:s.module.exports};}
const res=()=>({code:200,status(c){this.code=c;return this;},json(data){this.data=data;return this;}}),next=e=>{if(e)throw e;};
async function main(){const pg=new PGlite();const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',u='33333333-3333-4333-8333-333333333333',v='44444444-4444-4444-8444-444444444444';
 const db={query:async(sql,args)=>!args&&sql.includes(';')?(await pg.exec(sql)).at(-1):pg.query(sql,args),transaction:async fn=>{await pg.exec('BEGIN');try{const result=await fn(db);await pg.exec('COMMIT');return result;}catch(e){await pg.exec('ROLLBACK');throw e;}}};
 try{await pg.exec(`CREATE TABLE empresas(id uuid PRIMARY KEY,nombre text);CREATE TABLE usuarios(id uuid PRIMARY KEY,nombre text);CREATE TABLE colaboradores(id uuid PRIMARY KEY,empresa_id uuid,nombre text);CREATE TABLE pedidos(id uuid PRIMARY KEY,empresa_id uuid,numero text,estado text,origen text,destino text,colaborador_id uuid);INSERT INTO empresas VALUES('${a}','A'),('${b}','B');INSERT INTO usuarios VALUES('${u}','U'),('${v}','V');`);
 const support=route('soporte.js',db);support.exported.createSupportRouter();await support.exported.ensureSchema();const req={user:{id:u,nombre:'U'},empresaId:a,body:{asunto:'Consulta',mensaje:'Mensaje privado'},params:{}};let r=res();await support.h['post /'](req,r,next);assert.equal(r.code,201);const id=r.data.id;
 r=res();await support.h['get /:id']({...req,empresaId:b,params:{id}},r,next);assert.equal(r.code,404);
 r=res();await support.h['post /:id/mensajes']({...req,user:{id:v},params:{id},body:{mensaje:'No autorizado'}},r,next);assert.equal(r.code,404);
 const admin=route('soporte.js',db);admin.exported.createSupportRouter(true);r=res();await admin.h['post /:id/mensajes']({...req,superadmin:{id:'admin'},params:{id},body:{mensaje:'Respuesta de soporte'}},r,next);assert.equal(r.code,200);
 r=res();await support.h['get /:id']({...req,params:{id}},r,next);assert.equal(r.data.mensajes.length,2);assert.equal(r.data.estado,'respondida');
 // Read receipts retain SQL microseconds for both actors, and never consume later messages.
 await pg.query("UPDATE soporte_mensajes SET created_at='2026-09-16T20:00:00.123456Z' WHERE solicitud_id=$1",[id]);
 await pg.query('UPDATE soporte_solicitudes SET usuario_leido_at=NULL,soporte_leido_at=NULL WHERE id=$1',[id]);
 for(const [router,request] of [[support,req],[admin,{...req,superadmin:{id:'admin'}}]]){
   r=res();await router.h['get /'](request,r,next);assert.equal(r.data[0].sin_leer,1);
   await router.h['get /:id']({...request,params:{id}},res(),next);
   r=res();await router.h['get /'](request,r,next);assert.equal(r.data[0].sin_leer,0,'Reading must clear a microsecond timestamp');
 }
 await pg.query("INSERT INTO soporte_mensajes(id,solicitud_id,autor_id,autor_nombre,desde_soporte,mensaje,created_at) VALUES(gen_random_uuid(),$1,'admin','Soporte',true,'Nueva respuesta','2026-09-16T20:00:00.123789Z')",[id]);
 r=res();await support.h['get /'](req,r,next);assert.equal(r.data[0].sin_leer,1,'A later response remains unread');
 const query=db.query;
 let delayedRead;
 db.query=async(sql,args)=>{if(sql.startsWith('UPDATE soporte_solicitudes s SET usuario_leido_at')){delayedRead=[sql,args];return {rows:[]};}return query(sql,args);};
 await support.h['get /:id']({...req,params:{id}},res(),next);
 db.query=query;
 await pg.query("INSERT INTO soporte_mensajes(id,solicitud_id,autor_id,autor_nombre,desde_soporte,mensaje,created_at) VALUES(gen_random_uuid(),$1,'admin','Soporte',true,'Durante lectura','2026-09-16T20:00:00.124789Z')",[id]);
 await query(...delayedRead);
 r=res();await support.h['get /'](req,r,next);assert.equal(r.data[0].sin_leer,1,'Do not mark an unseen concurrent reply as read');
 await support.h['get /:id']({...req,params:{id}},res(),next);
 await query(...delayedRead);
 r=res();await support.h['get /'](req,r,next);assert.equal(r.data[0].sin_leer,0,'An older concurrent read must not rewind the receipt');
 await pg.exec('ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS peso_kg numeric;CREATE TABLE IF NOT EXISTS clientes(id uuid PRIMARY KEY);CREATE TABLE IF NOT EXISTS pedido_docs(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,pedido_id uuid,empresa_id uuid,nombre text,tipo text,file_base64 text,file_mime text,file_size_kb integer,notas text,created_at timestamptz DEFAULT now());CREATE TABLE facturas(id uuid PRIMARY KEY,empresa_id uuid)');await pg.exec(fs.readFileSync(path.join(__dirname,'migrations/019_planner_inventory.sql'),'utf8'));const planner=route('planner.js',db);r=res();await planner.h['post /muelles']({...req,body:{nombre:'M1',almacen:'Principal'}},r,next);assert.equal(r.code,201);const dock=r.data.id;
 const booking={...req,body:{muelle_id:dock,tipo:'carga',inicio:'2026-09-15T08:00:00Z',fin:'2026-09-15T09:00:00Z'}};r=res();await planner.h['post /reservas'](booking,r,next);assert.equal(r.code,201);
 r=res();await planner.h['post /reservas'](booking,r,next);assert.equal(r.code,409);
 r=res();await planner.h['post /reservas']({...booking,empresaId:b},r,next);assert.equal(r.code,404);
 r=res();await planner.h['post /reservas']({...booking,body:{...booking.body,inicio:'2026-09-15T09:15:00Z',fin:'2026-09-15T10:15:00Z'}},r,next);assert.equal(r.code,201);
 await pg.exec(`CREATE TABLE puntos_interes(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,empresa_id uuid,cliente_id uuid,nombre text,direccion text,codigo_postal text,ciudad text,provincia text,pais text,lat numeric,lng numeric,tipo text,ventana text,contacto_nombre text,contacto_telefono text,email text,notas text,metadata jsonb,activo boolean DEFAULT true,clientes_ids uuid[] DEFAULT '{}');`);
 const portal=route('cliente_portal.js',db),pointReq={...req,user:{...req.user,cliente_id:v},body:{nombre:'Almacén',direccion:'Calle Mayor 1',codigo_postal:'28001',ciudad:'Madrid',google_maps_url:'https://maps.google.com/?q=40.4,-3.7',tipo:'carga'}};
 r=res();await portal.h['post /puntos'](pointReq,r,next);assert.equal(r.code,201);assert.equal(r.data.codigo_postal,'28001');assert.equal(r.data.metadata.google_maps_url,pointReq.body.google_maps_url);
 r=res();await portal.h['get /puntos'](pointReq,r,next);assert.equal(r.data.length,1);assert.equal(r.data[0].metadata.google_maps_url,pointReq.body.google_maps_url);
 r=res();await portal.h['get /puntos']({...pointReq,empresaId:b},r,next);assert.equal(r.data.length,0);
 r=res();await portal.h['post /puntos']({...pointReq,body:{...pointReq.body,google_maps_url:'javascript:alert(1)'}},r,next);assert.equal(r.code,400);
 await pg.exec(`ALTER TABLE empresas ADD plan text;ALTER TABLE empresas ADD email_admin text;ALTER TABLE empresas ADD email_facturacion text;ALTER TABLE usuarios ADD empresa_id uuid;ALTER TABLE usuarios ADD rol text;ALTER TABLE usuarios ADD email text;ALTER TABLE usuarios ADD username text;CREATE TABLE invitaciones_usuario(usuario_id uuid,usado_at timestamptz);UPDATE empresas SET email_admin='old@example.invalid' WHERE id='${a}';UPDATE usuarios SET empresa_id='${a}',rol='gerente',email='old@example.invalid',username='old@example.invalid' WHERE id='${u}';UPDATE usuarios SET empresa_id='${a}',rol='trafico',email='traffic@example.invalid',username='traffic' WHERE id='${v}';INSERT INTO invitaciones_usuario VALUES('${u}',NULL);`);
 const code=fs.readFileSync(path.join(__dirname,'../src/routes/superadminCore.js'),'utf8');let patch;
 const start=code.indexOf('router.patch("/empresas/:id",');const end=code.indexOf('router.post("/empresas/:id/reset-password"',start);
 vm.runInNewContext(code.slice(start,end),{router:{patch:(p,...f)=>{patch=f.at(-1);}},superAuth:()=>{},db,audit:async()=>{},normalizeBillingMethod:x=>x,console});
 r=res();await patch({params:{id:a},body:{email_admin:'new@example.invalid',email_facturacion:'billing@example.invalid'}},r);assert.equal(r.code,200);
 const accounts=(await pg.query('SELECT id,email,username FROM usuarios ORDER BY id')).rows;assert.equal(accounts.find(x=>x.id===u).email,'new@example.invalid');assert.equal(accounts.find(x=>x.id===u).username,'new@example.invalid');assert.equal(accounts.find(x=>x.id===v).email,'traffic@example.invalid');assert.ok((await pg.query('SELECT usado_at FROM invitaciones_usuario')).rows[0].usado_at);
 r=res();await patch({params:{id:a},body:{email_admin:'traffic@example.invalid'}},r);assert.equal(r.code,409);assert.equal((await pg.query('SELECT email_admin FROM empresas WHERE id=$1',[a])).rows[0].email_admin,'new@example.invalid');
 await pg.exec(`ALTER TABLE pedidos ADD conductor_proveedor_usuario_id uuid;CREATE TABLE IF NOT EXISTS pedido_docs(id uuid DEFAULT gen_random_uuid() PRIMARY KEY,pedido_id uuid,empresa_id uuid,nombre text,tipo text,file_base64 text,file_mime text,file_size_kb integer,notas text,created_at timestamptz DEFAULT now());CREATE TABLE pedido_eventos(pedido_id uuid,empresa_id uuid,tipo text,actor_tipo text,detalle jsonb);INSERT INTO colaboradores VALUES('${u}','${a}','Proveedor');INSERT INTO pedidos(id,empresa_id,numero,estado,colaborador_id,conductor_proveedor_usuario_id) VALUES('${v}','${a}','QA-POD','entregado','${u}','${u}');`);
 const supplier=route('supplier_app.js',db),docReq={...req,user:{id:u,rol:'chofer',colaborador_id:u},params:{id:v},body:{nombre:'albaran.pdf',tipo:'albaran_colaborador',file_mime:'application/pdf',file_base64:Buffer.from('%PDF-1.4 QA only').toString('base64')}};
 r=res();await supplier.h['post /pedidos/:id/documentos'](docReq,r,next);assert.equal(r.code,201);const docId=r.data.id;
 r=res();await supplier.h['get /pedidos/:id/documentos/:docId']({...docReq,params:{id:v,docId}},r,next);assert.equal(r.data.file_base64,docReq.body.file_base64);
 r=res();await supplier.h['get /pedidos/:id/documentos']({...docReq,user:{...docReq.user,id:v}},r,next);assert.equal(r.code,404);
 r=res();await supplier.h['post /pedidos/:id/documentos']({...docReq,empresaId:b},r,next);assert.equal(r.code,404);
 console.log('PASS PostgreSQL schema and transactions: private support, admin replies, tenant isolation, dock overlap, postal/map persistence and atomic administrator email changes, post-delivery supplier POD and driver isolation');
 }finally{await pg.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
