const assert=require('node:assert/strict');
const {evaluateConstraints,proposeSequence,windowInstant}=require('../src/services/routeConstraints');
assert.equal(windowInstant('2026-03-29','02:30'),null);
assert.equal(windowInstant('2026-10-25','02:30'),null);
assert.equal(new Date(windowInstant('2026-09-27','08:00')).toISOString(),'2026-09-27T06:00:00.000Z');
const rules={start_day:'2026-09-27',start_time:'08:00',capacity_kg:1000,service_min:10,drive_limit_min:270,break_min:45,already_driven_min:0,truck_profile_confirmed:true};
const stops=[{id:'a',type:'carga',shipment_id:'s',weight_kg:800,date:'2026-09-27',window:'08:00-09:00'},{id:'b',type:'descarga',shipment_id:'s',weight_kg:800,date:'2026-09-27',window:'12:00-18:00'}];
const route={truck_aware:true,legs:[{duration_min:300}]};
let r=evaluateConstraints(stops,route,rules);
assert.equal(r.estado,'evaluado');assert.equal(r.paradas[1].pause_min,45);assert.equal(r.paradas[1].arrival_at,'2026-09-27T11:55:00.000Z');assert.equal(r.paradas[1].load_kg,0);
assert.ok(evaluateConstraints(stops,route,{...rules,capacity_kg:500}).incidencias.some(i=>i.code==='OVERWEIGHT'));
assert.ok(evaluateConstraints([...stops].reverse(),route,rules).incidencias.some(i=>i.code==='PRECEDENCE'));
assert.deepEqual(proposeSequence([...stops].reverse(),rules).map(s=>s.id),['a','b']);
r=evaluateConstraints(stops,{truck_aware:false,legs:[]},{...rules,service_min:null,capacity_kg:null,drive_limit_min:null,break_min:null,already_driven_min:null});
assert.equal(r.estado,'parcial');assert.equal(r.paradas[1].arrival_at,null);assert.ok(r.incidencias.some(i=>i.code==='BREAKS'));
assert.equal(evaluateConstraints([{...stops[0],weight_kg:null},stops[1]],route,rules).paradas[0].load_kg,null);
assert.equal(evaluateConstraints(stops,{...route,legs:[{duration_min:10},{duration_min:50}]},rules).paradas[1].arrival_at,null,'Ferry sections must not masquerade as stop-to-stop legs');
assert.throws(()=>proposeSequence(stops,{...rules,drive_limit_min:.00001}),/1.440/);
const {proposalSnapshot}=require('../src/services/routeConstraints');
const saved=proposalSnapshot(evaluateConstraints(stops,route,rules),['a','b']);
assert.equal(saved.verificacion,'estimacion_no_certificada');
assert.throws(()=>proposalSnapshot(saved,['b','a']),/secuencia/);
console.log('PASS route constraint proposal: precedence, simultaneous load, road times, pauses, missing sources, DST gap/overlap and extra provider sections');
