const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {PGlite}=require('@electric-sql/pglite');
const service=require('../src/services/transportDocumentVersions');
const {publicDocumentApiUrl}=require('../src/services/documentPublicUrl');
async function main(){
 const pg=new PGlite(),company=crypto.randomUUID(),other=crypto.randomUUID(),order=crypto.randomUUID();
 const db={query:(...a)=>pg.query(...a),transaction:fn=>pg.transaction(tx=>fn(tx))};
 try{
  const apiRequest={protocol:'https',get:name=>name==='host'?'api.transgest.app':''};
  assert.equal(publicDocumentApiUrl(apiRequest,{PUBLIC_APP_URL:'https://transgest.app'}),'https://api.transgest.app');
  assert.equal(publicDocumentApiUrl(apiRequest,{PUBLIC_API_URL:'https://api.transgest.app/ignored-path'}),'https://api.transgest.app');
  await pg.exec('CREATE TABLE pedidos(id UUID PRIMARY KEY,empresa_id UUID,updated_at timestamptz,descarga_real_at timestamptz,estado TEXT,carga_real_at timestamptz,remolque_id UUID);');
  for(const file of ['20260926_operational_model.sql','20260926_operational_model_groupage.sql','20260926_transport_document_versions.sql'])await pg.exec(fs.readFileSync(path.join(__dirname,'migrations',file),'utf8'));
  await pg.exec(fs.readFileSync(path.join(__dirname,'migrations/20260926_transport_document_versions.sql'),'utf8'));
  await pg.query('INSERT INTO pedidos(id,empresa_id,updated_at) VALUES($1,$2,NOW())',[order,company]);
  await pg.exec(`CREATE TABLE notificaciones_internas(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),empresa_id uuid,usuario_id uuid,tipo text,data jsonb,leida boolean DEFAULT false,read_at timestamptz);`);
  const request = (await pg.query("INSERT INTO notificaciones_internas(empresa_id,usuario_id,tipo,data) VALUES($1,$2,'deca_solicitado',$3) RETURNING id",[company,crypto.randomUUID(),JSON.stringify({pedido_id:order})])).rows[0].id;
  const d={codigo_control:'SINTETICO',referencia_pedido:'QA-DeCA-001',fecha_transporte:'2026-09-26',cargador_contractual:{nombre:'Cargador sintético SL',nif:'SINTETICO-NO-VALIDO',domicilio:'Calle de ensayo 1, Madrid'},transportista_efectivo:{nombre:'Transportista de prueba',nif:'SINTETICO-NO-VALIDO'},empresa:{nombre:'DEMOSTRACIÓN SINTÉTICA'},origen:{nombre:'Almacén de ensayo',direccion:'Madrid, España'},destino:{nombre:'Destino sintético',direccion:'Valencia, España',destinatario:'Destinatario de prueba'},mercancia:{descripcion:'Cerámica de ensayo',peso_kg:1250,bultos:64,embalaje:'Paletizado'},vehiculo:{tractora:'QA-0000'},cargas:[],descargas:[],observaciones:'DATOS SINTÉTICOS. Documento de prueba sin valor para un transporte real.'};
  const args={empresaId:company,pedidoId:order,payload:{documento:d},baseUrl:'https://example.invalid',reason:'Ensayo inicial'};
  d.observaciones_publicas=d.observaciones;d.observaciones='NOTA INTERNA QUE NO SE PUBLICA';
  d.condiciones={precio_acordado:'9999 EUR PRIVADOS'};
  d.firmas={chofer:{nombre:'FIRMA ANTIGUA NO VINCULADA',fecha:'2026-01-01'}};
  d.chofer={nombre:'CONDUCTOR DE ENSAYO',dni:'ID PRIVADO',telefono:'TELEFONO PRIVADO',email:'EMAIL PRIVADO'};
  await assert.rejects(service.issue(db,args),{code:'ORDER_NOT_CONFIRMED'});
  await pg.query("UPDATE pedidos SET estado='confirmado' WHERE id=$1",[order]);
  await pg.query('UPDATE pedidos SET remolque_id=$2 WHERE id=$1',[order,crypto.randomUUID()]);
  await assert.rejects(service.issue(db,args),{code:'DECA_FIELDS_REQUIRED'});
  d.vehiculo.remolque='QA-REM-01';
  // The first document is generated with known, complete data before service starts.
  // Loading changes require a new version and review before departure.
  const first=await service.issue(db,args);assert.equal(first.created,true);
  assert.equal((await pg.query('SELECT leida FROM notificaciones_internas WHERE id=$1',[request])).rows[0].leida,true,'Issuing the original closes its pending request within the transaction');
  const repeated=await service.issue(db,args);assert.equal(repeated.id,first.id);assert.equal(repeated.created,false);
  const initial=(await service.list(db,company,order))[0];const token=new URL(initial.public_url).searchParams.get('token');
  assert.deepEqual(initial.payload.documento.chofer,{nombre:'CONDUCTOR DE ENSAYO'},'Se conserva únicamente el nombre del conductor');
  assert.equal(initial.metadata.template_version,require('../src/services/transportDocumentPdf').DECA_TEMPLATE_VERSION);
  await assert.rejects(service.assertDeparture(db,company,{id:order,peso_kg:1250},{}),{code:'DECA_REVIEW_REQUIRED'});
  const reviewed={dcd_revisado:true,dcd_disponible:true,dcd_versiones_revisadas:[initial.id]};
  await service.assertDeparture(db,company,{id:order,peso_kg:1250},reviewed);
  const firstDriver=crypto.randomUUID(),replacementDriver=crypto.randomUUID();
  const assigned={id:order,chofer_id:firstDriver,matricula_colaborador:'QA-0000',remolque_matricula_colaborador:'QA-REM-01',peso_kg:1250};
  const firstAck=await service.acknowledgeDriverReview(db,company,assigned,{},firstDriver,[initial.id]);
  await service.assertDeparture(db,company,assigned,service.driverReviewFor(firstAck,assigned,firstDriver));
  await assert.rejects(service.assertDeparture(db,company,assigned,service.driverReviewFor(firstAck,assigned,replacementDriver)),{code:'DECA_REVIEW_REQUIRED'},'The second driver cannot inherit the first driver review');
  const replaced={...assigned,chofer_id:replacementDriver};
  await assert.rejects(service.acknowledgeDriverReview(db,company,replaced,firstAck,firstDriver,[initial.id]),{code:'DRIVER_ASSIGNMENT_CHANGED'});
  const replacementAck=await service.acknowledgeDriverReview(db,company,replaced,firstAck,replacementDriver,[initial.id]);
  await service.assertDeparture(db,company,replaced,service.driverReviewFor(replacementAck,replaced,replacementDriver));
  assert.equal((await service.list(db,company,order)).length,1,'A driver replacement alone does not create a new administrative DeCA');
  const changedTruck={...replaced,matricula_colaborador:'QA-9999'};
  await assert.rejects(service.assertDeparture(db,company,changedTruck,service.driverReviewFor(replacementAck,changedTruck,replacementDriver)),{code:'DECA_REVIEW_REQUIRED'});
  await assert.rejects(service.acknowledgeDriverReview(db,company,changedTruck,replacementAck,replacementDriver,[initial.id]),{code:'DECA_VEHICLE_CHANGED'},'A new tractor requires a matching document version');
  await assert.rejects(service.assertDeparture(db,company,{id:order,peso_kg:1251},reviewed),{code:'DECA_GOODS_CHANGED'});
  await assert.rejects(service.assertDeparture(db,company,{id:order,peso_kg:1250,mercancia:'Otra mercancía'},reviewed),{code:'DECA_GOODS_CHANGED'});
  await assert.rejects(service.assertDeparture(db,company,{id:order,peso_kg:1250,matricula_colaborador:'QA-9999'},reviewed),{code:'DECA_VEHICLE_CHANGED'});
  await assert.rejects(service.assertDeparture(db,company,{id:order,peso_kg:1250,remolque_matricula_colaborador:'QA-OTRO'},reviewed),{code:'DECA_VEHICLE_CHANGED'});
  const original=await service.publicOriginal(db,initial.id,token);assert.equal(service.hash(original.pdf),initial.pdf_hash);
  assert.doesNotMatch((await require('pdf-parse')(original.pdf)).text,/NOTA INTERNA/);
  assert.doesNotMatch((await require('pdf-parse')(original.pdf)).text,/9999 EUR PRIVADOS|FIRMA ANTIGUA NO VINCULADA/);
  const originalText=(await require('pdf-parse')(original.pdf)).text.replace(/\s+/g,' ');
  assert.ok(originalText.includes('Conductor: CONDUCTOR DE ENSAYO'));
  assert.doesNotMatch(originalText,/ID PRIVADO|TELEFONO PRIVADO|EMAIL PRIVADO/);
  d.chofer.nombre='OTRO CONDUCTOR DE ENSAYO';
  assert.equal((await service.read(db,company,order,initial.id)).payload.documento.chofer.nombre,'CONDUCTOR DE ENSAYO','Cambiar la asignación no reescribe el conductor del original emitido');
  assert.equal(await service.publicOriginal(db,initial.id,'wrong'),null);
  assert.equal(await service.read(db,other,order,initial.id),null);assert.deepEqual(await service.list(db,other,order),[]);
  await assert.rejects(service.issue(db,{...args,empresaId:other}),{code:'ORDER_NOT_FOUND'});
  await assert.rejects(pg.query('UPDATE transport_document_versions SET reason=$2 WHERE id=$1',[initial.id,'Rewrite']),{code:'55000'});
  await assert.rejects(pg.query('DELETE FROM transport_document_versions WHERE id=$1',[initial.id]),{code:'55000'});
  d.mercancia.peso_kg=1400;d.autorizacion_especial={requerida:true,referencia:''};
  await assert.rejects(service.issue(db,{...args,reason:'Peso revisado'}),{code:'DECA_FIELDS_REQUIRED'});
  d.autorizacion_especial.referencia='AUT-SINTETICA-001';
  await assert.rejects(service.issue(db,{...args,reason:''}),{code:'VERSION_REASON_REQUIRED'});
  const second=await service.issue(db,{...args,reason:'Peso revisado'});assert.equal(second.version,2);
  await assert.rejects(service.assertDeparture(db,company,{id:order,peso_kg:1400},reviewed),{code:'DECA_REVIEW_REQUIRED'});
  const versions=await service.list(db,company,order);assert.deepEqual(versions.map(v=>v.estado),['activa','superada']);
  assert.match((await require('pdf-parse')(Buffer.from((await service.read(db,company,order,second.id)).pdf))).text,/AUT-SINTETICA-001/);
  assert.notEqual(versions[0].public_url,initial.public_url);assert.notEqual(versions[0].pdf_hash,initial.pdf_hash);
  assert.deepEqual((await service.publicOriginal(db,initial.id,token)).pdf,original.pdf,'Old URL never regenerates current order data');
  await pg.query("INSERT INTO transport_document_events(empresa_id,document_id,event,effective_at,reason) VALUES($1,$2,'public_disabled',NOW(),'Disable requested too early')",[company,initial.id]);
  assert.deepEqual((await service.publicOriginal(db,initial.id,token)).pdf,original.pdf,'Manual disable cannot break a QR during transport');
  const completedAt=new Date('2026-09-25T12:00:00Z');
  assert.equal(service.publicAccessEnded(completedAt,new Date('2026-10-02T12:00:00Z')),false,'QR remains available after the optional seven-day cutoff');
  assert.equal(service.publicAccessEnded(completedAt,new Date('2027-09-25T11:59:59Z')),false);
  assert.equal(service.publicAccessEnded(completedAt,new Date('2027-09-25T12:00:00Z')),true);
  assert.equal(service.publicAccessEnded(new Date('2028-02-29T12:00:00Z'),new Date('2029-02-28T12:00:00Z')),false,'Leap-day completion is not shortened');
  await pg.exec('CREATE TABLE documento_control_repositorio(empresa_id UUID,pedido_id UUID,pdf_base64 TEXT,pdf_hash_sha256 TEXT,pdf_filename TEXT,filename TEXT,created_at timestamptz,retencion_minima_hasta date);');
  const legacyOrder=crypto.randomUUID();
  await pg.query('INSERT INTO pedidos(id,empresa_id,updated_at,descarga_real_at) VALUES($1,$2,NOW(),NULL)',[legacyOrder,company]);
  await pg.query('INSERT INTO documento_control_repositorio VALUES($1,$2,$3,$4,$5,$6,$7,NULL)',
    [company,legacyOrder,original.pdf.toString('base64'),service.hash(original.pdf),'original-archive.pdf','document.html','2026-09-20T12:00:00Z']);
  const legacy=await service.legacyPublicOriginal(db,{empresaId:company,pedidoId:legacyOrder});
  assert.deepEqual(legacy.pdf,original.pdf,'Old QR must download the exact original bytes, not regenerate a different PDF');
  assert.equal(legacy.filename,'original-archive.pdf');
  assert.equal(await service.legacyPublicOriginal(db,{empresaId:other,pedidoId:legacyOrder}),null);
  await pg.query('UPDATE pedidos SET descarga_real_at=$2 WHERE id=$1',[legacyOrder,completedAt]);
  assert.equal(await service.hasProtectedLegacyDeca(db,company,legacyOrder,new Date('2027-09-24T12:00:00Z')),true);
  assert.equal(await service.hasProtectedLegacyDeca(db,company,legacyOrder,new Date('2027-09-25T12:00:00Z')),false);
  assert.equal(await service.hasProtectedLegacyDeca(db,other,legacyOrder,new Date('2027-01-01T00:00:00Z')),false);
  assert.ok(await service.legacyPublicOriginal(db,{empresaId:company,pedidoId:legacyOrder,now:new Date('2027-09-25T11:59:59Z')}));
  await assert.rejects(service.legacyPublicOriginal(db,{empresaId:company,pedidoId:legacyOrder,now:new Date('2027-09-25T12:00:00Z')}),{code:'PUBLIC_EXPIRED'});
  await pg.query('UPDATE pedidos SET descarga_real_at=NULL WHERE id=$1',[legacyOrder]);
  await pg.query('UPDATE documento_control_repositorio SET pdf_hash_sha256=$2 WHERE pedido_id=$1',[legacyOrder,'wrong']);
  await assert.rejects(service.legacyPublicOriginal(db,{empresaId:company,pedidoId:legacyOrder}),{code:'DOCUMENT_INTEGRITY'});
  await assert.rejects(service.issue(db,{...args,payload:{documento:{...d,vehiculo:{}}}}),{code:'DECA_FIELDS_REQUIRED'});
  await assert.rejects(service.issue(db,{...args,baseUrl:'http://example.invalid'}),{code:'HTTPS_REQUIRED'});
  await assert.rejects(service.issue(db,{...args,payload:{documento:{...d,cargas:[{},{}]}}}),{code:'SHIPMENT_MAPPING_REQUIRED'});
  const external=await service.issue(db,{...args,source:'external',externalPdf:original.pdf.toString('base64'),nativeConfirmed:true,reason:'Original del cargador'});
  const stored=await service.read(db,company,order,external.id);assert.deepEqual(Buffer.from(stored.pdf),original.pdf);
  assert.equal((await service.issue(db,{...args,source:'external',externalPdf:original.pdf.toString('base64'),nativeConfirmed:true,reason:'Reintento'})).created,false,'La revisión de plantilla no cambia ni duplica un original externo');
  await assert.rejects(service.issue(db,args),{code:'EXTERNAL_DECA_ACTIVE'});
  await assert.rejects(service.issue(db,{...args,source:'external',externalPdf:original.pdf.toString('base64'),nativeConfirmed:false}),{code:'NATIVE_PDF_REQUIRED'});
  await pg.query("INSERT INTO transport_document_events(empresa_id,document_id,event,effective_at,reason) VALUES($1,$2,'service_completed',$3,'Fin real sintético')",[company,initial.id,'2025-08-01T12:00:00Z']);
  await assert.rejects(service.publicOriginal(db,initial.id,token,new Date('2026-08-01T12:00:00Z')),{code:'PUBLIC_EXPIRED'});
  await pg.query('UPDATE pedidos SET descarga_real_at=$2 WHERE id=$1',[order,'2025-09-01T12:00:00Z']);
  assert.ok(await service.publicOriginal(db,initial.id,token,new Date('2026-08-15T12:00:00Z')),'Later actual completion extends availability');
  await assert.rejects(service.publicOriginal(db,initial.id,token,new Date('2026-09-01T12:00:00Z')),{code:'PUBLIC_EXPIRED'});
  assert.ok((await service.read(db,company,order,initial.id)).pdf,'Authenticated retention survives public expiry');
  const out=path.resolve(__dirname,'../../../output/pdf');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'phase5-deca-synthetic.pdf'),original.pdf);
  const parsed=await require('pdf-parse')(original.pdf);assert.match(parsed.text,/CONTROL ADMINISTRATIVO/);assert.match(parsed.text,/Cerámica/);assert.doesNotMatch(parsed.text,/Formato carta de porte|firma certificada|AdES|QES/);
  const longPdf=await require('../src/services/transportDocumentPdf').renderDeca({documento:{...d,cargador_contractual:{...d.cargador_contractual,domicilio:`${'AVENIDA LARGA '.repeat(300)}FIN DE DIRECCION`},observaciones:''},version:1,generatedAt:new Date().toISOString(),url:'https://example.invalid/original'});
  const longParsed=await require('pdf-parse')(longPdf);assert.ok(longParsed.numpages>1);assert.match(longParsed.text,/ANEXO · DATOS ÍNTEGROS/);assert.match(longParsed.text,/FIN DE DIRECCION/);
  const templateOrder=crypto.randomUUID(),legacyId=crypto.randomUUID();
  await pg.query("INSERT INTO pedidos(id,empresa_id,updated_at,estado) VALUES($1,$2,NOW(),'confirmado')",[templateOrder,company]);
  const legacyDocument={...initial.payload.documento};delete legacyDocument.soporte_url;delete legacyDocument.qr_url;
  const legacyMaterialHash=service.hash(service.canonical({source:'transgest',documento:legacyDocument,pdf:null,envio_id:null}));
  await pg.query(`INSERT INTO transport_document_versions(id,empresa_id,pedido_id,envio_id,viaje_id,scope_key,version,source,payload,payload_hash,material_hash,pdf,pdf_hash,filename,reason,created_by,created_at,token_hash,public_url,retention_until,metadata)
    SELECT $1,empresa_id,$2,envio_id,viaje_id,scope_key,version,source,payload,payload_hash,$3,pdf,pdf_hash,filename,reason,created_by,created_at,token_hash,public_url,retention_until,metadata-'template_version' FROM transport_document_versions WHERE id=$4`,[legacyId,templateOrder,legacyMaterialHash,initial.id]);
  const templateArgs={...args,pedidoId:templateOrder,payload:{documento:legacyDocument},reason:''};
  await assert.rejects(service.issue(db,templateArgs),{code:'VERSION_REASON_REQUIRED'});
  const refreshed=await service.issue(db,{...templateArgs,reason:'Corrección del formato: partes visibles y direcciones sin duplicar'});
  assert.equal(refreshed.version,2);assert.equal(refreshed.created,true);
  assert.equal((await service.issue(db,{...templateArgs,reason:'Reintento'})).created,false,'No duplica la versión al repetir la misma plantilla');
  assert.deepEqual(Buffer.from((await service.read(db,company,templateOrder,legacyId)).pdf),original.pdf,'La corrección de formato conserva los bytes del original anterior');
  assert.deepEqual((await service.publicOriginal(db,legacyId,token)).pdf,original.pdf,'El QR anterior no se reemplaza por un PDF remaquetado');
  console.log('PASS document versions: old QR direct original bytes, one-year access after actual completion, manual disable guard, external originals, hashes, tenant isolation and retained private access. PDF pages:',parsed.numpages);
 }finally{await pg.close();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
