const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const service=require('../src/services/userExperience');
const {readOperationalNotices}=require('../src/services/agendaNotices');
const {validateAgendaReferences,validateAgendaDates}=require('../src/services/agendaValidation');
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',U='33333333-3333-4333-8333-333333333333',V='44444444-4444-4444-8444-444444444444';
const user={id:U,empresa_id:A,rol:'gerente'},other={id:V,empresa_id:B,rol:'gerente'},release='2026-09-agenda-updates';
(async()=>{const db=new PGlite();let server;
try{
  await db.exec(`CREATE TABLE empresas(id uuid PRIMARY KEY,cfg_alertas jsonb DEFAULT '[]');CREATE TABLE usuarios(id uuid PRIMARY KEY);
    CREATE TABLE usuario_empresas(usuario_id uuid,empresa_id uuid,activo boolean);
    CREATE TABLE pedidos(id uuid PRIMARY KEY,empresa_id uuid,numero text);CREATE TABLE vehiculos(id uuid PRIMARY KEY,empresa_id uuid);
    CREATE TABLE agenda_eventos(id uuid DEFAULT gen_random_uuid(),empresa_id uuid,titulo text,descripcion text,fecha_inicio timestamptz,explanation text,recommended_action text,pedido_id uuid,source_type text,metadata jsonb,resolved_at timestamptz,estado text,visibilidad text,creado_por uuid,asignado_a uuid);
    INSERT INTO empresas(id) VALUES('${A}'),('${B}');INSERT INTO usuarios VALUES('${U}'),('${V}');
    INSERT INTO usuario_empresas VALUES('${U}','${A}',true),('${V}','${B}',true);
    INSERT INTO pedidos VALUES('${A}','${A}','QA-A'),('${B}','${B}','SECRET-B');INSERT INTO vehiculos VALUES('${A}','${A}'),('${B}','${B}');
    INSERT INTO agenda_eventos(empresa_id,titulo,fecha_inicio,pedido_id,source_type,estado,visibilidad) VALUES
    ('${A}','Carga A',NOW(),'${A}','pedido','pendiente','equipo'),('${B}','SECRET-B',NOW(),'${B}','pedido','pendiente','equipo');`);
  const sql=fs.readFileSync(path.join(__dirname,'migrations/20260930_user_experience_preferences.sql'),'utf8');await db.exec(sql);await db.exec(sql);
  assert.equal((await service.getRelease(db,user,release)).dismissed,false);
  await service.dismissRelease(db,user,release);await service.dismissRelease(db,user,release);
  assert.equal((await service.getRelease(db,{...user},release)).dismissed,true,'Fresh device/session reads persisted acknowledgement');
  assert.equal((await service.getRelease(db,other,release)).dismissed,false,'Another user still sees release');
  assert.equal((await service.getRelease(db,{...user,empresa_id:B},release)).dismissed,true,'Account choice follows company switch');
  await assert.rejects(service.dismissRelease(db,user,'unknown'),e=>e.status===404);
  await assert.rejects(service.getRelease(db,{},release),e=>e.status===403);
  assert.deepEqual((await service.agendaPreferences(db,user)).notice_types,[]);
  await service.saveAgendaPreferences(db,user,['operativa','facturas']);
  assert.deepEqual((await service.agendaPreferences(db,{...user})).notice_types,['operativa','facturas']);
  assert.deepEqual((await service.agendaPreferences(db,other)).notice_types,[]);
  assert.deepEqual((await service.agendaPreferences(db,{...user,empresa_id:B})).notice_types,[]);
  const limited={...user,permisos:{modulos:{facturacion:{ver:false},pedidos:{ver:false}}}};
  assert.deepEqual((await service.agendaPreferences(db,limited)).notice_types,[],'Permission change immediately removes unauthorized overlays');
  await assert.rejects(service.saveAgendaPreferences(db,limited,['facturas']),e=>e.status===400);
  await assert.rejects(service.saveAgendaPreferences(db,user,['facturas','facturas']),e=>e.status===400);
  const notices=await readOperationalNotices(db,user);assert.equal(notices.length,1);assert.equal(notices[0].focus.pedido_id,A);assert.ok(!JSON.stringify(notices).includes('SECRET-B'));
  assert.deepEqual(await readOperationalNotices(db,limited),[]);
  await db.query("UPDATE agenda_eventos SET resolved_at=NOW() WHERE empresa_id=$1",[A]);assert.deepEqual(await readOperationalNotices(db,user),[]);
  await validateAgendaReferences(db,user,{asignado_a:U,pedido_id:A,vehiculo_id:A});
  for(const body of [{asignado_a:V},{pedido_id:B},{vehiculo_id:B}])await assert.rejects(validateAgendaReferences(db,user,body),e=>e.statusCode===400);
  assert.throws(()=>validateAgendaDates({fecha_inicio:'2026-09-27T12:00Z',fecha_fin:'2026-09-27T11:00Z'}));
  validateAgendaDates({fecha_fin:'2026-09-27T13:00Z'},{fecha_inicio:'2026-09-27T12:00Z'});
  // HTTP input cannot select another user/company; identity comes from middleware.
  const shared=require('../src/services/db');shared.query=db.query.bind(db);
  const express=require('express'),app=express();app.use(express.json());
  app.use((req,res,next)=>{if(!req.headers['x-qa-user'])return res.sendStatus(401);req.user=req.headers['x-qa-user']==='b'?other:user;next();});
  app.use('/prefs',require('../src/routes/userExperience'));
  await db.exec(`ALTER TABLE usuarios ADD COLUMN nombre text;ALTER TABLE usuarios ADD COLUMN rol text;
    ALTER TABLE agenda_eventos ADD COLUMN created_at timestamptz DEFAULT NOW();
    INSERT INTO agenda_eventos(empresa_id,titulo,fecha_inicio,estado,visibilidad,creado_por) VALUES('${A}','Reunión manual',NOW(),'pendiente','personal','${U}');
    INSERT INTO agenda_eventos(empresa_id,titulo,fecha_inicio,estado,visibilidad,creado_por,metadata) VALUES
      ('${A}','Evento sin autor',NOW(),'pendiente','equipo',NULL,'{}'),
      ('${A}','Aviso con autor técnico',NOW(),'pendiente','equipo','${U}','{"source":"aviso_automatico"}');`);
  const auth=require('../src/middleware/auth'),originalAuth=auth.authenticate;
  auth.authenticate=(req,res,next)=>next();
  app.use('/calendar',require('../src/routes/agenda'));
  auth.authenticate=originalAuth;
  server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});const url=`http://127.0.0.1:${server.address().port}/prefs`;
  const calendar=await fetch(url.replace('/prefs','/calendar')+'?origen=manual&empresa_id='+B,{headers:{'x-qa-user':'a'}});
  const calendarRows=await calendar.json();assert.equal(calendarRows.length,1);assert.equal(calendarRows[0].titulo,'Reunión manual','The actual calendar route excludes automatic notices without deleting them');
  assert.equal((await fetch(url+'/agenda')).status,401);
  let r=await fetch(url+'/agenda?empresa_id='+B,{headers:{'x-qa-user':'a'}});assert.equal(r.headers.get('cache-control'),'private, no-store');assert.deepEqual((await r.json()).notice_types,['operativa','facturas']);
  r=await fetch(url+`/releases/${release}/dismiss`,{method:'POST',headers:{'x-qa-user':'a','content-type':'application/json'},body:JSON.stringify({usuario_id:V})});assert.equal(r.status,200);
  assert.equal((await service.getRelease(db,other,release)).dismissed,false);
  console.log('User experience OK: additive migration, cross-device/account state, company/role isolation, HTTP no-store, operational deep links, dates and tenant references.');
}finally{if(server)await new Promise(r=>server.close(r));await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
