const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),express=require('express');
const {PGlite}=require('@electric-sql/pglite'),{uuid_ossp}=require('@electric-sql/pglite/contrib/uuid_ossp'),{pg_trgm}=require('@electric-sql/pglite/contrib/pg_trgm');
const db=require('../src/services/db'),auth=require('../src/middleware/auth'),ai=require('../src/services/documentAI');
const company=crypto.randomUUID(),other=crypto.randomUUID(),user=crypto.randomUUID();
const old={query:db.query,transaction:db.transaction,authenticate:auth.authenticate,readDocument:ai.readDocument};
const pg=new PGlite({extensions:{uuid_ossp,pg_trgm}});let server;
const adapt=client=>({query:async(sql,params)=>{const result=params?.length?await client.query(sql,params):(await client.exec(sql)).at(-1);return {...result,rowCount:result.affectedRows??result.rows.length};}});
(async()=>{try{
  const root=path.resolve(__dirname,'..');db.query=adapt(pg).query;db.transaction=fn=>pg.transaction(tx=>fn(adapt(tx)));
  await pg.exec(fs.readFileSync(path.join(__dirname,'install_completo.sql'),'utf8'));
  for(const file of fs.readdirSync(path.join(__dirname,'migrations')).filter(n=>n.endsWith('.sql')).sort())await pg.exec(fs.readFileSync(path.join(__dirname,'migrations',file),'utf8').replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;',''));
  const source=fs.readFileSync(path.join(root,'src/server.js'),'utf8'),errors=[];
  const migration=source.slice(source.indexOf('async function applyMigrations()'),source.indexOf('// ── Auto-seed:'));
  await vm.runInNewContext(migration+'\napplyMigrations()',{db,logger:{info(){},warn(){},error(message){errors.push(message);}},require:require('node:module').createRequire(path.join(root,'src/server.js')),process,console,ensureApiKeyTables:require('../src/services/apiKeys').ensureTables,captureStartupMigrationError:e=>errors.push(e.message),startupMigrationFailures:0});
  assert.deepEqual(errors,[],'Installation and startup migrations must succeed');
  await db.query("INSERT INTO empresas(id,nombre,cif,email_admin,plan,estado) VALUES($1,'QA vehicle','B00000000','a@example.invalid','enterprise','activo'),($2,'Other','B00000001','b@example.invalid','enterprise','activo')",[company,other]);
  await db.query("INSERT INTO usuarios(id,empresa_id,nombre,email,password_hash,rol) VALUES($1,$2,'QA','qa@example.invalid','synthetic','gerente')",[user,company]);
  auth.authenticate=(req,res,next)=>{const who=req.get('x-test-user');if(!who)return res.status(401).json({error:'No autenticado'});req.user={id:user,empresa_id:who==='other'?other:company,rol:who==='driver'?'chofer':'gerente',plan:who==='lite'?'lite':'enterprise',productos:['transgest']};req.empresaId=req.user.empresa_id;next();};
  const app=express();app.use(express.json({limit:'25mb'}));app.use('/vehiculos',require('../src/routes/vehiculos'));app.use('/docs',require('../src/routes/docs'));auth.authenticate=old.authenticate;
  server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.on('listening',resolve));
  async function call(method,url,body,who='manager',status=200){const response=await fetch(`http://127.0.0.1:${server.address().port}${url}`,{method,headers:{'content-type':'application/json',...(who?{'x-test-user':who}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=response.headers.get('content-type')?.includes('json')?await response.json():Buffer.from(await response.arrayBuffer());assert.equal(response.status,status,JSON.stringify(data));return data;}
  const file=Buffer.from('%PDF-1.4\nSynthetic vehicle document\n%%EOF'),document={tipo:'itv',file_url:'data:application/pdf;base64,'+file.toString('base64'),file_nombre:'ficha.pdf'};
  let reads=0;ai.readDocument=async(companyId,file)=>{reads++;assert.equal(companyId,company);assert.equal(file.mime,'application/pdf');return {provider:'synthetic',model:'fixture',data:{legible:true,confianza_lectura:.99,matricula_documento:'0001-QAT',campos:[{campo:'matricula',valor:'0001-QAT',confianza:.99,evidencia:'Matrícula 0001-QAT'},{campo:'marca',valor:'VOLVO',confianza:.99,evidencia:'D.1 VOLVO'}]}};};
  const result=await call('POST','/docs/vehiculo/analizar',document);assert.equal(result.fields.length,2);assert.equal(result.requires_review,true);
  await call('POST','/docs/vehiculo/analizar',document,'driver',403);await call('POST','/docs/vehiculo/analizar',document,'lite',403);assert.equal(reads,1);
  assert.equal((await db.query('SELECT count(*)::int n FROM vehiculos')).rows[0].n,0,'Analysis before saving must not create a vehicle');
  const vehicle=await call('POST','/vehiculos',{matricula:'0001-QAT',marca:'VOLVO',clase:'Tractora',anio:'',tara_kg:'',carga_max_kg:'',documentos:[document]},'manager',201);
  assert.equal(vehicle.anio,null);let docs=await call('GET',`/docs/vehiculo/${vehicle.id}`);assert.equal(docs.length,1);assert.equal(docs[0].tipo_doc,'itv');assert.ok(docs[0].storage_key);assert.equal(docs[0].file_url,null);
  assert.deepEqual(await call('GET',`/docs/archivo/vehiculo/${docs[0].id}`),file);
  await call('GET',`/docs/archivo/vehiculo/${docs[0].id}`,null,'other',404);
  const edited=await call('PUT',`/vehiculos/${vehicle.id}`,{...vehicle,anio:'',tara_kg:'',carga_max_kg:'',modelo:'UPDATED'});assert.equal(edited.modelo,'UPDATED');
  await call('POST',`/docs/vehiculo/${vehicle.id}`,document,'manager',201);assert.equal((await call('GET',`/docs/vehiculo/${vehicle.id}`)).length,2);
  await call('POST',`/docs/vehiculo/${vehicle.id}`,document,'other',404);
  await call('POST','/vehiculos',{matricula:'0002-QAT',documentos:[{...document,file_url:'data:application/pdf;base64,'+Buffer.from('fake binary').toString('base64')}]},'manager',400);
  assert.equal((await db.query('SELECT count(*)::int n FROM vehiculos')).rows[0].n,1,'Invalid document must not leave a vehicle behind');
  const tx=db.transaction;db.transaction=fn=>pg.transaction(t=>fn({query:(sql,params)=>{if(sql.includes('INSERT INTO docs_vehiculos'))throw Error('Synthetic persistence outage');return adapt(t).query(sql,params);}}));
  await call('POST','/vehiculos',{matricula:'0003-QAT',documentos:[document]},'manager',500);db.transaction=tx;
  assert.equal((await db.query('SELECT count(*)::int n FROM vehiculos')).rows[0].n,1,'Document write failure rolls back the vehicle and blob');
  assert.equal((await db.query('SELECT count(*)::int n FROM import_document_blobs')).rows[0].n,2);
  await db.query('ALTER TABLE docs_vehiculos ALTER COLUMN tipo TYPE tipo_doc_vehiculo USING tipo::tipo_doc_vehiculo');
  await call('POST',`/docs/vehiculo/${vehicle.id}`,{tipo:'seguro',descripcion:'Metadata only'},'manager',201);
  const png=Buffer.from('89504e470d0a1a0a0000000d49484452','hex');
  const image=await call('POST',`/docs/vehiculo/${vehicle.id}`,{tipo:'otro',file_url:'data:image/png;base64,'+png.toString('base64'),file_nombre:'foto.png'},'manager',201);
  const imageResponse=await fetch(`http://127.0.0.1:${server.address().port}/docs/archivo/vehiculo/${image.id}`,{headers:{'x-test-user':'manager'}});
  assert.equal(imageResponse.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await imageResponse.arrayBuffer()),png);
  console.log('PASS real installation schema: vehicle create/edit with empty numbers, pre-save AI review without persistence, role/plan gates, required document type, private file download, tenant isolation, atomic vehicle/document rollback. AI synthetic; no credits used.');
}finally{Object.assign(db,{query:old.query,transaction:old.transaction});auth.authenticate=old.authenticate;ai.readDocument=old.readDocument;if(server)await new Promise(resolve=>server.close(resolve));await pg.close();}})().catch(error=>{console.error(error.message,error.auditSql||'');process.exitCode=1;});
