import {useEffect,useState} from 'react';
import {Page,PageHeader,Button,Card,KpiCard,DataTable,MobileDataCard,Badge,SearchInput,Select} from '../../ui';
import VehiclePortrait from '../workshop/VehiclePortrait';
const labels={disponible:'Disponible',en_ruta:'En ruta',taller:'En taller',inactivo:'Inactivo',baja:'De baja'};
const date=x=>x?String(x).slice(0,10).split('-').reverse().join('/'):'—';
export default function FleetWorkspace({vehicles,items,loading,error,reload,type,setType,state,setState,canEdit,onNew,onOpen,advanced,isTrailer,canDrivers}){
 const[q,setQ]=useState(''),[location,setLocation]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[grid,setGrid]=useState(false),[due,setDue]=useState(false);
 useEffect(()=>setPage(1),[q,location,type,state,size,due]);
 const days=x=>x?Math.ceil((new Date(String(x).slice(0,10)+'T12:00:00')-new Date())/86400000):null;
 const hasDue=v=>[v.fecha_itv,v.fecha_seguro].some(x=>x&&days(x)<=30);
 const active=vehicles.filter(v=>v.activo!==false&&v.estado!=='baja'),trailers=active.filter(isTrailer),tractors=active.filter(v=>!isTrailer(v));
 const rows=items.filter(v=>(!location||v.ubicacion_actual===location)&&(!due||hasDue(v))&&`${v.matricula} ${v.clase} ${v.tipo} ${v.marca} ${v.modelo}`.toLowerCase().includes(q.toLowerCase()));
 const pages=Math.max(1,Math.ceil(rows.length/size)),current=Math.min(page,pages),visible=rows.slice((current-1)*size,current*size);
 const badge=v=><Badge tone={v.estado==='disponible'?'success':v.estado==='en_ruta'?'info':v.estado==='taller'?'warning':'neutral'}>{labels[v.estado]||v.estado||'Sin estado'}</Badge>;
 const expiry=x=><span className={x&&days(x)<0?'fleet-expired':x&&days(x)<=30?'fleet-due':''}>{date(x)}</span>;
 function exportRows(){const quote=x=>`"${String(x??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')}"`;const data=[['Matrícula','Tipo','Marca','Modelo','Estado','ITV','Seguro','Ubicación'],...rows.map(v=>[v.matricula,v.clase||v.tipo,v.marca,v.modelo,labels[v.estado]||v.estado,v.fecha_itv,v.fecha_seguro,v.ubicacion_actual])];const url=URL.createObjectURL(new Blob(['\ufeff'+data.map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='vehiculos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <Page className="fleet-workspace"><PageHeader title="Gestión de vehículos" description="Controla tu flota, su documentación, disponibilidad y ubicación." actions={<><Button disabled={loading||!!error} onClick={exportRows}>Exportar</Button>{canEdit&&<Button variant="primary" onClick={()=>onNew()}>+ Nuevo vehículo</Button>}</>}/>
 <nav className="fleet-nav"><strong>Vehículos</strong>{canDrivers&&<Button onClick={()=>window.dispatchEvent(new CustomEvent('tms:navegar',{detail:'choferes'}))}>Conductores</Button>}<Button onClick={advanced}>Gestión de flota y GPS</Button></nav>
 <div className="fleet-kpis"><KpiCard label="Tractoras activas" value={loading||error?'—':tractors.length} icon="truck" detail="Vehículos activos sin remolques"/><KpiCard label="Remolques activos" value={loading||error?'—':trailers.length} icon="truck" detail="Remolques y semirremolques"/><KpiCard label="Revisar documentación" value={loading||error?'—':active.filter(hasDue).length} tone="warning" icon="invoice" detail="ITV o seguro vencido o a 30 días"/><KpiCard label="Vehículos en taller" value={loading||error?'—':active.filter(v=>v.estado==='taller').length} tone="warning" icon="alert" detail="Estado registrado de la flota"/></div>
 <Card className="fleet-list"><div className="fleet-filters"><SearchInput label="Buscar vehículos" value={q} onChange={e=>setQ(e.target.value)} placeholder="Matrícula, tipo, marca o modelo…"/><Select label="Tipo de vehículo" value={type} onChange={e=>setType(e.target.value)}>{[['todos','Todos los tipos'],['tractoras','Tractoras'],['remolques','Remolques'],['baja','Dados de baja']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Select disabled={type==='baja'} label="Estado del vehículo" value={state} onChange={e=>setState(e.target.value)}><option value="todos">Todos los estados</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Select label="Ubicación" value={location} onChange={e=>setLocation(e.target.value)}><option value="">Todas las ubicaciones</option>{[...new Set(items.map(v=>v.ubicacion_actual).filter(Boolean))].sort().map(l=><option key={l}>{l}</option>)}</Select><Button aria-pressed={due} onClick={()=>setDue(!due)}>Vencimientos ≤ 30 días</Button><Button aria-pressed={grid} onClick={()=>setGrid(!grid)}>{grid?'Ver tabla':'Ver tarjetas'}</Button></div>
 {error?<div role="alert">{error}<Button onClick={reload}>Reintentar</Button></div>:grid&&!loading?<div className="fleet-grid">{visible.map(v=><Card key={v.id}><VehiclePortrait vehicle={v}/><h3>{v.matricula}</h3><p>{v.marca} {v.modelo}</p>{badge(v)}<p>{v.ubicacion_actual||'Sin ubicación registrada'}</p><Button onClick={()=>onOpen(v)}>Ver {v.matricula}</Button></Card>)}{!visible.length&&<p>No hay vehículos con estos filtros.</p>}</div>:<DataTable loading={loading} rows={visible} columns={[{key:'matricula',label:'Matrícula',render:v=><button className="fleet-link" onClick={()=>onOpen(v)}>{v.matricula}</button>},{key:'tipo',label:'Tipo',render:v=>v.clase||v.tipo||'—'},{key:'marca',label:'Marca / modelo',render:v=>`${v.marca||''} ${v.modelo||''}`},{key:'estado',label:'Estado',render:badge},{key:'fecha_itv',label:'ITV',render:v=>expiry(v.fecha_itv)},{key:'fecha_seguro',label:'Seguro',render:v=>expiry(v.fecha_seguro)},{key:'ubicacion_actual',label:'Última ubicación',render:v=><>{v.ubicacion_actual||'Sin ubicación registrada'}{v.ubicacion_ts&&<small>{new Date(v.ubicacion_ts).toLocaleString('es-ES')}</small>}</>},{key:'actions',label:'Acciones',render:v=><Button onClick={()=>onOpen(v)}>Ver</Button>}]} renderMobile={v=><MobileDataCard title={v.matricula} subtitle={`${v.marca||''} ${v.modelo||''}`} actions={<Button onClick={()=>onOpen(v)}>Ver {v.matricula}</Button>}>{badge(v)}<span>ITV: {expiry(v.fecha_itv)} · Seguro: {expiry(v.fecha_seguro)}</span><span>{v.ubicacion_actual||'Sin ubicación registrada'}</span></MobileDataCard>}/>}
 <footer className="fleet-pagination"><small>Vehículos: {rows.length} · página {current} de {pages}</small><Button disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</Button><Button disabled={current===pages} onClick={()=>setPage(current+1)}>Siguiente</Button><Select label="Vehículos por página" value={size} onChange={e=>setSize(Number(e.target.value))}>{[10,25,50].map(n=><option key={n} value={n}>{n} por página</option>)}</Select></footer></Card>
 <div className="fleet-bottom"><Card><h2>Documentación</h2><p>Vehículos con ITV o seguro para revisar: {active.filter(hasDue).length}.</p><Button onClick={()=>setDue(true)}>Ver vencimientos</Button></Card><Card><h2>Disponibilidad</h2><p>Disponibles: {active.filter(v=>v.estado==='disponible').length} · En ruta: {active.filter(v=>v.estado==='en_ruta').length}</p><Button onClick={()=>setState('disponible')}>Ver disponibles</Button></Card><Card><h2>Conjuntos y GPS</h2><p>Consulta asignaciones, ubicación y gestión de bajas.</p><Button onClick={advanced}>Abrir gestión de flota</Button></Card></div>
 </Page>;
}
