import {useState,useEffect} from 'react';
import {Card,Button,DataTable,MobileDataCard,SearchInput,Select,Badge,Tabs} from '../../ui';
import {useAuth} from '../../context/AuthContext';
import {guardarImagenVehiculo} from '../../services/api';
import VehiclePortrait from './VehiclePortrait';
const money=n=>Number(n||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const date=v=>String(v||'').slice(0,10).split('-').reverse().join('/')||'—';
export default function WorkshopOrders({orders,vehicles,onEdit,onClose,onNew,onVehicles,showTyres,showHistory}){
 const {user}=useAuth();const canEdit=['gerente','contable','responsable_taller'].includes(user?.rol),canPhoto=['gerente','trafico'].includes(user?.rol);
 const [q,setQ]=useState(''),[state,setState]=useState('todas'),[vehicle,setVehicle]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[detail,setDetail]=useState('detalle'),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>setPage(1),[q,state,vehicle]);
 const rows=orders.filter(r=>(state==='todas'||(state==='cerrada'?r.estado==='cerrada':r.estado!=='cerrada'))&&(!vehicle||r.vehiculo_id===vehicle)&&`${r.numero||r.id} ${r.vehiculo_matricula} ${r.tipo} ${r.descripcion}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha)));
 const pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages),active=rows.find(r=>r.id===selected)||rows[0],v=vehicles.find(v=>v.id===active?.vehiculo_id)||{};
 const badge=r=><Badge tone={r.estado==='cerrada'?'success':'warning'}>{r.estado==='cerrada'?'Finalizada':'Abierta'}</Badge>;
 async function savePhoto(file){setError('');if(file&&(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>256*1024)){setError('Elige una foto PNG, JPG o WebP de hasta 256 KB.');return;}setSaving(true);try{const data=file?await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);}):null;await guardarImagenVehiculo(v.id,data);onVehicles(vehicles.map(x=>x.id===v.id?{...x,imagen_data:data}:x));}catch(e){setError(e.message||'No se pudo guardar la foto.');}finally{setSaving(false);}}
 function exportRows(){const quote=x=>`"${String(x??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')}"`;const data=[['Orden','Fecha','Vehículo','Tipo','Descripción','Estado','Coste'],...rows.map(r=>[r.numero||r.id,r.fecha,r.vehiculo_matricula,r.tipo,r.descripcion,r.estado,r.coste_total])];const url=URL.createObjectURL(new Blob(['\ufeff'+data.map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ordenes-taller.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="workshop-orders"><Card><header className="workshop-section"><div><h2>Órdenes de taller</h2><p>Intervenciones de mantenimiento y reparación de la flota.</p></div>{canEdit&&<Button variant="primary" onClick={onNew}>+ Nueva orden de taller</Button>}</header>
 <Tabs value={state} onChange={setState} items={[{value:'todas',label:'Todas',count:orders.length},{value:'abierta',label:'Abiertas',count:orders.filter(r=>r.estado!=='cerrada').length},{value:'cerrada',label:'Finalizadas',count:orders.filter(r=>r.estado==='cerrada').length}]}/>
 <div className="workshop-filters"><SearchInput label="Buscar órdenes" value={q} onChange={e=>setQ(e.target.value)} placeholder="Orden, matrícula o descripción…"/><Select label="Vehículo" value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Todos los vehículos</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.matricula}</option>)}</Select><Button onClick={exportRows}>Exportar</Button></div>
 <DataTable rows={rows.slice((current-1)*8,current*8)} onRowClick={r=>setSelected(r.id)} rowClassName={r=>r.id===active?.id?'workshop-selected':''} columns={[{key:'numero',label:'Orden',render:r=><button className="workshop-link" onClick={()=>setSelected(r.id)}>{r.numero||String(r.id).slice(0,8)}</button>},{key:'fecha',label:'Fecha',render:r=>date(r.fecha)},{key:'vehiculo_matricula',label:'Vehículo'},{key:'tipo',label:'Tipo'},{key:'descripcion',label:'Descripción'},{key:'estado',label:'Estado',render:badge},{key:'coste_total',label:'Coste',render:r=>money(r.coste_total)}]} renderMobile={r=><MobileDataCard title={<button onClick={()=>setSelected(r.id)}>{r.vehiculo_matricula}</button>} subtitle={r.descripcion} amount={money(r.coste_total)}>{date(r.fecha)} {badge(r)}</MobileDataCard>}/>
 <footer className="workshop-pagination"><small>{rows.length} {rows.length===1?'orden':'órdenes'} · página {current} de {pages}</small><Button disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</Button><Button disabled={current===pages} onClick={()=>setPage(current+1)}>Siguiente</Button></footer></Card>
 {active&&<Card className="workshop-detail"><header className="workshop-section"><h2>Orden {active.numero||String(active.id).slice(0,8)}</h2>{badge(active)}</header><Tabs value={detail} onChange={setDetail} items={[{value:'detalle',label:'Detalle'},{value:'trabajos',label:'Trabajos'},{value:'recambios',label:'Recambios'},{value:'historial',label:'Historial'}]}/>
 <div className="workshop-vehicle"><VehiclePortrait vehicle={v}/><div><h3>{active.vehiculo_matricula||v.matricula}</h3><p>{v.marca} {v.modelo}</p><small>{Number(v.km_actuales||active.km_en_intervencion||0).toLocaleString('es-ES')} km</small></div></div>
 {canPhoto&&v.id&&<div className="workshop-photo-controls"><label>{saving?'Guardando…':'Añadir / cambiar foto'}<input aria-label="Foto del vehículo" type="file" accept="image/png,image/jpeg,image/webp" disabled={saving} onChange={e=>{if(e.target.files?.[0])savePhoto(e.target.files[0]);e.target.value='';}}/></label>{v.imagen_data&&<Button disabled={saving} onClick={()=>savePhoto(null)}>Quitar foto</Button>}<small>Opcional · PNG, JPG o WebP · hasta 256 KB</small></div>}{error&&<p role="alert">{error}</p>}
 {detail==='detalle'&&<><dl><dt>Fecha de entrada</dt><dd>{date(active.fecha)}</dd><dt>Intervención</dt><dd>{active.tipo}</dd><dt>Taller</dt><dd>{active.taller_externo||active.factura_proveedor_nombre||(active.origen_taller==='propio'?'Taller propio':'Sin especificar')}</dd></dl><h3>Descripción</h3><p>{active.descripcion||'Sin descripción'}</p></>}
 {detail==='trabajos'&&<><h3>Trabajo registrado</h3><p>{active.descripcion||'Sin descripción'}</p><p>Mano de obra: {money(active.coste_mano_obra)}</p><p>{active.notas||'Sin notas adicionales.'}</p></>}
 {detail==='recambios'&&<><h3>Recambios utilizados</h3>{active.piezas_usadas?.length?active.piezas_usadas.map((p,i)=><p key={i}>{p.nombre||p.referencia||p.pieza_id} · {p.cantidad_usada||p.cantidad||0} unidades · {money(p.precio_unitario)}</p>):<p>No hay recambios registrados.</p>}</>}
 {detail==='historial'&&<><h3>Intervenciones del vehículo</h3>{orders.filter(r=>r.vehiculo_id===active.vehiculo_id).map(r=><Button key={r.id} onClick={()=>{setSelected(r.id);setDetail('detalle');}}>{date(r.fecha)} · {r.tipo}</Button>)}<Button onClick={showHistory}>Trazabilidad de piezas</Button></>}
 <div className="workshop-detail-actions">{canEdit&&<Button onClick={()=>onEdit(active)}>Editar orden</Button>}{canEdit&&active.estado!=='cerrada'&&<Button onClick={()=>onClose(active)}>Finalizar orden</Button>}<Button onClick={showTyres}>Ver neumáticos</Button></div></Card>}
 </div>;
}
