const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(__dirname,'../build');
const today='2026-09-15';let points=[],writes=[];const orders=[{id:'order-a',numero:'QA-A',estado:'pendiente',fecha_carga:today,origen:'Madrid',destino:'Valencia'},{id:'order-b',numero:'QA-B',estado:'pendiente',fecha_carga:today,origen:'Madrid',destino:'Valencia'},{id:'old',numero:'QA-VENCIDO',estado:'en_curso',fecha_carga:'2026-08-10',fecha_descarga:'2026-08-11',origen:'Madrid',destino:'Sevilla'},{id:'future',numero:'QA-EN-RUTA',estado:'en_curso',fecha_carga:today,fecha_descarga:'2026-09-16',origen:'Madrid',destino:'Sevilla'}];
async function main(){const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'}[path.extname(f)]||'text/html'));fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];
try{browser=await chromium.launch({headless:true,channel:'msedge'});const origin=`http://127.0.0.1:${server.address().port}`;
async function makePage(role){const page=await browser.newPage({viewport:{width:1500,height:1000}}),user={id:'qa',empresa_id:'qa-company',rol:role,nombre:'QA',plan:'enterprise',...(role==='cliente'?{cliente_id:'client'}:{})};page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date(today+'T10:00:00Z'));await page.addInitScript(u=>{localStorage.setItem('tms_token','qa');localStorage.setItem('tms_user',JSON.stringify(u));localStorage.setItem(`tms_onboarding_done:${u.empresa_id}:${u.rol}:${u.id}`,'1');},user);
await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname.replace('/api/v1',''),body=req.method()==='GET'?null:req.postDataJSON();let data=[];if(body||req.method()==='DELETE')writes.push({p,body,method:req.method()});
if(p==='/auth/me')data=user;else if(p.includes('notificaciones'))data={data:[],no_leidas:0};else if(p==='/pedidos'||p==='/pedidos/resumen-lista')data=orders;else if(p==='/portal-cliente/puntos'){if(body){const point={...body,id:'point-'+points.length};points.push(point);data=point;}else data=points;}else if(p==='/portal-cliente/calcular-ruta')data={km:350,warning:'Estimación QA'};else if(p==='/portal-cliente/solicitudes'&&body)data={id:'request-qa'};else if(p.includes('resumen'))data={};else if(p.includes('empresa'))data={plan:'enterprise'};
await route.fulfill({status:200,json:data});});await page.goto(origin,{waitUntil:'networkidle'});return page;}
const page=await makePage('gerente');await page.locator('.dashboard-live').waitFor();const overdue=page.getByRole('region',{name:'Pedidos vencidos'});await overdue.getByText('QA-VENCIDO',{exact:true}).waitFor();assert.equal(await page.locator('.dashboard-live-list').first().getByText('QA-VENCIDO',{exact:true}).count(),0);
await page.evaluate(()=>window.dispatchEvent(new CustomEvent('tms:navegar',{detail:'pedidos'})));await page.locator('.orders-workspace').waitFor();for(const n of ['QA-A','QA-B'])await page.getByRole('checkbox',{name:'Seleccionar '+n,exact:true}).first().check();
await page.getByRole('button',{name:'Eliminar seleccionados',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Eliminar pedidos seleccionados'});await dialog.locator('textarea').fill('Duplicado QA');await dialog.getByRole('button',{name:'Confirmar acción'}).click();await dialog.waitFor({state:'hidden'});assert.equal(writes.filter(w=>w.method==='DELETE'&&['/pedidos/order-a','/pedidos/order-b'].includes(w.p)).length,2);assert.equal(writes.filter(w=>w.body?.motivo_cancelacion==='Duplicado QA').length,2);
for(const n of ['QA-A','QA-B'])await page.getByRole('checkbox',{name:'Seleccionar '+n,exact:true}).first().check();await page.locator('select').filter({has:page.locator('option[value="cancelado"]')}).filter({hasNot:page.locator('option[value="todos"]')}).selectOption('cancelado');await page.getByRole('button',{name:'Aplicar estado',exact:true}).click();dialog=page.getByRole('dialog',{name:'Cambiar estado de pedidos'});await dialog.getByRole('checkbox').check();await dialog.locator('textarea').nth(0).fill('Motivo A');await dialog.locator('textarea').nth(1).fill('Motivo B');await dialog.getByRole('button',{name:'Confirmar acción'}).click();await page.getByRole('button',{name:'Actualizar estados',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.ok(writes.some(w=>w.body?.motivo_cancelacion==='Motivo A'));assert.ok(writes.some(w=>w.body?.motivo_cancelacion==='Motivo B'));await page.getByRole('button',{name:'+ Nuevo pedido',exact:true}).click();const attachment=page.locator('.tg-attachment-trigger');await attachment.waitFor();assert.equal(await attachment.evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)');await page.close();
const client=await makePage('cliente');await client.getByRole('button',{name:'Solicitar servicio',exact:true}).first().click();await client.getByRole('button',{name:'+ Crear punto',exact:true}).first().click();await client.getByLabel('Nombre del punto',{exact:true}).fill('Almacén QA');await client.getByLabel('Direccion de carga',{exact:true}).fill('Calle Mayor 1');await client.getByLabel('Población',{exact:true}).fill('Madrid');await client.getByLabel('Código postal',{exact:true}).fill('28001');await client.getByLabel('Enlace del mapa',{exact:true}).fill('https://maps.google.com/?q=40.4,-3.7');await client.getByRole('button',{name:'Guardar y seleccionar'}).click();await client.getByLabel('Destino *',{exact:true}).fill('Valencia');await client.getByLabel('Peso',{exact:true}).fill('24,2');await client.getByLabel('Fecha carga',{exact:true}).fill(today);await client.getByLabel('Fecha descarga',{exact:true}).fill('2026-09-16');await client.getByRole('button',{name:'Calcular kilómetros',exact:true}).click();await client.getByText('Estimación QA',{exact:true}).waitFor();assert.equal(await client.getByLabel('Km ruta estimados',{exact:true}).inputValue(),'350');
await client.getByRole('button',{name:/Enviar solicitud/}).click();await client.getByRole('heading',{name:'Mis solicitudes',exact:true}).waitFor();const payload=writes.find(w=>w.p==='/portal-cliente/solicitudes'&&w.method==='POST').body;assert.equal(payload.peso_kg,24200);assert.equal(Number(payload.km_ruta),350);assert.equal(payload.origen_punto_id,'point-0');const location=writes.find(w=>w.p==='/portal-cliente/puntos').body;assert.equal(location.codigo_postal,'28001');assert.equal(location.google_maps_url,'https://maps.google.com/?q=40.4,-3.7');const routeRequest=writes.find(w=>w.p==='/portal-cliente/calcular-ruta').body;assert.equal(routeRequest.points[0].codigo_postal,'28001');assert.deepEqual(errors,[]);console.log('PASS bulk delete/common reasons, bulk states/individual reasons, overdue operations, client map/postcode/km/tonnes');
}finally{await browser?.close();await new Promise(r=>server.close(r));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
