const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(__dirname,'../build');
const driver={id:'driver-a',nombre:'Ana',apellidos:'García Pérez',alias:'Ana GP',vehiculo_id:'truck-a',vehiculo_matricula:'1234 ABC',remolque_matricula:'R-1234'};const today='2026-09-15';let points=[],writes=[];const orders=[{id:'order-a',numero:'QA-A',estado:'pendiente',fecha_carga:today,origen:'Madrid',destino:'Valencia'},{id:'order-b',numero:'QA-B',estado:'pendiente',fecha_carga:today,origen:'Madrid',destino:'Valencia'},{id:'old',numero:'QA-VENCIDO',estado:'en_curso',fecha_carga:'2026-08-10',fecha_descarga:'2026-08-11',origen:'Madrid',destino:'Sevilla'},{id:'future',numero:'QA-EN-RUTA',estado:'en_curso',fecha_carga:today,fecha_descarga:'2026-09-16',origen:'Madrid',destino:'Sevilla'}];
async function main(){const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'}[path.extname(f)]||'text/html'));fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[];
try{browser=await chromium.launch({headless:true,channel:'msedge'});const origin=`http://127.0.0.1:${server.address().port}`;
async function makePage(role){const page=await browser.newPage({viewport:{width:1500,height:1000}}),user={id:'qa',empresa_id:'qa-company',rol:role,nombre:'QA',plan:'enterprise',...(role==='cliente'?{cliente_id:'client'}:{})};page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date(today+'T10:00:00Z'));await page.addInitScript(u=>{localStorage.setItem('tms_token','qa');localStorage.setItem('tms_user',JSON.stringify(u));localStorage.setItem(`tms_onboarding_done:${u.empresa_id}:${u.rol}:${u.id}`,'1');},user);
await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname.replace('/api/v1',''),body=req.method()==='GET'?null:req.postDataJSON();let data=[];if(body||req.method()==='DELETE')writes.push({p,body,method:req.method()});
if(p==='/auth/me')data=user;else if(p.includes('notificaciones'))data={data:[],no_leidas:0};else if(p==='/pedidos'||p==='/pedidos/resumen-lista')data=[{id:'qa-info',numero:'QA-INFO',cliente_nombre:'CEMENTVAL MATERIALES DE CONSTRUCCIÓN, S.L.',fecha_descarga:'2026-09-18',hora_descarga:'16:30',chofer_id:'driver-a',vehiculo_id:'truck-a',vehiculo_matricula:'1234 ABC',remolque_matricula:'R-1234',estado:'incidencia',fecha_carga:today,origen:'Madrid',destino:'Valencia',puntos_carga:[{direccion:'Madrid'},{direccion:'Carga adicional Toledo'}],puntos_descarga:[{direccion:'Valencia'},{direccion:'Descarga adicional Alicante'}],incidencia_descripcion:'Retraso por avería en carretera'},{id:'qa-operativa',numero:'QA-OPERATIVA',estado:'confirmado',incidencia_tipo:'operativa',fecha_carga:today,fecha_entrega:'2026-09-19',origen:'Madrid',destino:'Valencia'}];else if(p==='/choferes')data=[driver];else if(p==='/portal-cliente/puntos'){if(body){const point={...body,id:'point-'+points.length};points.push(point);data=point;}else data=points;}else if(p==='/portal-cliente/calcular-ruta')data={km:350,warning:'Estimación QA'};else if(p==='/portal-cliente/solicitudes'&&body)data={id:'request-qa'};else if(p.includes('resumen'))data={};else if(p.includes('empresa'))data={plan:'enterprise'};
await route.fulfill({status:200,json:data});});await page.goto(origin,{waitUntil:'networkidle'});return page;}
const page=await makePage('gerente');
await page.locator('div[style*="z-index: 9999"]').waitFor({state:'hidden'});
await page.evaluate(()=>window.dispatchEvent(new CustomEvent('tms:navegar',{detail:'pedidos'})));
await page.locator('.orders-workspace').waitFor();
const row=page.getByRole('row').filter({hasText:'QA-INFO'});
await row.getByText('Ana GP',{exact:true}).waitFor();
await row.getByText(/18\/09\/2026/).waitFor();
await row.getByText('16:30',{exact:true}).waitFor();
await page.getByRole('columnheader',{name:'Fecha descarga',exact:true}).waitFor();
const scroll=page.locator('.orders-list-card .tgui-table-wrap');
const load=row.getByRole('button').filter({hasText:'+1 carga'});
await load.hover();
await page.getByRole('tooltip').filter({hasText:'Carga adicional Toledo'}).waitFor();
assert.equal(await load.evaluate(n=>getComputedStyle(n).cursor),'pointer');
await page.keyboard.press('Escape');
await page.getByRole('tooltip').waitFor({state:'hidden'});
const unload=row.getByRole('button').filter({hasText:'+1 descarga'});
await unload.click();
await page.getByRole('tooltip').filter({hasText:'Descarga adicional Alicante'}).waitFor();
// Pinned details remain visible when the pointer leaves; a second click closes.
await page.mouse.move(2,2);
assert.equal(await page.getByRole('tooltip').count(),1);
await unload.click();
await page.getByRole('tooltip').waitFor({state:'hidden'});
const incident=row.getByRole('button',{name:'Incidencia operativa',exact:true});
await incident.hover();
await page.getByRole('tooltip').filter({hasText:'Retraso por avería en carretera'}).waitFor();
await page.keyboard.press('Escape');
const operational=page.getByRole('row').filter({hasText:'QA-OPERATIVA'});
await operational.getByText('19/09/2026',{exact:true}).waitFor();
const explain=operational.getByRole('button',{name:'Operativa',exact:true});
await explain.hover();
await page.getByRole('tooltip').filter({hasText:'ejecución del transporte'}).waitFor();
assert.match(await page.getByRole('tooltip').innerText(),/No hay un motivo concreto registrado/);
await page.keyboard.press('Escape');
await explain.focus();
await page.getByRole('tooltip').waitFor();
await page.keyboard.press('Escape');
await explain.blur();
for(const width of [1500,1280,900]){
  await page.setViewportSize({width,height:1000});
  await scroll.evaluate(n=>{n.scrollLeft=0;});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Only the table should scroll horizontally');
  const dims=await row.evaluate(n=>({number:getComputedStyle(n.querySelector('.orders-number-cell')).whiteSpace,numberHeight:n.querySelector('.orders-link').getBoundingClientRect().height,action:n.querySelector('.orders-row-actions button').getBoundingClientRect().height,wordBreak:getComputedStyle(n.querySelector('.orders-client-cell')).overflowWrap}));
  assert.equal(dims.number,'nowrap');assert.equal(dims.wordBreak,'normal');assert.ok(dims.numberHeight<24);assert.ok(dims.action<45);
}
await page.setViewportSize({width:1500,height:1000});
await scroll.evaluate(n=>{n.scrollLeft=0;});
await page.locator('.orders-list-card').screenshot({path:path.join(process.env.TEMP,'transgest-orders-readable.png')});
await explain.hover();
await page.getByRole('tooltip').waitFor();
const bounds=await page.getByRole('tooltip').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=1500);
const tableBounds=await scroll.boundingBox(),numberBounds=await row.locator('.orders-number-cell').boundingBox();
assert.ok(numberBounds.x>=tableBounds.x-1&&numberBounds.x+numberBounds.width<=tableBounds.x+tableBounds.width,'Order reference stays visible while reading an incident');
await page.screenshot({path:path.join(process.env.TEMP,'transgest-orders-tooltip.png')});
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
const mobile=page.locator('.tgui-mobile-data .tgui-mobile-card').filter({hasText:'QA-INFO'});
await mobile.getByText('Descarga: 18/09/2026 16:30',{exact:true}).waitFor();
await mobile.getByRole('button',{name:'Incidencia operativa',exact:true}).click();
await page.getByRole('tooltip').filter({hasText:'Retraso por avería en carretera'}).waitFor();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
assert.deepEqual(errors,[]);
console.log('PASS: readable order columns/actions; unloading date/time and fallback; additional stops on hover/click; real incident descriptions and category explanations on confirmed orders; keyboard and mobile');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
