const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../build'),out=path.join(root,'qa/personnel');
const user={id:'qa-manager',empresa_id:'qa-company',rol:'gerente',nombre:'Responsable QA',activo:true,plan:'enterprise'};
const driver={id:'driver-1',nombre:'Ana',apellidos:'Prueba',vehiculo_id:'truck-1',activo:true};
const truck={id:'truck-1',matricula:'1234-BCD',clase:'tractora',chofer_id:driver.id,marca:'Vehículo QA',activo:true};
const order={id:'order-1',numero:'QA-001',vehiculo_id:truck.id,chofer_id:driver.id,fecha_carga:'2026-09-14',fecha_pedido:'2026-09-14',origen:'Valencia',destino:'Madrid',estado:'confirmado',importe:350,km_ruta:360};
async function main(){fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'}[path.extname(f)]||'text/html'));fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],writes=[];
try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1672,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-14T10:00:00Z'));await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname.replace('/api/v1','');let data=[];if(req.method()!=='GET')writes.push({p,body:req.postDataJSON()});
if(p==='/auth/me')data=user;else if(p==='/vehiculos')data=[truck];else if(p==='/choferes')data=[driver];else if(p==='/pedidos'||p==='/pedidos/resumen-lista')data=[order];else if(p.includes('chofer-config'))data={salario_base:1500,incentivo_pct:5,precio_noche:40,dieta_nacional:40};else if(p.includes('gasoil-config'))data={tipo:'fijo',precio_fijo:1.5};else if(p==='/taller/estado')data={stock:[],reparaciones:[]};else if(p==='/control-horario')data=[{id:'time-1',fecha:'2026-09-14',usuario_nombre:'Ana Prueba',usuario_rol:'oficina',estado:'cerrado',entrada_at:'2026-09-14T06:00:00Z',salida_at:'2026-09-14T14:00:00Z',trabajado_min:420,pausa_total_min:60}];else if(p==='/control-horario/resumen')data={jornadas:1,trabajado_min:420,abiertos:[]};else if(p.includes('jornada-config'))data={hora_entrada:'08:00',hora_salida:'17:00',pausa_min:60};else if(p.includes('notificaciones'))data={data:[],no_leidas:0};else if(p.includes('empresa')&&!/noches|repostajes|nominas|jornadas/.test(p))data={razon_social:'Empresa QA',plan:'enterprise'};return route.fulfill({status:200,json:data});});
await page.addInitScript(u=>{localStorage.setItem('tms_token','qa-only');localStorage.setItem('tms_user',JSON.stringify(u));localStorage.setItem(`tms_onboarding_done:${u.empresa_id}:${u.rol}:${u.id}`,'1');},user);
await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'networkidle'});await page.locator('[style*="tgSplashLogo"]').waitFor({state:'hidden'});
const go=async id=>{await page.evaluate(id=>window.dispatchEvent(new CustomEvent('tms:navegar',{detail:id})),id);await page.locator('.personnel-page').waitFor();await page.waitForTimeout(500);};
const shot=async name=>{for(const width of [390,768,1672]){await page.setViewportSize({width,height:1040});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`${name} overflow ${width}`);await page.screenshot({path:path.join(out,`${name}-${width}.png`),fullPage:true});}};
for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await go('hojas_ruta');await page.getByRole('button',{name:'Ver hoja',exact:true}).waitFor();await shot(`overview-${theme}`);await page.getByLabel('Buscar conductor o matrícula').fill('sin resultado');assert.equal(await page.getByRole('button',{name:'Ver hoja',exact:true}).count(),0);await page.getByLabel('Buscar conductor o matrícula').fill('');await page.getByRole('button',{name:'Ver hoja',exact:true}).click();for(const tab of ['Hoja de ruta','Gasoil','Noches','Conductor / Nómina']){await page.locator('.personnel-page').getByRole('button',{name:tab,exact:true}).click();await shot(`${tab.replaceAll('/','')}-${theme}`);}await page.getByRole('button',{name:'Gasoil',exact:true}).click();for(const action of ['Registrar litros','Configurar precios']){await page.getByRole('button',{name:action,exact:true}).click();await page.getByRole('dialog').waitFor();await shot(`${action}-${theme}`);await page.getByRole('dialog').locator('button').first().click();}
await page.getByRole('button',{name:'Noches',exact:true}).click();await page.getByRole('button',{name:'+ Añadir noches',exact:true}).click();await shot(`diet-modal-${theme}`);await page.getByRole('dialog').locator('button').first().click();await page.getByRole('button',{name:'Config.',exact:true}).click();await shot(`salary-modal-${theme}`);await page.getByRole('dialog').locator('button').first().click();
const printed=page.waitForEvent('popup');await page.getByRole('button',{name:'Imprimir / PDF',exact:true}).click();const printPage=await printed;await printPage.waitForLoadState();assert.match(await printPage.locator('body').innerText(),/1234-BCD/);await printPage.close();
await go('nominas');await page.getByRole('button',{name:'Preparar nómina',exact:true}).first().waitFor();for(const tab of ['Generar nóminas','Historial emitidas','Transparencia salarial']){await page.getByRole('button',{name:tab,exact:true}).click();await shot(`${tab}-${theme}`);}await page.getByRole('button',{name:'Generar nóminas',exact:true}).click();await page.getByRole('button',{name:'Preparar nómina',exact:true}).first().click();await page.getByRole('dialog').waitFor();await shot(`payroll-modal-${theme}`);await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();
await go('control_horario');await page.getByRole('button',{name:'Editar',exact:true}).first().waitFor();await shot(`clock-${theme}`);const csv=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar CSV',exact:true}).click();assert.match((await csv).suggestedFilename(),/^control-horario-/);await page.getByRole('button',{name:'Editar',exact:true}).first().click();await shot(`clock-modal-${theme}`);await page.getByLabel('Motivo obligatorio').fill('Corrección QA');await page.getByRole('button',{name:'Guardar ajuste',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('navigation',{name:'Gestión del personal'}).getByRole('button',{name:'Hojas de ruta',exact:true}).click();await page.getByRole('button',{name:'Ver hoja',exact:true}).waitFor();
}
assert(writes.some(w=>w.p.includes('time-1')&&w.body.motivo==='Corrección QA'));assert.deepEqual(errors,[]);console.log('OK personnel: overview filters, all tabs, modal layouts, time edit, 3 sizes and 2 themes');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({errors,writes},null,2));}finally{await browser?.close();await new Promise(r=>server.close(r));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
