const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../build'),out=path.join(root,'qa','portal');
const user={id:'qa-client-user',cliente_id:'client-1',empresa_id:'company-1',rol:'cliente_portal',nombre:'Carlos Prueba',activo:true,plan:'enterprise'};
const empresa={razon_social:'Transportes de prueba',telefono:'960000000',email:'qa@example.com',plan:'enterprise'};
const orders=[{id:'order-1',numero:'P-QA-001',origen:'Valencia',destino:'Barcelona',estado:'en_curso',mercancia:'Palets',peso_kg:4200,bultos:8,fecha_carga:'2026-09-12',fecha_descarga:'2026-09-13',vehiculo_matricula:'1234-BCD'},{id:'order-2',numero:'P-QA-002',origen:'Madrid',destino:'Valencia',estado:'confirmado',mercancia:'Mercancía general',fecha_carga:'2026-09-13'},{id:'order-3',numero:'P-QA-003',origen:'Bilbao',destino:'Madrid',estado:'facturado',fecha_carga:'2026-09-10'}];
const invoices=[{id:'invoice-1',numero:'F-QA-001',estado:'emitida',fecha:'2026-09-01',fecha_vencimiento:'2026-09-30',base_imponible:1000,cuota_iva:210,total:1210,lineas:[{id:'line-1',concepto:'Transporte',cantidad:1,precio_unit:1000}]}];
const requests=[{id:'request-1',estado:'pendiente',origen:'Valencia',destino:'Madrid',referencia_cliente:'REF-QA',mercancia:'Palets',fecha_carga:'2026-10-01',fecha_descarga:'2026-10-02',viajes:1}];
async function main(){fs.mkdirSync(out,{recursive:true});const errors=[],writes=[],checks=[];let fail=false;const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'}[path.extname(file)]||'text/html'));fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1672,height:1040}});page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});await page.clock.setFixedTime(new Date('2026-09-12T08:00:00Z'));
 await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname.replace('/api/v1','');let data=[];const body=req.method()==='GET'?null:req.postDataJSON();if(body)writes.push({p,body,method:req.method()});
 if(p==='/auth/me')data=user;
 else if(p==='/portal-cliente/pedidos'){if(fail)return route.fulfill({status:503,json:{error:'No disponible'}});data=orders;}
 else if(p==='/portal-cliente/facturas')data=invoices;
 else if(p==='/portal-cliente/facturas/invoice-1')data=invoices[0];
 else if(p==='/portal-cliente/solicitudes')data=body?{id:'request-created',...body}:requests;
 else if(p==='/portal-cliente/solicitudes/request-1')data={...requests[0],...body};
 else if(p==='/portal-cliente/puntos')data=body?{id:'point-created',...body}:[];
 else if(p==='/portal-cliente/resumen')data={pedidos:{activos:2},solicitudes:{abiertas:1},facturas:{total_facturado:1210,total_pendiente:1210},documentos:{con_albaran:1,viajes:3},acciones:[{tipo:'factura',titulo:'Una factura pendiente',detalle:'Consulta tu estado de cuenta',tab:'cuenta',prioridad:'media'}]};
 else if(p==='/portal-cliente/documentos-resumen')data={pedidos:[{pedido_id:'order-1',albaranes_count:1}],total:3,con_albaran:1,sin_albaran:2,documentos_total:1};
 else if(p.endsWith('/albaranes'))data=[{id:'doc-1',nombre:'Albarán QA.pdf',download_url:'/api/v1/portal-cliente/qa-file'}];
 else if(p==='/portal-cliente/qa-file')return route.fulfill({status:200,contentType:'application/pdf',body:Buffer.from('%PDF-1.4\nQA fixture')});
 else if(p.endsWith('/eventos'))data=[{id:'event-1',tipo:'creada',etiqueta:'Salida registrada',created_at:'2026-09-12T08:00:00Z'}];
 else if(p.includes('notificaciones'))data={data:[],no_leidas:0};
 else if(p.includes('empresa')||p.includes('config'))data=empresa;
 return route.fulfill({status:200,json:data});});
 await page.addInitScript(u=>{localStorage.setItem('tms_token','qa-local');localStorage.setItem('tms_user',JSON.stringify(u));localStorage.setItem(`tms_onboarding_done:${u.empresa_id}:${u.rol}:${u.id}`,'1');},user);
 await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'networkidle'});await page.getByRole('heading',{name:'¡Hola, Carlos!'}).waitFor().catch(async e=>{console.error(await page.locator('body').innerText());throw e;});await page.locator('[style*="tgSplashLogo"]').waitFor({state:'hidden'});
 const nav=page.getByRole('navigation',{name:'Navegación del portal'}),tabs=page.getByRole('navigation',{name:'Apartados del portal'});
 assert.equal(await page.locator('.portal-shipment-list button').count(),3);await page.locator('.portal-shipment-list button').filter({hasText:'P-QA-002'}).click();await page.locator('.portal-shipment-detail').getByText('P-QA-002',{exact:true}).waitFor();await page.getByLabel('Estado del envío').selectOption('en_curso');assert.equal(await page.locator('.portal-shipment-list button').count(),1);await page.getByLabel('Estado del envío').selectOption('');await page.getByLabel('Buscar en el portal').fill('P-QA-003');assert.equal(await page.locator('.portal-shipment-list button').count(),1);await page.getByLabel('Buscar en el portal').fill('');checks.push('Shipment selection, live detail and combined filters');
 for(const theme of ['light','dark']){if(theme==='dark'){await page.locator('.portal-account summary').click();await page.getByRole('button',{name:'Tema oscuro',exact:true}).click();await page.locator('.portal-account summary').click();}
 for(const tab of ['Inicio','Mis envíos','Solicitar servicio','Documentos','Facturación','Ayuda']){await nav.getByRole('button',{name:tab,exact:true}).click();for(const width of [390,768,1672]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`${tab} overflow ${width}`);assert.deepEqual(await page.locator('.portal-header nav button,.portal-tabs button').evaluateAll(nodes=>nodes.filter(n=>n.scrollWidth>n.clientWidth+1).map(n=>n.textContent)),[],`${tab} compressed navigation ${width}`);await page.screenshot({path:path.join(out,`${tab}-${theme}-${width}.png`),fullPage:true});}}}
 checks.push('All main sections at mobile/tablet/desktop sizes in both themes');
 await nav.getByRole('button',{name:'Mis envíos',exact:true}).click();await page.locator('.portal-shipment-list button').filter({hasText:'P-QA-001'}).click();await page.getByRole('button',{name:'Ver actividad',exact:true}).click();await page.getByText('Salida registrada',{exact:true}).waitFor();await page.getByRole('button',{name:'Consultar documentos',exact:true}).click();await page.locator('.portal-documents button').first().waitFor();const docDownload=page.waitForEvent('download');await page.locator('.portal-documents button').first().click();assert.equal((await docDownload).suggestedFilename(),'Albarán QA.pdf');checks.push('Shipment document download');
 await nav.getByRole('button',{name:'Facturación',exact:true}).click();await page.getByRole('button',{name:'Ver factura',exact:true}).click();await page.locator('.portal-overlay').waitFor();for(const width of [390,1440]){await page.setViewportSize({width,height:1000});await page.screenshot({path:path.join(out,`invoice-${width}.png`)});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}await page.locator('.portal-overlay').getByRole('button',{name:'Cerrar',exact:true}).click();
 await tabs.getByRole('button',{name:'Estado de cuenta',exact:true}).click();let dl=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar estado',exact:true}).click();assert.match((await dl).suggestedFilename(),/^estado-cuenta/);
 await tabs.getByRole('button',{name:'Mis solicitudes',exact:true}).click();dl=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar resumen',exact:true}).click();assert.match((await dl).suggestedFilename(),/^resumen-solicitudes/);
 await page.getByRole('button',{name:'Editar solicitud',exact:true}).click();const form=page.locator('.portal-overlay .portal-form');await form.waitFor();await form.getByLabel('Referencia cliente',{exact:true}).fill('REF-EDITED');await form.getByRole('button',{name:'Guardar cambios',exact:true}).click();await form.waitFor({state:'hidden'});assert(writes.some(w=>w.p.endsWith('/solicitudes/request-1')&&w.body.referencia_cliente==='REF-EDITED'));checks.push('Invoice detail, report downloads and edit request');
 await nav.getByRole('button',{name:'Solicitar servicio',exact:true}).click();const create=page.locator('.portal-form');await create.getByLabel('Origen *',{exact:true}).fill('Valencia');await create.getByLabel('Destino *',{exact:true}).fill('Madrid');await create.getByLabel('Fecha carga',{exact:true}).fill('2026-10-01');await create.getByLabel('Fecha descarga',{exact:true}).fill('2026-10-02');await create.getByRole('button',{name:'Enviar solicitud',exact:true}).click();await page.getByRole('heading',{name:'Mis solicitudes',exact:true}).waitFor();assert(writes.some(w=>w.p==='/portal-cliente/solicitudes'&&w.method==='POST'&&w.body.origen==='Valencia'));checks.push('Create service request via existing portal API');
 fail=true;await page.getByRole('button',{name:'Actualizar',exact:true}).click();await page.locator('.portal-load-error').waitFor();fail=false;await page.locator('.portal-load-error').getByRole('button',{name:'Reintentar',exact:true}).click();await page.locator('.portal-load-error').waitFor({state:'hidden'});
 await page.locator('.portal-account summary').click();await page.getByRole('button',{name:'Cerrar sesión',exact:true}).click();await page.getByRole('heading',{name:'Iniciar sesión',exact:true}).waitFor();checks.push('API failure/retry and logout');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
