const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../',process.env.BUILD_PATH||'build');
async function main(){const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'}[path.extname(f)]||'text/html'));fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],writes=[];let tickets=[];const id='11111111-1111-4111-8111-111111111111';
 try{browser=await chromium.launch({headless:true,channel:'msedge'});const origin=`http://127.0.0.1:${server.address().port}`;
 async function pageFor(role){const page=await browser.newPage({viewport:{width:1440,height:1000}}),user={id:'qa-user',empresa_id:'qa-company',rol:role,nombre:'Responsable QA',plan:'enterprise',...(['colaborador','chofer'].includes(role)?{colaborador_id:'supplier'}:{})};page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(u=>{localStorage.setItem('tms_token','qa');localStorage.setItem('tms_user',JSON.stringify(u));localStorage.setItem(`tms_onboarding_done:${u.empresa_id}:${u.rol}:${u.id}`,'1');},user);
 await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname.replace('/api/v1','');let data=[];if(req.method()!=='GET')writes.push({p,body:req.postDataJSON()});
 if(p==='/auth/me')data=user;else if(p.includes('product'))data={producto:'planner'};else if(p.includes('notificaciones'))data={data:[],no_leidas:0};else if(p==='/soporte'){if(req.method()==='POST'){tickets=[{id,asunto:req.postDataJSON().asunto,estado:'abierta',updated_at:new Date().toISOString()}];data={id};}else data=tickets;}
 else if(p===`/soporte/${id}`)data={...tickets[0],mensajes:[{id:'msg',autor_nombre:'Responsable QA',mensaje:'Consulta de prueba',created_at:new Date().toISOString()}]};
 else if(p==='/supplier-app/pedidos')data=[{id:'trip',numero:'PROV-QA',estado:'pendiente',origen:'Madrid',destino:'Valencia'}];else if(p==='/supplier-app/vehiculos')data=[{id:'v',matricula:'1234ABC',tipo:'tractora'}];
 else if(p==='/planner/muelles')data=[{id:'dock',nombre:'Muelle 1',almacen:'Central'}];else if(p==='/planner/reservas')data=[];else if(p.includes('empresa'))data={plan:'enterprise'};
 await route.fulfill({status:200,json:data});});await page.goto(origin,{waitUntil:'networkidle'});return page;}
 const page=await pageFor('gerente');await page.getByRole('button',{name:process.env.BUILD_PATH?'Soporte':'Contactar soporte',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Asunto',{exact:true}).fill('Consulta QA');await dialog.getByLabel('Mensaje',{exact:true}).fill('Consulta de prueba');await dialog.getByRole('button',{name:'Enviar',exact:true}).click();await dialog.getByRole('heading',{name:'Consulta QA'}).waitFor();assert.ok(writes.some(w=>w.p==='/soporte'&&w.body.mensaje==='Consulta de prueba'));
 await page.setViewportSize({width:390,height:844});assert.equal(await dialog.evaluate(n=>n.scrollWidth>n.clientWidth+1),false);await dialog.getByRole('button',{name:'Cerrar',exact:true}).click();
 if(process.env.BUILD_PATH){await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Muelles y horarios',exact:true}).click();await page.getByRole('heading',{name:'Planificación de cargas y muelles'}).waitFor();await page.getByRole('button',{name:'Reservar hueco',exact:true}).click();const booking=page.getByRole('dialog');await booking.getByLabel('Notas',{exact:true}).fill('Reserva QA');await booking.getByRole('button',{name:'Guardar',exact:true}).click();await booking.waitFor({state:'hidden'});assert.ok(writes.some(w=>w.p==='/planner/reservas'&&w.body.notas==='Reserva QA'));for(const label of ['Almacén y stock','Planificación de flota','Gestión de viajes','Conductores','Vehículos','Intelligence'])assert.equal(await page.getByRole('navigation',{name:'Planner'}).getByRole('button',{name:label,exact:true}).count(),1);await page.getByRole('button',{name:'Gestión de viajes',exact:true}).click();await page.locator('.orders-workspace').waitFor();await page.evaluate(()=>window.dispatchEvent(new CustomEvent('tms:navegar',{detail:'gestion_trafico'})));await page.getByRole('heading',{name:'Mesa de tráfico',exact:true}).waitFor();}
 await page.close();
 const supplier=await pageFor('colaborador');await supplier.getByRole('heading',{name:'Portal del colaborador'}).waitFor();await supplier.getByText('PROV-QA',{exact:true}).waitFor();assert.equal(await supplier.getByRole('button',{name:/factur|vacaciones|tacógrafo/i}).count(),0);await supplier.getByRole('button',{name:'Añadir vehículo'}).click();await supplier.getByRole('dialog').getByLabel('Matrícula').fill('5678ABC');await supplier.getByRole('dialog').getByRole('button',{name:'Guardar'}).click();assert.ok(writes.some(w=>w.p==='/supplier-app/vehiculos'&&w.body.matricula==='5678ABC'));
 await supplier.getByRole('button',{name:'Invitar conductor'}).click();await supplier.getByRole('dialog').getByLabel('Nombre',{exact:true}).fill('Conductor QA');await supplier.getByRole('dialog').getByLabel('Email',{exact:true}).fill('qa@example.invalid');await supplier.getByRole('dialog').getByRole('button',{name:'Enviar invitación'}).click();assert.ok(writes.some(w=>w.p==='/supplier-app/conductores'));
 await supplier.getByRole('button',{name:'Albaranes / POD',exact:true}).click();const documents=supplier.getByRole('dialog');await documents.locator('input[type=file]').setInputFiles({name:'albaran.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 QA')});await documents.getByRole('button',{name:'Adjuntar albarán',exact:true}).click();await supplier.waitForTimeout(250);assert.ok(writes.some(w=>w.p==='/supplier-app/pedidos/trip/documentos'&&w.body.tipo==='albaran_colaborador'));await supplier.close();
 const driver=await pageFor('chofer');await driver.getByRole('heading',{name:'Mis viajes',exact:true}).waitFor();assert.equal(await driver.getByRole('button',{name:/vacaciones|tacógrafo|invitar conductor|añadir vehículo/i}).count(),0);assert.equal(await driver.getByRole('combobox',{name:'Asignar conductor'}).count(),0);await driver.close();assert.deepEqual(errors,[]);console.log('PASS browser: support conversation/mobile, restricted supplier portal, vehicle and driver forms');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
