const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../build'),out=path.join(root,'qa/traffic');
const user={id:'qa-manager',empresa_id:'qa-company',rol:'gerente',nombre:'Responsable QA',activo:true,plan:'enterprise'};
const driver={id:'driver-1',nombre:'Ana',apellidos:'Prueba',vehiculo_id:'truck-1',activo:true};
const truck={id:'truck-1',matricula:'1234-BCD',clase:'tractora',chofer_id:driver.id,marca:'Vehículo QA',activo:true};
const order={id:'order-1',numero:'QA-001',vehiculo_id:truck.id,chofer_id:driver.id,fecha_carga:'2026-09-14',fecha_pedido:'2026-09-14',origen:'Valencia',destino:'Madrid',estado:'confirmado',importe:350,km_ruta:360};
async function main(){fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'}[path.extname(f)]||'text/html'));fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],writes=[];
try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1672,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-14T10:00:00Z'));await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname.replace('/api/v1','');let data=[];if(req.method()!=='GET')writes.push({p,body:req.postDataJSON()});
if(p==='/auth/me')data=user;else if(p==='/vehiculos')data=[truck];else if(p==='/choferes')data=[driver];else if(p==='/pedidos'||p==='/pedidos/resumen-lista')data=[order,{...order,id:'order-2',numero:'QA-002',fecha_carga:'2026-09-15'}];else if(p.includes('chofer-config'))data={salario_base:1500,incentivo_pct:5,precio_noche:40,dieta_nacional:40};else if(p.includes('gasoil-config'))data={tipo:'fijo',precio_fijo:1.5};else if(p==='/taller/estado')data={stock:[],reparaciones:[]};else if(p==='/control-horario')data=[{id:'time-1',fecha:'2026-09-14',usuario_nombre:'Ana Prueba',usuario_rol:'oficina',estado:'cerrado',entrada_at:'2026-09-14T06:00:00Z',salida_at:'2026-09-14T14:00:00Z',trabajado_min:420,pausa_total_min:60}];else if(p==='/control-horario/resumen')data={jornadas:1,trabajado_min:420,abiertos:[]};else if(p.includes('jornada-config'))data={hora_entrada:'08:00',hora_salida:'17:00',pausa_min:60};else if(p.includes('notificaciones'))data={data:[],no_leidas:0};else if(p.includes('empresa')&&!/noches|repostajes|nominas|jornadas/.test(p))data={razon_social:'Empresa QA',plan:'enterprise'};return route.fulfill({status:200,json:data});});
await page.addInitScript(u=>{localStorage.setItem('tms_token','qa-only');localStorage.setItem('tms_user',JSON.stringify(u));localStorage.setItem(`tms_onboarding_done:${u.empresa_id}:${u.rol}:${u.id}`,'1');},user);
await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'networkidle'});await page.locator('[style*="tgSplashLogo"]').waitFor({state:'hidden'});
const go=async id=>{await page.evaluate(id=>window.dispatchEvent(new CustomEvent('tms:navegar',{detail:id})),id);await page.locator('.traffic-shell').waitFor();await page.waitForTimeout(500);};
const shot=async name=>{for(const width of [390,768,1672]){await page.setViewportSize({width,height:1040});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`${name} overflow ${width}`);await page.screenshot({path:path.join(out,`${name}-${width}.png`),fullPage:true});if(width===390&&name.startsWith('week')){assert.equal(await page.locator('.traffic-redesign').evaluate(n=>n.scrollWidth>n.clientWidth+1),false,'traffic container overflow');await page.locator('.traffic-mobile-board').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`mobile-cards-${name}.png`)});}}};
for(const theme of ['light','dark']){
await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await go('gestion_trafico');await page.locator('.tg-planificacion-tabs').getByRole('button',{name:'Cuadrante semanal',exact:true}).click();await page.locator('.tg-traffic-board').getByText('QA-001',{exact:false}).first().waitFor();await shot(`week-${theme}`);
await page.setViewportSize({width:390,height:1040});assert.equal(await page.locator('.traffic-mobile-trip').count(),2);await page.getByRole('button',{name:'Vista día',exact:true}).click();assert.equal(await page.locator('.traffic-mobile-trip').count(),1);await page.getByLabel('Día del plan').fill('2026-09-15');assert.equal(await page.locator('.traffic-mobile-trip').count(),1);assert.match(await page.locator('.traffic-mobile-trip').innerText(),/QA-002/);await shot(`day-${theme}`);await page.getByRole('button',{name:'Vista semana',exact:true}).click();
await page.getByLabel('Buscar viajes').fill('QA-002');assert.equal(await page.locator('.traffic-mobile-trip').count(),1);await page.getByLabel('Buscar viajes').fill('');
await page.setViewportSize({width:390,height:1040});await page.getByRole('button',{name:'+ Añadir viaje',exact:true}).first().click();await page.getByRole('dialog').waitFor();await shot(`add-modal-${theme}`);await page.getByRole('button',{name:'Cancelar',exact:true}).click();
for(const tab of ['Plan diario','Agrupaciones','Optimización de rutas']){await page.locator('.tg-planificacion-tabs').getByRole('button',{name:tab,exact:true}).click();await page.waitForTimeout(300);await shot(`${tab}-${theme}`);}
}
assert.deepEqual(errors,[]);console.log('OK traffic: weekly/daily views, search, assignment window, all planning tabs, mobile/tablet/desktop and both themes');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({errors},null,2));}finally{await browser?.close();await new Promise(r=>server.close(r));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
