const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../build'),out=path.join(root,'qa/workspaces');
const user={id:'qa-manager',empresa_id:'qa-company',rol:'gerente',nombre:'Responsable QA',activo:true,plan:'enterprise'};
const driver={id:'driver-1',nombre:'Ana',apellidos:'Prueba',vehiculo_id:'truck-1',activo:true};
const truck={id:'truck-1',matricula:'1234-BCD',clase:'tractora',chofer_id:driver.id,marca:'Vehículo QA',activo:true};
const order={id:'order-1',numero:'QA-001',vehiculo_id:truck.id,chofer_id:driver.id,fecha_carga:'2026-09-14',fecha_pedido:'2026-09-14',origen:'Valencia',destino:'Madrid',estado:'confirmado',importe:350,km_ruta:360};
async function main(){fs.mkdirSync(out,{recursive:true});const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(root,'index.html');res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'}[path.extname(f)]||'text/html'));fs.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],writes=[];
try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1672,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-14T10:00:00Z'));await page.route('**/api/v1/**',async route=>{const req=route.request(),p=new URL(req.url()).pathname.replace('/api/v1','');let data=[];if(req.method()!=='GET')writes.push({p,body:req.postDataJSON()});
if(p==='/auth/me')data=user;else if(p==='/agenda')data=[{id:'event-1',metadata:{recordatorio_pospuesto_hasta:'2026-09-16T12:00:00Z'},titulo:'Confirmar entrega QA',fecha_inicio:'2026-09-14T18:00:00',estado:'pendiente',tipo:'tarea',prioridad:'alta'}];else if(p==='/agenda/usuarios')data=[user];else if(p==='/portal-cliente/admin/solicitudes')data=[{id:'request-1',cliente_nombre:'Cliente QA',origen:'Valencia',destino:'Madrid',estado:'pendiente',fecha_carga:'2026-09-15',created_at:'2026-09-14T08:00:00Z',importe:350}];else if(p==='/facturas')data=[{id:'invoice-1',numero:'F-QA',cliente_nombre:'Cliente QA',cliente_id:'client-1',estado:'emitida',fecha:'2026-09-14',base_imponible:350,total:423.5}];else if(p==='/vehiculos')data=[truck];else if(p==='/choferes')data=[driver];else if(p==='/pedidos'||p==='/pedidos/resumen-lista')data=[order,{...order,id:'order-2',numero:'QA-002',fecha_carga:'2026-09-15'}];else if(p.includes('chofer-config'))data={salario_base:1500,incentivo_pct:5,precio_noche:40,dieta_nacional:40};else if(p.includes('gasoil-config'))data={tipo:'fijo',precio_fijo:1.5};else if(p==='/taller/estado')data={stock:[],reparaciones:[]};else if(p==='/control-horario')data=[{id:'time-1',fecha:'2026-09-14',usuario_nombre:'Ana Prueba',usuario_rol:'oficina',estado:'cerrado',entrada_at:'2026-09-14T06:00:00Z',salida_at:'2026-09-14T14:00:00Z',trabajado_min:420,pausa_total_min:60}];else if(p==='/control-horario/resumen')data={jornadas:1,trabajado_min:420,abiertos:[]};else if(p.includes('jornada-config'))data={hora_entrada:'08:00',hora_salida:'17:00',pausa_min:60};else if(p==='/notificaciones/operativas/colaboradores')data={items:[{key:'alert-1',pedido_id:'order-1',title:'Albarán pendiente QA',detail:'Falta el justificante de entrega.',severity:'alta',fecha_carga:'2026-09-14',fecha_descarga:'2026-09-15'}],resumen:{total:1,alta:1,albaranes_pendientes:1,colaboradores:1}};else if(p.includes('notificaciones'))data={data:[],no_leidas:0};else if(p.includes('empresa')&&!/noches|repostajes|nominas|jornadas/.test(p))data={razon_social:'Empresa QA',plan:'enterprise'};return route.fulfill({status:200,json:data});});
await page.addInitScript(u=>{localStorage.setItem('tms_token','qa-only');localStorage.setItem(`tms_avim_minimized:${u.empresa_id}`,'1');localStorage.setItem('tms_user',JSON.stringify(u));localStorage.setItem(`tms_onboarding_done:${u.empresa_id}:${u.rol}:${u.id}`,'1');},user);
await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'networkidle'});await page.locator('[style*="tgSplashLogo"]').waitFor({state:'hidden'});
const go=async (id,selector)=>{await page.evaluate(id=>window.dispatchEvent(new CustomEvent('tms:navegar',{detail:id})),id);await page.locator(selector).waitFor();await page.waitForTimeout(300);};
const shot=async (name,selector)=>{for(const width of [390,768,1672]){await page.setViewportSize({width,height:1040});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`${name} document overflow ${width}`);if(selector&&await page.locator(selector).evaluate(n=>n.scrollWidth>n.clientWidth+1)){console.log(name,await page.locator(selector).evaluate(n=>[...n.querySelectorAll('*')].filter(e=>e.getBoundingClientRect().right>n.getBoundingClientRect().right+1).slice(0,8).map(e=>({html:e.outerHTML.slice(0,180),width:e.getBoundingClientRect().width}))));await page.screenshot({path:path.join(out,'overflow.png')});}if(selector)assert.equal(await page.locator(selector).evaluate(n=>n.scrollWidth>n.clientWidth+1),false,`${name} container overflow ${width}`);await page.screenshot({path:path.join(out,`${name}-${width}.png`),fullPage:true});}};
for(const theme of ['light','dark']){
await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);
await go('agenda','.tg-agenda-page');await page.getByRole('button',{name:'Semana',exact:true}).click();await page.locator('.agenda-event').waitFor();await shot(`agenda-${theme}`,'.tg-agenda-page');await page.getByRole('button',{name:'Día',exact:true}).click();assert.equal(await page.locator('.agenda-time-grid>.agenda-day-heading').count(),1);await page.getByRole('button',{name:'Mes',exact:true}).click();assert.equal(await page.locator('.tg-agenda-day').count(),42);await page.getByRole('button',{name:'+ Nueva tarea',exact:true}).click();await page.getByRole('dialog').waitFor();await shot(`agenda-modal-${theme}`);await page.getByPlaceholder('Ej: Confirmar entregas de mañana').fill('Nueva tarea QA');await page.getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.ok(writes.some(w=>w.p==='/agenda'&&w.body.titulo==='Nueva tarea QA'));
await go('choferes','.drivers-workspace');await page.getByLabel('Buscar conductores').fill('inexistente');await page.getByText('No hay conductores con estos filtros').waitFor();await page.getByLabel('Buscar conductores').fill('Ana');await page.getByRole('button',{name:'Ver',exact:true}).click();await page.getByRole('dialog').waitFor();await shot(`driver-modal-${theme}`);for(const tab of ['Contrato y permisos','Nóminas','Plataformas','Equipos / EPIs','Jornadas','Historial de vehículos']){await page.getByRole('dialog').getByRole('button',{name:tab,exact:true}).click();await page.waitForTimeout(150);}await page.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();await shot(`drivers-${theme}`,'.drivers-workspace');
// Navigation unmounts the driver editor without writing changes.
await go('solicitudes','.operations-requests');await page.getByText('Cliente QA',{exact:true}).first().waitFor();await shot(`requests-${theme}`,'.operations-requests');await page.getByRole('button',{name:'Editar',exact:true}).click();await page.getByText('Editar solicitud',{exact:true}).waitFor();await shot(`request-modal-${theme}`);await page.getByRole('button',{name:'Guardar cambios',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.ok(writes.some(w=>w.p==='/portal-cliente/admin/solicitudes/request-1'));
await go('dashboard','.dashboard-workspace');await page.getByRole('button',{name:'Análisis BI',exact:true}).click();await page.getByLabel('Buscar cliente en BI').waitFor();await page.getByLabel('Buscar cliente en BI').fill('inexistente');await page.getByLabel('Buscar cliente en BI').fill('');await page.getByLabel('Serie financiera').selectOption('facturado');await shot(`bi-${theme}`);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar indicadores',exact:true}).click();assert.match((await download).suggestedFilename(),/dashboard-bi/);
await go('avisos','.notices-workspace');await shot(`notices-${theme}`,'.notices-workspace');await page.getByTitle('Avisos importantes',{exact:true}).click();await page.locator('.avimp-panel').waitFor();await shot(`avimp-${theme}`,'.avimp-panel');await page.getByTitle('Minimizar avisos importantes',{exact:true}).click();
}
assert.deepEqual(errors,[]);console.log('OK workspaces: agenda views, conductor search/editor, request editor, BI filters/export, notices, three widths and two themes');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({errors},null,2));}finally{await browser?.close();await new Promise(r=>server.close(r));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
