export const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const movementLabels={entrega:"Entrada cliente / obra",devolucion:"Devolución al propietario",rectificativa_devolucion:"Rectificación de devolución",entrada_stock:"Entrada de stock",salida_stock:"Salida de stock"};
export function warehouseDocument(title, empresa, body) {
  const name=empresa?.razon_social || empresa?.nombre || "TransGest";
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font:12px Arial,sans-serif;color:#172e36;margin:24px}header{border-bottom:3px solid #00867e;padding-bottom:16px;margin-bottom:22px;display:flex;justify-content:space-between;gap:20px}h1{font-size:22px;margin:0 0 8px}h2{font-size:16px}p{line-height:1.5}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.box{border:1px solid #d6e3e5;padding:14px;border-radius:7px}table{border-collapse:collapse;width:100%;margin:18px 0;font-size:11px}th{background:#edf7f5;text-align:left;padding:9px}td{padding:9px;border-bottom:1px solid #d6e3e5}tr{break-inside:avoid}small{color:#547078}.status{padding:12px;background:#fff5df;border:1px solid #e5ba67;margin:14px 0}.sign{margin-top:25px;height:95px;border:1px solid #bcced1;padding:12px}.tools{margin:0 0 18px}button{background:#007f78;color:white;border:0;border-radius:6px;padding:10px 20px;cursor:pointer}@media print{body{margin:0}.tools{display:none}thead{display:table-header-group}}</style></head><body><div class="tools"><button data-print="true">Imprimir / Guardar PDF</button></div><header><div><h1>${escapeHtml(title)}</h1><small>Gestión de almacén</small></div><div><strong>${escapeHtml(name)}</strong><br>${escapeHtml(empresa?.cif||empresa?.nif||"")}<br>${escapeHtml(empresa?.direccion||"")}</div></header>${body}</body></html>`;
}
export function buildWarehouseDelivery(m,cliente,empresa,obra) {
  const pending=m.tipo==='devolucion' && String(m.estado_salida||'confirmada')!=='confirmada';
  const label=m.tipo==='devolucion'?'Albarán de devolución':'Albarán de entrada';
  return warehouseDocument(`${label} · ${m.num_albaran||'Sin número'}`,empresa,`${pending?'<div class="status"><strong>DEVOLUCIÓN PREPARADA · SALIDA NO CONFIRMADA</strong><br>La preparación de este documento no confirma la entrega ni modifica el stock.</div>':''}<div class="grid"><div class="box"><h2>Propietario de los palets</h2>${escapeHtml(cliente?.nombre||m.propietario_nombre||m.cliente_nombre||'Sin identificar')}<p>${escapeHtml(cliente?.cif||'')}<br>${escapeHtml(cliente?.direccion||'')}</p></div><div class="box"><h2>Referencia del movimiento</h2>Fecha: ${escapeHtml(String(m.fecha||'').slice(0,10))}<br>Obra / referencia: ${escapeHtml(m.obra_referencia||m.pedido_ref||'—')}<br>Cliente de la obra: ${escapeHtml(obra?.nombre||m.cliente_movimiento_nombre||'—')}<br>Almacén: ${escapeHtml(m.almacen_nombre||'Sin especificar')}</div></div><table><thead><tr><th>Movimiento</th><th>Soporte</th><th>Unidades</th></tr></thead><tbody><tr><td>${escapeHtml(movementLabels[m.tipo]||m.tipo)}</td><td>Palets</td><td>${Number(m.cantidad)||0}</td></tr></tbody></table><p>Observaciones: ${escapeHtml(m.notas||'—')}</p><p>Transporte vinculado: ${escapeHtml(m.pedido_transporte_id||'Sin vincular')}</p><div class="grid"><div class="sign">Entrega · Nombre, DNI, fecha y firma</div><div class="sign">Recepción · Nombre, DNI, fecha, sello y firma</div></div>`);
}
export function openWarehouseDocument(html) {
  const win=window.open('','_blank');
  if(!win)throw new Error('Permite las ventanas emergentes para abrir el documento.');
  win.opener=null;win.document.open();win.document.write(html);win.document.close();const printButton=win.document.querySelector("[data-print]");if(printButton)printButton.onclick=()=>win.print();return win;
}
