import { useMemo, useState } from "react";
import { Button, Card, KpiCard, Tabs, SearchInput, DataTable, MobileDataCard, Badge, EmptyState, Icon } from "../../ui";
import { useAuth } from "../../context/AuthContext";
import { notify } from "../../services/notify";
import { warehouseDocument, escapeHtml as esc, movementLabels, openWarehouseDocument } from "./documents";
import TransportDocuments from "./TransportDocuments";
import "./warehouse.css";

export default function WarehouseWorkspace({ movements, loading, error, reload, stock, alerts, empresa, sign, create, edit, confirm, rectify, albaran, onSection, details, setAlert }) {
  const {puedeEditar,puedeVer}=useAuth(),canEdit=puedeEditar('palets');
  const [section,setSection]=useState('');
  const openSection=value=>{setSection(value);onSection(value);};
  const [tab,setTab]=useState('stock'),[q,setQ]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[transport,setTransport]=useState(null);
  const pending=m=>m.tipo==='devolucion'&&String(m.estado_salida||'confirmada')!=='confirmada';
  const rows=useMemo(()=>{
    const owners=new Map();
    movements.forEach(m=>{const id=m.propietario_cliente_id||m.cliente_id||m.propietario_nombre||m.cliente_nombre||'empresa';let r=owners.get(id);if(!r){r={id,name:m.propietario_nombre||m.cliente_nombre||(id==='empresa'?'Stock propio / sin propietario':'Cliente sin nombre'),stock:0,prepared:0,locations:new Set()};owners.set(id,r);}r.stock+=sign(m)*Number(m.cantidad||0);if(pending(m))r.prepared+=Number(m.cantidad||0);if(m.almacen_nombre)r.locations.add(m.almacen_nombre);});
    return [...owners.values()].map(r=>({...r,locations:[...r.locations].join(', ')||'Sin ubicación registrada'})).sort((a,b)=>b.stock-a.stock);
  },[movements,sign]);
  const needle=q.toLocaleLowerCase('es');
  const matches=m=>[m.cliente_nombre,m.propietario_nombre,m.cliente_movimiento_nombre,m.obra_referencia,m.num_albaran,m.pedido_ref].join(' ').toLocaleLowerCase('es').includes(needle)&&(!from||String(m.fecha).slice(0,10)>=from)&&(!to||String(m.fecha).slice(0,10)<=to);
  const ledger=movements.filter(matches).filter(m=>tab!=='regularizaciones'||m.tipo==='rectificativa_devolucion');
  const stocks=rows.filter(r=>r.name.toLocaleLowerCase('es').includes(needle));
  const list=tab==='stock'?stocks:ledger, pages=Math.max(1,Math.ceil(list.length/10)), current=Math.min(page,pages), visible=list.slice((current-1)*10,current*10);
  const prepared=movements.filter(pending), now=new Date(), today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
  const state=m=>pending(m)?<Badge tone="warning">Preparada · no descuenta stock</Badge>:<Badge tone={m.factura_id?'info':'success'}>{m.factura_id?'Facturada':'Registrada'}</Badge>;
  const actionButtons=m=><div className="warehouse-actions">
    {canEdit&&!m.factura_id&&(m.tipo!=='devolucion'||pending(m))&&<Button onClick={()=>edit(m)}>Editar</Button>}
    {canEdit&&pending(m)&&<Button onClick={()=>confirm(m)}>Confirmar salida</Button>}
    {['entrega','devolucion'].includes(m.tipo)&&m.num_albaran&&<Button onClick={()=>albaran(m)}>Albarán</Button>}
    {m.tipo==='devolucion'&&canEdit&&puedeVer('pedidos')&&<Button onClick={()=>setTransport(m)}>Transporte / DCD</Button>}
    {canEdit&&m.tipo==='devolucion'&&!pending(m)&&!m.factura_id&&<Button onClick={()=>rectify(m)}>Rectificar</Button>}
  </div>;
  const stockColumns=[{key:'name',label:'Propietario / cliente'},{key:'support',label:'Soporte',render:()=> 'Palets'},{key:'stock',label:'Saldo registrado'},{key:'prepared',label:'Preparados'},{key:'locations',label:'Almacén'},{key:'state',label:'Estado',render:r=><Badge tone={r.stock<0?'danger':r.prepared?'warning':'neutral'}>{r.stock<0?'Revisar saldo':r.prepared?'Salida pendiente':'Sin salidas preparadas'}</Badge>},{key:'actions',label:'Acciones',render:r=><Button onClick={()=>{setQ(r.id==='empresa'?'':r.name);setTab('movimientos');setPage(1)}}>Movimientos</Button>}];
  const moveColumns=[{key:'fecha',label:'Fecha',render:m=>String(m.fecha||'').slice(0,10)},{key:'tipo',label:'Movimiento',render:m=>movementLabels[m.tipo]||m.tipo},{key:'cliente_nombre',label:'Propietario'},{key:'cantidad',label:'Palets',render:m=><strong>{sign(m)>0?'+':sign(m)<0?'−':''}{Number(m.cantidad)||0}</strong>},{key:'obra_referencia',label:'Obra / referencia',render:m=>m.obra_referencia||m.pedido_ref||'—'},{key:'num_albaran',label:'Albarán'},{key:'state',label:'Estado',render:state},{key:'actions',label:'Acciones',render:actionButtons}];
  function csv(){const cols=tab==='stock'?['Cliente','Saldo registrado','Preparados','Almacén']:['Fecha','Tipo','Propietario','Cantidad','Efecto stock','Albarán','Referencia'];const data=tab==='stock'?stocks.map(r=>[r.name,r.stock,r.prepared,r.locations]):ledger.map(m=>[String(m.fecha||'').slice(0,10),movementLabels[m.tipo],m.cliente_nombre,m.cantidad,sign(m)*Number(m.cantidad||0),m.num_albaran,m.obra_referencia||m.pedido_ref]);const escape=v=>`"${String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')}"`;const url=URL.createObjectURL(new Blob(['\ufeff'+[cols,...data].map(r=>r.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`almacen-${tab}.csv`;a.click();URL.revokeObjectURL(url);}
  function report(){try{const isStock=tab==='stock';const head=isStock?['Cliente','Saldo','Preparados','Almacén']:['Fecha','Movimiento','Propietario','Palets','Efecto stock','Albarán'];const data=isStock?stocks.map(r=>[r.name,r.stock,r.prepared,r.locations]):ledger.map(m=>[String(m.fecha||'').slice(0,10),movementLabels[m.tipo],m.cliente_nombre,m.cantidad,sign(m)*Number(m.cantidad||0),m.num_albaran]);openWarehouseDocument(warehouseDocument(isStock?'Informe de stock de palets':'Informe de movimientos',empresa,`<p>Generado: ${esc(today)} · ${data.length} registros · Filtro: ${esc(q||'Todos')}${isStock?'':` · Desde ${esc(from||'inicio')} hasta ${esc(to||'hoy')}`}</p><p>Saldo según movimientos cargados. Las devoluciones preparadas reservan palets, pero no descuentan stock hasta confirmar la salida.</p><table><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`));}catch(e){notify(e.message,'warning')}}
  return <div className="warehouse-workspace"><header className="warehouse-heading"><div><h1>Gestión de almacén</h1><p>Consulta saldos, sigue cada movimiento y prepara las devoluciones con su documentación.</p></div><div className="warehouse-actions"><Button disabled={loading||!!error} onClick={report}>Informe de {tab==='stock'?'stock':'movimientos'}</Button>{canEdit&&<Button variant="primary" onClick={()=>create()}>+ Nuevo movimiento</Button>}</div></header>
    {error&&<div role="alert">{error} <Button onClick={reload}>Reintentar</Button></div>}
    <div className="warehouse-kpis"><KpiCard label="Stock registrado" value={stock} icon="truck" tone="success" detail="Palets · movimientos cargados"/><KpiCard label="Movimientos hoy" value={movements.filter(m=>String(m.fecha||'').slice(0,10)===today).length} icon="route" tone="info" detail="Entradas, salidas y rectificaciones"/><KpiCard label="Salidas preparadas" value={prepared.reduce((s,m)=>s+Number(m.cantidad||0),0)} icon="clock" tone="warning" detail={`${prepared.length} devoluciones sin confirmar`}/><KpiCard label="Clientes con saldo" value={rows.filter(r=>r.stock>0&&r.id!=='empresa').length} icon="clients" detail={`${alerts.length} alertas activas`}/></div>
    <div className="warehouse-module-links"><Button onClick={()=>setSection('')}>Stock y movimientos</Button><Button onClick={()=>openSection('stock')}>Saldos y liquidaciones</Button><Button onClick={()=>openSection('almacen_propio')}>Mercancía propia</Button><Button onClick={()=>openSection('almacen_cliente')}>Depósitos de clientes</Button><Button onClick={()=>openSection('historial')}>Historial detallado y facturación</Button></div>
    {section?<Card><h2>{({stock:"Saldos y liquidaciones",almacen_propio:"Mercancía propia",almacen_cliente:"Depósitos de clientes",historial:"Historial y facturación"})[section]}</h2>{details}</Card>:<div className="warehouse-grid"><Card className="warehouse-main"><Tabs label="Gestión de almacén" idPrefix="warehouse" value={tab} onChange={v=>{setTab(v);setPage(1)}} items={[{value:'stock',label:'Stock',icon:'truck'},{value:'movimientos',label:'Entradas / Salidas',icon:'route'},{value:'regularizaciones',label:'Rectificaciones',icon:'invoice'},{value:'alertas',label:`Alertas (${alerts.length})`,icon:'alert'}]}/><div role="tabpanel" id="warehouse-panel" aria-labelledby={`warehouse-${tab}`}>
    <div className="warehouse-toolbar"><SearchInput label="Buscar en almacén" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Buscar por cliente, obra o albarán…"/>{tab!=='stock'&&<><input aria-label="Desde" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/><input aria-label="Hasta" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></>}<Button disabled={loading||!!error} onClick={csv}>Exportar CSV</Button></div>
    <p className="warehouse-caption">{movements.length} movimientos cargados (máximo actual de la API: 1.000). Los saldos no representan un recuento físico conciliado.</p>
    {tab==='alertas'?<div>{alerts.length?alerts.map(a=><div key={a.alerta_key} className="warehouse-alert"><Icon name="alert"/><div><strong>{a.cliente_nombre||a.cliente||'Cliente'} · {a.palets} palets</strong><p>{a.obra_nombre||a.obra_referencia||a.obra||a.ref||''} · {a.dias} días</p></div><Button onClick={()=>setAlert(a.alerta_key,'leida')}>Marcar leída</Button></div>):<EmptyState title="Sin alertas activas"/>}</div>:<><DataTable loading={loading} rows={visible} columns={tab==='stock'?stockColumns:moveColumns} emptyTitle="No hay registros con estos filtros" renderMobile={r=>tab==='stock'?<MobileDataCard title={r.name} amount={`${r.stock} palets`} subtitle={r.locations}><span>{r.prepared} preparados</span><Button onClick={()=>{setQ(r.id==='empresa'?'':r.name);setTab('movimientos');setPage(1)}}>Movimientos</Button></MobileDataCard>:<MobileDataCard title={movementLabels[r.tipo]||r.tipo} amount={`${r.cantidad} palets`} subtitle={`${r.cliente_nombre||'Stock propio'} · ${String(r.fecha||'').slice(0,10)}`} actions={actionButtons(r)}>{state(r)}<span>{r.num_albaran||'Sin albarán'}</span></MobileDataCard>}/><footer className="warehouse-pagination"><span>{list.length} registros · Página {current} de {pages}</span><Button disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</Button><Button disabled={current===pages} onClick={()=>setPage(current+1)}>Siguiente</Button></footer></>}
    </div></Card><aside><Card><h2>Últimos movimientos</h2>{movements.slice(0,5).map(m=><button className="warehouse-recent" key={m.id} onClick={()=>{setTab('movimientos');setQ(m.num_albaran||'');setPage(1)}}><Icon name={sign(m)<0?'truck':'route'}/><span>{movementLabels[m.tipo]}<small>{m.cliente_nombre||'Stock propio'}</small></span><strong>{sign(m)>0?'+':sign(m)<0?'−':''}{m.cantidad}</strong></button>)}</Card><Card><h2>Devoluciones preparadas</h2><p>{prepared.length} pendientes de salida</p><p className="warehouse-caption">Prepara el albarán, vincula el transporte y confirma la salida cuando se realice.</p>{canEdit&&<Button onClick={()=>create('devolucion')}>Preparar devolución</Button>}<Button onClick={()=>{setTab('movimientos');setQ('');setPage(1)}}>Revisar movimientos</Button></Card></aside></div>}
    {transport&&<TransportDocuments movement={transport} onClose={()=>setTransport(null)} onSaved={reload} albaran={()=>albaran(transport)}/>}
  </div>;
}
