import {useEffect,useState} from 'react';
import {supplierInvoiceReview as api} from '../../services/api';
import {Button,Modal,Section} from '../../ui';
import {setRuntimeFocus} from '../../services/runtimeFocus';
import {useAuth} from '../../context/AuthContext';
import './supplierInvoiceReview.css';
import SupplierInvoicePaymentPanel from '../../components/SupplierInvoicePaymentPanel';
const blankLine=()=>({descripcion:'',referencia:'',fecha:'',origen:'',destino:'',matricula:'',base:'',impuestos:'',parcial:false});
const blank=()=>({numero:'',proveedor_cif:'',fecha:'',vencimiento:'',moneda:'EUR',base:'',impuestos:'',total:'',nota_revision:'',lineas:[blankLine()]});
export default function SupplierInvoiceReview({proveedor,onRegistered}){
 const {user,puedeVer,puedeEditar}=useAuth(),allowed=puedeVer('facturacion')&&['gerente','contable','administrativo'].includes(user.rol),editable=puedeEditar('facturacion');
 const [items,setItems]=useState({data:[],total:0}),[page,setPage]=useState(1),[item,setItem]=useState(null),[data,setData]=useState(blank),[matches,setMatches]=useState([]),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tolerance,setTolerance]=useState({tolerancia_eur:0,tolerancia_pct:0});
 async function load(){setItems(await api(`?proveedor_id=${encodeURIComponent(proveedor.id)}&page=${page}`));}
 useEffect(()=>{if(!allowed)return;let active=true;Promise.all([api(`?proveedor_id=${encodeURIComponent(proveedor.id)}&page=${page}`),api('/config')]).then(([rows,cfg])=>{if(active){setItems(rows);setTolerance(cfg);}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[allowed,proveedor.id,page]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function open(row){setItem(row);setData({...blank(),proveedor_cif:proveedor.cif||'',...row.datos,lineas:row.datos?.lineas?.length?row.datos.lineas:[blankLine()]});setMatches(row.conciliacion?.lineas||row.lineas?.map(l=>l.datos)||[]);setReviewed(false);}
 function update(key,value){setData(d=>({...d,[key]:value}));setReviewed(false);setMatches([]);}
 const field=(key,label,type='text')=><label key={key}>{label}<input type={type} step={type==='number'?'0.01':undefined} value={data[key]??''} disabled={busy||!editable||item?.estado==='revisada'} onChange={e=>update(key,e.target.value)}/></label>;
 async function original(){const f=await api(`/${item.id}/original`),url=URL.createObjectURL(new Blob([Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0))],{type:f.mime}));const a=document.createElement('a');a.href=url;a.download=f.nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function upload(file){if(!file)return;if(file.size>5*1024*1024)throw Error('Máximo 5 MB por factura.');const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const row=await api('',{method:'POST',body:{proveedor_id:proveedor.id,nombre:file.name,mime:file.type||(/\.xml$/i.test(file.name)?'application/xml':''),base64:content}});open(row);await load();}
 async function extract(ia){const row=await api(`/${item.id}/extraer`,{method:'POST',body:{ia}});setItem(row);const candidate=row.candidatos;if(candidate.lineas)setData({...blank(),...data,...candidate,lineas:candidate.lineas.length?candidate.lineas:[blankLine()]});setReviewed(false);setMatches([]);}
 if(!allowed)return null;
 return <Section title="Conciliación de facturas recibidas"><div className="supplier-review"><p>PDF, XML Facturae o imagen. El original se conserva; la revisión registra la factura sin efectuar pagos ni cambiar el precio acordado del viaje.</p>{error&&!item&&<p role="alert">{error}</p>}{editable&&<label>Subir factura (máximo 5 MB)<input type="file" accept=".pdf,.xml,.jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>{const file=e.target.files[0];e.target.value='';run(()=>upload(file));}}/></label>}
 <details><summary>Tolerancias de conciliación de la empresa</summary><div className="supplier-review-grid">{[['tolerancia_eur','Diferencia admitida (€ netos)'],['tolerancia_pct','Diferencia admitida (%)']].map(([k,label])=><label key={k}>{label}<input type="number" min="0" step="0.01" value={tolerance[k]} disabled={user.rol!=='gerente'||busy} onChange={e=>setTolerance({...tolerance,[k]:e.target.value})}/></label>)}</div><p>Se admite el mayor de ambos umbrales. Las diferencias siempre siguen visibles.</p>{user.rol==='gerente'&&editable&&<Button disabled={busy} onClick={()=>run(()=>api('/config',{method:'PUT',body:tolerance}))}>Guardar tolerancias</Button>}</details>
 <ul>{items.data.map(row=><li key={row.id}><Button onClick={()=>run(async()=>open(await api('/'+row.id)))} disabled={busy}>{row.numero||row.nombre}</Button> · {row.estado==='revisada'?'Revisada':'Pendiente de revisión'}</li>)}</ul>{!items.total&&<p>No hay documentos en revisión para este proveedor.</p>}<div className="supplier-review-actions"><Button disabled={busy||page===1} onClick={()=>setPage(page-1)}>Anterior</Button><span>Página {page} · {items.total} documentos</span><Button disabled={busy||page*25>=items.total} onClick={()=>setPage(page+1)}>Siguiente</Button></div>
 {item&&<Modal title={`Factura de proveedor · ${item.numero||item.nombre}`} onClose={()=>!busy&&setItem(null)} width={1100}><div className="supplier-review">{error&&<p role="alert">{error}</p>}<div className="supplier-review-actions"><Button disabled={busy} onClick={()=>run(original)}>Descargar original</Button>{item.estado==='revision'&&editable&&<><Button disabled={busy} onClick={()=>run(()=>extract(false))}>Leer texto / XML</Button>{puedeVer('ia')&&<Button disabled={busy} onClick={()=>run(()=>extract(true))}>Extraer con IA</Button>}</>}</div>{item.extraccion?.advertencia&&<p>{item.extraccion.advertencia}</p>}{item.extraccion?.texto&&<details><summary>Texto extraído</summary><pre style={{whiteSpace:'pre-wrap',maxHeight:220,overflow:'auto'}}>{item.extraccion.texto}</pre></details>}
 <div className="supplier-review-grid">{field('numero','Número de factura')}{field('proveedor_cif','NIF/CIF emisor')}{field('fecha','Fecha factura','date')}{field('vencimiento','Vencimiento','date')}{field('moneda','Moneda (registro disponible en EUR)')}{field('base','Base neta (€)','number')}{field('impuestos','Cuota neta de impuestos y retenciones (€)','number')}{field('total','Total documento (€)','number')}</div>
 <h3>Servicios y desglose</h3><p>Importes de cada línea, con impuestos separados. Usa la referencia del pedido o fecha, ruta y matrícula; varias líneas del mismo servicio se concilian juntas.</p>
 {data.lineas.map((line,index)=><fieldset key={index}><legend>Línea {index+1} · {matches[index]?.conciliacion?.estado?.replaceAll('_',' ')||'Sin conciliar'}</legend><div className="supplier-review-grid">{[['descripcion','Descripción'],['referencia','Referencia pedido/viaje'],['fecha','Fecha servicio','date'],['origen','Origen'],['destino','Destino'],['matricula','Matrícula'],['base','Base de la línea (€)','number'],['impuestos','Impuestos de la línea (€)','number']].map(([key,label,type='text'])=><label key={key}>{label}<input type={type} step={type==='number'?'0.01':undefined} value={line[key]??''} disabled={busy||!editable||item.estado==='revisada'} onChange={e=>update('lineas',data.lineas.map((l,i)=>i===index?{...l,[key]:e.target.value,pedido_id:null}:l))}/></label>)}</div><label><input type="checkbox" checked={line.parcial===true} disabled={busy||item.estado==='revisada'||!editable} onChange={e=>update('lineas',data.lineas.map((l,i)=>i===index?{...l,parcial:e.target.checked}:l))}/> Facturación parcial de este servicio</label>{matches[index]?.conciliacion&&<p>Precio acordado neto: {matches[index].conciliacion.precio_acordado??'Sin dato'} € · Diferencia: {matches[index].conciliacion.diferencia??'No calculable'} €. {matches[index].conciliacion.incidencias.join(' · ')}</p>}{matches[index]?.conciliacion?.documentacion&&<p>Documentación de entrega: {matches[index].conciliacion.documentacion.estado==='disponible_para_revision'?'Disponible para revisión':matches[index].conciliacion.documentacion.estado==='pendiente'?'Pendiente':'Sin servicio vinculado'}. {matches[index].conciliacion.documentacion.documentos.map(d=>d.nombre).join(' · ')} {puedeVer('pedidos')&&matches[index].pedido_id&&<Button onClick={()=>{setRuntimeFocus('tms_pedidos_focus',{pedido_id:matches[index].pedido_id,source:'supplier_invoice_review'});window.dispatchEvent(new CustomEvent('tms:navegar',{detail:'pedidos'}));}}>Abrir pedido y documentos</Button>}</p>}{matches[index]?.conciliacion?.candidatos?.length>1&&<label>Selecciona el servicio exacto<select value={line.pedido_id||''} onChange={e=>update('lineas',data.lineas.map((l,i)=>i===index?{...l,pedido_id:e.target.value}:l))}><option value="">Pendiente de elegir</option>{matches[index].conciliacion.candidatos.map(p=><option key={p.id} value={p.id}>{p.numero} · {p.origen} → {p.destino}</option>)}</select></label>}{editable&&item.estado==='revision'&&<Button disabled={busy} onClick={()=>update('lineas',data.lineas.filter((_,i)=>i!==index))}>Quitar línea {index+1}</Button>}</fieldset>)}
 {editable&&item.estado==='revision'&&<><Button disabled={busy||data.lineas.length>=200} onClick={()=>update('lineas',[...data.lineas,blankLine()])}>Añadir línea</Button><label>Justificación de diferencias / revisión<textarea value={data.nota_revision} onChange={e=>update('nota_revision',e.target.value)}/></label><div className="supplier-review-actions"><Button disabled={busy} onClick={()=>run(async()=>open(await api('/'+item.id,{method:'PUT',body:{version:item.version,datos:data}})))}>Guardar y conciliar</Button><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> He contrastado los importes, el emisor y los servicios con el documento original</label><Button variant="primary" disabled={busy||!reviewed} onClick={()=>run(async()=>{open(await api('/'+item.id+'/revisar',{method:'POST',body:{version:item.version,datos:data,revisado:reviewed}}));await load();onRegistered?.();})}>Registrar factura revisada</Button></div></>}{item.estado==='revisada'&&<><p>Revisión conservada desde {new Date(item.revisada_at).toLocaleString('es-ES')}. Revisar la factura no realiza su pago.</p><SupplierInvoicePaymentPanel invoiceId={item.id} editable={editable} onRegistered={onRegistered}/></>}</div></Modal>}
 </div></Section>;
}
