-- Campos de procedencia sin modificar los registros existentes.
ALTER TABLE choferes ADD COLUMN IF NOT EXISTS apellidos VARCHAR(150);
ALTER TABLE choferes ADD COLUMN IF NOT EXISTS movil_empresa VARCHAR(60);
ALTER TABLE choferes ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE;
ALTER TABLE choferes ADD COLUMN IF NOT EXISTS fecha_alta DATE;
ALTER TABLE choferes ADD COLUMN IF NOT EXISTS estado VARCHAR(40) NOT NULL DEFAULT 'disponible';
ALTER TABLE choferes ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE choferes ADD COLUMN IF NOT EXISTS import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS provincia VARCHAR(120);
ALTER TABLE vehiculos ADD COLUMN IF NOT EXISTS import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL;
ALTER TABLE vehiculos ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE colaboradores ADD COLUMN IF NOT EXISTS import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL;
ALTER TABLE colaboradores ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE colaboradores ADD COLUMN IF NOT EXISTS calle VARCHAR(200);
ALTER TABLE colaboradores ADD COLUMN IF NOT EXISTS ciudad VARCHAR(100);
ALTER TABLE colaboradores ADD COLUMN IF NOT EXISTS provincia VARCHAR(100);
ALTER TABLE colaboradores ADD COLUMN IF NOT EXISTS codigo_postal VARCHAR(20);
ALTER TABLE colaboradores ADD COLUMN IF NOT EXISTS pais VARCHAR(80);
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS empresa_id UUID REFERENCES empresas(id) ON DELETE CASCADE;
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS cliente_id UUID REFERENCES clientes(id) ON DELETE SET NULL;
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS tarifa_tipo VARCHAR(30) DEFAULT 'viaje';
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS precio_base NUMERIC(12,2);
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS notas TEXT;
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS import_batch_id UUID REFERENCES import_batches(id) ON DELETE SET NULL;
ALTER TABLE ruta_precios_cliente ADD COLUMN IF NOT EXISTS tarifa_tipo VARCHAR(30) DEFAULT 'viaje';
CREATE INDEX IF NOT EXISTS idx_choferes_import_batch ON choferes(import_batch_id) WHERE import_batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_clientes_import_batch ON clientes(import_batch_id) WHERE import_batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vehiculos_import_batch ON vehiculos(import_batch_id) WHERE import_batch_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_colaboradores_import_batch ON colaboradores(import_batch_id) WHERE import_batch_id IS NOT NULL;
