import { useEffect, useRef, useState } from 'react';
import { cargarImagen, leerArchivoComoDataUrl, detectarRectanguloPapel, recortarCanvas, limpiarCanvasComoEscaner } from './documentScan';
import './driver-expenses.css';

export default function DocumentScanner({onCapture,onClose}){
 const video=useRef(null),stream=useRef(null),source=useRef(null),drag=useRef(null),frame=useRef(null);
 const [photo,setPhoto]=useState(''),[rect,setRect]=useState({x:5,y:5,w:90,h:90}),[error,setError]=useState(''),[ready,setReady]=useState(false),[detected,setDetected]=useState(false);
 const stop=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};
 useEffect(()=>{
  let alive=true;
  if(photo)return;
  setReady(false);
  (async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Este navegador no permite la cámara en directo. Usa Tomar o elegir foto.');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920}},audio:false});if(!alive){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;video.current.srcObject=s;await video.current.play();if(alive)setReady(true);}catch(e){if(alive)setError(e.message||'No se pudo abrir la cámara. Usa Tomar o elegir foto.');}})();
  const timer=setInterval(()=>{if(!video.current?.videoWidth)return;const c=document.createElement('canvas');c.width=320;c.height=Math.round(320*video.current.videoHeight/video.current.videoWidth);c.getContext('2d').drawImage(video.current,0,0,c.width,c.height);const r=detectarRectanguloPapel(c);setDetected(r.detected);setRect({x:r.x/c.width*100,y:r.y/c.height*100,w:r.w/c.width*100,h:r.h/c.height*100});},600);
  return()=>{alive=false;clearInterval(timer);stop();};
 },[photo]);
 useEffect(()=>{const back=e=>{e.preventDefault();onClose();};window.addEventListener('tms:driver-back',back);return()=>window.removeEventListener('tms:driver-back',back);},[onClose]);
 function review(c){const scale=Math.min(1,1800/Math.max(c.width,c.height));const resized=document.createElement('canvas');resized.width=Math.round(c.width*scale);resized.height=Math.round(c.height*scale);resized.getContext('2d').drawImage(c,0,0,resized.width,resized.height);source.current=resized;const r=detectarRectanguloPapel(resized);setRect({x:r.x/resized.width*100,y:r.y/resized.height*100,w:r.w/resized.width*100,h:r.h/resized.height*100});setDetected(r.detected);stop();setPhoto(resized.toDataURL('image/jpeg',.9));setError('');}
 function capture(){const v=video.current;if(!v?.videoWidth)return;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);review(c);}
 async function choose(e){const f=e.target.files?.[0];if(!f)return;try{const img=await cargarImagen(await leerArchivoComoDataUrl(f));const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d').drawImage(img,0,0);review(c);}catch(e){setError(e.message);}finally{e.target.value='';}}
 function move(e){if(!drag.current||!photo)return;const b=frame.current.getBoundingClientRect();const x=Math.max(0,Math.min(100,(e.clientX-b.left)/b.width*100)),y=Math.max(0,Math.min(100,(e.clientY-b.top)/b.height*100));setRect(r=>{const right=r.x+r.w,bottom=r.y+r.h;const left=drag.current.includes('l')?Math.min(x,right-5):r.x,top=drag.current.includes('t')?Math.min(y,bottom-5):r.y;return{x:left,y:top,w:(drag.current.includes('r')?Math.max(x,left+5):right)-left,h:(drag.current.includes('b')?Math.max(y,top+5):bottom)-top};});}
 function accept(){const c=source.current;if(!c)return;const crop={x:c.width*rect.x/100,y:c.height*rect.y/100,w:c.width*rect.w/100,h:c.height*rect.h/100};const scan=limpiarCanvasComoEscaner(recortarCanvas(c,crop));let q=.9,result=scan.toDataURL('image/jpeg',q);while(result.length>3900000&&q>.45){q-=.1;result=scan.toDataURL('image/jpeg',q);}if(result.length>4000000){setError('La imagen es demasiado grande. Acerca el documento y repite la foto.');return;}onCapture({preview:result,base64:result.split(',')[1],mime:'image/jpeg',sizeKb:Math.ceil(result.length*.75/1024),scan_detected:detected,scan_crop:crop,scan_quality:q});}
 return <div className="document-scanner"><section role="dialog" aria-modal="true" aria-label="Escanear documento" className="document-scanner-dialog"><h2>{photo?'Revisar recorte':'Escanear documento'}</h2><p>{photo?'Arrastra las esquinas para conservar solo el documento.':detected?'Documento detectado. Mantén el teléfono estable y captura.':'Coloca el documento sobre un fondo contrastado, con las esquinas visibles.'}</p>{error&&<p role="alert">{error}</p>}
 <div className="document-scanner-frame" ref={frame}>{photo?<img src={photo} alt="Documento para recortar"/>:<video ref={video} autoPlay muted playsInline/>}<svg viewBox="0 0 100 100" preserveAspectRatio="none" onPointerMove={move} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><rect x={rect.x} y={rect.y} width={rect.w} height={rect.h}/>{photo&&[['tl',rect.x,rect.y],['tr',rect.x+rect.w,rect.y],['bl',rect.x,rect.y+rect.h],['br',rect.x+rect.w,rect.y+rect.h]].map(([key,x,y])=><circle key={key} cx={x} cy={y} r="3" onPointerDown={e=>{drag.current=key;e.currentTarget.setPointerCapture(e.pointerId);}}/>)}</svg></div>
 <footer><button onClick={onClose}>Cancelar</button>{photo?<><button onClick={()=>{source.current=null;setPhoto('');}}>Repetir</button><button onClick={()=>setRect({x:0,y:0,w:100,h:100})}>Imagen completa</button><button onClick={accept}>Usar documento recortado</button></>:<button disabled={!ready} onClick={capture}>Capturar documento</button>}<label>Tomar o elegir foto<input type="file" accept="image/*" capture="environment" onChange={choose}/></label></footer>
 </section></div>;
}
