import { useTheme } from "../../context/ThemeContext";
import darkLogo from "../../assets/brand/transgest_logo_dark.svg";
import whiteLogo from "../../assets/brand/transgest_logo_white.svg";
import "./portal.css";

const paths={inicio:"m3 10 9-7 9 7 M5 9v12h5v-7h4v7h5V9",seguimiento:"M3 6h11v11H3z M14 10h4l3 4v3h-7 M7 17a2 2 0 1 0 0 .01 M18 17a2 2 0 1 0 0 .01",nuevo:"M12 5v14 M5 12h14",albaranes:"M3 6h7l2 3h9v11H3z",facturas:"M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h6",cuenta:"M18 6a7 7 0 1 0 0 12 M4 10h11 M4 14h11",solicitudes:"M4 5h16v16H4z M8 3v4 M16 3v4 M8 11h8 M8 15h5",ayuda:"M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3 M12 17v.1 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0",avisos:"M5 16h14l-2-3V8a5 5 0 0 0-10 0v5z M10 20h4"};
export function PortalIcon({name}){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.facturas}/></svg>;}
const titles={inicio:"Inicio",seguimiento:"Mis envíos",nuevo:"Solicitar servicio",albaranes:"Documentos",facturas:"Facturación",cuenta:"Estado de cuenta",solicitudes:"Mis solicitudes",ayuda:"Ayuda"};
export function PortalHeader({empresa,user,tab,onNavigate,onLogout,unread}){
 const {isDark,toggle}=useTheme()||{};
 return <header className="portal-header"><div className="portal-brand">{empresa.logo_url ? <img src={empresa.logo_url} alt={empresa.razon_social||"Empresa transportista"}/> : <img src={isDark?whiteLogo:darkLogo} alt="TransGest"/>}{empresa.razon_social && <strong>{empresa.razon_social}</strong>}</div><nav aria-label="Navegación del portal">{["inicio","seguimiento","nuevo","albaranes","facturas","ayuda"].map(id=><button key={id} aria-current={tab===id || (id==="facturas"&&tab==="cuenta") ? "page":undefined} onClick={()=>onNavigate(id)}><PortalIcon name={id}/>{titles[id]}</button>)}</nav><div className="portal-account"><button className="portal-bell" aria-label="Ver novedades" onClick={()=>{onNavigate("inicio");requestAnimationFrame(()=>document.getElementById("portal-news")?.scrollIntoView({block:"center"}));}}><PortalIcon name="avisos"/>{unread>0&&<span>{unread}</span>}</button><details><summary><span className="portal-avatar">{(user?.nombre||"Cliente").split(/\s+/).slice(0,2).map(s=>s[0]).join("").toUpperCase()}</span><span>{user?.nombre||user?.username}<small>Cliente</small></span><span aria-hidden="true">⌄</span></summary><div className="portal-account-menu"><button onClick={toggle}>{isDark?"Tema claro":"Tema oscuro"}</button><button onClick={()=>onNavigate("solicitudes")}>Mis solicitudes</button><button onClick={onLogout}>Cerrar sesión</button></div></details></div></header>;
}
export function PortalOverview({empresa,user,tab,resumen,loading,onNavigate,provider}){
 const number=n=>Number(n||0).toLocaleString("es-ES"),money=n=>Number(n||0).toLocaleString("es-ES",{style:"currency",currency:"EUR"});
 return <><div className="portal-hero"><div><h1>{tab==="inicio"?`¡Hola, ${(user?.nombre||user?.username||"").split(" ")[0]}!`:titles[tab]||"Portal del cliente"}</h1><p>{tab==="inicio"?`Consulta tus envíos y gestiona tus servicios${empresa.razon_social?` con ${empresa.razon_social}`:""}.`:"Toda la información de tus servicios, en un solo lugar."}</p></div>{tab!=="nuevo"&&tab!=="inicio"&&<button className="portal-primary" onClick={()=>onNavigate("nuevo")}><PortalIcon name="nuevo"/>Solicitar servicio</button>}</div>
 {tab==="inicio"&&<><div className="portal-kpis">{[
 ["Viajes activos",number(resumen.pedidos?.activos),"seguimiento","Estado actualizado de tus envíos"],
 [provider?"Peticiones abiertas":"Solicitudes abiertas",number(resumen.solicitudes?.abiertas),"solicitudes","Pendientes de planificación"],
 ["Facturado",money(resumen.facturas?.total_facturado),"facturas","Total de facturas disponibles"],
 ["Pendiente de pago",money(resumen.facturas?.total_pendiente),"cuenta","Consulta tu estado de cuenta"],
 ["Viajes con albarán",number(resumen.documentos?.con_albaran),"albaranes",`De ${number(resumen.documentos?.viajes)} viajes`],
 ].map(([label,value,id,sub])=><button key={id} onClick={()=>onNavigate(id)}><span className={`portal-icon-tile portal-tone-${id}`}><PortalIcon name={id}/></span><span><span>{label}</span><strong>{loading?"—":value}</strong><small>{sub}</small></span><span aria-hidden="true">›</span></button>)}</div><div className="portal-shortcuts">{[["nuevo","Nuevo servicio","Solicita un transporte en pocos pasos"],["cuenta","Estado de cuenta","Consulta saldos y facturas"],["albaranes","Documentos","Albaranes y documentos de tus envíos"]].map(([id,label,sub])=><button key={id} onClick={()=>onNavigate(id)}><PortalIcon name={id}/><span><strong>{label}</strong><small>{sub}</small></span><span aria-hidden="true">→</span></button>)}</div></>}
 </>;
}
export function PortalTracking({pedidos,selected,onSelect,estado,onEstado,estados,docs,loadingDocs,onDocuments,onDownload,children}){
 const date=value=>value?new Date(value).toLocaleDateString("es-ES"):"Pendiente";
 return <div className="portal-tracking"><section className="portal-shipments portal-panel"><h2>Mis envíos</h2><label className="portal-status-filter">Estado del envío<select value={estado} onChange={e=>onEstado(e.target.value)}><option value="">Todos los estados</option>{Object.entries(estados).map(([key,val])=><option key={key} value={key}>{val.l}</option>)}</select></label><div className="portal-shipment-list">{pedidos.length ? pedidos.map(p=><button key={p.id} aria-pressed={selected?.id===p.id} onClick={()=>onSelect(p.id)}><span><strong>{p.numero||"Envío"}</strong><small>{p.origen||"Pendiente"} → {p.destino||"Pendiente"}</small></span><span className={`portal-status portal-status-${p.estado}`}>{estados[p.estado]?.l||p.estado||"Pendiente"}</span></button>):<p className="portal-empty">No hay envíos con estos filtros.</p>}</div></section><section className="portal-shipment-detail" aria-label="Seguimiento del envío">{children}</section><aside className="portal-shipment-aside">{selected&&<><section className="portal-panel"><h2>Detalles del envío</h2><dl>{[["Número",selected.numero],["Origen",selected.origen],["Destino",selected.destino],["Fecha de carga",date(selected.fecha_carga)],["Entrega prevista",date(selected.fecha_descarga||selected.fecha_entrega)],["Mercancía",selected.mercancia],["Peso",selected.peso_kg?`${Number(selected.peso_kg).toLocaleString("es-ES")} kg`:null],["Bultos / palets",selected.bultos]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??"No informado"}</dd></div>)}</dl></section><section className="portal-panel"><h2>Documentos del envío</h2><button className="portal-secondary" disabled={loadingDocs===selected.id} onClick={()=>onDocuments(selected.id)}><PortalIcon name="albaranes"/>{loadingDocs===selected.id?"Cargando…":"Consultar documentos"}</button>{Array.isArray(docs[selected.id])&&<div className="portal-documents">{docs[selected.id].length?docs[selected.id].map(d=><button key={d.id} onClick={()=>onDownload(d)}><PortalIcon name="facturas"/><span>{d.nombre||"Albarán"}</span><span>↓</span></button>):<p className="portal-empty">No hay documentos adjuntos disponibles.</p>}</div>}</section></>}</aside></div>;
}
export function PortalHelp({empresa}){return <section className="portal-panel portal-help"><span className="portal-icon-tile"><PortalIcon name="ayuda"/></span><h2>Estamos para ayudarte</h2><p>Contacta con tu empresa de transporte para resolver dudas sobre tus envíos, solicitudes o facturas.</p><div>{empresa.telefono&&<a href={`tel:${empresa.telefono.replace(/[^\d+]/g,"")}`}>{empresa.telefono}</a>}{empresa.email&&<a href={`mailto:${empresa.email}`}>{empresa.email}</a>}{!empresa.telefono&&!empresa.email&&<p>Tu empresa de transporte todavía no ha configurado los datos de contacto.</p>}</div></section>;}
