const express=require('express'),db=require('../services/db'),s=require('../services/invoiceOperationalWorkflow');
const {GERENTE_O_CONTABLE,SOLO_GERENTE,requireModulePermission}=require('../middleware/auth');
const router=express.Router(),uuid=/^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i;
router.use(requireModulePermission('facturacion'),GERENTE_O_CONTABLE,(req,res,next)=>{res.set('Cache-Control','private, no-store');next();});
router.get('/',async(req,res)=>{const page=Number(req.query.page||1);if(!Number.isSafeInteger(page)||page<1||page>1000000||req.query.cliente_id&&!uuid.test(req.query.cliente_id))throw s.fail('Filtro inválido');res.json(await s.list(db,req.empresaId||req.user.empresa_id,{page,cliente_id:req.query.cliente_id}));});
router.get('/reglas/:scope',async(req,res)=>{const scope=req.params.scope;if(scope!=='empresa'&&!uuid.test(scope))throw s.fail('Ámbito inválido');const rows=(await db.query("SELECT reglas,updated_at FROM invoice_operational_policies WHERE empresa_id=$1 AND scope_key IN ($2,'empresa') ORDER BY (scope_key=$2) DESC LIMIT 1",[req.empresaId||req.user.empresa_id,scope])).rows;res.json({reglas:s.policy(rows[0]?.reglas),personalizada:!!rows[0],updated_at:rows[0]?.updated_at});});
router.put('/reglas/:scope',SOLO_GERENTE,async(req,res)=>{const c=req.empresaId||req.user.empresa_id,scope=req.params.scope;if(scope!=='empresa'&&!uuid.test(scope))throw s.fail('Ámbito inválido');if(!['departure','delivery'].includes(req.body.hito)||['exigir_pod','exigir_deca','bloquear_incidencia'].some(k=>typeof req.body[k]!=='boolean'))throw s.fail('Reglas inválidas');const rules=s.policy(req.body);await db.transaction(async tx=>{if(scope!=='empresa'&&!(await tx.query('SELECT id FROM clientes WHERE empresa_id=$1 AND id=$2',[c,scope])).rows.length)throw s.fail('Cliente no encontrado',404);await tx.query('INSERT INTO invoice_operational_policies(empresa_id,scope_key,reglas,updated_by) VALUES($1,$2,$3,$4) ON CONFLICT(empresa_id,scope_key) DO UPDATE SET reglas=$3,updated_by=$4,updated_at=now()',[c,scope,JSON.stringify(rules),req.user.id]);await tx.query("INSERT INTO invoice_operational_events(empresa_id,usuario_id,evento,datos) VALUES($1,$2,'reglas',$3)",[c,req.user.id,JSON.stringify({scope,reglas:rules})]);});res.json({reglas:rules});});
router.post('/:id/revisar',async(req,res)=>{if(!uuid.test(req.params.id)||req.body.confirmado!==true)throw s.fail('Confirma que has revisado tarifa, suplementos, incidencia y documentos');res.json(await db.transaction(tx=>s.review(tx,req.empresaId||req.user.empresa_id,req.user.id,req.params.id,req.body.huella)));});
module.exports=router;
