const router=require('express').Router(),db=require('../services/db'),s=require('../services/supplierInvoiceReview'),{fail}=require('../services/plannerInventory');
const {requireModulePermission,requireRole,requirePlanFeature}=require('../middleware/auth');
router.use(requireRole('gerente','contable','administrativo'),requireModulePermission('facturacion'));
router.use((req,res,next)=>{res.set('Cache-Control','private, no-store');next();});
const wrap=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){if(e.status)return res.status(e.status).json({error:e.message});next(e);}};
const payments=require('../services/supplierInvoicePayments');
router.get('/:id/pagos',wrap(async(req,res)=>{await payments.ensure(db);res.json(await payments.read(db,req.empresaId,req.params.id));}));
router.post('/:id/pagos',wrap(async(req,res)=>res.status(201).json(await payments.record(db,req.empresaId,req.params.id,req.user.id,req.body))));
router.get('/proveedores',wrap(async(req,res)=>res.json((await db.query("SELECT id,nombre,cif FROM colaboradores WHERE empresa_id=$1 AND (nombre ILIKE $2 OR cif ILIKE $2) ORDER BY nombre,id LIMIT 100",[req.empresaId,'%'+String(req.query.q||'').slice(0,120)+'%'])).rows)));
router.get('/config',wrap(async(req,res)=>res.json((await db.query('SELECT tolerancia_eur,tolerancia_pct FROM factura_proveedor_config WHERE empresa_id=$1',[req.empresaId])).rows[0]||{tolerancia_eur:0,tolerancia_pct:0})));
router.put('/config',requireRole('gerente'),wrap(async(req,res)=>{const eur=s.amount(req.body.tolerancia_eur),pct=s.amount(req.body.tolerancia_pct);if(eur===null||eur<0||pct===null||pct<0||pct>100)throw fail('Tolerancias no válidas.');await db.query('INSERT INTO factura_proveedor_config(empresa_id,tolerancia_eur,tolerancia_pct,updated_by) VALUES($1,$2,$3,$4) ON CONFLICT(empresa_id) DO UPDATE SET tolerancia_eur=$2,tolerancia_pct=$3,updated_by=$4,updated_at=now()',[req.empresaId,eur,pct,req.user.id]);res.json({ok:true});}));
router.get('/',wrap(async(req,res)=>{const page=Math.max(1,Math.min(100000,Number.parseInt(req.query.page)||1)),params=[req.empresaId,String(req.query.proveedor_id||'')];const count=await db.query("SELECT count(*)::int n FROM facturas_proveedor WHERE empresa_id=$1 AND proveedor_id::text=$2",params);const rows=await db.query('SELECT id,nombre,numero,estado,created_at,datos->>\'total\' total FROM facturas_proveedor WHERE empresa_id=$1 AND proveedor_id::text=$2 ORDER BY created_at DESC,id LIMIT 25 OFFSET $3',[...params,(page-1)*25]);res.json({data:rows.rows,page,total:count.rows[0].n,limit:25});}));
router.post('/',wrap(async(req,res)=>res.status(201).json(await s.receive(db,req.empresaId,req.user.id,req.body.proveedor_id,req.body))));
router.get('/:id',wrap(async(req,res)=>{const row=await s.get(db,req.empresaId,req.params.id);res.json({...row,lineas:(await db.query('SELECT * FROM factura_proveedor_lineas WHERE factura_id=$1 AND empresa_id=$2 ORDER BY posicion',[row.id,req.empresaId])).rows,eventos:(await db.query('SELECT tipo,actor_id,created_at FROM factura_proveedor_eventos WHERE factura_id=$1 AND empresa_id=$2 ORDER BY created_at DESC LIMIT 100',[row.id,req.empresaId])).rows});}));
router.get('/:id/original',wrap(async(req,res)=>{const row=await s.get(db,req.empresaId,req.params.id,{original:true});if(require('../services/transportDocumentVersions').hash(Buffer.from(row.original))!==row.sha256)throw fail('Fallo de integridad.',500);res.json({nombre:row.nombre,mime:row.mime,base64:Buffer.from(row.original).toString('base64'),sha256:row.sha256});}));
const extract=async(req,res)=>{
 const row=await s.get(db,req.empresaId,req.params.id,{original:true});if(row.estado!=='revision')throw fail('La factura ya está revisada.',409);
 let text='';try{text=await s.textOf(row);}catch(e){if(!req.body.ia||e.status!==422)throw e;}
 const data=req.body.ia?await require('../services/supplierInvoiceExtraction').extract(req.empresaId,row,text):row.mime.includes('xml')?s.parseXml(text):{metodo:'texto',texto:text.slice(0,90000),advertencia:text?'Completa el desglose revisando el texto y el original.':'Sin texto extraíble. Completa manualmente o utiliza IA visual.'};
 await db.transaction(async tx=>{const current=await s.get(tx,req.empresaId,row.id,{lock:true});if(current.version!==row.version||current.estado!=='revision')throw fail('La revisión cambió durante el análisis; vuelve a abrirla.',409);await tx.query('UPDATE facturas_proveedor SET extraccion=$3,version=version+1 WHERE id=$1 AND empresa_id=$2',[row.id,req.empresaId,JSON.stringify(data)]);await s.event(tx,req.empresaId,row.id,req.user.id,'extraida',{metodo:data.metodo});});res.json({...await s.get(db,req.empresaId,row.id),candidatos:data});
};
router.post('/:id/extraer',(req,res,next)=>req.body.ia?requirePlanFeature('ai')(req,res,()=>requireModulePermission('ia')(req,res,next)):next(),wrap(extract));
router.put('/:id',wrap(async(req,res)=>res.json(await s.save(db,req.empresaId,req.params.id,req.user.id,req.body))));
router.post('/:id/revisar',wrap(async(req,res)=>res.json(await s.save(db,req.empresaId,req.params.id,req.user.id,req.body,true))));
module.exports=router;
