import React,{useEffect,useState} from 'react';
import {getBiGroups,getGroupBi} from '../../services/api';
import {Button,Card} from '../../ui';
const money=n=>n==null?'No calculable':new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n);
export default function BiGroupPanel({periodo}){
 const [open,setOpen]=useState(false),[groups,setGroups]=useState([]),[loadingGroups,setLoadingGroups]=useState(false),[group,setGroup]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const range=JSON.stringify(periodo);
 useEffect(()=>{setResult(null);},[range,group]);
 useEffect(()=>{let active=true;if(open){setLoadingGroups(true);getBiGroups().then(r=>{if(active){setGroups(r.groups);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoadingGroups(false);});}return()=>{active=false;};},[open]);
 useEffect(()=>{if(!busy)return;let active=true;setError('');getGroupBi({grupo_id:group,...JSON.parse(range)}).then(r=>{if(active)setResult(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[busy,range,group]);
 return <Card as="section"><Button onClick={()=>setOpen(v=>!v)} aria-expanded={open}>Análisis de grupo empresarial</Button>{open&&<><p>Se aplica el periodo de arriba, a todas las sociedades autorizadas del grupo. Los filtros de cliente, ruta y vehículo pertenecen a una sola empresa.</p><label>Grupo<select value={group} onChange={e=>{setBusy(false);setGroup(e.target.value);}}><option value="">Seleccionar</option>{groups.map(g=><option key={g.id} value={g.id}>{g.nombre}</option>)}</select></label><Button disabled={!group||busy} onClick={()=>setBusy(true)}>{busy?'Calculando…':'Consultar grupo'}</Button>{loadingGroups&&<p role="status">Cargando grupos autorizados…</p>}{!loadingGroups&&!error&&!groups.length&&<p>No hay grupos completamente autorizados para este usuario.</p>}{error&&<p role="alert">{error}</p>}{result&&<><p>{result.advertencia}</p><p>{result.periodo.desde} — {result.periodo.hasta} · Corte {result.fecha_corte}</p><p>Ingreso: <strong>{money(result.totales.ingreso)}</strong> · Coste directo: <strong>{money(result.totales.coste_directo)}</strong> · Margen directo: <strong>{money(result.totales.margen_directo)}</strong> · Estado: {result.totales.estado}</p><div style={{overflowX:'auto'}}><table><thead><tr>{['Empresa','Ingreso','Coste directo','Margen','Km totales','Cobertura costes'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{result.empresas.map(c=><tr key={c.id}><td>{c.nombre}</td><td>{money(c.economia.ingreso_servicios_realizados)}</td><td>{money(c.economia.costes_directos.directo_registrado)}</td><td>{money(c.economia.margen_directo)}</td><td>{c.economia.kilometros.cobertura.evaluables<c.economia.kilometros.cobertura.total?'No calculable':new Intl.NumberFormat('es-ES').format(c.economia.kilometros.total)}</td><td>{c.economia.costes_directos.cobertura.evaluables}/{c.economia.costes_directos.cobertura.total}</td></tr>)}</tbody></table></div></>}</>}</Card>;
}
