import './invoiceWorkflow.css';
import {useEffect,useState} from 'react';
import {invoiceWorkflow,crearFactura} from '../../services/api';
import {Button,Card} from '../../ui';
import {confirmDialog} from '../../services/notify';
const initial={hito:'delivery',exigir_pod:true,exigir_deca:false,bloquear_incidencia:true};
export default function InvoiceWorkflow({clients=[],canEdit,manager,onInvoice,onOrder}){
 const [open,setOpen]=useState(false),[page,setPage]=useState(1),[customer,setCustomer]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0),[selected,setSelected]=useState([]),[rules,setRules]=useState(initial);
 useEffect(()=>{if(!open)return;let current=true;setBusy(true);setError('');setData(null);setSelected([]);Promise.all([invoiceWorkflow(`?page=${page}${customer?'&cliente_id='+customer:''}`),invoiceWorkflow('/reglas/'+(customer||'empresa'))]).then(([d,r])=>{if(current){setData(d);setRules(r.reglas);}}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setBusy(false);});return()=>{current=false;};},[open,page,customer,version]);
 const action=async fn=>{setBusy(true);setError('');try{await fn();setVersion(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <details className="finance-accounting invoice-workflow" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Preparación y excepciones de facturación</summary>{open&&<Card style={{padding:16,minWidth:0}}><p>Revisa POD, DeCA, tarifa e incidencias. Un borrador todavía necesita revisión antes de emitirse. Los importes se calculan en el servidor; combustible en línea separada.</p>
 <label>Cliente de la preparación <select className="tgui-input" disabled={busy} value={customer} onChange={e=>{setCustomer(e.target.value);setPage(1);}}><option value="">Todos · reglas generales</option>{clients.map(c=><option value={c.id} key={c.id}>{c.nombre}</option>)}</select></label>
 {manager&&<details><summary>Reglas {customer?'de este cliente':'generales de empresa'}</summary><div className="tgui-filter-fields"><label>Facturar desde<select className="tgui-input" value={rules.hito} onChange={e=>setRules({...rules,hito:e.target.value})}><option value="delivery">Entrega</option><option value="departure">Salida real registrada</option></select></label>{[['exigir_pod','Exigir POD / albarán / CMR'],['exigir_deca','Exigir DeCA de cada envío'],['bloquear_incidencia','Bloquear incidencias activas']].map(([key,label])=><label key={key}><input type="checkbox" checked={rules[key]} onChange={e=>setRules({...rules,[key]:e.target.checked})}/>{label}</label>)}<Button disabled={busy} onClick={()=>action(()=>invoiceWorkflow('/reglas/'+(customer||'empresa'),{method:'PUT',body:rules}))}>Guardar reglas</Button></div><p>Las reglas actuales se vuelven a comprobar al revisar y emitir; no modifican facturas históricas.</p></details>}
 {error&&<p role="alert">{error}</p>}{busy&&<p role="status">Actualizando preparación…</p>}
 {data&&!busy&&<><p>{data.total} servicios pendientes · todas las fechas · página {page}</p>{!data.data.length&&<p>No hay servicios pendientes en este ámbito.</p>}<div style={{overflowX:'auto'}}><table className="tgui-table"><thead><tr><th>Seleccionar</th><th>Pedido / cliente</th><th>Importe sin IVA</th><th>Preparación</th><th>Acción</th></tr></thead><tbody>{data.data.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={'Seleccionar '+row.numero} disabled={!canEdit||row.estado!=='listo'} checked={selected.includes(row.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,row.id]:prev.filter(id=>id!==row.id))}/></td><td><Button disabled={!canEdit} onClick={()=>onOrder(row)}>{row.numero}</Button><div>{row.cliente_nombre}</div></td><td>{row.importe==null?'Sin importe':Number(row.importe).toLocaleString('es-ES',{style:'currency',currency:'EUR'})}</td><td>{row.estado==='listo'?'Listo para borrador':row.estado==='revisar'?'Pendiente de revisión humana':row.errores.join(' · ')}<div>POD: {row.documentos.pod} · DeCA: {row.documentos.deca}</div></td><td>{canEdit&&row.estado==='revisar'&&<Button onClick={async()=>{if(await confirmDialog({title:'Revisión operativa',message:'Confirma que has contrastado tarifa, combustible, suplementos, incidencias y documentos de '+row.numero+'.'}))action(()=>invoiceWorkflow('/'+row.id+'/revisar',{method:'POST',body:{confirmado:true,huella:row.huella}}));}}>Confirmar revisión</Button>}</td></tr>)}</tbody></table></div></>}
 <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Button disabled={busy||page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</Button><Button disabled={busy||!data||page*30>=data.total} onClick={()=>setPage(p=>p+1)}>Siguiente</Button><Button disabled={busy} onClick={()=>setVersion(v=>v+1)}>Actualizar preparación</Button>{canEdit&&<Button disabled={busy||!selected.length} onClick={()=>action(async()=>{const invoice=await crearFactura({workflow_pedidos_ids:selected});setSelected([]);await onInvoice(invoice.id);})}>Preparar borrador del lote ({selected.length})</Button>}</div><p>Selecciona servicios revisados del mismo cliente. La selección corresponde a esta página; no se emiten ni envían automáticamente.</p>
 </Card>}</details>;
}
