import {useEffect,useRef,useState} from 'react';
import {getPedidos,transportExchange} from '../services/api';
import {Button} from '../ui';
import {Panel,money} from './PlannerUI';

export default function NetworkConsentPanel({user,clients,canReceive,onConnected}){
 const [catalog,setCatalog]=useState({}),[invitations,setInvitations]=useState([]),[orders,setOrders]=useState([]),[workspace,setWorkspace]=useState(user.productos?.includes('planner')?'planner':'transgest');
 const [order,setOrder]=useState(''),[outScopes,setOutScopes]=useState(['pedidos']),[generated,setGenerated]=useState(null),[suggestion,setSuggestion]=useState(null);
 const [token,setToken]=useState(()=>new URLSearchParams(window.location.hash.slice(1)).get('encargo')||''),[preview,setPreview]=useState(null),[inScopes,setInScopes]=useState([]),[customer,setCustomer]=useState(''),[accepted,setAccepted]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const operation=useRef(null);
 const loadInvites=async()=>setInvitations(await transportExchange('/invitaciones'));
 useEffect(()=>{let alive=true;Promise.all([transportExchange('/catalogo'),transportExchange('/invitaciones')]).then(([c,i])=>{if(alive){setCatalog(c.scopes);setInvitations(i);}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[]);
 useEffect(()=>{let alive=true;setOrders([]);setOrder('');setSuggestion(null);getPedidos({workspace,limit:200}).then(data=>{if(alive)setOrders((Array.isArray(data)?data:data.data||[]).filter(p=>p.colaborador_id&&!['cancelado','entregado','facturado','borrador'].includes(p.estado)));}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[workspace]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const code=()=>{const raw=token.trim(),match=raw.match(/(?:encargo=)([a-f0-9]{64})/i);return match?match[1]:raw;};
 const scopeFields=(selected,set)=>Object.entries(catalog).map(([key,label])=><label className="pl-check-line" key={key}><input type="checkbox" checked={selected.includes(key)} disabled={busy||key==='pedidos'} onChange={e=>set(e.target.checked?[...selected,key]:selected.filter(s=>s!==key))}/>{label}</label>);
 return <>
 {error&&<p role="alert">{error}</p>}
 <Panel title="Invitar a otra empresa TransGest" icon="users"><form className="planner-form" style={{padding:18}} onSubmit={e=>{e.preventDefault();run(async()=>{const body={pedido_id:order,scopes:outScopes},fingerprint=JSON.stringify(body);if(operation.current?.fingerprint!==fingerprint)operation.current={fingerprint,id:crypto.randomUUID()};setGenerated(await transportExchange('/invitaciones',{method:'POST',body:{...body,operacion:operation.current.id}}));await loadInvites();});}}>
 <p>La coincidencia de NIF/CIF solo identifica al destinatario. La conexión se activa cuando su gerente revisa y acepta estos permisos. Se compartirán los encargos posteriores que acepte ese transportista, nunca toda tu cartera.</p>
 <div className="planner-grid"><label>Espacio de los pedidos<select value={workspace} disabled={busy} onChange={e=>setWorkspace(e.target.value)}>{user.productos?.includes('transgest')&&<option value="transgest">TransGest</option>}{user.productos?.includes('planner')&&<option value="planner">Planner</option>}</select></label><label>Encargo con colaborador<select required value={order} disabled={busy} onChange={e=>{setOrder(e.target.value);setSuggestion(null);setGenerated(null);}}><option value="">Seleccionar…</option>{orders.map(p=><option value={p.id} key={p.id}>{p.numero} · {p.origen} → {p.destino}</option>)}</select><small>Pedidos abiertos entre los primeros 200 del espacio seleccionado.</small></label></div>
 <Button disabled={busy||!order} onClick={()=>run(async()=>{const p=orders.find(p=>p.id===order);setSuggestion(await transportExchange(`/sugerencia?colaborador_id=${encodeURIComponent(p.colaborador_id)}`));})}>Comprobar destinatario por NIF</Button>{suggestion&&<p>{suggestion.nombre} · {suggestion.cif}. Coincidencia encontrada; aún no se ha conectado.</p>}
 <fieldset><legend>Permisos propuestos</legend>{scopeFields(outScopes,setOutScopes)}</fieldset><p>GPS solo durante el servicio activo, sin historial. ETA solo si el transportista ha calculado una estimación vigente. Las facturas de estos encargos requieren el permiso específico. Costes internos y nóminas quedan fuera de esta conexión.</p>
 <Button type="submit" variant="primary" disabled={busy||!order}>Crear invitación autorizada</Button>
 </form>{generated&&<div style={{padding:18}}><p>Invitación creada. Caduca el {new Date(generated.expires_at).toLocaleString('es-ES')}. Comparte este enlace con el gerente destinatario.</p><label>Enlace privado<input readOnly value={`${window.location.origin}/transportistas/conexiones#encargo=${generated.token}`} onFocus={e=>e.target.select()}/></label></div>}</Panel>
 {canReceive&&<Panel title="Revisar y aceptar invitación Network" icon="file"><form className="planner-form" style={{padding:18}} onSubmit={e=>{e.preventDefault();run(async()=>{const data=await transportExchange('/conectar',{method:'POST',body:{token:code(),cliente_id:customer,scopes:inScopes,acepta_condiciones:accepted}});setToken('');setPreview(null);setAccepted(false);window.history.replaceState(null,'',window.location.pathname);onConnected(data);});}}>
 <label>Código o enlace Network<input required autoComplete="off" value={token} onChange={e=>{setToken(e.target.value);setPreview(null);setAccepted(false);}}/></label><Button disabled={busy||!token} onClick={()=>run(async()=>{setPreview(null);setAccepted(false);const data=await transportExchange('/previsualizar',{method:'POST',body:{token:code()}});setPreview(data);setInScopes(data.scopes);})}>Revisar invitación</Button>
 {preview&&<><p><strong>{preview.cargador}</strong> · {preview.cif} · {preview.encargo.numero}</p><p>{preview.encargo.origen} → {preview.encargo.destino} · Precio de transporte: {money(preview.encargo.precio_colaborador)} sin impuestos.</p><label>Remitente en mi cartera de clientes<select required value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Seleccionar cliente…</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nombre} · {c.cif}</option>)}</select></label><fieldset><legend>Permisos que acepto compartir</legend>{Object.entries(catalog).filter(([key])=>preview.scopes.includes(key)).map(([key,label])=><label className="pl-check-line" key={key}><input type="checkbox" disabled={busy||key==='pedidos'} checked={inScopes.includes(key)} onChange={e=>{setInScopes(e.target.checked?[...inScopes,key]:inScopes.filter(s=>s!==key));setAccepted(false);}}/>{label}</label>)}</fieldset><label className="pl-check-line"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Acepto las condiciones del encargo y autorizo únicamente los permisos seleccionados, revocables desde Conexiones.</label><Button type="submit" variant="primary" disabled={busy||!accepted}>Aceptar y crear viaje</Button></>}
 </form></Panel>}
 <details style={{padding:18}}><summary>Invitaciones emitidas (últimas 100)</summary>{invitations.map(i=><div key={i.id} className="pl-action-row"><span>{i.numero} · {i.destinatario} · {i.revocada_at?'Revocada':i.aceptada_at?'Aceptada':Date.parse(i.expires_at)<Date.now()?'Caducada':'Pendiente'}</span>{!i.revocada_at&&!i.aceptada_at&&<Button disabled={busy} onClick={()=>run(async()=>{await transportExchange(`/invitaciones/${i.id}`,{method:'DELETE'});await loadInvites();})}>Revocar invitación</Button>}</div>)}</details>
 </>;
}
