import {useEffect,useState} from 'react';
import {transportExchange} from '../services/api';
import {Button} from '../ui';
import {Panel,money} from './PlannerUI';
import SupplierInvoiceReview from '../pages/colaboradores/SupplierInvoiceReview';
export default function NetworkBillingPanel({links,canEdit}){
 const [link,setLink]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[invoice,setInvoice]=useState(''),[file,setFile]=useState(null),[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{if(!link)return;let current=true;setData(null);setError('');transportExchange('/facturacion/'+link).then(d=>{if(current)setData(d);}).catch(e=>current&&setError(e.message));return()=>{current=false;};},[link,reload]);
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn();setReload(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function send(){if(!file||file.size>5*1024*1024)throw Error('Selecciona un PDF de hasta 5 MB.');const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('No se pudo leer el archivo.'));r.readAsDataURL(file);});await transportExchange(`/facturacion/${link}/compartir`,{method:'POST',body:{factura_id:invoice,nombre:file.name,base64,confirmado:confirmed}});setInvoice('');setFile(null);setConfirmed(false);}
 return <Panel title="Cierre económico Network" icon="file"><div className="planner-form" style={{padding:18}}><label>Empresa conectada<select value={link} onChange={e=>{setLink(e.target.value);setData(null);setInvoice('');setFile(null);setConfirmed(false);}}><option value="">Seleccionar conexión…</option>{links.filter(l=>l.activo).map(l=><option key={l.id} value={l.id}>{l.cargador} ↔ {l.transportista}</option>)}</select></label>{error&&<p role="alert">{error}</p>}
 {data&&<><p>{data.definicion}</p><p>{data.autorizado?'Intercambio de facturas autorizado por ambas empresas.':data.autorizado_por_mi?'Autorizado por tu empresa; falta la aceptación de la otra parte.':'Requiere consentimiento de gerencia en ambas empresas.'}</p><div className="pl-action-row"><Button disabled={busy} onClick={()=>setReload(n=>n+1)}>Actualizar</Button><Button disabled={busy||!canEdit} onClick={()=>run(()=>transportExchange(`/facturacion/${link}/consentimiento`,{method:'POST',body:{autorizar:!data.autorizado_por_mi}}))}>{data.autorizado_por_mi?'Retirar permiso de facturas':'Autorizar intercambio de facturas'}</Button></div>
 {data.autorizado&&<><div className="planner-table"><table><thead><tr><th>Factura</th><th>Base / total</th><th>Revisión del destinatario</th><th>Diferencias</th><th>Pago declarado</th></tr></thead><tbody>{data.facturas.map(f=><tr key={f.id}><td>{f.numero}</td><td>{money(f.base_imponible)} / {money(f.total)}</td><td>{f.revision==='revisada'?'Revisada':'Pendiente'}</td><td>{f.diferencias}</td><td>{f.pagos_declarados?'Registrado por destinatario':'Sin pago declarado'}</td></tr>)}</tbody></table></div><small>Hasta {data.limite} facturas recientes. Las diferencias no se ocultan al aceptar una revisión.</small>
 {data.emisor?<form className="planner-form" onSubmit={e=>{e.preventDefault();run(send);}}><label>Factura emitida<select required value={invoice} onChange={e=>{setInvoice(e.target.value);setConfirmed(false);}}><option value="">Seleccionar…</option>{data.disponibles.map(f=><option key={f.id} value={f.id}>{f.numero} · {money(f.total)}</option>)}</select></label><label>PDF original emitido (máximo 5 MB)<input key={invoice} required type="file" accept="application/pdf,.pdf" onChange={e=>{setFile(e.target.files?.[0]||null);setConfirmed(false);}}/></label><label className="pl-check-line"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo que el PDF es el original emitido de esta factura y autorizo su entrega al destinatario</label><Button type="submit" disabled={busy||!canEdit||!confirmed||!invoice||!file}>Compartir factura</Button><p>Solo facturas cuyos servicios pertenecen a esta conexión. El destinatario revisará el original, los importes, el encargo y sus documentos antes de registrarla.</p></form>:<SupplierInvoiceReview key={data.proveedor_id} proveedor={{id:data.proveedor_id}} onRegistered={()=>setReload(n=>n+1)}/>}
 </>}</>}
 </div></Panel>;
}
