import {useEffect,useState,useCallback} from 'react';
import {plannerApi,getColaboradores} from '../services/api';
import {useAuth} from '../context/AuthContext';
import {PageHead,Panel,Badge,Empty} from './PlannerUI';
import {Button,Modal} from '../ui';

export default function PlannerDrivers(){
 const {puedeEditar}=useAuth(),canEdit=puedeEditar('colaboradores');
 const [rows,setRows]=useState([]),[providers,setProviders]=useState([]),[provider,setProvider]=useState(''),[search,setSearch]=useState(''),[draft,setDraft]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [d,p]=await Promise.all([plannerApi('/proveedores/conductores'),getColaboradores()]);setRows(d);setProviders(Array.isArray(p)?p:p.data||[]);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 const filtered=rows.filter(d=>(!provider||d.colaborador_id===provider)&&`${d.nombre} ${d.apellidos} ${d.alias} ${d.colaborador}`.toLowerCase().includes(search.toLowerCase()));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await plannerApi(`/proveedores/conductores${draft.id?`/${draft.id}`:''}`,{method:draft.id?'PUT':'POST',body:draft});setDraft(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><PageHead icon="truck" title="Conductores por proveedor" description="Organiza los conductores que recogen o entregan cargas en tu almacén.">{canEdit&&<Button variant="primary" onClick={()=>setDraft({colaborador_id:provider,nombre:'',apellidos:'',alias:'',telefono:'',email:'',dni:'',carnet:'',activo:true})}>Nuevo conductor</Button>}</PageHead>
 {error&&!draft&&<p role="alert">{error}</p>}<Panel title="Directorio de conductores" icon="truck"><div className="pl-filters"><input aria-label="Buscar conductores" placeholder="Nombre, alias o proveedor…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Proveedor de los conductores" value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Todos los proveedores</option>{providers.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></div><div className="planner-table"><table><thead><tr>{['Proveedor','Conductor','Teléfono','Email','Permiso','Estado','Acciones'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(d=><tr key={d.id}><td>{d.colaborador}</td><td><strong>{d.alias||`${d.nombre} ${d.apellidos}`}</strong>{d.alias&&<small>{d.nombre} {d.apellidos}</small>}</td><td>{d.telefono||'—'}</td><td>{d.email||'—'}</td><td>{d.carnet||'—'}</td><td><Badge value={d.activo?'lista':'cancelada'}>{d.activo?'Activo':'Inactivo'}</Badge></td><td><Button disabled={!canEdit} onClick={()=>setDraft(d)}>Editar</Button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty>Añade un conductor y vincúlalo a su proveedor de transporte.</Empty>}<footer>Directorio operativo de Planner. El acceso a la app del chófer se gestiona mediante las invitaciones del proveedor.</footer></Panel>
 {draft&&<Modal title={draft.id?'Editar conductor':'Nuevo conductor'} onClose={()=>!busy&&setDraft(null)}><form className="planner-form" onSubmit={save}><div className="planner-grid"><label>Proveedor de transporte<select required value={draft.colaborador_id} onChange={e=>setDraft({...draft,colaborador_id:e.target.value})}><option value="">Selecciona un proveedor</option>{providers.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label>{[['nombre','Nombre'],['apellidos','Apellidos'],['alias','Alias (opcional)'],['telefono','Teléfono'],['email','Email'],['dni','DNI / NIE'],['carnet','Permiso de conducción']].map(([k,label])=><label key={k}>{label}<input type={k==='email'?'email':'text'} required={k==='nombre'} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Estado<select value={String(draft.activo)} onChange={e=>setDraft({...draft,activo:e.target.value==='true'})}><option value="true">Activo</option><option value="false">Inactivo</option></select></label></div>{error&&<p role="alert">{error}</p>}<Button type="submit" variant="primary" disabled={busy}>Guardar conductor</Button></form></Modal>}
 </section>;
}
