import {useEffect,useRef,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {plannerLoadingApi,plannerApi,getPedidoDocumentoControl,generarPedidoDocumentoControl} from '../services/api';
import {Button} from '../ui';
import {Panel,quantity} from './PlannerUI';
import './planner.css';
import './planner-presentation.css';
import './planner-loading.css';
const names={planificada:'Planificada',asignada:'Asignada',en_muelle:'En muelle',cargando:'Cargando',cargada:'Cargada',lista_para_salida:'Lista para salida',en_transito:'En tránsito',entregada:'Entregada',incidencia:'Incidencia',cancelada:'Cancelada'};
function BillingPolicy(){
 const [data,setData]=useState(null),[scope,setScope]=useState('empresa'),[trigger,setTrigger]=useState('departure'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{let alive=true;plannerLoadingApi('/politicas').then(d=>{if(alive){setData(d);setTrigger(d.politicas.find(p=>p.ambito==='empresa')?.billing_trigger||'departure');}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[]);
 return <details><summary>Hito de facturación por empresa o cliente</summary>{error&&<p role="alert">{error}</p>}{data&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await plannerLoadingApi('/politicas',{method:'POST',body:{ambito:scope,billing_trigger:trigger}});setData(d=>({...d,politicas:[...d.politicas.filter(p=>p.ambito!==scope),{ambito:scope,billing_trigger:trigger}]}));setNotice('Guardado. Se aplicará a las nuevas preparaciones; las existentes conservan su condición.');}catch(e){setError(e.message);}finally{setBusy(false);}}}><div className="planner-grid"><label>Ámbito<select value={scope} onChange={e=>{const s=e.target.value;setScope(s);setNotice('');setTrigger(data.politicas.find(p=>p.ambito===s)?.billing_trigger||data.politicas.find(p=>p.ambito==='empresa')?.billing_trigger||'departure');}}><option value="empresa">Predeterminado de la empresa</option>{data.clientes.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Listo para revisión tras<select value={trigger} onChange={e=>setTrigger(e.target.value)}><option value="departure">Salida confirmada</option><option value="delivery">Entrega con POD</option></select></label></div><Button type="submit" disabled={busy}>Guardar condición</Button><p>{notice||'Se muestran hasta 500 clientes. Este hito no emite facturas automáticamente.'}</p></form>}</details>;
}
export default function PlannerLoading({standalone=false}){
 const {user,logout}=useAuth(),office=['gerente','trafico','administrativo'].includes(user?.rol);
 const [rows,setRows]=useState([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[detail,setDetail]=useState(null),[workers,setWorkers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[docs,setDocs]=useState(null),[review,setReview]=useState(false);
 const [scan,setScan]=useState({linea_id:'',ubicacion:'',referencia:'',lote:'',cantidad:''}),[photo,setPhoto]=useState(null),[assigned,setAssigned]=useState(''),[trigger,setTrigger]=useState('departure'),[reason,setReason]=useState(''),[pod,setPod]=useState('');
 const epoch=useRef(0),pending=useRef(null);
 async function load(){const n=++epoch.current;const result=await plannerLoadingApi(`?page=${page}`);if(n===epoch.current){setRows(result.data);setTotal(result.total);}}
 useEffect(()=>{load().catch(e=>setError(e.message));return()=>{epoch.current++;};},[page]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{let alive=true;if(office)plannerLoadingApi('/operarios').then(r=>alive&&setWorkers(r)).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[office]);
 async function open(id){setBusy(true);setError('');setDocs(null);setReview(false);try{const d=await plannerLoadingApi('/'+id);setDetail(d);setAssigned(d.carretillero_id||'');setTrigger(d.billing_trigger);setPhoto(null);pending.current=null;}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function action(body){if(busy)return;setBusy(true);setError('');const key=JSON.stringify({id:detail.id,...body});if(pending.current?.key!==key)pending.current={key,operacion:crypto.randomUUID()};try{
  setDetail(await plannerLoadingApi(`/${detail.id}/accion`,{method:'POST',body:{...body,version:detail.version,operacion:pending.current.operacion}}));pending.current=null;setScan(s=>({...s,cantidad:''}));await load();
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 async function readDocs(generate=false){setBusy(true);setError('');setReview(false);try{if(generate)await generarPedidoDocumentoControl(detail.pedido_id,{motivo:'Mercancía confirmada en Planner'});setDocs(await getPedidoDocumentoControl(detail.pedido_id));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function dispatch(){setBusy(true);setError('');try{await plannerApi(`/inventario/preparaciones/${detail.id}/accion`,{method:'POST',body:{accion:'expedir',version:detail.version,dcd_revisado:review,dcd_disponible:review,dcd_versiones_revisadas:docs?.versiones?.filter(d=>d.estado==='activa').map(d=>d.id)||[]}});await open(detail.id);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function takePhoto(file){setError('');if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>5*1024*1024){setError('Selecciona una foto JPEG o PNG de hasta 5 MB.');return;}const reader=new FileReader();reader.onload=()=>setPhoto({foto_mime:file.type,foto_base64:String(reader.result).split(',')[1]});reader.onerror=()=>setError('No se pudo leer la foto.');reader.readAsDataURL(file);}
 const completed=detail?.lineas.filter(l=>l.cantidad_cargada!==null&&Number(l.cantidad_cargada)===Number(l.cantidad)).length||0;
 return <main className="planner-loading planner-form">{standalone&&<header><strong>TransGest Planner · Almacén</strong><Button onClick={logout}>Salir</Button></header>}<h1>Carga en muelle</h1><p>Lecturas de mercancía y cierre de carga. La salida requiere confirmación separada.</p>{error&&<p role="alert">{error}</p>}
 {!detail?<>{user?.rol==='gerente'&&<BillingPolicy/>}<Panel title={office?'Preparaciones activas':'Mis cargas asignadas'}>{rows.map(p=><Button key={p.id} disabled={busy} onClick={()=>open(p.id)}>{p.numero} · {names[p.estado_operativo]}</Button>)}{!rows.length&&<p>No hay cargas asignadas en esta página.</p>}</Panel><nav aria-label="Páginas de cargas"><Button disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>Anterior</Button><span>Página {page}</span><Button disabled={busy||page*50>=total} onClick={()=>setPage(p=>p+1)}>Siguiente</Button></nav></>:<>
 <Button disabled={busy} onClick={()=>{setDetail(null);setDocs(null);}}>Volver a cargas</Button><Panel title={`${detail.numero} · ${names[detail.estado_operativo]}`}><p>Referencia: {detail.referencia_cliente||'Sin referencia'} · {detail.origen} → {detail.destino}</p><p>Muelle: {detail.muelle||'Sin registrar'} · {completed} de {detail.lineas.length} líneas cargadas ({Math.round(completed/Math.max(1,detail.lineas.length)*100)} %)</p><progress max={detail.lineas.length||1} value={completed} aria-label="Líneas cargadas"/>{detail.incidencia&&<p role="alert">{detail.incidencia}</p>}
 {office&&detail.estado!=='expedida'&&!detail.carga_confirmada_at&&<form onSubmit={e=>{e.preventDefault();action({accion:'asignar',carretillero_id:assigned,billing_trigger:trigger});}}><div className="planner-grid"><label>Carretillero<select required value={assigned} onChange={e=>setAssigned(e.target.value)}><option value="">Seleccionar</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre}</option>)}</select></label><label>Preparar facturación tras<select value={trigger} onChange={e=>setTrigger(e.target.value)}><option value="departure">Salida confirmada</option><option value="delivery">Entrega con POD</option></select></label></div><Button type="submit" disabled={busy}>Guardar asignación</Button></form>}
 {detail.lineas.map(l=><article key={l.id}><strong>{l.referencia} · {l.descripcion}</strong><p>{quantity(l.cantidad_cargada??0)} / {quantity(l.cantidad)} {l.unidad} · Peso previsto: {quantity(Number(l.peso_kg)*Number(l.cantidad))} kg</p><p>Faltan: {quantity(Number(l.cantidad)-Number(l.cantidad_cargada||0))} {l.unidad} · Palés previstos: {l.unidades_palet?quantity(Math.ceil(Number(l.cantidad)/Number(l.unidades_palet))):'Sin dato'}</p><p>{l.almacen} / {l.ubicacion||'Sin ubicación'} · Lote {l.lote||'sin lote'} · Descarga {l.parada}</p></article>)}
 {detail.situacion_camion==='espera_carga'&&<Button disabled={busy} onClick={()=>action({accion:'iniciar'})}>Iniciar carga</Button>}
 {detail.situacion_camion==='cargando'&&!detail.carga_confirmada_at&&<><form onSubmit={e=>{e.preventDefault();action({accion:'escanear',...scan});}}><h2>Registrar lectura</h2><p>Lee con el escáner conectado o introduce el código impreso. Cada envío se registra una sola vez.</p><label>Línea<select required value={scan.linea_id} onChange={e=>setScan({...scan,linea_id:e.target.value})}><option value="">Seleccionar</option>{detail.lineas.map(l=><option key={l.id} value={l.id}>{l.referencia} · Descarga {l.parada}</option>)}</select></label><div className="planner-grid">{[['ubicacion','Ubicación'],['referencia','Referencia del artículo'],['lote','Lote'],['cantidad','Cantidad']].map(([key,label])=><label key={key}>{label}<input value={scan[key]} required={['referencia','cantidad'].includes(key)} type={key==='cantidad'?'number':'text'} min={key==='cantidad'?'0.001':undefined} step="0.001" onChange={e=>setScan({...scan,[key]:e.target.value})}/></label>)}</div><Button type="submit" disabled={busy}>Confirmar lectura</Button></form><label>Foto de carga terminada<input type="file" accept="image/jpeg,image/png" capture="environment" onChange={e=>takePhoto(e.target.files?.[0])}/></label><Button disabled={busy||!photo||completed!==detail.lineas.length} onClick={()=>action({accion:'finalizar',confirmado:true,...photo})}>Confirmar camión cargado</Button></>}
 {office&&detail.situacion_camion==='cargado'&&<><h2>Documentos y salida</h2><Button disabled={busy} onClick={()=>readDocs(true)}>Preparar DeCA con mercancía actual</Button><Button disabled={busy} onClick={()=>readDocs()}>Consultar documentos vigentes</Button>{docs&&<><p>{docs.status?.summary}</p>{docs.versiones?.filter(d=>d.estado==='activa').map(d=><p key={d.id}><a href={d.public_url} target="_blank" rel="noreferrer">Abrir DeCA · versión {d.version}</a></p>)}<label className="pl-check-line"><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/>He revisado las versiones vigentes y están disponibles para el conductor.</label><Button disabled={busy||!review} onClick={()=>action({accion:'documentos_listos',dcd_revisado:review,dcd_disponible:review,dcd_versiones_revisadas:docs.versiones?.filter(d=>d.estado==='activa').map(d=>d.id)||[]})}>Marcar lista para salida</Button><Button disabled={busy||!review||!detail.documentos_listos_at} onClick={dispatch}>Confirmar salida real y descontar stock</Button></>}</>}
 {office&&detail.estado==='expedida'&&!detail.entrega_confirmada_at&&<form onSubmit={e=>{e.preventDefault();action({accion:'entregada',confirmado:true,pod_id:pod});}}><label>POD del expediente<select required value={pod} onChange={e=>setPod(e.target.value)}><option value="">Selecciona el documento de entrega</option>{detail.pods?.map(d=><option key={d.id} value={d.id}>{d.nombre}</option>)}</select></label><Button type="submit" disabled={busy}>Confirmar entrega revisada</Button></form>}
 {detail.documentacion_estado&&<p role="status">{detail.documentacion_estado.detalle}</p>}
 <p>{detail.listo_facturar?'Listo para revisión de facturación. No se ha emitido ninguna factura.':'Pendiente del hito y revisión para facturar.'}</p>
 {!detail.entrega_confirmada_at&&<form onSubmit={e=>{e.preventDefault();action({accion:detail.incidencia&&office?'resolver':'incidencia',motivo:reason});}}><label>{detail.incidencia&&office?'Resolución':'Incidencia'}<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button type="submit" disabled={busy}>{detail.incidencia&&office?'Resolver incidencia':'Registrar incidencia'}</Button></form>}
 </Panel></>}{busy&&<p role="status">Guardando / consultando…</p>}</main>;
}
