export const money=value=>Number(value||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
export const quantity=value=>Number(value||0).toLocaleString('es-ES',{maximumFractionDigits:3});
export const dayKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export const labels={preparando:'Preparando',lista:'Lista',expedida:'Expedida',cancelada:'Cancelada',pendiente:'Pendiente',espera_carga:'En espera de carga',cargando:'Cargando',cargado:'Cargado',salida:'Salida',confirmado:'Confirmado',en_ruta:'En ruta',entregado:'Entregado',incidencia:'Incidencia',recepcion:'Recepción',fabricacion:'Fabricación',devolucion:'Devolución',ajuste:'Ajuste',reserva:'Reserva',liberacion:'Liberación',expedicion:'Expedición'};
export function Icon({name='box'}){const paths={box:<><path d="m12 3 9 5-9 5-9-5 9-5Zm-9 5v9l9 5 9-5V8M12 13v9M7 5.8l9 5"/></>,truck:<><path d="M3 5h11v12H3V5Zm11 5h4l3 4v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/></>,warehouse:<><path d="m3 10 9-7 9 7v11H3V10Zm4 11V11h10v10M7 15h10M7 18h10"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>,file:<><path d="M5 3h10l4 4v14H5V3Zm10 0v5h4M8 12h8M8 16h8"/></>,alert:<><path d="m12 3 10 18H2L12 3ZM12 9v5m0 3v.1"/></>,users:<><circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M16 4a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 5v3"/></>};return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.box}</svg>;}
export function Badge({value,children}){return <span className={`pl-badge pl-${value}`}>{children||labels[value]||value}</span>;}
export function PageHead({icon,title,description,children}){return <header className="pl-page-head"><span className="pl-page-icon"><Icon name={icon}/></span><div><h1>{title}</h1><p>{description}</p></div><div className="pl-head-actions">{children}</div></header>;}
export function Metrics({items}){return <div className="pl-metrics">{items.map(({label,value,note,icon,tone='teal'})=><article className="pl-metric" key={label}><span className={`pl-metric-icon pl-tone-${tone}`}><Icon name={icon}/></span><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>)}</div>;}
export function Panel({title,icon,actions,children,className=''}){return <section className={`pl-panel ${className}`}><header><h2>{icon&&<Icon name={icon}/>} {title}</h2>{actions}</header>{children}</section>;}
export function Empty({children}){return <div className="pl-empty"><Icon name="box"/><p>{children}</p></div>;}
export function exportCSV(name,columns,rows){const safe=v=>`"${String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')}"`;const csv='\uFEFF'+[columns.map(c=>c[1]),...rows.map(r=>columns.map(c=>r[c[0]]))].map(r=>r.map(safe).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
