import {useCallback,useEffect,useState} from 'react';
import {plannerApi,descargarArchivoProtegido,getPedidoDocumentoControl,generarPedidoDocumentoControl,getPedidoDocs,getPedidoDocsB64,subirPedidoDoc} from '../services/api';
import {useAuth} from '../context/AuthContext';
import {Button,Modal} from '../ui';
import {PageHead,Metrics,Panel,Badge,Empty,quantity,exportCSV} from './PlannerUI';
const download=file=>{const bytes=Uint8Array.from(atob(file.file_base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:file.file_mime||'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=file.nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export default function PlannerDocuments(){
 const {puedeEditar}=useAuth(),canEdit=puedeEditar('pedidos');
 const [rows,setRows]=useState([]),[preps,setPreps]=useState([]),[selected,setSelected]=useState(null),[tab,setTab]=useState('albaranes'),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[control,setControl]=useState(null),[upload,setUpload]=useState(null),[file,setFile]=useState(null),[docs,setDocs]=useState([]);
 const load=useCallback(async()=>{const [a,p]=await Promise.all([plannerApi('/inventario/albaranes'),plannerApi('/inventario/preparaciones')]);setRows(a);setPreps(p);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function select(row){await run(async()=>{setSelected({...row,...await plannerApi(`/inventario/albaranes/${row.id}`)});});}
 const controlUrl=control?.data?.documento?.soporte_url||control?.data?.soporte_url||control?.data?.documento?.url_publica||'';
 const filtered=rows.filter(r=>`${r.numero} ${r.pedido_numero} ${r.cliente} ${r.destino}`.toLowerCase().includes(search.toLowerCase()));
 async function openDocs(p){await run(async()=>{const data=await getPedidoDocs(p.pedido_id);setDocs(Array.isArray(data)?data:data.data||[]);setUpload(p);setFile(null);});}
 return <section><PageHead icon="file" title="Documentos y expedición" description="Albaranes de mercancía, documentos de control y justificantes de entrega de cada carga."><Button onClick={()=>exportCSV('albaranes-planner.csv',[['numero','Albarán'],['pedido_numero','Carga'],['cliente','Cliente'],['destino','Destino'],['created_at','Fecha']],filtered)}>Exportar CSV</Button></PageHead><Metrics items={[{label:'Albaranes generados',value:rows.length,icon:'file',note:'Hasta 300 documentos recientes'},{label:'Cargas preparadas',value:preps.filter(p=>p.estado==='lista').length,icon:'box',tone:'blue'},{label:'Expediciones',value:preps.filter(p=>p.estado==='expedida').length,icon:'truck'},{label:'Preparaciones abiertas',value:preps.filter(p=>p.estado==='preparando').length,icon:'clock',tone:'amber'}]}/><div className="pl-tabs">{[['albaranes','Albaranes'],['dcd','DCD digitales'],['pod','POD / entregas']].map(([id,label])=><button key={id} aria-pressed={id===tab} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<p role="alert">{error}</p>}
 {tab==='albaranes'?<div className={selected?'pl-document-layout':''}><Panel title="Listado de albaranes" icon="file"><div className="pl-filters"><input placeholder="Buscar por referencia, cliente o destinatario…" aria-label="Buscar albaranes" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="planner-table"><table><thead><tr>{['Documento','Referencia de carga','Cliente','Destino','Fecha','Estado','Acciones'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className={selected?.id===r.id?'pl-selected':''}><td><button onClick={()=>select(r)}>{r.numero}</button></td><td>{r.pedido_numero}</td><td>{r.cliente}</td><td>{r.destino}</td><td>{new Date(r.created_at).toLocaleDateString('es-ES')}</td><td><Badge value="lista">Generado</Badge></td><td><Button disabled={busy} onClick={()=>select(r)}>Ver</Button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty>Genera el albarán desde una preparación lista o expedida.</Empty>}</Panel>{selected&&<Panel title={selected.numero} icon="file" actions={<Button aria-label="Cerrar albarán" onClick={()=>setSelected(null)}>×</Button>}><div className="pl-document-preview"><header><strong>{selected.datos.empresa?.nombre}</strong><span>ALBARÁN</span></header><p>{selected.datos.empresa?.cif}</p><h3>{selected.datos.cliente_nombre}</h3><p>{selected.datos.cliente_cif}<br/>{selected.datos.cliente_direccion}</p><p>{selected.datos.origen} → {selected.datos.destino}</p><div className="planner-table"><table><thead><tr><th>Artículo</th><th>Cantidad</th><th>Reparto</th></tr></thead><tbody>{selected.datos.lineas.map((l,i)=><tr key={i}><td>{l.referencia}<small>{l.descripcion} · {l.lote}</small></td><td>{quantity(l.cantidad)} {l.unidad}</td><td>{l.parada}</td></tr>)}</tbody></table></div></div><div className="pl-action-row"><Button variant="primary" disabled={busy} onClick={()=>run(async()=>download(await plannerApi(`/inventario/albaranes/${selected.id}/pdf`)))}>Descargar PDF</Button><Button onClick={()=>{setTab('pod');setSelected(null);}}>Documentos de entrega</Button></div></Panel>}</div>:<Panel title={tab==='dcd'?'Documento de control por carga':'Albaranes y justificantes de entrega'} icon="truck"><div className="planner-table"><table><thead><tr><th>Carga</th><th>Cliente / destino</th><th>Mercancía</th><th>Viaje</th><th>Acciones</th></tr></thead><tbody>{preps.map(p=><tr key={p.id}><td>{p.numero}</td><td>{p.cliente}<small>{p.destino}</small></td><td><Badge value={p.estado}/></td><td><Badge value={p.viaje_estado}/></td><td><Button disabled={busy} onClick={()=>tab==='dcd'?run(async()=>setControl({pedido:p,data:await getPedidoDocumentoControl(p.pedido_id)})):openDocs(p)}>{tab==='dcd'?'Ver / generar DCD':'Ver / subir POD'}</Button></td></tr>)}</tbody></table></div>{!preps.length&&<Empty>Aquí aparecerán los documentos de tus cargas preparadas.</Empty>}</Panel>}
 {control&&<Modal title={`DCD · ${control.pedido.numero}`} onClose={()=>setControl(null)}><div className="planner-form"><p>El documento de control utiliza el emisor, el transportista, los puntos y la mercancía del pedido.</p><Badge value={control.data?.documento?.estado||'pendiente'}/>{/^https?:\/\//.test(controlUrl)&&<p><a href={controlUrl} target="_blank" rel="noreferrer">Abrir documento de control</a></p>}{control.data?.repositorio?.id&&<Button disabled={busy} onClick={()=>run(()=>descargarArchivoProtegido(`/pedidos/documento-control-repositorio/${encodeURIComponent(control.data.repositorio.id)}/descargar`,'DCD.pdf'))}>Descargar DCD PDF</Button>}{canEdit&&<Button disabled={busy} variant="primary" onClick={()=>run(async()=>{const data=await generarPedidoDocumentoControl(control.pedido.pedido_id);setControl({...control,data});})}>Generar / actualizar DCD</Button>}{error&&<p role="alert">{error}</p>}</div></Modal>}
 {upload&&<Modal title={`POD / entregas · ${upload.numero}`} onClose={()=>!busy&&setUpload(null)}><div className="planner-form">{docs.map(d=><p key={d.id}><Button onClick={()=>run(async()=>{const result=await getPedidoDocsB64(upload.pedido_id);const files=Array.isArray(result)?result:result.data||[];const found=files.find(x=>x.id===d.id);if(!found?.file_base64)throw new Error('El archivo no está disponible para descargar.');download(found);})}>{d.nombre}</Button> · {d.tipo}</p>)}{!docs.length&&<p>No hay documentos adjuntos.</p>}{canEdit&&<form onSubmit={e=>{e.preventDefault();run(async()=>{if(!file||file.size>3*1024*1024)throw new Error('Selecciona un PDF o imagen de hasta 3 MB.');const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});await subirPedidoDoc(upload.pedido_id,{nombre:file.name,tipo:'pod',file_mime:file.type,file_base64:base64});const refreshed=await getPedidoDocs(upload.pedido_id);setDocs(Array.isArray(refreshed)?refreshed:refreshed.data||[]);setFile(null);});}}><label>Albarán firmado / POD<input required type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button type="submit" disabled={busy||!file}>Adjuntar justificante</Button></form>}{error&&<p role="alert">{error}</p>}</div></Modal>}
 </section>;
}
