import {useCallback,useEffect,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {getPedidos,plannerApi} from '../services/api';
import {Button,Modal} from '../ui';
import {confirmDialog} from '../services/notify';
import {PageHead,Metrics,Panel,Badge,Empty,dayKey} from './PlannerUI';
const time=d=>new Date(d).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});
const localInput=d=>`${dayKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;
export default function PlannerSlots({compact=false,onOrder,selectedDay,onDayChange}){
 const {puedeEditar}=useAuth(),canEdit=puedeEditar('pedidos');
 const [ownDay,setOwnDay]=useState(dayKey()),[view,setView]=useState('dia'),[warehouse,setWarehouse]=useState(''),[docks,setDocks]=useState([]),[bookings,setBookings]=useState([]),[requests,setRequests]=useState([]),[orders,setOrders]=useState([]),[draft,setDraft]=useState(null),[dock,setDock]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const day=selectedDay||ownDay;
 const setDay=value=>{setOwnDay(value);onDayChange?.(value);};
 const load=useCallback(async()=>{
   const start=new Date(`${day}T00:00:00`),end=new Date(start);end.setDate(end.getDate()+(view==='semana'?7:1));
   const [d,b,o,r]=await Promise.all([plannerApi('/muelles'),plannerApi(`/reservas?${new URLSearchParams({desde:start.toISOString(),hasta:end.toISOString()})}`),getPedidos({workspace:'planner',desde:day,hasta:dayKey(end),limit:200}),plannerApi('/solicitudes-hueco')]);
   setDocks(d);setBookings(b);setOrders(Array.isArray(o)?o:o.data||[]);setRequests(r);
 },[day,view]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 const visible=docks.filter(d=>!warehouse||d.almacen===warehouse);
 const filtered=bookings.filter(b=>visible.some(d=>d.id===b.muelle_id));
 const newReservation=(d=visible.find(d=>d.activo),hour=9,date=day,request=null)=>{
  if(!d)return;const start=new Date(request?.inicio||`${date}T${String(hour).padStart(2,'0')}:00`),end=new Date(request?.fin||(+start+Number(d.duracion_min||90)*60000));
  setDraft({muelle_id:d.id,pedido_id:request?.pedido_id||'',solicitud_id:request?.id,tipo:'carga',inicio:localInput(start),fin:localInput(end),notas:request?.notas||'',palets:0});setError('');
 };
 async function save(e){e.preventDefault();setBusy(true);setError('');try{
   if(dock)await plannerApi(dock.id?`/muelles/${dock.id}`:'/muelles',{method:dock.id?'PUT':'POST',body:dock});
   else await plannerApi('/reservas',{method:'POST',body:{...draft,inicio:new Date(draft.inicio).toISOString(),fin:new Date(draft.fin).toISOString()}});
   setDraft(null);setDock(null);await load();
 }catch(err){setError(err.message);}finally{setBusy(false);}}
 async function cancel(b){if(!await confirmDialog({title:'Liberar hueco',message:'Se liberará esta reserva del muelle. La carga y su mercancía se conservan.',confirmText:'Liberar hueco',tone:'warning'}))return;setBusy(true);try{await plannerApi(`/reservas/${b.id}`,{method:'DELETE'});setSelected(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const occupied=new Set(filtered.map(b=>b.muelle_id)).size;
 const hours=Array.from({length:24},(_,i)=>i).filter(h=>h>=Math.min(6,...visible.map(d=>Number(d.horario_inicio?.slice(0,2)||6)))&&h<=Math.max(18,...visible.map(d=>Number(d.horario_fin?.slice(0,2)||18))));
 const first=hours[0]||6,rowHeight=64;
 const openDock=()=>setDock({nombre:'',almacen:'Principal',activo:true,horario_inicio:'06:00',horario_fin:'18:00',dias:[1,2,3,4,5],capacidad:33,duracion_min:90,margen_min:15,zona_horaria:'Europe/Madrid'});
 return <section className="pl-slots">{!compact&&<PageHead icon="truck" title="Planificación de muelles y horarios" description="Organiza la carga y descarga por almacén, controla capacidades y evita solapes.">{canEdit&&<><Button onClick={openDock}>Nuevo muelle</Button><Button variant="primary" disabled={!visible.some(d=>d.activo)} onClick={()=>newReservation()}>Reservar hueco</Button></>}</PageHead>}
 <p className="pl-muted">Horas en la zona de este dispositivo: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Se comprueba el horario local de cada muelle al reservar.</p>
 <div className="pl-filters"><Button onClick={()=>setDay(dayKey())}>Hoy</Button><Button aria-label="Periodo anterior" onClick={()=>{const d=new Date(`${day}T12:00`);d.setDate(d.getDate()-(view==='semana'?7:1));setDay(dayKey(d));}}>‹</Button><input aria-label="Fecha del cuadrante" type="date" value={day} onChange={e=>e.target.value&&setDay(e.target.value)}/><Button aria-label="Periodo siguiente" onClick={()=>{const d=new Date(`${day}T12:00`);d.setDate(d.getDate()+(view==='semana'?7:1));setDay(dayKey(d));}}>›</Button><select aria-label="Filtrar almacén" value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">Todos los almacenes</option>{[...new Set(docks.map(d=>d.almacen))].map(w=><option key={w}>{w}</option>)}</select><div className="pl-segment">{[['dia','Día'],['semana','Semana']].map(([id,l])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{l}</button>)}</div><Button onClick={()=>load().catch(e=>setError(e.message))}>Actualizar</Button></div>
 {!compact&&<Metrics items={[{label:'Reservas del periodo',value:filtered.length,icon:'clock',note:view==='dia'?'Vista diaria':'Siete días desde la fecha seleccionada'},{label:'Muelles activos',value:`${visible.filter(d=>d.activo).length} / ${visible.length}`,icon:'warehouse',tone:'blue'},{label:'Muelles con reservas',value:occupied,icon:'truck',note:'En el periodo seleccionado'},{label:'Solicitudes pendientes',value:requests.length,icon:'alert',tone:'amber'}]}/>}
 {error&&!draft&&!dock&&<p role="alert">{error}</p>}
 <div className="pl-workspace"><Panel title={view==='dia'?'Planning de muelles':'Cuadrante semanal'} icon="clock"><div className="pl-calendar-scroll">{view==='dia'?<div className="pl-calendar" style={{gridTemplateColumns:`64px repeat(${visible.length||1},minmax(190px,1fr))`}}><div className="pl-calendar-head">Hora</div>{visible.map(d=><div className="pl-calendar-head" key={d.id}><button onClick={()=>canEdit&&setDock(d)} disabled={!canEdit}>{d.nombre}</button><small>{d.almacen} · {d.activo?'Operativo':'Fuera de servicio'}</small></div>)}<div className="pl-time-column">{hours.map(h=><div key={h} style={{height:rowHeight}}>{String(h).padStart(2,'0')}:00</div>)}</div>{visible.map(d=><div className="pl-dock-column" key={d.id} style={{height:hours.length*rowHeight}}>{hours.map(h=><button key={h} className="pl-free-slot" style={{height:rowHeight}} disabled={!canEdit||!d.activo} aria-label={`Reservar ${d.nombre} a las ${h}:00`} onClick={()=>newReservation(d,h)}>+</button>)}{filtered.filter(b=>b.muelle_id===d.id).map(b=>{const start=new Date(b.inicio),end=new Date(b.fin),top=Math.max(0,(start.getHours()-first+start.getMinutes()/60)*rowHeight),height=Math.max(54,(end-start)/3600000*rowHeight-5);return <button className={`pl-booking pl-booking-${b.estado||b.tipo}`} key={b.id} style={{top,height}} onClick={()=>setSelected(b)}><strong>{b.numero||'Hueco reservado'}</strong><span>{b.origen} {b.destino&&`→ ${b.destino}`}</span><small>{b.colaborador||'Flota / transportista pendiente'}</small><small>{time(b.inicio)} – {time(b.fin)}</small><Badge value={b.estado||'pendiente'}/></button>;})}</div>)}</div>:<div className="pl-week">{Array.from({length:7},(_,i)=>{const date=new Date(`${day}T12:00`);date.setDate(date.getDate()+i);const key=dayKey(date);return <section key={key}><h3>{date.toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short'})}</h3>{visible.map(d=><div className="pl-week-dock" key={d.id}><strong>{d.nombre}</strong>{filtered.filter(b=>b.muelle_id===d.id&&dayKey(new Date(b.inicio))===key).map(b=><button className={`pl-booking pl-booking-${b.estado||b.tipo}`} key={b.id} onClick={()=>setSelected(b)}><strong>{time(b.inicio)}–{time(b.fin)}</strong><span>{b.numero||'Reserva'} · {b.destino}</span></button>)}{canEdit&&d.activo&&<button onClick={()=>newReservation(d,Number(d.horario_inicio.slice(0,2)),key)}>+ Reservar</button>}</div>)}</section>;})}</div>}</div>{!visible.length&&<Empty>Añade los muelles de tu almacén para comenzar.</Empty>}</Panel>
 <aside><Panel title="Solicitudes pendientes" icon="file">{requests.map(r=><article className="pl-side-item" key={r.id}><strong>{r.numero}</strong><p>{r.colaborador} · {r.destino}</p><small>{new Date(r.inicio).toLocaleString('es-ES')}</small>{canEdit&&<Button disabled={!visible.some(d=>d.activo)} onClick={()=>newReservation(undefined,9,day,r)}>Asignar hueco</Button>}</article>)}{!requests.length&&<Empty>No hay solicitudes pendientes.</Empty>}</Panel><Panel title="Capacidad y configuración" icon="warehouse">{visible.map(d=><article key={d.id} className="pl-side-item"><strong>{d.nombre}</strong><p>{d.capacidad} palets · {d.duracion_min} min por operación</p><small>{d.horario_inicio?.slice(0,5)}–{d.horario_fin?.slice(0,5)} · Margen {d.margen_min} min · {d.zona_horaria}</small>{canEdit&&<Button onClick={()=>setDock(d)}>Configurar</Button>}</article>)}</Panel></aside></div>
 {(draft||dock)&&<Modal title={dock?'Muelle y horario operativo':'Reservar hueco de carga / descarga'} onClose={()=>!busy&&(setDraft(null),setDock(null))}><form className="planner-form" onSubmit={save}><div className="planner-grid">{dock?<>{[['nombre','Nombre del muelle','text'],['almacen','Almacén','text'],['horario_inicio','Apertura','time'],['horario_fin','Cierre','time'],['capacidad','Capacidad en palets','number'],['duracion_min','Duración habitual (min)','number'],['margen_min','Margen entre reservas (min)','number']].map(([k,l,t])=><label key={k}>{l}<input required type={t} min="0" value={dock[k]} onChange={e=>setDock({...dock,[k]:t==='number'?Number(e.target.value):e.target.value})}/></label>)}<label>Zona horaria<select value={dock.zona_horaria} onChange={e=>setDock({...dock,zona_horaria:e.target.value})}>{['Europe/Madrid','Atlantic/Canary','Europe/Lisbon','Europe/Paris','UTC'].map(z=><option key={z}>{z}</option>)}</select></label><label>Estado<select value={String(dock.activo)} onChange={e=>setDock({...dock,activo:e.target.value==='true'})}><option value="true">Operativo</option><option value="false">Fuera de servicio</option></select></label><fieldset><legend>Días de apertura</legend>{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map((label,i)=><label className="pl-check-line" key={label}><input type="checkbox" checked={dock.dias.includes(i+1)} onChange={e=>setDock({...dock,dias:e.target.checked?[...dock.dias,i+1]:dock.dias.filter(d=>d!==i+1)})}/>{label}</label>)}</fieldset></>:<><label>Muelle<select value={draft.muelle_id} onChange={e=>setDraft({...draft,muelle_id:e.target.value})}>{docks.filter(d=>d.activo).map(d=><option key={d.id} value={d.id}>{d.almacen} · {d.nombre}</option>)}</select></label><label>Carga / pedido<select value={draft.pedido_id} onChange={e=>setDraft({...draft,pedido_id:e.target.value})}><option value="">Reserva sin pedido</option>{!orders.some(o=>o.id===draft.pedido_id)&&draft.pedido_id&&<option value={draft.pedido_id}>Carga de la solicitud</option>}{orders.map(o=><option key={o.id} value={o.id}>{o.numero} · {o.destino}</option>)}</select></label><label>Operación<select value={draft.tipo} onChange={e=>setDraft({...draft,tipo:e.target.value})}><option value="carga">Carga</option><option value="descarga">Descarga</option></select></label>{[['inicio','Inicio'],['fin','Fin']].map(([k,l])=><label key={k}>{l}<input required type="datetime-local" value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Palets previstos<input type="number" min="0" value={draft.palets} onChange={e=>setDraft({...draft,palets:e.target.value})}/></label><label>Notas<textarea maxLength={2000} value={draft.notas} onChange={e=>setDraft({...draft,notas:e.target.value})}/></label></>}</div>{error&&<p role="alert">{error}</p>}<Button type="submit" variant="primary" disabled={busy}>{busy?'Guardando…':'Guardar'}</Button></form></Modal>}
 {selected&&<Modal title={selected.numero||'Reserva de muelle'} onClose={()=>setSelected(null)}><p>{selected.almacen} · {selected.muelle}</p><p>{new Date(selected.inicio).toLocaleString('es-ES')} – {time(selected.fin)}</p><p>{selected.origen} → {selected.destino}</p><p>{selected.colaborador||'Sin proveedor externo'} · <Badge value={selected.estado||'pendiente'}/></p><p>{selected.notas}</p><div className="pl-action-row">{onOrder&&selected.pedido_id&&<Button onClick={()=>{onOrder(selected.pedido_id);setSelected(null);}}>Abrir carga</Button>}{canEdit&&<Button disabled={busy} onClick={()=>cancel(selected)}>Liberar hueco</Button>}</div>{error&&<p role="alert">{error}</p>}</Modal>}
 </section>;
}
