import {useCallback,useEffect,useState} from 'react';
import {plannerApi,getColaboradores} from '../services/api';
import {useAuth} from '../context/AuthContext';
import {Button,Modal} from '../ui';
import {PageHead,Panel,Metrics,Badge,Empty} from './PlannerUI';
const api=(path='',body,method='POST')=>plannerApi(`/vehiculos-autorizados${path}`,body?{method,body}:{});
export default function PlannerVehicles(){
 const {puedeEditar}=useAuth(),edit=puedeEditar('pedidos');
 const [rows,setRows]=useState([]),[agencies,setAgencies]=useState([]),[draft,setDraft]=useState(null),[selected,setSelected]=useState(null),[docs,setDocs]=useState([]),[file,setFile]=useState(null),[type,setType]=useState('itv'),[expiry,setExpiry]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const load=useCallback(async()=>setRows(await api()),[]);
 useEffect(()=>{load().catch(e=>setError(e.message));getColaboradores().then(d=>setAgencies(Array.isArray(d)?d:d.data||[])).catch(e=>setError(e.message));},[load]);
 async function run(fn){setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function open(v){setSelected(v);setFile(null);setDocs(await api(`/${v.id}/documentos`));}
 async function upload(e){e.preventDefault();run(async()=>{if(!file||file.size>3*1024*1024)throw new Error('Adjunta un PDF o una imagen de hasta 3 MB.');const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('No se pudo leer el archivo'));r.readAsDataURL(file);});await api(`/${selected.id}/documentos`,{tipo:type,nombre:file.name,file_mime:file.type,file_base64:base64,vencimiento:expiry||null});const updated=await api();setRows(updated);await open(updated.find(v=>v.id===selected.id));});}
 const filtered=rows.filter(v=>`${v.matricula} ${v.colaborador||''} ${v.marca} ${v.modelo}`.toLowerCase().includes(search.toLowerCase()));
 return <section><PageHead title="Vehículos autorizados" icon="truck" description="Revisa las matrículas, la documentación y el acceso de los transportistas al almacén.">{edit&&<Button variant="primary" onClick={()=>setDraft({matricula:'',tipo:'tractora',colaborador_id:'',marca:'',modelo:'',notas:''})}>+ Registrar vehículo</Button>}</PageHead><Metrics items={[{label:'Vehículos registrados',value:rows.length,icon:'truck'},{label:'Autorizados',value:rows.filter(v=>v.estado==='autorizado'&&!v.caducados).length,icon:'file'},{label:'Documentación caducada',value:rows.filter(v=>v.caducados>0).length,icon:'alert',tone:'red'},{label:'Pendientes de revisión',value:rows.filter(v=>v.estado==='pendiente').length,icon:'clock',tone:'amber'}]}/>{error&&<p role="alert">{error}</p>}<Panel title="Control de acceso y documentación" icon="truck"><div className="pl-filters"><input placeholder="Buscar matrícula, transportista o modelo…" aria-label="Buscar vehículos autorizados" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="planner-table"><table><thead><tr>{['Matrícula','Tipo','Transportista','Marca / modelo','Documentos','Estado','Acciones'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(v=><tr key={v.id}><td><strong>{v.matricula}</strong></td><td>{v.tipo}</td><td>{v.colaborador||'Flota propia / recogida'}</td><td>{v.marca} {v.modelo}</td><td>{v.documentos}{v.caducados>0&&<small>{v.caducados} caducados</small>}</td><td><Badge value={v.caducados?'incidencia':v.estado==='autorizado'?'lista':v.estado==='bloqueado'?'incidencia':'pendiente'}>{v.caducados?'Revisar vencimientos':v.estado}</Badge></td><td><Button disabled={busy} onClick={()=>run(()=>open(v))}>Ver ficha</Button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty>Registra los vehículos y revisa su documentación antes de autorizarlos.</Empty>}</Panel>
 {draft&&<Modal title="Registrar vehículo" onClose={()=>!busy&&setDraft(null)}><form className="planner-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api('',draft);setDraft(null);});}}><div className="planner-grid">{[['matricula','Matrícula'],['marca','Marca'],['modelo','Modelo']].map(([k,l])=><label key={k}>{l}<input required={k==='matricula'} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Tipo<select value={draft.tipo} onChange={e=>setDraft({...draft,tipo:e.target.value})}>{[['tractora','Tractora'],['remolque','Remolque'],['rigido','Rígido'],['furgoneta','Furgoneta'],['banera','Bañera'],['otro','Otro']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Transportista<select value={draft.colaborador_id} onChange={e=>setDraft({...draft,colaborador_id:e.target.value})}><option value="">Flota propia / recogida</option>{agencies.map(a=><option key={a.id} value={a.id}>{a.nombre}</option>)}</select></label><label>Observaciones<textarea value={draft.notas} onChange={e=>setDraft({...draft,notas:e.target.value})}/></label></div>{error&&<p role="alert">{error}</p>}<Button type="submit" variant="primary" disabled={busy}>Guardar vehículo</Button></form></Modal>}
 {selected&&<Modal title={`Vehículo · ${selected.matricula}`} onClose={()=>!busy&&setSelected(null)}><div className="planner-form"><p>{selected.colaborador||'Flota propia / recogida'} · {selected.tipo}</p>{docs.map(d=><div key={d.id}><Button onClick={()=>run(async()=>{const f=await api(`/${selected.id}/documentos/${d.id}`);const url=URL.createObjectURL(new Blob([Uint8Array.from(atob(f.file_base64),c=>c.charCodeAt(0))],{type:f.file_mime}));const a=document.createElement('a');a.href=url;a.download=f.nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>{d.nombre}</Button><small> {d.tipo} · {d.vencimiento?.slice(0,10)||'Sin vencimiento'}{!d.vigente?' · Versión anterior':''}</small></div>)}{edit&&<><form onSubmit={upload}><div className="planner-grid"><label>Tipo de documento<select value={type} onChange={e=>setType(e.target.value)}>{[['itv','ITV'],['seguro','Seguro'],['permiso_circulacion','Permiso de circulación'],['ficha_tecnica','Ficha técnica'],['autorizacion','Autorización de transporte'],['otro','Otro']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Vencimiento<input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label>Archivo PDF o imagen<input required type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><Button type="submit" disabled={busy||!file}>Adjuntar y solicitar revisión</Button></form><label>Observaciones de revisión<textarea value={selected.notas} onChange={e=>setSelected({...selected,notas:e.target.value})}/></label><div className="pl-action-row">{[['autorizado','Autorizar acceso'],['bloqueado','Bloquear acceso'],['pendiente','Dejar pendiente']].map(([estado,label])=><Button key={estado} disabled={busy} onClick={()=>run(async()=>{const v=await api(`/${selected.id}`,{version:selected.version,estado,notas:selected.notas},'PATCH');setSelected({...selected,...v});})}>{label}</Button>)}</div></>}{error&&<p role="alert">{error}</p>}</div></Modal>}
 </section>;
}
