import {useCallback,useEffect,useRef,useState} from 'react';
import {plannerApi} from '../services/api';
import {Modal,Button} from '../ui';
import {Panel,Empty,quantity} from './PlannerUI';
import './PlannerWms.css';
import PlannerAutomation from './PlannerAutomation';

const api=(path='',body)=>plannerApi(`/wms${path}`,body?{method:'POST',body}:{});
const day=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date());
const date=v=>v?new Date(v).toLocaleDateString('es-ES'):'Sin registrar';
const labels={ubicacion:'Nueva ubicación',asn:'Aviso de recepción',recibir:'Registrar recepción',cerrar_asn:'Cerrar recepción',calidad:'Control de calidad',trasladar:'Traslado / reposición',abrir_conteo:'Abrir conteo',confirmar_conteo:'Confirmar conteo',gtin:'Identificar artículo',packing:'Embalaje y SSCC',checkin:'Registrar llegada al muelle'};

export default function PlannerWms({articles=[],stock=[],preps=[],canEdit=false,onRefresh}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(null);
 const [query,setQuery]=useState(''),[proposal,setProposal]=useState(null),[method,setMethod]=useState('FEFO'),[article,setArticle]=useState('');
 const [code,setCode]=useState(''),[decoded,setDecoded]=useState(null),[label,setLabel]=useState(null),[bookings,setBookings]=useState([]);
 const [from,setFrom]=useState(day().slice(0,7)+'-01'),[to,setTo]=useState(day()),[kpis,setKpis]=useState(null);
 const pending=useRef(null),generation=useRef(0);
 const load=useCallback(async()=>{const result=await api();setData(result);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));return()=>{generation.current++;};},[load]);
 const open=(accion,values={})=>{setError('');pending.current=null;setForm({accion,...values});};
 const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function run(fn){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();await run(async()=>{const {opciones,...body}=form;const fingerprint=JSON.stringify(body);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,operacion:crypto.randomUUID()};await api('/accion',{...body,operacion:pending.current.operacion});setForm(null);pending.current=null;setNotice('Operación registrada.');setProposal(null);await Promise.all([load(),onRefresh?.()]);});}
 const locations=(data?.ubicaciones||[]).filter(x=>x.activo).map(x=>[x.id,`${x.almacen} · ${x.codigo}`]);
 const articleOptions=articles.filter(x=>x.activo).map(x=>[x.id,`${x.referencia} · ${x.descripcion}`]);
 const field=(k,title,type='text',optional=false)=><label key={k}>{title}<input required={!optional} type={type} step="0.001" min={type==='number'?'0':undefined} value={form[k]??''} onChange={e=>update(k,e.target.value)}/></label>;
 const select=(k,title,items)=><label key={k}>{title}<select required value={form[k]??''} onChange={e=>update(k,e.target.value)}><option value="">Seleccionar…</option>{items.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
 const reason=()=>field('motivo','Motivo / resultado de la revisión');
 const currentAsn=data?.recepciones.find(x=>x.id===form?.asn_id);
 const visibleStock=stock.filter(s=>`${s.referencia} ${s.almacen} ${s.ubicacion} ${s.lote}`.toLowerCase().includes(query.toLowerCase()));
 const lineFields=(kind)=>{const key=kind==='asn'?'articulo_id':'linea_id',options=kind==='asn'?articleOptions:(form.opciones||[]);return <><div>{(form.lineas||[]).map((l,i)=><div className="wms-line" key={i}><label>{kind==='asn'?'Artículo':'Mercancía'}<select required value={l[key]} onChange={e=>update('lineas',form.lineas.map((x,n)=>n===i?{...x,[key]:e.target.value}:x))}><option value="">Seleccionar…</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>Cantidad<input required type="number" min="0.001" step="0.001" value={l.cantidad} onChange={e=>update('lineas',form.lineas.map((x,n)=>n===i?{...x,cantidad:e.target.value}:x))}/></label><Button onClick={()=>update('lineas',form.lineas.filter((_,n)=>n!==i))}>Quitar</Button></div>)}</div><Button onClick={()=>update('lineas',[...(form.lineas||[]),{[key]:'',cantidad:1}])}>Añadir línea</Button></>;};
 return <div className="planner-wms">
 <p>Recepciones y calidad → ubicación → preparación → embalaje → carga. El stock histórico sin inspección conserva el estado «Sin revisión registrada».</p>
 {error&&!form&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!data?<Empty>Cargando procesos de almacén…</Empty>:<>
 <PlannerAutomation articles={articles} locations={data.ubicaciones} canEdit={canEdit} onRefresh={async()=>{await load();await onRefresh?.();}}/>
 <Panel title="Recepciones previstas (ASN)" icon="warehouse" actions={<Button disabled={!canEdit||busy} onClick={()=>open('asn',{lineas:[{articulo_id:'',cantidad:1}],fecha_prevista:day()})}>Nueva recepción</Button>}>
 <div className="planner-table"><table><thead><tr><th>Referencia / fecha</th><th>Previsto y recibido</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.recepciones.map(r=><tr key={r.id}><td>{r.referencia}<small>{date(r.fecha_prevista)}</small></td><td>{r.lineas.map(l=><div key={l.id}>{l.referencia}: {quantity(l.recibida)} / {quantity(l.prevista)} <strong>{l.recibida>l.prevista?'Exceso':l.recibida<l.prevista?'Falta por recibir':'Completo'}</strong></div>)}</td><td>{r.estado}</td><td>{r.estado!=='cerrada'&&<><Button disabled={!canEdit||busy} onClick={()=>open('recibir',{asn_id:r.id,linea_id:r.lineas[0]?.id,cantidad:'',ubicacion_id:''})}>Recibir mercancía</Button><Button disabled={!canEdit||busy} onClick={()=>open('cerrar_asn',{asn_id:r.id})}>Cerrar recepción</Button></>}</td></tr>)}</tbody></table></div>{!data.recepciones.length&&<Empty>Registra un aviso antes de recibir. Las discrepancias quedan conservadas al cerrar.</Empty>}<small>Hasta {data.limites.recepciones} recepciones recientes.</small>
 </Panel>
 <details><summary>Ubicaciones y códigos de artículo</summary><div className="wms-actions"><Button disabled={!canEdit||busy} onClick={()=>open('ubicacion',{almacen:'Principal'})}>Nueva ubicación</Button><Button disabled={!canEdit||busy} onClick={()=>open('gtin')}>Asignar GTIN-14</Button></div><div className="planner-table"><table><thead><tr><th>Almacén</th><th>Código</th><th>Zona</th><th>Pasillo / estantería / nivel</th></tr></thead><tbody>{data.ubicaciones.map(l=><tr key={l.id}><td>{l.almacen}</td><td>{l.codigo}</td><td>{l.zona}</td><td>{[l.pasillo,l.estanteria,l.nivel].filter(Boolean).join(' / ')||'—'}</td></tr>)}</tbody></table></div><small>Hasta {data.limites.ubicaciones} ubicaciones.</small></details>
 <Panel title="Calidad, traslados y conteos" icon="box"><input aria-label="Buscar lote en WMS" placeholder="Artículo, ubicación o lote…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="planner-table"><table><thead><tr><th>Artículo / lote</th><th>Ubicación</th><th>Cantidad / reservada</th><th>Calidad</th><th>Acciones</th></tr></thead><tbody>{visibleStock.map(s=><tr key={s.id}><td>{s.referencia}<small>{s.lote||'Sin lote'} · {date(s.caducidad)}</small></td><td>{s.almacen} / {s.ubicacion||'Sin ubicación'}</td><td>{quantity(s.cantidad)} / {quantity(s.reservado)} {s.unidad}</td><td>{s.calidad||'Sin revisión registrada'}</td><td><Button disabled={!canEdit||busy} onClick={()=>open('calidad',{existencia_id:s.id,version:s.version})}>Revisar</Button><Button disabled={!canEdit||busy} onClick={()=>open('trasladar',{existencia_id:s.id,version:s.version})}>Trasladar</Button><Button disabled={!canEdit||busy} onClick={()=>open('abrir_conteo',{existencia_id:s.id})}>Contar</Button></td></tr>)}</tbody></table></div><small>Coincide con el stock cargado en Almacén. Los movimientos respetan las reservas de cargas.</small>
 <h3>Conteos recientes</h3>{data.conteos.map(c=><div className="wms-count" key={c.id}><span>{c.referencia} · {c.ubicacion} · {c.lote||'Sin lote'}: sistema {quantity(c.cantidad_sistema)}, contado {c.cantidad_contada===null?'pendiente':quantity(c.cantidad_contada)} · {c.estado}</span>{c.estado==='pendiente'&&<Button disabled={!canEdit||busy} onClick={()=>open('confirmar_conteo',{conteo_id:c.id})}>Registrar conteo</Button>}</div>)}
 </Panel>
 <details><summary>Propuesta de picking FIFO / FEFO</summary><p>Solo lotes liberados y no caducados. Ordena existencias disponibles; revisa y reserva desde Preparación y expedición.</p><form className="wms-actions" onSubmit={e=>{e.preventDefault();const n=++generation.current;run(async()=>{setProposal(null);const result=await api(`/propuesta?articulo_id=${encodeURIComponent(article)}&metodo=${method}`);if(n===generation.current)setProposal(result);});}}><label>Artículo<select required value={article} onChange={e=>{setArticle(e.target.value);setProposal(null);generation.current++;}}><option value="">Seleccionar…</option>{articleOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Criterio<select value={method} onChange={e=>{setMethod(e.target.value);setProposal(null);generation.current++;}}><option>FEFO</option><option>FIFO</option></select></label><Button type="submit" disabled={busy}>Consultar propuesta</Button></form>{proposal&&<><p>{proposal.criterio} Cobertura: {proposal.cobertura}. Máximo {proposal.limite} lotes.</p><ol>{proposal.datos.map(s=><li key={s.id}>{s.almacen} / {s.ubicacion} · {s.lote||'Sin lote'} · {quantity(Number(s.cantidad)-Number(s.reservado))} {s.unidad} · Caducidad: {date(s.caducidad)} · Recepción: {date(s.recepcion_real_at)}</li>)}</ol></>}</details>
 <details><summary>Embalaje, SSCC y lectura GS1</summary><p>Introduce un SSCC de tu empresa. Se valida el dígito de control; no se asignan prefijos GS1 ni se certifica su titularidad.</p><label>Preparación para embalar<select aria-label="Preparación para embalar" value="" disabled={!canEdit||busy} onChange={e=>{const id=e.target.value;if(id)run(async()=>{const prep=await plannerApi(`/inventario/preparaciones/${id}`);open('packing',{preparacion_id:id,opciones:prep.lineas.map(l=>[l.id,`${l.referencia} · ${quantity(l.cantidad)} ${l.unidad}`]),lineas:[{linea_id:prep.lineas[0]?.id,cantidad:1}]});});}}><option value="">Seleccionar carga…</option>{preps.filter(p=>['preparando','lista'].includes(p.estado)).map(p=><option key={p.id} value={p.id}>{p.numero} · {p.destino}</option>)}</select></label>{data.packs.map(p=><div className="wms-count" key={p.id}><span>{p.numero} · SSCC {p.sscc}</span><Button disabled={busy} onClick={()=>run(async()=>setLabel(await api(`/packs/${p.id}/etiqueta`)))}>Ver etiqueta QR</Button></div>)}
 <form className="wms-actions" onSubmit={e=>{e.preventDefault();run(async()=>{setDecoded(null);setDecoded(await api('/gs1',{codigo:code}));});}}><label>Lectura GS1 (lector de teclado o manual)<input required value={code} onChange={e=>{setCode(e.target.value);setDecoded(null);}} placeholder="(01)…(10)…"/></label><Button type="submit" disabled={busy}>Interpretar código</Button></form>{decoded&&<dl>{Object.entries(decoded).map(([k,v])=><div key={k}><dt>{k==='caducidad_yymmdd'?'Caducidad GS1 AAMMDD (00 = fin de mes)':k}</dt><dd>{String(v)}</dd></div>)}</dl>}</details>
 <details><summary>Llegadas a muelle</summary><p>Selecciona una reserva de carga de ayer a los próximos siete días. El registro guarda la llegada efectiva; no sustituye la aceptación del transportista.</p><Button disabled={!canEdit||busy} onClick={()=>run(async()=>{const result=await plannerApi(`/reservas?${new URLSearchParams({desde:new Date(Date.now()-86400000).toISOString(),hasta:new Date(Date.now()+7*86400000).toISOString()})}`);setBookings(Array.isArray(result)?result:result.data||[]);open('checkin');})}>Registrar llegada</Button></details>
 <details><summary>Indicadores de almacén</summary><form className="wms-actions" onSubmit={e=>{e.preventDefault();run(async()=>{setKpis(null);setKpis(await api(`/kpis?desde=${from}&hasta=${to}`));});}}><label>Desde<input type="date" required value={from} onChange={e=>{setFrom(e.target.value);setKpis(null);}}/></label><label>Hasta<input type="date" required value={to} onChange={e=>{setTo(e.target.value);setKpis(null);}}/></label><Button disabled={busy} type="submit">Calcular</Button></form>{kpis&&<><p>{kpis.carga.definicion} Cobertura: {kpis.carga.cobertura}. Muestra: {kpis.carga.muestra} cargas.</p><p>Media: {kpis.carga.media_min==null?'No calculable':quantity(kpis.carga.media_min)+' min'} · Mediana: {kpis.carga.mediana_min==null?'No calculable':quantity(kpis.carga.mediana_min)+' min'} · P90: {kpis.carga.p90_min==null?'No calculable':quantity(kpis.carga.p90_min)+' min'}</p><p>{kpis.stock.definicion}</p><ul>{kpis.stock.datos.map(s=><li key={s.unidad}>{s.unidad}: {quantity(s.cantidad)} en stock / {quantity(s.reservado)} reservadas · {s.lotes_sin_revision} lotes sin revisión</li>)}</ul></>}</details>
 <details><summary>Trazabilidad de las últimas {data.movimientos.length} operaciones</summary><ul>{data.movimientos.map(m=><li key={m.operacion}>{new Date(m.created_at).toLocaleString('es-ES')} · {labels[m.tipo]||m.tipo} · {m.datos.motivo||'Registro operativo'} <small>Operación {m.operacion}</small></li>)}</ul><small>Últimas {data.limites.movimientos} operaciones; identificadores conservados para la auditoría.</small></details>
 </>}
 {form&&<Modal title={labels[form.accion]} onClose={()=>!busy&&setForm(null)}><form className="planner-form" onSubmit={save}><fieldset disabled={busy||!canEdit} className="wms-fields">
 {form.accion==='ubicacion'&&<div className="planner-grid">{[['almacen','Almacén'],['codigo','Código'],['zona','Zona'],['pasillo','Pasillo'],['estanteria','Estantería'],['nivel','Nivel']].map(([k,l],i)=>field(k,l,'text',i>1))}</div>}
 {form.accion==='asn'&&<>{field('referencia','Referencia del aviso')}{field('fecha_prevista','Fecha prevista','date')}{lineFields('asn')}</>}
 {form.accion==='recibir'&&<>{select('linea_id','Línea del aviso',currentAsn?.lineas.map(l=>[l.id,`${l.referencia}: ${l.recibida} / ${l.prevista}`])||[])}{select('ubicacion_id','Ubicación de recepción',locations)}<div className="planner-grid">{field('cantidad','Cantidad recibida','number')}{field('lote','Lote / serie','text',true)}{field('caducidad','Caducidad','date',true)}</div><p>Quedará pendiente de calidad. Un exceso se registra como discrepancia; no se oculta.</p></>}
 {form.accion==='cerrar_asn'&&<><p>Se conservarán las cantidades esperadas, recibidas y sus diferencias.</p>{reason()}</>}
 {form.accion==='calidad'&&<>{select('calidad','Resultado',[['liberado','Liberar para preparación'],['bloqueado','Bloquear mercancía']])}{reason()}</>}
 {form.accion==='trasladar'&&<>{select('ubicacion_id','Ubicación destino',locations)}{field('cantidad','Cantidad a trasladar','number')}{reason()}</>}
 {form.accion==='abrir_conteo'&&<p>Se guardará el stock actual como referencia. Si hay movimientos mientras se cuenta, será necesario abrir otro conteo.</p>}
 {form.accion==='confirmar_conteo'&&<>{field('cantidad','Cantidad física contada','number')}{reason()}</>}
 {form.accion==='gtin'&&<>{select('articulo_id','Artículo',articleOptions)}{field('gtin','GTIN de 14 dígitos')}</>}
 {form.accion==='packing'&&<>{field('sscc','SSCC de 18 dígitos')}{lineFields('packing')}</>}
 {form.accion==='checkin'&&<>{select('reserva_id','Reserva de carga',bookings.filter(b=>b.tipo==='carga'&&b.pedido_id).map(b=>[b.id,`${b.pedido_numero||b.numero||b.pedido_id} · ${b.muelle_nombre||b.muelle||''} · ${new Date(b.inicio).toLocaleString('es-ES')}`]))}<label>Lectura QR de llegada<input placeholder="TG-CHECKIN:…" value={form.codigo||''} onChange={e=>{const codigo=e.target.value.trim();setForm(f=>({...f,codigo,reserva_id:codigo.startsWith('TG-CHECKIN:')?codigo.slice(11):f.reserva_id}));}}/></label><Button disabled={!form.reserva_id||busy} onClick={()=>run(async()=>setLabel(await api(`/reservas/${encodeURIComponent(form.reserva_id)}/etiqueta`)))}>Ver QR de la reserva</Button></>}
 {error&&<p role="alert">{error}</p>}<Button type="submit" variant="primary" disabled={busy||!canEdit}>{busy?'Registrando…':'Confirmar operación'}</Button>
 </fieldset></form></Modal>}
 {label&&<Modal title={label.titulo||"Etiqueta de unidad logística"} onClose={()=>setLabel(null)}><div className="wms-label"><img src={label.qr} alt={label.titulo||`QR SSCC ${label.sscc}`}/><strong>{label.contenido}</strong><p>{label.aviso}</p><a href={label.qr} download={`etiqueta-${label.sscc||label.id}.png`}>Descargar etiqueta QR</a></div></Modal>}
 </div>;
}
