import {useCallback,useEffect,useRef,useState} from 'react';
import {plannerApi} from '../services/api';
import {Button,Modal} from '../ui';
import {Panel,quantity} from './PlannerUI';
const api=(path,body)=>plannerApi('/wms'+path,body?{method:'POST',body}:{});
export default function PlannerAutomation({articles,locations,canEdit,onRefresh}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(null),[notice,setNotice]=useState('');
 const [at,setAt]=useState(''),[docks,setDocks]=useState(null),[orders,setOrders]=useState([]),[order,setOrder]=useState(''),[occupied,setOccupied]=useState(null);
 const pending=useRef(null),generation=useRef(0);
 const load=useCallback(async()=>{const next=await api('/automatismos');if(!['reglas','reposiciones','conteos'].every(k=>Array.isArray(next?.[k])))throw Error('No se pudieron interpretar las propuestas de almacén. Actualiza e inténtalo de nuevo.');setData(next);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function run(fn){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function write(body){const fingerprint=JSON.stringify(body);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,operacion:crypto.randomUUID()};await api('/accion',{...body,operacion:pending.current.operacion});pending.current=null;setForm(null);setNotice('Operación registrada.');await load();await onRefresh?.();}
 const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 const field=(k,label,type='text')=><label>{label}<input required type={type} min={type==='number'?0:undefined} step={k==='conteo_dias'?1:'0.001'} value={form[k]??''} onChange={e=>update(k,e.target.value)}/></label>;
 async function reserve(dock,confirm=false){await plannerApi('/reservas',{method:'POST',body:{muelle_id:dock.id,pedido_id:order,inicio:new Date(at).toISOString(),tipo:'carga',confirmar_ocupado:confirm,notas:'Selección de propuesta por cola registrada'}});setOccupied(null);setDocks(null);setOrder('');setNotice('Muelle asignado.');await onRefresh?.();}
 return <Panel title="Reposición, conteos y propuestas de muelle" icon="warehouse">
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="wms-actions"><Button disabled={busy} onClick={()=>run(load)}>Actualizar propuestas</Button><Button disabled={!canEdit||busy} onClick={()=>setForm({accion:'regla_reposicion',minimo:'',objetivo:'',conteo_dias:30,activo:true})}>Nueva regla de ubicación</Button></div>
 {data&&<><p>{data.criterio}</p><details><summary>Reglas de reposición y conteo ({data.reglas.length})</summary>{data.reglas.map(r=><div className="wms-count" key={r.id}><span>{r.referencia} · {r.almacen}/{r.codigo} · Mínimo {quantity(r.minimo)}, objetivo {quantity(r.objetivo)} {r.unidad} · Conteo cada {r.conteo_dias} días · {r.activo?'Activa':'Inactiva'}</span><Button disabled={!canEdit||busy} onClick={()=>setForm({...r,accion:'regla_reposicion',motivo:''})}>Editar regla</Button></div>)}</details>
 <h3>Reposiciones propuestas</h3>{!data.reposiciones.length&&<p>Sin reposiciones pendientes según las reglas configuradas.</p>}{data.reposiciones.map(p=><div className="wms-count" key={p.regla_id}><div><strong>{p.referencia} → {p.almacen}/{p.destino}</strong><p>Disponible: {quantity(p.disponible)} · Objetivo: {quantity(p.objetivo)} {p.unidad}{p.faltante>0&&` · Falta stock de origen: ${quantity(p.faltante)}`}</p><ul>{p.movimientos.map(m=><li key={m.existencia_id}>{m.origen} · Lote {m.lote||'sin lote'}: {quantity(m.cantidad)} {p.unidad}</li>)}</ul></div><Button disabled={!canEdit||busy||!p.movimientos.length} onClick={()=>setForm({accion:'reponer_propuesta',regla_id:p.regla_id,huella:p.huella,descripcion:`${p.referencia} a ${p.destino}`,confirmado:false,motivo:''})}>Confirmar traslado físico</Button></div>)}
 <h3>Conteos por realizar</h3>{!data.conteos.length&&<p>Sin conteos pendientes según las reglas configuradas.</p>}{data.conteos.map(c=><div className="wms-count" key={c.existencia_id}><span>{c.referencia} · {c.ubicacion} · {c.lote||'Sin lote'} · Último conteo: {c.ultimo_conteo||'Sin registrar'}</span><Button disabled={!canEdit||busy} onClick={()=>run(()=>write({accion:'abrir_conteo',existencia_id:c.existencia_id}))}>Abrir conteo</Button></div>)}<small>Registra el resultado físico en «Calidad, traslados y conteos».</small></>}
 <details><summary>Sugerir muelle para una carga</summary><form className="wms-actions" onSubmit={e=>{e.preventDefault();const n=++generation.current;run(async()=>{setDocks(null);const [result,list]=await Promise.all([api('/muelles-propuestos?inicio='+encodeURIComponent(new Date(at).toISOString())),plannerApi('/solicitudes-hueco')]);if(n===generation.current){setDocks(result);setOrders(Array.isArray(list)?list:[]);}});}}><label>Llegada prevista (hora de este dispositivo)<input required type="datetime-local" value={at} onChange={e=>{setAt(e.target.value);setDocks(null);generation.current++;}}/></label><Button disabled={busy} type="submit">Consultar muelles</Button></form>
 {docks&&<><p>{docks.criterio}</p><label>Carga pendiente<select value={order} onChange={e=>setOrder(e.target.value)}><option value="">Seleccionar carga…</option>{orders.map(o=><option key={o.pedido_id} value={o.pedido_id}>{o.numero} · {o.destino}</option>)}</select></label>{!docks.datos.length&&<p>No hay muelles abiertos a esa hora.</p>}{docks.datos.map(d=><div className="wms-count" key={d.id}><span>{d.nombre} · {d.almacen} · {d.ocupado?'Camión cargando':'Sin carga en curso'} · Cola: {d.cola} · Mediana {d.mediana_min==null?'sin datos':quantity(d.mediana_min)+' min'} ({d.muestra} cargas)</span><Button disabled={!canEdit||busy||!order} onClick={()=>d.ocupado?setOccupied(d):run(()=>reserve(d))}>Asignar carga</Button></div>)}</>}
 </details>
 {occupied&&<Modal title="Camión cargando en muelle" onClose={()=>!busy&&setOccupied(null)}><p>Hay una carga en curso en {occupied.nombre}. La nueva carga quedará en la misma zona; no se interrumpe la anterior.</p><Button disabled={busy} onClick={()=>run(()=>reserve(occupied,true))}>Continuar con la asignación</Button></Modal>}
 {form&&<Modal title={form.accion==='regla_reposicion'?'Regla de ubicación':'Confirmar reposición'} onClose={()=>!busy&&setForm(null)}><form className="planner-form" onSubmit={e=>{e.preventDefault();run(()=>write(form));}}><fieldset className="wms-fields" disabled={busy||!canEdit}>
 {form.accion==='regla_reposicion'?<><label>Artículo<select required disabled={!!form.id} value={form.articulo_id||''} onChange={e=>update('articulo_id',e.target.value)}><option value="">Seleccionar…</option>{articles.filter(a=>a.activo).map(a=><option key={a.id} value={a.id}>{a.referencia}</option>)}</select></label><label>Ubicación de destino<select required disabled={!!form.id} value={form.ubicacion_id||''} onChange={e=>update('ubicacion_id',e.target.value)}><option value="">Seleccionar…</option>{locations.filter(l=>l.activo).map(l=><option key={l.id} value={l.id}>{l.almacen}/{l.codigo}</option>)}</select></label><div className="planner-grid">{field('minimo','Mínimo disponible','number')}{field('objetivo','Cantidad objetivo','number')}{field('conteo_dias','Conteo cada (días)','number')}</div><label><input type="checkbox" checked={form.activo} onChange={e=>update('activo',e.target.checked)}/>Regla activa</label></>:<><p>{form.descripcion}</p><label><input type="checkbox" required checked={form.confirmado} onChange={e=>update('confirmado',e.target.checked)}/>He realizado los traslados indicados</label></>}
 {field('motivo','Motivo / observaciones')}{error&&<p role="alert">{error}</p>}<Button type="submit" variant="primary">Guardar</Button></fieldset></form></Modal>}
 </Panel>;
}
