import React,{useEffect,useState} from 'react';
import './AdminExtensions.css';
const labels={planned:'Planificada',development:'En desarrollo',sandbox_verified:'Ensayo verificado',pilot:'Piloto',production_ready:'Producción verificada',degraded:'Degradada'};
const criteria={authentication:'Autenticación',roundtrip:'Envío y respuesta',idempotence:'Idempotencia',errors_retries:'Errores y reintentos',tenant_isolation:'Aislamiento de empresa',logs:'Registros',monitoring:'Monitorización',tests:'Pruebas',healthcheck:'Prueba real de conexión'};
const box={background:'var(--sa-panel)',color:'var(--sa-text)',border:'1px solid var(--sa-border)',borderRadius:8,padding:14,minWidth:0};
const input={width:'100%',boxSizing:'border-box',marginTop:5,padding:9,border:'1px solid var(--sa-border)',borderRadius:6,background:'var(--sa-input)',color:'var(--sa-text)'};
export default function IntegrationRegistryAdmin({saFetchFn,empresas=[]}){
 const [company,setCompany]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false),[reload,setReload]=useState(0),[busy,setBusy]=useState(false);
 const [future,setFuture]=useState('');
 const [form,setForm]=useState({}),[evidence,setEvidence]=useState({criterion:'tests',reference:'',passed:true});
 useEffect(()=>{let active=true;setLoading(true);setData(null);setSelected(null);saFetchFn('/integraciones/registry'+(company?'?empresa_id='+company:'')).then(r=>{if(active){setData(r);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[company,reload,saFetchFn]);
 const choose=row=>{setSelected(row);setForm({state:row.state,environment:row.environment,api_version:row.api_version});setEvidence({criterion:'tests',reference:'',passed:true});};
 async function save(event){event.preventDefault();setBusy(true);setError('');try{await saFetchFn('/integraciones/registry/'+selected.provider,{method:'PUT',body:{...form,empresa_id:company||null,revision:selected.revision,...(evidence.reference.trim()?{evidence}: {})}});setReload(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="sa-extension" style={box}><h3>Registro de integraciones</h3><p>El estado exige evidencias de la empresa, entorno y versión seleccionados. Una clave guardada no acredita una integración lista.</p>
 <label>Ámbito<select style={input} value={company} onChange={e=>setCompany(e.target.value)} disabled={busy}><option value="">Plataforma · sin acceso a datos de empresas</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.nombre}</option>)}</select></label>
 {error&&<p role="alert" style={{color:'var(--sa-danger,#b91c1c)'}}>{error}</p>}{loading&&<p role="status">Cargando registro…</p>}
 {data&&<div style={{overflowX:'auto',marginTop:14}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Proveedor','Estado efectivo','Salud','Última prueba','Versión API','Acción'].map(x=><th key={x} style={{padding:8,textAlign:'left'}}>{x}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.provider}><td style={{padding:8}}>{r.label}</td><td>{labels[r.effective_state]}</td><td>{({not_tested:'Sin prueba',stale:'Caducada',healthy:'Correcta',failed:'Fallida'})[r.health]}</td><td>{r.last_test?new Date(r.last_test).toLocaleString('es-ES'):'Sin prueba'}</td><td>{r.api_version}</td><td><button type="button" disabled={busy} onClick={()=>choose(r)}>Revisar {r.label}</button></td></tr>)}</tbody></table></div>}
 <div style={{marginTop:14}}><label>Futura integración · identificador<input style={input} value={future} placeholder="proveedor_nuevo" onChange={e=>setFuture(e.target.value)}/></label><button type="button" disabled={busy||!data||!/^[a-z][a-z0-9_]{1,47}$/.test(future)} onClick={()=>choose(data.rows.find(r=>r.provider===future)||{provider:future,label:future,state:'planned',environment:'sandbox',api_version:'unspecified',revision:0,missing:data.criteria,evidence:[]})}>Preparar registro</button></div>
 {selected&&<form onSubmit={save} style={{...box,marginTop:16}}><h4>{selected.label} · revisión {selected.revision}</h4><p>Último error: {selected.last_error||'Sin error registrado'}</p><p>Faltan: {selected.missing.map(x=>criteria[x]||x).join(', ')||'Ningún criterio pendiente'}</p>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}><label>Estado solicitado<select style={input} value={form.state} onChange={e=>setForm({...form,state:e.target.value})}>{data.states.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Entorno<select style={input} value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}><option value="sandbox">Ensayo</option><option value="production">Producción</option></select></label><label>Versión API<input style={input} maxLength={80} required value={form.api_version} onChange={e=>setForm({...form,api_version:e.target.value})}/></label></div>
 <h4>Añadir evidencia verificada por el administrador</h4><p>No introduzcas claves ni datos de clientes. Referencia el acta o prueba reproducible. No se ejecuta una prueba por escribir aquí. La salud solo se registra desde «Probar» en la configuración real del proveedor.</p>
 <label>Criterio<select style={input} value={evidence.criterion} onChange={e=>setEvidence({...evidence,criterion:e.target.value})}>{data.criteria.filter(c=>c!=='healthcheck').map(c=><option key={c} value={c}>{criteria[c]}</option>)}</select></label><label>Referencia de evidencia (opcional)<input style={input} maxLength={1000} value={evidence.reference} onChange={e=>setEvidence({...evidence,reference:e.target.value})}/></label><label>Resultado<select style={input} value={String(evidence.passed)} onChange={e=>setEvidence({...evidence,passed:e.target.value==='true'})}><option value="true">Superada, verificada por mí</option><option value="false">Fallida</option></select></label><button type="submit" disabled={busy} style={{marginTop:12}}>{busy?'Guardando…':'Guardar revisión'}</button>
 <details><summary>Historial auditable ({selected.evidence.length})</summary><ul>{selected.evidence.map(e=><li key={e.id}>{new Date(e.created_at).toLocaleString('es-ES')} · {e.source} · {criteria[e.criterion]||e.kind}: {e.reference} {e.passed===true?'· Superada':e.passed===false?'· Fallida':''}</li>)}</ul></details></form>}
 </section>;
}
