import React,{useEffect,useState} from 'react';
import './AdminExtensions.css';
import {MODULOS_PERM} from './Usuarios';
const field={display:'grid',gap:5,minWidth:0},grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},panel={background:'var(--sa-panel)',color:'var(--sa-text)',border:'1px solid var(--sa-border)',padding:16,borderRadius:8,marginBottom:16};
export default function MultiCompanyAdmin({saFetchFn}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[group,setGroup]=useState({nombre:'',empresas:[]}),[user,setUser]=useState(''),[company,setCompany]=useState(''),[member,setMember]=useState(null),[refs,setRefs]=useState({}),[search,setSearch]=useState('');
 useEffect(()=>{let active=true;saFetchFn('/multiempresas').then(r=>{if(active){setData(r);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[saFetchFn,reload]);
 useEffect(()=>{if(!data||!user||!company){setMember(null);return;}setMember(data.members.find(m=>m.usuario_id===user&&m.empresa_id===company)||{usuario_id:user,empresa_id:company,rol:'visualizador',permisos:{},activo:true,bi_consolidado:false,revision:0});},[data,user,company]);
 useEffect(()=>{let active=true;setRefs({});if(company)saFetchFn('/multiempresas/referencias?empresa_id='+company+'&q='+encodeURIComponent(search)).then(r=>{if(active)setRefs(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[company,search,saFetchFn]);
 async function save(path,method,body){setBusy(true);setError('');try{await saFetchFn(path,{method,body});setReload(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 function permission(id,value){const rules={...(member.permisos?.modulos||member.permisos||{})};if(value==='inherit')delete rules[id];else rules[id]={ver:value!=='none',editar:value==='write'};setMember({...member,permisos:{modulos:rules}});}
 return <section className="sa-extension"><h2>Grupos y acceso multiempresa</h2><p>Un grupo no concede acceso. Cada usuario necesita membresía, rol y permisos en cada sociedad. Los documentos y la numeración permanecen separados.</p>{error&&<p role="alert">{error}</p>}{!data?<p role="status">Cargando membresías…</p>:<>
 <form style={panel} onSubmit={e=>{e.preventDefault();save('/multiempresas/grupos','POST',group);}}><h3>Grupo empresarial</h3><div style={grid}><label style={field}>Grupo<select value={group.id||''} onChange={e=>setGroup(data.groups.find(g=>g.id===e.target.value)||{nombre:'',empresas:[]})}><option value="">Crear grupo</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.nombre}</option>)}</select></label><label style={field}>Nombre<input required maxLength={120} value={group.nombre} onChange={e=>setGroup({...group,nombre:e.target.value})}/></label></div><fieldset disabled={busy}><legend>Sociedades del grupo</legend><div style={grid}>{data.companies.map(c=><label key={c.id}><input type="checkbox" checked={group.empresas.includes(c.id)} onChange={e=>setGroup({...group,empresas:e.target.checked?[...group.empresas,c.id]:group.empresas.filter(id=>id!==c.id)})}/> {c.nombre}</label>)}</div></fieldset><button disabled={busy||!group.empresas.length}>Guardar grupo</button></form>
 <form style={panel} onSubmit={e=>{e.preventDefault();save('/multiempresas/membresias','PUT',member);}}><h3>Acceso de un usuario existente</h3><div style={grid}><label style={field}>Usuario<select value={user} disabled={busy} onChange={e=>setUser(e.target.value)}><option value="">Seleccionar</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.nombre} · {u.email}</option>)}</select></label><label style={field}>Empresa<select value={company} disabled={busy} onChange={e=>setCompany(e.target.value)}><option value="">Seleccionar</option>{data.companies.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label></div>
 {member&&<fieldset disabled={busy}><legend>Membresía · revisión {member.revision}</legend><div style={grid}><label style={field}>Rol<select value={member.rol} onChange={e=>setMember({...member,rol:e.target.value,permisos:{},bi_consolidado:false})}>{data.roles.map(r=><option key={r} value={r}>{r}</option>)}</select></label><label><input type="checkbox" checked={member.activo} onChange={e=>setMember({...member,activo:e.target.checked})}/> Acceso activo</label><label><input type="checkbox" checked={member.bi_consolidado} disabled={!['gerente','contable'].includes(member.rol)} onChange={e=>setMember({...member,bi_consolidado:e.target.checked})}/> Permitir BI del grupo (también requiere acceso en las demás sociedades)</label></div>
 {['cliente','chofer','colaborador'].includes(member.rol)&&<div><label style={field}>Buscar ficha en esta empresa<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label style={field}>Ficha vinculada (hasta 100 coincidencias)<select required value={member[member.rol+'_id']||''} onChange={e=>setMember({...member,[member.rol+'_id']:e.target.value})}><option value="">Seleccionar ficha</option>{(refs[member.rol]||[]).map(r=><option key={r.id} value={r.id}>{r.nombre}</option>)}</select></label></div>}
 <details><summary>Permisos específicos de esta empresa</summary><p>El rol y el plan siguen limitando las capacidades del programa.</p><div style={grid}>{MODULOS_PERM.map(m=>{const rule=(member.permisos?.modulos||member.permisos||{})[m.id];return <label key={m.id} style={field}>{m.label}<select value={!rule?'inherit':rule.editar?'write':rule.ver?'read':'none'} onChange={e=>permission(m.id,e.target.value)}><option value="inherit">Heredar del rol</option><option value="none">Sin acceso</option><option value="read">Consultar</option><option value="write">Consultar y editar</option></select></label>;})}</div></details><button type="submit" disabled={busy}>{busy?'Guardando…':'Guardar membresía'}</button></fieldset>}</form>
 </>}</section>;
}
