import {useCallback,useEffect,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {resolveApiBase} from '../utils/serverConfig';
import {Button,Modal} from '../ui';
import SupportInbox from '../components/SupportInbox';
import '../planner/planner.css';
import logo from '../assets/brand/transgest_logo_white.svg';
async function api(path,options={}){const res=await fetch(`${resolveApiBase()}/api/v1/supplier-app${path}`,{method:options.method||'GET',headers:{Authorization:`Bearer ${localStorage.getItem('tms_token')||''}`,'Content-Type':'application/json'},...(options.body?{body:JSON.stringify(options.body)}:{})});const data=await res.json();if(!res.ok)throw new Error(data.error||'No se pudo completar la operación');return data;}
export default function SupplierApp(){
 const {user,logout}=useAuth();const [slot,setSlot]=useState(null),[slotData,setSlotData]=useState(null),[slotDraft,setSlotDraft]=useState({inicio:'',fin:'',notas:''});const planner=user.productos?.includes('planner');const [docOrder,setDocOrder]=useState(null),[docs,setDocs]=useState([]),[docFile,setDocFile]=useState(null);const [drivers,setDrivers]=useState([]),[driver,setDriver]=useState(null);const [orders,setOrders]=useState([]),[vehicles,setVehicles]=useState([]),[draft,setDraft]=useState(null),[error,setError]=useState(''),[support,setSupport]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [o,v]=await Promise.all([api('/pedidos'),api('/vehiculos')]);setOrders(o);setVehicles(v);if(user.rol==='colaborador')setDrivers(await api('/conductores'));},[user.rol]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 async function open(order){setBusy(true);try{const data=await api(`/pedidos/${order.id}/acceso`,{method:'POST'});window.location.assign(`${resolveApiBase()}/api/v1${data.path}`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function documents(o){setError('');setDocFile(null);try{setDocs(await api(`/pedidos/${o.id}/documentos`));setDocOrder(o);}catch(e){setError(e.message);}}
 async function uploadDoc(e){e.preventDefault();if(!docFile)return;setBusy(true);setError('');try{if(docFile.size>3*1024*1024)throw new Error('El archivo supera los 3 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('No se pudo leer el archivo'));reader.readAsDataURL(docFile);});await api(`/pedidos/${docOrder.id}/documentos`,{method:'POST',body:{nombre:docFile.name,file_mime:docFile.type,file_base64:data,tipo:'albaran_colaborador'}});setDocFile(null);setDocs(await api(`/pedidos/${docOrder.id}/documentos`));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function downloadDoc(d){try{const file=await api(`/pedidos/${docOrder.id}/documentos/${d.id}`);const bytes=Uint8Array.from(atob(file.file_base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:file.file_mime}));const a=document.createElement('a');a.href=url;a.download=file.nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e.message);}}
 async function openSlot(o){setError('');setBusy(true);try{const data=await api(`/pedidos/${o.id}/hueco`);setSlotData(data);setSlotDraft({inicio:'',fin:'',notas:''});setSlot(o);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function requestSlot(e){e.preventDefault();setBusy(true);setError('');try{await api(`/pedidos/${slot.id}/hueco`,{method:'POST',body:{...slotDraft,inicio:new Date(slotDraft.inicio).toISOString(),fin:new Date(slotDraft.fin).toISOString()}});setSlotData(await api(`/pedidos/${slot.id}/hueco`));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function departureNote(o){setError('');try{const file=await api(`/pedidos/${o.id}/albaran-salida`);const url=URL.createObjectURL(new Blob([Uint8Array.from(atob(file.file_base64),c=>c.charCodeAt(0))],{type:file.file_mime}));const a=document.createElement('a');a.href=url;a.download=file.nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e.message);}}
 async function save(e){e.preventDefault();setBusy(true);try{await api(driver?'/conductores':'/vehiculos',{method:'POST',body:driver||draft});setDraft(null);setDriver(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="planner-app"><header className="planner-header"><img src={logo} alt="TransGest"/><strong>{user.nombre}</strong><Button onClick={()=>setSupport(true)}>Soporte</Button><Button onClick={logout}>Salir</Button></header><section className="planner-loads"><h1>{user.rol==='chofer'?'Mis viajes':'Portal del colaborador'}</h1><p>Consulta tus viajes, confirma las cargas, actualiza su estado y adjunta los albaranes.</p>{error&&<p role="alert">{error}</p>}
 <Button onClick={()=>load().catch(e=>setError(e.message))}>Actualizar</Button><div className="planner-grid">{orders.map(o=><article key={o.id} className="planner-stop"><h2>{o.numero}</h2><p>{o.origen} → {o.destino}</p><p>{o.fecha_carga?.slice(0,10)} · {o.estado}</p><p>{o.matricula_colaborador||'Matrícula pendiente'}</p>{user.rol==='colaborador'&&<label>Asignar conductor<select className="tgui-select" defaultValue="" onChange={async e=>{if(!e.target.value)return;try{await api(`/pedidos/${o.id}/conductor`,{method:'POST',body:{usuario_id:e.target.value}});await load();}catch(err){setError(err.message);}}}><option value="">{o.conductor_colaborador||'Selecciona conductor'}</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.nombre}</option>)}</select></label>}<Button disabled={busy||['entregado','facturado','cancelado'].includes(o.estado)} onClick={()=>open(o)}>Abrir viaje / confirmar</Button><Button onClick={()=>documents(o)}>Albaranes / POD</Button>{planner&&<><Button disabled={busy} onClick={()=>openSlot(o)}>Hueco de carga</Button><Button onClick={()=>departureNote(o)}>Albarán de salida</Button></>}</article>)}</div>{!orders.length&&<p>No hay viajes asignados.</p>}
 <h2>Vehículos del proveedor</h2>{vehicles.map(v=><p key={v.id}>{v.matricula} · {v.tipo}</p>)}{user.rol==='colaborador'&&<Button onClick={()=>setDraft({matricula:'',tipo:'tractora'})}>Añadir vehículo</Button>}{user.rol==='colaborador'&&<><h2>Conductores</h2>{drivers.map(d=><p key={d.id}>{d.nombre} · {d.activo?'Cuenta activa':'Invitación pendiente'}</p>)}<Button onClick={()=>setDriver({nombre:'',email:''})}>Invitar conductor</Button></>}</section>
 {slot&&<Modal title={`Hueco de carga · ${slot.numero}`} onClose={()=>!busy&&setSlot(null)}>{slotData?.reservas.map(r=><div key={r.id}><h3>{r.almacen} · {r.muelle}</h3><p>{new Date(r.inicio).toLocaleString('es-ES',{timeZone:r.zona_horaria})} — {new Date(r.fin).toLocaleTimeString('es-ES',{timeZone:r.zona_horaria})} ({r.zona_horaria})</p></div>)}{slotData?.solicitudes.map(r=><p key={r.id}>{new Date(r.inicio).toLocaleString('es-ES')} · {r.estado}</p>)}{user.rol==='colaborador'&&!slotData?.reservas.length&&!slotData?.solicitudes.some(r=>r.estado==='pendiente')&&<form onSubmit={requestSlot}><p>La solicitud queda pendiente hasta que el almacén asigne un muelle. Acepta primero la carga.</p>{[['inicio','Inicio deseado'],['fin','Fin deseado']].map(([k,label])=><label key={k}>{label}<input className="tgui-input" type="datetime-local" required value={slotDraft[k]} onChange={e=>setSlotDraft({...slotDraft,[k]:e.target.value})}/></label>)}<label>Observaciones<textarea className="tgui-input" maxLength={2000} value={slotDraft.notas} onChange={e=>setSlotDraft({...slotDraft,notas:e.target.value})}/></label><Button type="submit" disabled={busy}>Solicitar hueco</Button></form>}{error&&<p role="alert">{error}</p>}</Modal>}
 {docOrder&&<Modal title={`Albaranes · ${docOrder.numero}`} onClose={()=>!busy&&setDocOrder(null)}><p>Los albaranes pueden adjuntarse también después de la entrega.</p>{docs.map(d=><p key={d.id}><Button onClick={()=>downloadDoc(d)}>{d.nombre}</Button></p>)}{!docs.length&&<p>No hay albaranes.</p>}{docOrder.estado!=='cancelado'&&<form onSubmit={uploadDoc}><label>Archivo PDF o imagen (máximo 3 MB)<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required onChange={e=>setDocFile(e.target.files?.[0]||null)}/></label><Button type="submit" disabled={busy||!docFile}>Adjuntar albarán</Button></form>}{error&&<p role="alert">{error}</p>}</Modal>}
 {driver&&<Modal title="Invitar conductor del proveedor" onClose={()=>!busy&&setDriver(null)}><form onSubmit={save}>{[['nombre','Nombre'],['email','Email']].map(([k,l])=><label key={k}>{l}<input required type={k==='email'?'email':'text'} className="tgui-input" value={driver[k]} onChange={e=>setDriver({...driver,[k]:e.target.value})}/></label>)}{error&&<p role="alert">{error}</p>}<Button type="submit" disabled={busy}>Enviar invitación</Button></form></Modal>}
 {support&&<SupportInbox onClose={()=>setSupport(false)}/>}{draft&&<Modal title="Nuevo vehículo" onClose={()=>!busy&&setDraft(null)}><form onSubmit={save}><label>Matrícula<input required className="tgui-input" maxLength={20} value={draft.matricula} onChange={e=>setDraft({...draft,matricula:e.target.value})}/></label><label>Tipo<select className="tgui-select" value={draft.tipo} onChange={e=>setDraft({...draft,tipo:e.target.value})}>{['tractora','remolque','rigido','furgoneta'].map(t=><option key={t}>{t}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<Button type="submit" disabled={busy}>Guardar</Button></form></Modal>}</main>;
}
