import React,{useState,useEffect} from 'react';
import TransportShipmentEditor from './TransportShipmentEditor';
import OperationSignature from './driver/OperationSignature';
import {adjuntarDecaExterno,generarPedidoDocumentoControl,descargarArchivoProtegido,getFirmasOperacion,anularFirmaOperacion,guardarFirmaEntrega} from '../services/api';
export default function TransportDocumentVersions({pedidoId,data,onChange}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[native,setNative]=useState(false);
 const [signatures,setSignatures]=useState([]);
 const [shipment,setShipment]=useState('');
 const [correction,setCorrection]=useState(null);
 useEffect(()=>{let live=true;getFirmasOperacion(pedidoId).then(v=>{if(live)setSignatures(v);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[pedidoId]);
 const consolidated=shipment==='consolidado';
 const versions=data?.versiones||[],shipments=data?.envios||[],scope=shipment||(shipments.length===1?shipments[0].id:null),external=versions.some(v=>v.estado==='activa'&&v.source==='external'&&v.envio_id===scope);
 async function run(fn){setBusy(true);setError('');try{const d=await fn();if(d)onChange(d);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(file){if(!file)return;if(file.size>5*1024*1024){setError('El PDF no puede superar 5 MB.');return;}await run(async()=>{const pdf=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});return adjuntarDecaExterno(pedidoId,{pdf_base64:pdf,pdf_nativo:native,motivo:reason,envio_id:scope});});}
 return <section aria-label="Originales y versiones del DeCA" style={{padding:12,border:'1px solid var(--border)',borderRadius:10,marginBlock:12}}>
  <strong>Originales y versiones del DeCA</strong><p>Disponible antes del transporte. Cada cambio crea una nueva versión; los originales y sus QR se conservan.</p>
  {!shipments.length&&!versions.length&&<TransportShipmentEditor pedidoId={pedidoId} points={data?.puntos_envio||[]} onChange={onChange}/>}
  {shipments.length>1&&<label>Envío<select value={shipment} onChange={e=>setShipment(e.target.value)}><option value="">Selecciona un envío</option>{data?.consolidacion_permitida&&<option value="consolidado">Todos los envíos · DeCA consolidado</option>}{shipments.map((s,i)=><option key={s.id} value={s.id}>{s.referencia||`Envío ${i+1}`}</option>)}</select></label>}
  <label>Motivo de emisión o sustitución<input value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box'}}/></label>
  <div style={{display:'flex',gap:10,flexWrap:'wrap',marginBlock:10}}><button disabled={busy||external||(shipments.length>1&&!scope)} onClick={()=>run(()=>generarPedidoDocumentoControl(pedidoId,{motivo:reason,envio_id:consolidated?null:scope,consolidado:consolidated}))}>Generar versión TransGest</button><label style={{display:'flex',alignItems:'center',gap:8}}><input type="checkbox" checked={native} onChange={e=>setNative(e.target.checked)}/>El PDF del cargador es digital nativo, no un escaneo</label><label>Adjuntar original del cargador (PDF, hasta 5 MB)<input type="file" accept="application/pdf,.pdf" disabled={busy||!native||consolidated||(shipments.length>1&&!scope)} onChange={e=>{upload(e.target.files[0]);e.target.value='';}}/></label></div>
  {external&&<p>Se utiliza el original del cargador. Para corregirlo, adjunta su nueva versión.</p>}{error&&<p role="alert">{error}</p>}
  <ul>{versions.map(v=><li key={v.id} style={{marginBlock:8,overflowWrap:'anywhere'}}>Versión {v.version} · {v.source==='external'?'Cargador':'TransGest'} · {v.estado} · {new Date(v.created_at).toLocaleString('es-ES')} <button disabled={busy} onClick={()=>run(async()=>{await descargarArchivoProtegido(`/pedidos/${pedidoId}/documento-control-digital/versiones/${v.id}/pdf`,v.filename);})}>Descargar original</button><details><summary>Integridad y motivo</summary><p>{v.reason}</p><p>SHA256: {v.pdf_hash}</p></details></li>)}</ul>
  <details><summary>Justificantes de carga y entrega ({signatures.length})</summary><ul>{signatures.map(s=><li key={s.id} style={{marginBlock:10}}>{s.operacion} · {s.identidad.nombre} {s.identidad.apellidos} · {s.anulacion?'Anulada':'Firmada'} <button disabled={busy} onClick={()=>run(async()=>{await descargarArchivoProtegido(`/pedidos/${pedidoId}/firma/${s.id}/justificante.pdf`,'justificante.pdf');})}>Descargar justificante</button>{!s.anulacion&&<button disabled={busy||!reason.trim()} onClick={()=>run(async()=>{await anularFirmaOperacion(pedidoId,s.id,reason);setSignatures(await getFirmasOperacion(pedidoId));})}>Anular con el motivo indicado</button>}{s.anulacion&&<><p>{s.anulacion}</p>{!signatures.some(v=>v.replaces_id===s.id)&&<button disabled={busy} onClick={()=>setCorrection(s)}>Corregir firma</button>}</>}</li>)}</ul><p>La anulación conserva la evidencia original. La corrección requiere una nueva revisión y firma, sin reabrir la operación física.</p></details>
  {correction&&<OperationSignature pedido={{id:pedidoId}} paradaId={correction.parada_id} correctionId={correction.id} title="Corregir firma de conformidad" onCancel={()=>setCorrection(null)} onFirma={async(image,name,evidence)=>{await guardarFirmaEntrega(pedidoId,{...evidence,firma_destinatario:image});setSignatures(await getFirmasOperacion(pedidoId));setCorrection(null);}}/>}
  <button disabled={busy} onClick={()=>run(async()=>{await descargarArchivoProtegido(`/pedidos/${pedidoId}/expediente-transporte.zip`,'expediente-transporte.zip');})}>Descargar expediente completo</button>
 </section>;
}
