import React,{useState,useEffect} from 'react';
import TransportShipmentEditor from './TransportShipmentEditor';
import OperationSignature from './driver/OperationSignature';
import './TransportDocumentVersions.css';
import {adjuntarDecaExterno,generarPedidoDocumentoControl,descargarArchivoProtegido,getFirmasOperacion,anularFirmaOperacion,guardarFirmaEntrega} from '../services/api';

export default function TransportDocumentVersions({pedidoId,data,onChange}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[native,setNative]=useState(false);
 const [signatures,setSignatures]=useState([]),[shipment,setShipment]=useState(''),[correction,setCorrection]=useState(null);
 useEffect(()=>{let live=true;getFirmasOperacion(pedidoId).then(v=>{if(live)setSignatures(v);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[pedidoId]);
 const consolidated=shipment==='consolidado';
 const versions=data?.versiones||[],shipments=data?.envios||[],scope=shipment||(shipments.length===1?shipments[0].id:null);
 const external=versions.some(v=>v.estado==='activa'&&v.source==='external'&&v.envio_id===scope);
 const needsReason=versions.some(v=>v.estado==='activa'&&(consolidated?!v.envio_id:v.envio_id===scope));
 const disabled=busy||(shipments.length>1&&!scope);
 async function run(fn){setBusy(true);setError('');try{const d=await fn();if(d)onChange(d);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(file){if(!file)return;if(file.size>5*1024*1024){setError('El PDF no puede superar 5 MB.');return;}await run(async()=>{const pdf=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});return adjuntarDecaExterno(pedidoId,{pdf_base64:pdf,pdf_nativo:native,motivo:reason,envio_id:scope});});}
 const download=(url,name)=>run(async()=>{await descargarArchivoProtegido(url,name);});
 return <section className="deca-versions" aria-label="Originales y versiones del DeCA">
  <div className="deca-versions-heading"><div><strong>Originales y versiones del DeCA</strong><p>Emite el documento del pedido confirmado con los datos conocidos antes de iniciar el transporte. Si la carga cambia los datos, genera una nueva versión y entrégala al conductor antes de salir.</p></div><span className="deca-versions-count">{versions.length} {versions.length===1?'versión':'versiones'}</span></div>
  {!shipments.length&&!versions.length&&<TransportShipmentEditor pedidoId={pedidoId} points={data?.puntos_envio||[]} onChange={onChange}/>}
  {shipments.length>1&&<label className="deca-versions-field">Envío<select value={shipment} onChange={e=>setShipment(e.target.value)}><option value="">Selecciona un envío</option>{data?.consolidacion_permitida&&<option value="consolidado">Todos los envíos · DeCA consolidado</option>}{shipments.map((s,i)=><option key={s.id} value={s.id}>{s.referencia||`Envío ${i+1}`}</option>)}</select></label>}
  <div className="deca-versions-actions">
   <button type="button" className="deca-action deca-action-primary" disabled={disabled||external||(needsReason&&!reason.trim())} onClick={()=>run(()=>generarPedidoDocumentoControl(pedidoId,{motivo:reason,envio_id:consolidated?null:scope,consolidado:consolidated}))}>{busy?'Procesando…':needsReason?'Generar nueva versión':'Generar DeCA'}</button>
   <button type="button" className="deca-action" disabled={busy} onClick={()=>download(`/pedidos/${pedidoId}/expediente-transporte.zip`,'expediente-transporte.zip')}>Descargar expediente</button>
  </div>
  {needsReason&&<p className="deca-versions-hint">Para sustituir una versión, indica el motivo antes de generar.</p>}
  <label className="deca-versions-field">Motivo de emisión o sustitución<input value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder={needsReason?'Explica qué dato se corrige':'Opcional en la primera emisión'}/></label>
  <details className="deca-versions-extra"><summary>Original del cargador y otras opciones</summary><p>Antes de usar un DeCA externo, comprueba sus datos obligatorios y que el QR del propio PDF abra directamente ese original por HTTPS durante el transporte. La subida no valida su contenido legal ni el QR.</p><label className="deca-versions-check"><input type="checkbox" checked={native} onChange={e=>setNative(e.target.checked)}/> El PDF del cargador es digital nativo, no un escaneo</label><label className="deca-versions-field">Adjuntar original del cargador (PDF, hasta 5 MB)<input type="file" accept="application/pdf,.pdf" disabled={disabled||!native||consolidated} onChange={e=>{upload(e.target.files[0]);e.target.value='';}}/></label>{external&&<p>Se utiliza el original del cargador. Para corregirlo, adjunta su nueva versión.</p>}</details>
  {error&&<p role="alert" className="deca-versions-error">{error}</p>}
  {!!versions.length&&<details className="deca-versions-extra"><summary>Consultar versiones ({versions.length})</summary><ul className="deca-versions-list">{versions.map(v=><li key={v.id}><span><strong>Versión {v.version}</strong> · {v.source==='external'?'Cargador':'TransGest'} · {v.estado}<small>{new Date(v.created_at).toLocaleString('es-ES')}</small></span><button type="button" className="deca-action" disabled={busy} onClick={()=>download(`/pedidos/${pedidoId}/documento-control-digital/versiones/${v.id}/pdf`,v.filename)}>Descargar original</button><details><summary>Integridad y motivo</summary><p>{v.reason}</p><p>SHA256: {v.pdf_hash}</p></details></li>)}</ul></details>}
  <details className="deca-versions-extra"><summary>Justificantes de carga y entrega ({signatures.length})</summary><ul className="deca-versions-list">{signatures.map(s=><li key={s.id}><span>{s.operacion} · {s.identidad.nombre} {s.identidad.apellidos} · {s.anulacion?'Anulada':'Firmada'}</span><button type="button" className="deca-action" disabled={busy} onClick={()=>download(`/pedidos/${pedidoId}/firma/${s.id}/justificante.pdf`,'justificante.pdf')}>Descargar justificante</button>{!s.anulacion&&<button type="button" className="deca-action" disabled={busy||!reason.trim()} onClick={()=>run(async()=>{await anularFirmaOperacion(pedidoId,s.id,reason);setSignatures(await getFirmasOperacion(pedidoId));})}>Anular con motivo</button>}{s.anulacion&&<><p>{s.anulacion}</p>{!signatures.some(v=>v.replaces_id===s.id)&&<button type="button" className="deca-action" disabled={busy} onClick={()=>setCorrection(s)}>Corregir firma</button>}</>}</li>)}</ul><p>La anulación conserva la evidencia original. La corrección exige nueva revisión y firma.</p></details>
  {correction&&<OperationSignature pedido={{id:pedidoId}} paradaId={correction.parada_id} correctionId={correction.id} title="Corregir firma de conformidad" onCancel={()=>setCorrection(null)} onFirma={async(image,name,evidence)=>{await guardarFirmaEntrega(pedidoId,{...evidence,firma_destinatario:image});setSignatures(await getFirmasOperacion(pedidoId));setCorrection(null);}}/>}
 </section>;
}
