import React,{useState,useEffect} from 'react';
import SupplierDocumentDelivery from '../components/SupplierDocumentDelivery';
import OperationSignature from './driver/OperationSignature';
import './TransportDocumentVersions.css';
import {adjuntarDecaExterno,generarPedidoDocumentoControl,solicitarDecaPedido,getPedidoDocumentoControl,descargarArchivoProtegido,getFirmasOperacion,anularFirmaOperacion,guardarFirmaEntrega} from '../services/api';

export default function TransportDocumentVersions({pedidoId,pedido,data,onChange}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[native,setNative]=useState(false);
 const [permitChoice,setPermitChoice]=useState('mantener'),[permitReference,setPermitReference]=useState('');
 const [signatures,setSignatures]=useState([]),[shipment,setShipment]=useState(''),[correction,setCorrection]=useState(null);
 const [externalIndex,setExternalIndex]=useState('');
 useEffect(()=>{let live=true;getFirmasOperacion(pedidoId).then(v=>{if(live)setSignatures(v);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[pedidoId]);
 const consolidated=shipment==='consolidado';
 const all=shipment==='todos';
 const versions=data?.versiones||[],shipments=data?.envios||[],scope=all||consolidated?null:shipment||(shipments.length===1?shipments[0].id:null);
 const external=versions.some(v=>v.estado==='activa'&&v.source==='external'&&(all||v.envio_id===scope));
 const needsReason=versions.some(v=>v.estado==='activa'&&(all||(consolidated?!v.envio_id:v.envio_id===scope)));
 const disabled=busy||(shipments.length>1&&!scope&&!all&&!consolidated);
 const expectedShipments=data?.envios_previstos||[];
 async function run(fn){setBusy(true);setError('');try{const d=await fn();if(d)onChange(d);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function upload(file){if(!file)return;if(file.size>5*1024*1024){setError('El PDF no puede superar 5 MB.');return;}await run(async()=>{const pdf=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});return adjuntarDecaExterno(pedidoId,{pdf_base64:pdf,pdf_nativo:native,motivo:reason,envio_id:scope,...(!shipments.length&&expectedShipments.length>1&&externalIndex!==''?{envio_indice:Number(externalIndex)}:{})});});}
 const download=(url,name)=>run(async()=>{await descargarArchivoProtegido(url,name);});
 return <section className="deca-versions" aria-label="Originales y versiones del DeCA">
  <div className="deca-versions-heading"><div><strong>Originales y versiones del DeCA</strong><p>Adjunta el original recibido o emite el DeCA antes del transporte. Los puntos, mercancías, pesos y destinatarios se toman del pedido. Si falta algún dato, complétalo en las cargas o descargas del pedido y guarda los cambios.</p></div><span className="deca-versions-count">{versions.length} {versions.length===1?'versión':'versiones'}</span></div>
  {data?.solicitud_deca&&!data?.status?.ready&&<p role="status" className="deca-versions-hint">DeCA solicitado a tráfico el {new Date(data.solicitud_deca.created_at).toLocaleString('es-ES')}. Pendiente de completar los originales vigentes de todos los envíos.</p>}
  {data?.recepcion_cargador&&!data?.status?.ready&&<p role="status" className="deca-versions-hint">El conductor indicó que recibió el DeCA del cargador el {new Date(data.recepcion_cargador.created_at).toLocaleString('es-ES')}. Comprueba y adjunta el original; esta confirmación no sustituye el PDF.</p>}
  {!shipments.length&&!versions.length&&<p className="deca-versions-hint">Al generar el DeCA, TransGest preparará automáticamente los envíos a partir de las cargas y descargas guardadas en el pedido. Si hay varias cargas y descargas, relaciona cada descarga con su carga de origen en el pedido.</p>}
  {shipments.length>1&&<label className="deca-versions-field">Documentos del pedido<select value={shipment} onChange={e=>setShipment(e.target.value)}><option value="">Selecciona un envío</option><option value="todos">Todos los envíos · DeCA por envío</option>{data?.consolidacion_permitida&&<option value="consolidado">Todos los envíos · DeCA consolidado</option>}{shipments.map((s,i)=><option key={s.id} value={s.id}>Envío {i+1}: {s.referencia||'Sin referencia'}</option>)}</select></label>}
  <div className="deca-versions-actions">
   {!data?.solicitud_deca&&!data?.recepcion_cargador&&!versions.length&&<button type="button" className="deca-action" disabled={busy} onClick={()=>run(async()=>{await solicitarDecaPedido(pedidoId);return getPedidoDocumentoControl(pedidoId);})}>Registrar que el cargador no entregó el DeCA</button>}
   <button type="button" className="deca-action deca-action-primary" disabled={disabled||external||(needsReason&&!reason.trim())||(permitChoice==='si'&&!permitReference.trim())} onClick={()=>run(()=>generarPedidoDocumentoControl(pedidoId,{motivo:reason,envio_id:consolidated?null:scope,consolidado:consolidated,...(permitChoice==='mantener'?{}:{autorizacion_especial:{requerida:permitChoice==='si',referencia:permitReference.trim()}})}))}>{busy?'Procesando…':needsReason?'Generar nueva versión':'Generar DeCA'}</button>
   <button type="button" className="deca-action" disabled={busy} onClick={()=>download(`/pedidos/${pedidoId}/expediente-transporte.zip`,'expediente-transporte.zip')}>Descargar expediente</button>
  </div>
  {needsReason&&<p className="deca-versions-hint">Para sustituir una versión, indica el motivo antes de generar.</p>}
  <label className="deca-versions-field">Motivo de emisión o sustitución<input value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder={needsReason?'Explica qué dato se corrige':'Opcional en la primera emisión'}/></label>
  <details className="deca-versions-extra"><summary>Autorización especial de circulación</summary><p>Si este transporte requiere autorización especial, consigna su referencia en el original. Si corriges una versión, se conserva la declaración anterior salvo que la cambies aquí.</p><label className="deca-versions-field">Situación<select value={permitChoice} onChange={e=>setPermitChoice(e.target.value)}><option value="mantener">Sin cambio</option><option value="no">No requerida</option><option value="si">Requerida</option></select></label>{permitChoice==='si'&&<label className="deca-versions-field">Referencia de la autorización<input value={permitReference} maxLength={120} onChange={e=>setPermitReference(e.target.value)} required/></label>}</details>
  <p className="deca-versions-legal">Las firmas locales de carga y entrega se conservan como justificantes operativos. Este DeCA no se presenta como carta de porte firmada electrónicamente hasta incorporar la firma avanzada de cargador y porteador sobre su versión concreta.</p>
  <details className="deca-versions-extra"><summary>Original del cargador y otras opciones</summary><p>Antes de usar un DeCA externo, comprueba sus datos obligatorios y que el QR del propio PDF abra directamente ese original por HTTPS durante el transporte. La subida no valida su contenido legal ni el QR.</p><label className="deca-versions-check"><input type="checkbox" checked={native} onChange={e=>setNative(e.target.checked)}/> El PDF del cargador es digital nativo, no un escaneo</label>{!shipments.length&&expectedShipments.length>1&&<label className="deca-versions-field">Envío del pedido al que pertenece el original<select value={externalIndex} onChange={e=>setExternalIndex(e.target.value)}><option value="">Selecciona un envío</option>{expectedShipments.map((item,index)=><option key={index} value={index}>Envío {index+1}: {item.destino||item.referencia}</option>)}</select></label>}<label className="deca-versions-field">Adjuntar original del cargador (PDF, hasta 5 MB)<input type="file" accept="application/pdf,.pdf" disabled={disabled||!native||consolidated||all||(!shipments.length&&expectedShipments.length>1&&externalIndex==='')} onChange={e=>{upload(e.target.files[0]);e.target.value='';}}/></label>{external&&<p>Se utiliza el original del cargador. Para corregirlo, adjunta su nueva versión.</p>}</details>
  {pedido?.colaborador_id&&<SupplierDocumentDelivery pedidoId={pedidoId}/>}
  {error&&<p role="alert" className="deca-versions-error">{error}</p>}
  {!!versions.length&&<details className="deca-versions-extra"><summary>Consultar versiones ({versions.length})</summary><ul className="deca-versions-list">{versions.map(v=><li key={v.id}><span><strong>Versión {v.version}</strong> · {v.source==='external'?'Cargador':'TransGest'} · {v.estado}<small>{new Date(v.created_at).toLocaleString('es-ES')}</small></span><button type="button" className="deca-action" disabled={busy} onClick={()=>download(`/pedidos/${pedidoId}/documento-control-digital/versiones/${v.id}/pdf`,v.filename)}>Descargar original</button><details><summary>Integridad y motivo</summary><p>{v.reason}</p><p>SHA256: {v.pdf_hash}</p></details></li>)}</ul></details>}
  <details className="deca-versions-extra"><summary>Justificantes de carga y entrega ({signatures.length})</summary><ul className="deca-versions-list">{signatures.map(s=><li key={s.id}><span>{s.operacion} · {s.identidad.nombre} {s.identidad.apellidos} · {s.anulacion?'Anulada':'Firmada'}</span><button type="button" className="deca-action" disabled={busy} onClick={()=>download(`/pedidos/${pedidoId}/firma/${s.id}/justificante.pdf`,'justificante.pdf')}>Descargar justificante</button>{!s.anulacion&&<button type="button" className="deca-action" disabled={busy||!reason.trim()} onClick={()=>run(async()=>{await anularFirmaOperacion(pedidoId,s.id,reason);setSignatures(await getFirmasOperacion(pedidoId));})}>Anular con motivo</button>}{s.anulacion&&<><p>{s.anulacion}</p>{!signatures.some(v=>v.replaces_id===s.id)&&<button type="button" className="deca-action" disabled={busy} onClick={()=>setCorrection(s)}>Corregir firma</button>}</>}</li>)}</ul><p>La anulación conserva la evidencia original. La corrección exige nueva revisión y firma.</p></details>
  {correction&&<OperationSignature pedido={{id:pedidoId}} paradaId={correction.parada_id} correctionId={correction.id} title="Corregir firma de conformidad" onCancel={()=>setCorrection(null)} onFirma={async(image,name,evidence)=>{await guardarFirmaEntrega(pedidoId,{...evidence,firma_destinatario:image});setSignatures(await getFirmasOperacion(pedidoId));setCorrection(null);}}/>}
 </section>;
}
