import { useEffect, useRef, useState } from "react";
import "./personnel.css";
const sections=[["nominas","Nóminas"],["hojas_ruta","Hojas de ruta"],["control_horario","Control horario"]];
export const openPersonnel=id=>window.dispatchEvent(new CustomEvent("tms:navegar",{detail:id}));
export function PersonnelIcon({clock=false}) {return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{clock?<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>:<><path d="M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h6"/></>}</svg>;}
export function PersonnelHeader({active}) {const nav=useRef(null);useEffect(()=>{nav.current?.querySelector("[aria-current=page]")?.scrollIntoView({block:"nearest",inline:"nearest"});},[active]);return <><div className="personnel-breadcrumb">Inicio <span>›</span> Gestión <span>›</span><b>{sections.find(([id])=>id===active)?.[1]}</b></div><header className="personnel-heading"><h1>Gestión del personal</h1><p>Nóminas, hojas de ruta y control horario de tu equipo, en un solo lugar.</p></header><nav ref={nav} className="personnel-nav" aria-label="Gestión del personal">{sections.map(([id,label])=><button key={id} aria-current={id===active?"page":undefined} onClick={()=>openPersonnel(id)}><PersonnelIcon clock={id==="control_horario"}/>{label}</button>)}</nav></>;}
export function PersonnelMetrics({items}) {return <div className="personnel-metrics">{items.map(([label,value,detail],i)=><article key={label}><span className={`personnel-tile tone-${i}`}><PersonnelIcon clock={i===2}/></span><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>)}</div>;}
export function RouteSheetsOverview({vehiculos,choferes,pedidos,desde,hasta,onOpen,loading}) {
 const [query,setQuery]=useState("");const [activity,setActivity]=useState("");const [page,setPage]=useState(1);
 const rows=vehiculos.filter(v=>!String(v.clase||v.tipo||"").toLowerCase().includes("remolque")&&!String(v.matricula||"").startsWith("R-")).map(v=>{const c=choferes.find(c=>c.vehiculo_id===v.id||c.id===v.chofer_id);const trips=pedidos.filter(p=>p.vehiculo_id===v.id&&p.estado!=="cancelado"&&String(p.fecha_carga||p.fecha_pedido||"").slice(0,10)>=desde&&String(p.fecha_carga||p.fecha_pedido||"").slice(0,10)<=hasta);return {v,c,trips};});
 const filtered=rows.filter(({v,c,trips})=>(!activity||(activity==="con"?trips.length>0:!trips.length))&&`${v.matricula} ${c?.nombre||""} ${c?.apellidos||""}`.toLowerCase().includes(query.trim().toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages);
 return <><PersonnelMetrics items={[["Vehículos",loading?"—":rows.length,"Con hoja de ruta disponible"],["Viajes del período",loading?"—":rows.reduce((s,r)=>s+r.trips.length,0),"Según las fechas seleccionadas"],["Conductores asignados",loading?"—":new Set(rows.filter(r=>r.c).map(r=>r.c.id)).size,"Asignación actual de la flota"],["Sin conductor",loading?"—":rows.filter(r=>!r.c).length,"Vehículos pendientes de asignación"]]}/><div className="personnel-overview"><section className="personnel-panel"><h2>Hojas de ruta de conductores</h2><p>Consulta los viajes, dietas, combustible y costes de cada vehículo.</p><div className="personnel-filters"><input aria-label="Buscar conductor o matrícula" placeholder="Buscar conductor o matrícula…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><select aria-label="Actividad del período" value={activity} onChange={e=>{setActivity(e.target.value);setPage(1);}}><option value="">Toda la actividad</option><option value="con">Con viajes</option><option value="sin">Sin viajes</option></select></div><div className="personnel-table"><table><thead><tr><th>Conductor</th><th>Matrícula</th><th>Período</th><th>Viajes</th><th>Kilómetros</th><th>Acciones</th></tr></thead><tbody>{filtered.slice((current-1)*10,current*10).map(({v,c,trips})=><tr key={v.id}><td>{c?`${c.nombre} ${c.apellidos||""}`:"Sin asignar"}</td><td><b>{v.matricula}</b></td><td>{desde} — {hasta}</td><td>{trips.length}</td><td>{trips.reduce((s,p)=>s+Number(p.km_ruta||p.km||0),0).toLocaleString("es-ES")}</td><td><button onClick={()=>onOpen(v.id)}>Ver hoja</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p role="status">{loading?"Cargando hojas de ruta…":"No hay vehículos con estos filtros."}</p>}<footer className="personnel-pagination"><span>{filtered.length} hojas de ruta</span><button disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Siguiente</button></footer></section><aside><section className="personnel-panel"><h2>Gestión de jornadas</h2><p>Consulta los registros de horario, pausas y solicitudes de teletrabajo.</p><button onClick={()=>openPersonnel("control_horario")}>Ver control horario →</button></section><section className="personnel-panel"><h2>Nóminas y dietas</h2><p>Prepara las liquidaciones y revisa las jornadas antes de emitir la nómina.</p><button onClick={()=>openPersonnel("nominas")}>Ver nóminas →</button></section></aside></div></>;
}
